realm/realm-core

- CHANGELOG.md
- src/realm/column.hpp
- src/realm/column_linklist.cpp
- src/realm/column_linklist.hpp
- src/realm/group.cpp
- src/realm/impl/transact_log.hpp
- src/realm/replication.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_lang_bind_helper.cpp
- test/test_replication.cpp
- test/test_table.cpp
This changes the following:
- The misnomer `ChangeLinkTargets` is renamed to something that properly describes its purpose, even if the implementation can only live up to its promises under very particular circumstances.
- The behavior of `MergeRows` is simplified to be equivalent of `SwapRows` on the storage layer (but accessors are still updated through a separate mechanism, `adj_acc_merge_rows`).
- `SetUnique` instructions with local conflicts (which never happen in real life due to PK conflict detection) do not generate extra instructions.
**NOTE:** Due to the rename, this is an API-breaking change.
> Fallout of stability improvements in RMP, and a rename

- test/test_all.cpp
- test/test_shared.cpp
- test/util/random.cpp
- test/util/random.hpp
Use C++11's non-deterministic random number generator, `std::random_device` in place of our own `time() ^ getpid()` solution.
Also fixes warnings in Visual Studio re. redefinition of `NOMINMAX`.
@rrrlasse @ironage 
( other fixes extracted into separate issue #2210 )
> Use C++11's non-deterministic random number generator

- src/realm/column.hpp
- test/test_column.cpp
I made the `ColumnRandIterator::operator bool()` explicit (and noexcept) which causes Microsoft Visual Studio Community 2015 (Version 14.0.25431.01 Update 3) to produce a compiler error for missing `operator<`. The `bool()` operator was erroneously (and implicitly) used to compare two iterators (`a < b`) as bools(!), which caused the `Column_SwapRows` unit test in `test_column.cpp` to crash.
TODO: Implement `operator<` (and more?).
cc: @ironage @rrrlasse
> ColumnRandIterator completeness

- Jenkinsfile
It's needed by the packaging stage
> Always stash the cocoa package

- test/test_index_string.cpp
This PR fixes an error in the unit test random string generation that for _some_ seeds on _some_ platforms (due to variations in the implementation of `std::uniform_int_distribution`) inserted extra `0` characters at unexpected positions - resulting in identical strings being inserted.
Extracted from #2245.
@rrrlasse @ironage Please review.
> Fix random string generation in unit test

- CHANGELOG.md
- src/realm/null.hpp
- src/realm/table.cpp
- test/test_column_float.cpp
`DoubleFloatColumn_InitOfEmptyColumnNullable` failed for nullable float columns (`test_column_float.cpp:516`) on both 32- and 64-bit _devices_ (iPhone 5 and iPhone 6s Plus). Unintentional promotion to double and back modified our NaN's bit pattern.
Extracted from #2245.
@rrrlasse @ironage Please review.
> Fix initialisation of nullable float columns

- src/realm/group_shared.cpp
Changed some variables from uint32_t to uint_fast32_t.
Fixes #2213 
@danielpovlsen @finnschiermer
> Remove some clang warnings

- Jenkinsfile
@ironage @danielpovlsen 
This should at least fix the fails for the PRs. Looks like a bug in s3cmd.
@emanuelez Not sure if we should do the same at the publish step, the android and cocoa tar balls are pretty big, this would slow down the process a lot.
```
Downloads s3cmd put realm-core-dotnet-cocoa-test.tar.bz2 s3://static.realm.io/downloads/core
upload: 'realm-core-dotnet-cocoa-test.tar.bz2' -> 's3://static.realm.io/downloads/core'  [1 of 1]
5308416 of 11602593    45% in    3s  1591.92 kB/s  failed
WARNING: Upload failed: /downloads/core ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
upload: 'realm-core-dotnet-cocoa-test.tar.bz2' -> 's3://static.realm.io/downloads/core'  [1 of 1]
8781824 of 11602593    75% in    2s     3.05 MB/s …
```
> Fix dotnet-cocoa upload

- src/realm/Makefile
- src/realm/array.hpp
This is included in array.hpp so it needs to exist.
> Add array_direct.hpp to installed headers

- CHANGELOG.md
- src/realm/table.cpp
- test/test_replication.cpp
Link nullification is a side-effect of deletion of target rows, and they used to be purely informational instructions for notification handlers. They also used to come after the `MoveLastOver` instruction of which they were a side-effect in the transaction log, but this was changed during the development of RMP, where the `LinkListNullify` and set-link nullification instructions now have an effect and are used to document effects of the merge logic in the merged transaction logs.
However, the semantics were only changed on the normal `Table::move_last_over` and `Table::clear` methods, not the method `Table::batch_erase_rows`, which happens to be invoked when deleting rows through a `TableView` (including when deleting the results of a `Query`). The result is that `LinkListNullify` is …
> Table::batch_erase_rows generates wrong instructions

- CHANGELOG.md
- src/realm/util/logger.hpp
- test/util/unit_test.hpp
@ironage @danielpovlsen 
Not a bug fix, just an improvement in the usability of the logger API.
> Parameter arguments passed to logger methods are now perfectly forwarded

- CHANGELOG.md
- src/realm/alloc.hpp
- test/test_alloc.cpp
Large refs (with MSB set) on 32-bit platforms were converted to _signed_ `int_fast64_t` before stored in an array (in `from_ref`). However, this was not handled symmetrically in `to_ref`, which would trigger an assert. Moreover, a lot of places these conversion functions were not even used, resulting in a lot of new issues. I tried to find them all in #2245, but have not yet managed to succeed.
In this PR, I propose storing these refs directly (keep them unsigned) and accepting the array bit width expansion in the case of large refs. This seems to be the quickest - and safest - solution for now. For a longer term solution, we should consider switching the `ref_type` to a fixed 64-bit type instead.
@rrrlasse @ironage @finnschiermer
> Fix large refs on certain 32-bit platforms

- CHANGELOG.md
- src/realm/util/interprocess_mutex.cpp
- src/realm/util/interprocess_mutex.hpp
This fix places the static mutex variables of `InterprocessMutex` onto the heap. They will not be destructed at all, fixing the problem of them automatically being destructed before the `InterprocessMutex` instances were destructed. This may cause a problem for valgrind, but it could be legitimately suppressed. To guarantee that the static variables are available on the first use, they are allocated by a `std::call_once` call which is thread safe.
@finnschiermer @jedelbo 
This should fix the stack trace reported by @alazier below:
```
util/thread.cpp:217: [realm-core-2.1.4] pthread_mutex_lock() failed: Invalid mutex object provided
0   realm-node.node                     0x00000001041c1ea8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocator …
```
> Fix a destruction race.

- src/realm/util/features.h
- src/realm/util/terminate.cpp
- test/test_all.cpp
Some time ago we decided to have our `REALM_` macros to be always defined. While doing #2245 I stumbled across these and just fixed them.
@ironage
> Minor preprocessor / define fixes

- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_conditions.hpp
- src/realm/query_expression.hpp
- src/realm/string_data.hpp
- src/realm/table_accessors.hpp
- src/realm/unicode.cpp
- src/realm/unicode.hpp
- test/test_query.cpp
- test/test_string_data.cpp
This adds query support for simple wildcard matching (`?` for single character, `*` for multiple chars). It is not regex matching, more like the kind of wildcards you can use on the command line. This is needed to support the `LIKE` predicate in NSPredicates (which is different from `MATCHES` that _does_ use regex). The related Cocoa issue is: https://github.com/realm/realm-cocoa/issues/1490
I needed a wildcard matching for a project I was experimenting with, and I noticed that it was not implemented yet, so I just added it given that it was such a simple thing to implement. 
@rrrlasse @bdash
> Add support for "like" (wildcard) queries

- src/realm/bptree.hpp
- src/realm/column.hpp
- src/realm/column_timestamp.cpp
- src/realm/util/features.h
Exposing Array type through the public interface is exposing the
implementation. We might not use Array as the fundamental BpTree
building block forever.
If you use the deprecated function, you can instead do like this:
```
ref_type ref = BpTree<int>::create_leaf(Array::type_Normal, 0, 0, alloc);
_impl::DeepArrayRefDestroyGuard dg_2(ref, alloc);
auto bp_tree = std::make_unique<BpTree<int>>(alloc, ref); // Throws
bp_tree->set_parent(...);
bp_tree->root().update_parent(); // Throws
dg_2.release(); // Ownership transferred
```
@kspangsege This could solve the problem we discussed yesterday
@finnschiermer
> Deprecate Array type parameters in Column<T> and BpTree<T> constructors

- src/realm/column_string.cpp
There was a debug assertion in `StringColumn::find_all_no_copy` that was hit when running with a debug Core, because a binding tried to run a query that was looking for NULLs on a non-nullable column.
Crashing when looking for NULL on a non-nullable column does not seem like the right thing to do. This changes the assertion to an early-out.
@ironage @rrrlasse @radu-tutueanu
> Allow querying for NULL in non-nullable string columns

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- test/test_lang_bind_helper.cpp
This PR adds an exception to specifically indicate that a Realm is being opened with an incompatible history type. Requested by PR #2275
> added specific exception for incompatible histories

- CHANGELOG.md
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
- test/test_query.cpp
`m_table` needs to not be set on the handover Query in order for the column
references to be updated properly when re-importing it into the same
SharedGroup. This could theoretically cause problems when exporting and
importing into a different SharedGroup, but it's very unlikely (it'd require
that the source SharedGroup be destroyed and then the target one happen to
allocate the equivalent Table at the same memory address).
The removed assertion was not actually asserting anything sensible (`m_table`
was previously the same table as it was getting the column index from, so it
wasn't an interesting assert, and now is null so the assert would just crash).
> Fix a crash when reimporting a Query into the same SharedGroup as it was exported from

- CHANGELOG.md
- src/realm/exceptions.hpp
- src/realm/group_shared.cpp
- src/realm/replication.hpp
@jedelbo @ironage , can I ask you guys to review?
This PR provides (completes) the facilities needed to detect attempts at adding multiple concurrent sync agents to a single Realm file access session. This is not allowed as it will generally lead to corruption. Now we have a chance to detect if somebody makes this occur by mistake.
> Offer facilities to prevent multiple sync agents per Realm file access session

- CHANGELOG.md
- src/realm/util/interprocess_condvar.cpp
mkfifo on Android 4.x has a different behaviour when mkfifo fails by
creating on the external storage. 4.x fails with errno EPERM but the
on recent Android devices it fails with EACCES.
> mkfifo in tmp again if fails with EPERM

- src/realm/alloc_slab.cpp
Asserts in debug mode, if the slab allocator ever hands out a ref which is inside the file.
> checks that allocations always are above baseline

- src/realm/bptree.hpp
- src/realm/column.hpp
- src/realm/column_timestamp.cpp
No need to convert to ref_type as it is costly to convert back again.
@kspangsege
> Use MemRef instead of ref_type in BpTree constructor

- src/realm/bptree.hpp
- src/realm/link_view.hpp
- test/test_lang_bind_helper.cpp
The problem occurred when refreshing a link view accessor from a leaf to a node. We should take into
account that we need to create another class when the root is an inner node.
Fixes issue #2321
> Fix LinkView::refresh_accessor_tree

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/group_writer.cpp
And probably a bunch of other things since none of this is specific to the file format upgrade. Gives roughly a 10x performance improvement on the sample file sent in for https://github.com/realm/realm-cocoa/issues/4368 (goes from 10-15 seconds on my machine to 1.5 seconds).
Deferring the consolidation of the read-only free space until just before it's actually written to the file makes the best case slightly slower, since it'll always push_back() a new chunk rather than just updating the previous one when all of the chunks being freed are contiguous, but it makes the worst case O(N log N) rather than O(N^2). In practice in the happy case of upgrading a compacted Realm the time spent in the allocator is trivial in both versions.
Adding and using `Array::find_gte_unsorted()` rather than …
> Improve performance of the 5 -> 6 file format upgrade

- CHANGELOG.md
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- test/test_upgrade_database.cpp
When `util::File::copy()` was added, it was apparently done as a quick hack, and error handling was improper.
Errors are now reported via `File::AccessError` exceptions. This greatly increases the utility and robustness of `util::File::copy()`.
I added `util::File::compare()` because I needed it to test `util::File::copy()`, but I think it has general utility, so I'll leave it in.
@jedelbo @ironage
> Fix util::File::copy() and add util::File::compare().

- src/realm/group_writer.cpp
Realized that we might free an entry which comes after all entries in m_free_positions
> Add boundary check in GroupWriter::write_group()

- CHANGELOG.md
- src/realm/impl/simulated_failure.hpp
Make `_impl::make_error_code(_impl::SimulatedFailure::FailureType)` participate in overload resolution in unqualified ADL contexts like `make_error_code(_impl::SimulatedFailure::sync_client__read_head)` and `ec == _impl::SimulatedFailure::sync_client__read_head`.
@ironage @jedelbo @finnschiermer
> Fix ADL use of make_error_code(SimulatedFailure::FailureType)

- src/realm/group_shared.cpp
@rrrlasse @jedelbo please review. Should be trivial. 😉
> Use our millisleep function instead of a copy of it.

- build.sh
- test/valgrind.suppress
We recently changed the design for the lifetime of some memory so that it is intentionally not cleaned up by us. This was to avoid race conditions on destruction. We should suppress these warnings so we get a clean valgrind run to tell if there are any new leaks.
Apparently the existing suppressions file was unused by Jenkins. It was also really old, so I wiped it and added new valid suppressions. I've gone over the source of each allocation that is now suppressed and I believe they are all intentional. It would be nice if @finnschiermer or @rrrlasse could confirm these though (the description tag of each suppression shows the source of the allocation but if you want a stack trace just ask).
Fixes #2304 
Here's the end output from a local run of the unit test suite on my machine for …
> New valgrind suppressions

- build.sh
Mostly just to bring it in line with Xcode's default settings, as otherwise it produces warnings when building a dynamic framework using the core library (although it's unclear as to why it's [only recently started to produce those warnings](https://github.com/realm/realm-object-store/issues/281)). It does reduce the compiled size by a not very interesting amount (~30 KB).
> Build the Cocoa package with -fvisibility-inlines-hidden

- src/realm/util/file.cpp
GCC 6 includes support for the C++17 changes to the `std::unique_ptr::reset()` signature, which breaks current usage. It's probably a bug in libstdc++, but this constitutes a workaround. :)
> Fix compilation with GCC 6

- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- test/valgrind.suppress
The previous suppression would cancel any reachable memory from strings generated in the test framework but these reachable memory locations would still show up if the file paths are generated from some different application (e.g. realm sync tests). This is a more robust way of suppressing the memory warning because it no longer matters where the strings were allocated, the slab_alloc makes it's own deep copy of the path so we know where exactly to suppress.
The reachable memory is generated by std::string::create when the file path is born. The std::string assignment and copy implementations are most likely trying to optimise by not actually copying the data but by reference counting with copy-on-write machinery. Apparently this implementation is not allowed any more since C++11 but …
> Deep copy realm file path for better valgrind suppression.

- CHANGELOG.md
A fix released in 2.1.4 was still mentioned at the top of CHANGELOG.md.
> removed note for fix that was released already (in 2.1.4)

- CHANGELOG.md
- src/realm/util/file.cpp
`P_tmpdir` is defined in `stdio.h` but its value is `/tmp/`. Since that directory is typically not writable on an Android device, `/data/local/tmp` is a better choice.
See also https://code.google.com/p/android/issues/detail?id=74497
> P_tmpdir should not be used on Android

- CHANGELOG.md
- src/realm/util/interprocess_condvar.cpp
`InterProcessCondVar::set_shared_part()` sets a certain flag (`uses_emulation`) before filling the file descriptor fields. If it then fails to set the file descriptors, later the destructor will try to close them, which leads to `close(0)` and lots of terrible stuff to happen everywhere.
The PR moves `uses_emulation = true` to the bottom of the method, where the file descriptors are valid.
> Prevent `stdin` being accidentally closed during `~InterProcessCondVar()`

- CONTRIBUTING.md
- README.md
Hi realm-core team!
I fixed typo and a link. This pull request has 2 commits:
- Fix typo in README.md.
- In CONTRIBUTING.md file, the link to style guide (coding_style_guide.cpp)  is not set correctly. It shows just blank page. Use relative link to fix the link since it is linked to internal file in the repository. ([Reference to relative link](https://help.github.com/articles/relative-links-in-readmes/))
Can I please ask you to review this PR? It would be great if you could merge it :) Thanks!
---
I read CONTRIBUTING.md, and submitted Realm Contributor Licensing Agreement.
> Fix typo and link

- src/realm/array_string.cpp
`m_width` is not used for the calculation, so that can be discarded from condition. For `value.size() = 0`, we have `::round_up(0 + 1) = ::round_up(1)`. No need for `if`.
@rrrlasse @danielpovlsen @ironage
> No need to branch.

- src/realm/index_string.cpp
I would like to know what these values could possibly be in case https://github.com/realm/realm-cocoa/issues/4316 ever happens again.
> Verbose assertion for debugging.

- CHANGELOG.md
- src/realm/impl/transact_log.cpp
- src/realm/link_view.cpp
- src/realm/link_view.hpp
- test/test_lang_bind_helper.cpp
Handover of a detached LinkView used to constrain a query did not work. The detached LinkView was inadvertently transformed into no LinkView, which has a different meaning. This is demonstrated in #2378. The testcase provided there is included in this PR.
This PR fixes #2378  by allowing handover of a detached LinkView.
LinkView holds a member variable m_origin_column which was originally a *reference* to a column. Since there is no column available when creating a new detached LinkView, m_origin_column had to be changed to a *pointer* instead, allowing it to be nullptr.
> Fix handover of detached constraining view

- src/realm/alloc_slab.cpp
Not sure if this is the best way, but here goes.
> Fix implicit conversion warning (string literal -> bool)

- CHANGELOG.md
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_basic_tpl.hpp
- src/realm/array_blob.cpp
- src/realm/array_blobs_big.cpp
- src/realm/array_string.cpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
This is currently mostly just an exploration into whether this is actually a useful thing to do.
A seemingly very common pattern in apps which talk to a REST API is to blindly update all fields in a Realm object with new values from the server, regardless of whether or not they've actually changed (because the server doesn't send that information, and checking would be a bunch of extra code).
I suspect that this extra churn could make realm file size growth noticeably worse, so the new test has a single table with 5000 rows, and then it makes a series of commits which each modify several columns of several rows, while self-assigning all other columns of those rows.
The current changes cut the file size 20-30% with small numbers of pinned versions and the total bytes written to disk by …
> Avoid calling Array::copy_on_write() when the value will not change

- Jenkinsfile
Add `macos` as a label to the Mac builds in order to rely on newer slaves in CPH.
> Added macOS slave to Jenkinsfile

- CHANGELOG.md
- how-to-build.md
- test/test_all.cpp
- test/util/unit_test.cpp
- test/util/unit_test.hpp
My agenda is really to make this change for sync, but since sync tracks cores version of the unit test framework, I needed to make the changes core-side first.
@ironage 
Part of fixing https://github.com/realm/realm-sync/issues/1131
> No longer disable unit test console output when setting envvar UNITTEST_XML

- src/realm/query_expression.hpp
This issue was introduced in b927788a0cb429b519fc32eb4e303631ef9b7fb4.
> Fix compilation when old query engine fallback is disabled

- Jenkinsfile
I don't think Xcode 7.3.1 is available on the macOS slaves anymore. In sync we moved to 8.2.
cc @jpsim
> Build with Xcode 8.2 instead of Xcode 7.3.1

- CHANGELOG.md
- src/realm/group_shared.cpp
When robust mutex emulation is enabled each of these would open an extra file which is never actually used.
> Don't init async daemon CVs when not using async commits

- src/project.mk
While experimenting with various configuration related to https://github.com/realm/realm-java/issues/3651, I noticed that LTO is enabled. We have disabled it for Android since it increases linking time and not effectively reduces size (it might increase size).
For ARM v7 stripped `.so` file distributed with apps:
* with LTO: 1,852,944 bytes
* without LTO: 1,840,660 bytes
Yes, small increase when using LTO (partially).
@danielpovlsen @finnschiermer @beeender @ironage
> Disable LTO for Android

- CHANGELOG.md
- src/realm/row.hpp
Related to https://github.com/realm/realm-object-store/issues/357: supporting counters within bindings.
Who should I ask to review this?
> Add `add_int()` to `RowFuncs`

- build.sh
c80f9d0a8c2fbaad4b9c0a781dcbcae160b74fee removed the old license from tools/LICENSE, but did not notice that it was still being used.
> Update build.sh to use LICENSE from the top level of the repository

- test/unit-tests-ios/Images.xcassets/AppIcon.appiconset/Contents.json
Xcode insists on (== automatically makes) this change if the `unit-tests-ios` target is selected.
> Add placeholders for missing icon sizes

- src/realm/util/file.cpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_lang_bind_helper.cpp
Passing the encryption key down to `mremap()` allows us to only obtain the mutex if the key is used, so this should speed up the case when encryption has been compiled in but we are not actually using it.
This also allows us to check for and throw when an encryption key is used but we can't find the mapping in the cache. If this ever happened, we would fall through and mmap using `nullptr` as the encryption key meaning it wouldn't be added to the mappings either. We should throw if this ever happens (it shouldn't).
Testing with variations of encryption enabled showed an error in a test case, it is fixed here as well.
> Encrypted remap

- Visual Studio/Realm.vcxproj
- test/test_optional.cpp
constexpr support isn't sufficient on Visual Studio
> Disable some tests on Windows

- CHANGELOG.md
- src/realm/binary_data.hpp
- src/realm/string_data.hpp
This tell us about errors like the following in unit tests at compile time:
`BinaryData data(std::string(45, 'y'))`
If data is referenced again, it's pointers into memory would be invalid as the object it refers to has been destructed. BinaryData should only be a wrapper around external data, it doesn't store anything itself. This is similar to how the same StringData constructor has been removed. I made that one const to catch more cases too.
Note that we still allow code like `BinaryData data("test string", 11);` because that string should always be addressable since it is compiled into the data section of the binary.
> Remove a BinaryData constructor

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/group_shared_options.hpp
- test/test_shared.cpp
When compacting the Realm on external storage for Android, SharedGroup
always uses the default sys_tmp_dir which is invalid for Android. Thus
we need an API for setting the default sys_tmp_dir for bindings.
The getters is also required since ObjectStore may use it to create
pipe/fifo.
To solve java issue https://github.com/realm/realm-java/issues/4140
Part of #2411
> Get and set sys_tmp_dir

- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/utilities.hpp
Extracted from another branch to keep PRs clean.
Probably easier to review commit by commit.
The most significant change here is probably the simplification of selecting the next string offset for the key generation (4c7fc5c). When the end of the search string is reached, which happens immediately for strings of less than 4 bytes, the old code set the next key offset to be the string length + 1.:
```C++
stringoffset += value.size() - stringoffset + 1; // stringoffset = value.size() + 1;
```
Unfortunately that would trigger an unsigned int (`size_t`) underflow at the next iteration at the line:
```C++
if (value.size() - stringoffset >= 4) // (size_t(-1) >= size_t(4)) == true
stringoffset += 4; // value.size() + 1 + 4
```
Again, setting the offset further outside the bounds of the string. …
> String index improvements

- src/realm/link_view.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/table.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/test_table.cpp
Changes:
* Remove a comment that dates to when `TableViewBase::size` called `sync_if_needed()`.
* Remove two methods that are no longer used.
* Have `Table::get_range_view` delegate to `Query` so that the resulting `TableView` can be synced when needed.
* Remove an unused code path in `TableViewBase::do_sync`.
* Update some comments about where `TableView`s come from.
* Update the structure of `TableViewBase::is_in_table_order` to match that of `TableViewBase::do_sync` to make it clearer that they both handle the same cases.
* Update the structure of `TableViewBase::outside_version` to match that of `TableViewBase::do_sync` to make it clearer that they both handle the same cases.
* Replace `TableViewBase::sync_distinct_view` with a constructor.
* Add a constructor to create a `TableView` …
> Clean up some things within TableView's implementation

- test/test_optional.cpp
The latest Visual Studio 2017 RC rejects `constexpr bool e{<some Optional>}` with an error about there being no conversion from `Optional<T>` to `const bool`.  This seems to be a bug, so [I've reported it to Microsoft](https://developercommunity.visualstudio.com/content/problem/20100/cannotconvert-from-s-to-const-bool-when-initializi.html). Since this exact syntax isn't relevant to what we're trying to test we can instead use `constexpr bool e = bool(<some Optional>)` to test the relevant behavior.
While making this change I noticed that the tests involving constexpr and optional references now pass, so I've taken the liberty of enabling them on Windows as well.
> Tweak some Optional tests so they're compatible with VS2017, and reenable them

- test/test_upgrade_database.cpp
The tests cannot run without previously build database files of the specific node size.
> Skip upgrade database unit tests if running on uncommon node sizes

- CHANGELOG.md
- src/realm/table_view.cpp
- test/test_table_view.cpp
@beeender enabled assertions and ran Realm Java's unit tests - and discovered an assertions.
Aggregate functions can survive if rows are deleted, but we forgot to update the timestamp column type.
@rrrlasse @finnschiermer @danielpovlsen
> Aggregate functions must skip detached rows

- CHANGELOG.md
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
When using a named pipe for a condition variable we can use the same file descriptor for both reading and writing. It's only necessary to use multiple file descriptors on tvOS, where we are forced to use an anonymous pipe instead.
> Don't open a condition variable's pipe twice when once will do

- CHANGELOG.md
- src/realm/util/memory_stream.cpp
- src/realm/util/memory_stream.hpp
- test/test_util_memory_stream.cpp
`seekpos()` and `seekoff()` in `realm::util::MemoryInputStreambuf` now behave
correctly when argument is out of range.
Fixes https://github.com/realm/realm-core/issues/2463.
@morten-krogh @ironage
> Fix seekpos() and seekoff() in realm::util::MemoryInputStreambuf

- CHANGELOG.md
This is a proposal to have (working) links in our `CHANGELOG.md`. Currently we have a mix of PR / issues numbers and/or links in plain text. I propose we use Markdown syntax to have real links and make a habit of always referencing the PR - and if meaningful also a link to the issue in this or the bindings' repo(s).
Only the latest and NEXT release sections have been fixed in this PR.
> Use Markdown syntax to make links to PRs and issues

- CHANGELOG.md
- src/realm/group_writer.cpp
Bug fixed in `GroupWriter::write_group()` where the maximum size of the top array was calculated incorrectly. This bug had the potential to cause corruption in Realm files.
This bug is my fault. It happened during the introduction of in-Realm histories.
@finnschiermer @ironage
> Bug fixed in GroupWriter::write_group(), bad maximum size of top array

- CHANGELOG.md
- src/realm/handover_defs.hpp
- src/realm/query.cpp
- src/realm/table.cpp
- test/test_lang_bind_helper.cpp
It is now possible to handover a TableVies based on a sub-table.
Throw if running a query on a detached table. Could be the case
if you have created a query on a sub-table that later is deleted.
> Support handover of a TableView on a subtable

- src/realm/column.cpp
- src/realm/column.hpp
- src/realm/column_string.cpp
- src/realm/column_string.hpp
- src/realm/column_string_enum.cpp
- src/realm/column_string_enum.hpp
- src/realm/column_timestamp.cpp
- src/realm/column_timestamp.hpp
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/table.cpp
- test/test_index_string.cpp
This is small cleanup of seemingly unused functionality. This change was done before Christmas, but never pushed. Yay / nay?
> Remove toggle for disallowing duplicates in the string index.

- src/project.mk
Some of the flags we used in coverage builds are not supported by clang and gave warnings when building. We should only apply them to GCC coverage builds.
> Fix warnings in coverage build with clang.

- test/bench/benchmark_version
- test/benchmark-crud/main.cpp
Without changing the structure of these benchmarks too much, results are now tracked at the table level so that each iteration on a table counts as one benchmark result instead of over all tables.
To get a more accurate standard deviation without increasing duration, the number of rows in a table was decreased by a factor of ten, and the number of tables was increased by a factor of ten. This gives 500 iterations and actually decreases the overall run time.
The "total_time" tracks the amount of time for this whole CRUD suite and standard deviations is not something that is meaningful. I considered taking this metric out, but left it in because it could be useful to see this metric over time even with only a single value per run. It has been renamed to "crud_total_time" for a more …
> Increase granularity of benchmark-crud to see standard deviations.

- CHANGELOG.md
- Jenkinsfile
- src/realm/column_backlink.hpp
- src/realm/impl/transact_log.hpp
- test/test_lang_bind_helper.cpp
The failing test was found with AFL through #2490. 
The problem is that reversing a `merge_rows` instruction did not trigger a refresh of tables connected by backlinks. This means that after a rollback in this case, a connected table could have the incorrect address which could cause corruption in any following write.  i.e. in the attached test, we find that the last call to `g.verify()` would fail at `REALM_ASSERT_3(ref_in_parent, ==, m_ref);` of the second table because the accessor hasn't been refreshed. 
Note that if the rolled back transaction did contain any other instructions that caused the connected table to be refreshed it would be fine.
The way I propose to trigger a refresh here is to call `merge_rows` twice, merging each affected row into itself sequentially. This will be a …
> Fix rollback of merge_rows with backlinks

- CHANGELOG.md
- Jenkinsfile
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/array.hpp
- src/realm/array_basic.hpp
- src/realm/array_binary.hpp
- src/realm/array_blob.hpp
- src/realm/array_blobs_big.hpp
- src/realm/array_integer.hpp
- src/realm/array_string_long.hpp
- src/realm/bptree.hpp
- src/realm/column.hpp
- src/realm/group.hpp
- src/realm/group_shared.hpp
- src/realm/impl/destroy_guard.hpp
- src/realm/spec.cpp
- src/realm/table.hpp
- src/realm/util/encrypted_file_mapping.hpp
- src/realm/util/file.hpp
- src/realm/util/interprocess_condvar.hpp
- src/realm/util/interprocess_mutex.hpp
- src/realm/util/thread.hpp
- src/realm/views.hpp
This will prevent incorrect use internally and by bindings at compile time by explicitly deleting the compiler generated copy constructors and assignment operators.
Each one deleted in this PR could have caused some pretty serious issues if it was used.
> Prevent copy errors at compile time.

- CHANGELOG.md
- src/realm/array.cpp
- src/realm/array.hpp
- test/test_lang_bind_helper.cpp
This was found with AFL. 
Requests to reallocate memory should pass an aligned size. Otherwise we hit the assertion in `SlabAlloc::do_realloc` line 511: 
`REALM_ASSERT((new_size & 0x7) == 0); // only allow sizes that are multiples of 8`
The case where it is not aligned is when doubling the existing memory goes past the maximum size allowed `max_array_payload` so we choose to clamp to the maximum. The fix is just to clamp to the maximum aligned value.
> Fixed a reallocation corner case found by AFL.

- Jenkinsfile
Use the stashed workspace instead of a new clone. Both an improvement and a workaround for the known issue with VMware Fusion, NAT, git clone issue that sometimes stalls our CI.
> Use the stashed workspace instead of a new clone

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/replication.hpp
Changes:
- History type enumeration value `Replication::hist_Sync` renamed to `Replication::hist_SyncClient`.
- New history type enumeration value `Replication::hist_SyncServer`. This allows for the sync server to start using the same kind of in-Realm history scheme as is currently used by clients.
Prerequisite for https://github.com/realm/realm-core/pull/2481.
@jedelbo @finnschiermer
> Prepare for introduction of sync server history

- test/fuzz_group.cpp
This lets AFL choose a random table and column to apply the `set_unique()` operation to. It's also a refactoring step for upcoming changes. 
The diff of the actual set part looks bad, but nothing changed in there it's just been unindented.
> Fuzz random set unique

- realm.xcodeproj/project.pbxproj
`continuous_transactions_history.cpp` was deleted in #2481, but the Xcode project was not updated to reflect this and cannot build without this change.
> Fix xcode project

- CHANGELOG.md
- src/realm/impl/transact_log.hpp
- src/realm/mixed.hpp
- test/test_column_mixed.cpp
- test/test_lang_bind_helper.cpp
These changes are motivated by fuzz testing of `Mixed(Timestamp)` types from #2490.
No binding code should be using a `Mixed(Timestamp)` type, so these changes mostly cover our bases for this in the future, but the main point is that we allow the fuzz tester to try all combinations of Mixed types. It is in our public interface so until Mixed is removed (if ever) we should support these operations and test them.
> Mixed timestamp enhancements.

- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/utilities.hpp
This is a number of refactoring to prepare for the search index support for the different combinations of case sensitive / case insensitive / prefix / full string searches. The idea is that the current "find all" (aka those that return results in a column) functions will be merged to support all use cases.
Each commit here corresponds to a simple change (that in a better world would be done by a tool). Should be trivial to review commit by commit.
> Prepare for prefix search

- src/realm/column_string.cpp
- src/realm/column_string.hpp
- test/test_index_string.cpp
`StringColumn::find_all(...)` does not support case insensitive searches. I accidentally added the parameter when doing the string index implementation for such searches. However, it only worked if there was an index on the column, otherwise the parameter would be ignored. To get the index optimised searches, the `StringIndex::find_all(...)` should be used directly.
This PR removes that parameter and changes the unit tests to use the `StringIndex` directly.
> Remove parameter exposing non-existent functionality

- CHANGELOG.md
- src/realm/column_mixed_tpl.hpp
- test/test_lang_bind_helper.cpp
Rolling back a transaction which set a Mixed type containing a `StringData` or `BinaryData` would cause an assertion failure because the accessor was not reset while the underlying array structure had made what the accessor referred to disappear. 
The same problem existed for `Timestamp` but I am sure a `Mixed(Timestamp)` has not existed in user data.
This was discovered through AFL after adding instructions for `Mixed` types and has been cherry-picked from #2490 by request, to analyse separately from that PR.
> Fix rollback on mixed binary/string.

- Makefile
- test/fuzz_group.cpp
Adds the following instructions to AFL:
- add_int
- merge_rows
- rename_column
- setting mixed types
This revealed a bug when rolling back a transaction involving a `Mixed` type which contained a `StringData` or a `BinaryData`. The problem is fixed here and a test case added for it.
Other small changes:
- Include the `fuzz_group.cpp` file in coverage reports to allow analysis of what instructions are run.
- Assert immediately when constructing a `Mixed` type with the new `Timestamp` because it is missing some critical functionality and not supported at this point.
Fixes #1636.
> AFL improvements

- src/realm/query_engine.hpp
Otherwise the `m_dD` of `ParentNode` will be used uninitialised.
Please check that it is initialised to the correct value.
This should fix the valgrind error here: https://ci.realm.io/job/core_valgrind/654/
> Initialise distance in SizeNode.

- Jenkinsfile
- test/bench/gen_bench_hist.sh
- test/bench/revs_to_benchmark.txt
This updates the performance reports:
- Adds a couple new tags released recently
- Adds support for comments and empty lines in the `revs_to_benchmark.txt` file
- Adds comparison of the base branch at the point where the current branch diverged
> Performance update

- Jenkinsfile
For reals this time.
The 'fastlinux' change keeps popping up because it was integrated into so many branches to get CI to pass.
> Use android hub

- CHANGELOG.md
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- test/test_query.cpp
Supports syntax like this:
```
Query q = table->column<SubTable>(0).list<Int>() == 5;
Query q = table->column<SubTable>(0).list<Int>().min() >= 2;
```
As an alternative to `list<Int>()` you can write `column<Int>(0)`. So we can have more columns in the sub-table although we currently don't have a use case for that. I also considered `self` instead of `list`.
> Add support for query on subtables

- test/benchmark-common-tasks/main.cpp
The new support for path guard context is nicer but is not available in previous releases of core, which is a problem for the performance scripts. This partially reverts a change from https://github.com/realm/realm-core/pull/2506.
> Fix a compile error when benchmarking old core versions

- Visual Studio/Realm.vcxproj
The incorrect setting prevents dotnet from linking to core in UWP.
> Use the correct RuntimeLibrary when building for UWP in debug

- Visual Studio/Realm.vcxproj
- realm.xcodeproj/project.pbxproj
- src/realm/Makefile
- src/realm/util/overload.hpp
- test/test_util_overload.cpp
This is a minimal version of [C++ Library Evolution Working Group proposal P0051R2](http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0051r2.pdf). There are places in the object store and in the Cocoa binding where this would improve the code.
> Add a helper function to allow declaring an overload set using lambdas

- Jenkinsfile
- test/CMakeLists.txt
- test/bench/gen_bench.sh
- test/bench/util/build_benchmarks.sh
- test/bench/util/build_core.sh
- test/benchmark-common-tasks/CMakeLists.txt
- test/benchmark-crud/CMakeLists.txt
This enables the performance scripts to checkout, build, and benchmark versions of core using either cmake or a build.sh type system.
Each benchmark program now gets its own subdirectory in CMake because results are written to the same directory in files that would overwrite each other and get mixed up between benchmark programs.
The Jenkinsfile code is copied from master verbatim.
Build time should decrease because I made an optimisation to not bother building the whole test suite since we only care about the benchmarks.
> Performance support for cmake

- Jenkinsfile
The current implementation is faulty in the way that each time the warning collection step is invoked, it does not analyze only the result of the building step, but the whole console log up to that
point, including the other parallel branches. This results in incorrect and confusing results.
> Improve the collection of warnings during CI builds

- CHANGELOG.md
- src/realm/group_shared.cpp
macos has a bug (releasing an exclusive lock will only wake ONE thread waiting for a shared lock). In use cases where locks are held briefly, this does not cause problems, but in our use case --- where we hold shared locks for the full duration of having the database open --- it does.
This PR works around the bug by busy waiting on the shared lock.
Fixes #2434
> workaround a bug in flock on macos by busy-waiting

- src/realm/util/assert.hpp
Always call `realm::util::terminate()` from `REALM_UNREACHABLE()`  to avoid `noreturn` warnings in coverage mode.
@jedelbo @simonask
> Always call realm::util::terminate() from REALM_UNREACHABLE()

- src/realm/array_basic_tpl.hpp
Just write values to array. This will remove some issues reported by valgrind.
> Do not read uninitialized values in BasicArray<T>::create_array

- src/realm/util/terminate.cpp
- src/realm/util/terminate.hpp
Fixes compiler warning (Clang 4.0). The function's mangled name will change from C++14 to C++17 causing possible compatibility issues across that boundary.
Fixes #2553.
> Remove unused function set_termination_notification_callback

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- src/realm/util/interprocess_mutex.hpp
- src/realm/util/thread.cpp
- src/realm/util/thread.hpp
- test/test_shared.cpp
- test/test_thread.cpp
This allows for trying to obtain a write transaction in a non-blocking fashion.
Fixes #2538 
No tests yet.
> Nonblocking variant of begin write

- src/realm/column_table.hpp
- src/realm/query_engine.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
Only create subtable accessor if table is created
- When running a query, we should not create degenerated subtable accessors, but rather a ConstTableRef containing a nullptr.
About performance impact from this change: If you have a subtable column where most of the entries are null, then there is a big performance improvement (~ 300 %).
> Optimize query

- Jenkinsfile
- test/benchmark-common-tasks/main.cpp
Passing the target branch to the scripts makes them benchmark the last common commit at the divergence point of this pull request. This is especially nice when merging pull requests into a feature branch that is not master or develop. 
The wrong variable name was used here so there was an error in the performance script but it was not fatal because if the divergence point could not be understood then that version was just skipped.
> Fix base branch name for performance scripts

- CHANGELOG.md
- src/realm/column_mixed_tpl.hpp
- src/realm/column_table.cpp
- src/realm/column_table.hpp
- src/realm/descriptor.cpp
- src/realm/descriptor.hpp
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- src/realm/impl/transact_log.hpp
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/query.cpp
- src/realm/replication.cpp
- src/realm/spec.cpp
- src/realm/spec.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_replication.cpp
- test/test_table.cpp
Make Table::m_spec a pointer into the spec/subspec structure
We must follow the rule that we cannot have multiple accessor objects
for the same file object. For this reason a subtable accessor cannot
have its own spec accessor object. Rather should all accessors to
objects in the same subtable column share the same Spec accessor object.
So the Spec is changed from being embedded in the Table class to being
referenced. The Spec objects are being managed in a tree with root in
the root table Spec object. A new class - SpecPtr - is introduced to
handle the ownership of the Spec object. Only if the table is a table
with independent spec, the spec object should be deleted when the Table
object is deleted.
Support adding search index to subtable columns
You add the search index using the …
> Support adding search index to subtable columns

- CHANGELOG.md
- src/realm/index_string.cpp
- test/test_index_string.cpp
- test/test_query.cpp
The index tree traversal incorrectly (and redundantly) searched for non-unique keys, due to some characters being identical in the upper and lower case version of the search string (e.g. numbers).
This has now been fixed by filtering out identical _keys_, that is the 4-byte chunks of the search string that makes up the prefix tree that is our string index.
Related to https://github.com/realm/realm-cocoa/issues/4895
> Fix string index based case insensitive searches for strings containing numbers

- CHANGELOG.md
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/table.cpp
- src/realm/table.hpp
These functions compute the aggregated number of bytes of all the array nodes that make up a group or table respectively. In case of group, the result includes the sizes of all the tables in the group.
The purpose of these is mainly problem solving and diagnostics.
> Add compute_aggregated_byte_size() to classes Group and Table

- CHANGELOG.md
- src/realm/row.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
This follows the approach taken by Table::get() in making the templated function have the actual implementation and turning the existing non-template version into a wrapper. It also moves these wrappers to table.hpp as they'll trivially inline out of existence.
There are no changes to the bodies of the functions here other than moving where in the file they are.
> Add a templated version of Table::set()

- Visual Studio/Realm.vcxproj
- src/win32/pthread/pthread_mutex_init.c
As https://msdn.microsoft.com/en-us/library/aa382954(v=vs.85).aspx describes, Windows Store apps don't have access to the Global namespace.
However, there is the possibility for data loss if a Desktop app and a Store app access the same realm file because they wouldn't share the write mutex.
Without this change we cannot use realm-dotnet in UWP apps because creating a process-shared write mutex fails.
> On UWP, create shared mutexes in the Local namespace

- test/test_shared.cpp
Fixes #2588.
@rrrlasse I think this should fix it without ifdefing out the whole test, can you check?
Does windows now have support for `RobustMutex::try_lock` ?
> Clean up mutex in unit test

- CHANGELOG.md
- src/realm/lang_bind_helper.hpp
- test/test_lang_bind_helper.cpp
- test/test_link_query_view.cpp
I believe we need `LangBindHelper::get_backlink_table()` to finalize backlink support in Realm Java. I have also added a couple of unit tests to "document" backlink behaviour.
> LangBindHelper::get_backlink_table()

- src/realm/alloc.cpp
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/group_shared.cpp
- src/realm/group_writer.cpp
- src/realm/table.cpp
Confine the handling of file format version to the Group/SharedGroup
complex. There is no logic in having the allocator involved in this.
> Remove file format version handling from allocator

- CHANGELOG.md
- Visual Studio/Realm.vcxproj
That way end users won't need to have a Visual C++ redistributable package installed to run applications relying on realm-dotnet or realm-js on Windows.
> Statically link the VC runtime on Windows

- CHANGELOG.md
- src/realm/util/features.h
Ever since the encryption refactoring in core 0.95 to avoid mach signals for encryption, this has been possible but the checks preventing its use were never removed.
Addresses https://github.com/realm/realm-cocoa/issues/2876.
> Enable encryption on watchOS

- CHANGELOG.md
- src/realm/util/aes_cryptor.hpp
- src/realm/util/encrypted_file_mapping.cpp
- test/test_lang_bind_helper.cpp
The openssl implementation of [AES_cbc_encrypt](https://github.com/openssl/openssl/blob/b1498c98f3fb5b8a340acc9ce20b0fd5346294e5/crypto/modes/cbc128.c#L69) seems to use the destination as scratch and must make multiple iterations on a block before the decrypted result is produced. If we have multiple readers looking at the same mapping and a writer which updates that page in the file (at a later memory location) then one reader will find that the page is out of date and decrypt from the file again. This will work for the reader triggering the decryption, but the other reader that is using the same memory concurrently will have a chance to read the partially decrypted data.
The fix is to decrypt to a temporary buffer and copy the fully decrypted data afterwards. The memory is then …
> Decryption buffer

- CHANGELOG.md
- src/realm/alloc.hpp
A missing include because alloc.hpp calls from_twos_compl
> include <realm/util/safe_int_ops.hpp> in alloc.hpp

- test/bench/benchmark_version
- test/bench/revs_to_benchmark.txt
- test/benchmark-common-tasks/main.cpp
A stab at benchmarking the case insensitive queries, one with an index and one without.
- bump the benchmark version so that the performance reruns the suite for all previous core versions
- updated the versions to benchmark with the new release and removed some minor versions
> Benchmark insensitive queries

- CHANGELOG.md
- src/realm/table.cpp
A number of overloads of `Table::find_first` were not making it into the prebuilt core release for Node. Adding explicit instantiations ensures they do.
This is needed for realm/realm-js#1023.
> Explicitly instantiate Table::find_first

- CHANGELOG.md
- src/realm/group_shared.cpp
Two issues fixed:
- Now rejecting a Realm file specifying a history schema version that is newer than the one expected by the code.
- No longer triggering a history schema upgrade when opening an empty Realm file (when `top_ref` is zero).
@simonask @jedelbo 
Fixes https://github.com/realm/realm-core/issues/2636.
> Fix history schema version check when opening a Realm file

- CHANGELOG.md
- src/realm/group_shared.cpp
This sleep was causing unit tests in `realm-sync` to take very long to finish due to recent changes.
The sleep existed to exercise a particular critical section in the code, but there have been no bugs in this code for a long while.
> Disable call to millisleep during file upgrade

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
- test/test_version.cpp
This reverts commit 5171bdb7f24b47a0d161f3500ba97f8671b05364.
Trying to get back to smooth automated merges.
> Revert "Version bump to 3.0.0-rc1"

- CHANGELOG.md
- src/realm/group.hpp
- src/realm/group_shared.hpp
- src/realm/group_writer.cpp
- test/test_lang_bind_helper.cpp
In this PR:
- Fix an assert that prevented Group::commit() from discarding history from a Realm file opened in nonshared mode (via `Group::open()`, as opposed to via `SharedGroup::open()`).
- Improve documentation relating to history check when opening a Realm file.
- Add unit test `LangBindHelper_NonsharedAccessToRealmWithHistory`.
These changes were motivated by a need to use Group::open() for the purpose of sync server side migration.
@jedelbo @finnschiermer
> Fix Group::commit() for Realm file with history

- CHANGELOG.md
- Jenkinsfile
- build.sh
- src/realm/.gitignore
- test/.gitignore
- test/util/.gitignore
Improve ASAN and TSAN build modes (`sh build.sh asan` and `sh build.sh tsan`) such that they do not clobber the files produced during regular builds, and also do not clobber each others files. Also `UNITTEST_THREADS` and `UNITTEST_PROGRESS` options are no longer hard-coded in ASAN and TSAN build modes.
Following recent similar change in sync repo: https://github.com/realm/realm-sync/pull/1405
@finnschiermer  @simonask @emanuelez
> Improve ASAN and TSAN build modes

- .gitignore
I have switched to GNU Global, and I would like to see a cleaner `git status`. If you're an Emacs user, pop by my desk for a demo ;-)
> Ignore files produced by GNU Global.

- build.sh
This change force make to always use as many parallel processes as possible but always caring about the load of the machine. This should keep builds as fast as possible, while maintaining the machine usable.
> Make should always be sensitive about the load of the machine

- CHANGELOG.md
- src/realm/row.hpp
- src/realm/spec.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_table.cpp
Needed by users who wants to implement their own delete logic (like only delete the object if there are no other objects linking to it).
> Add method to get total backlink count for a row

- CHANGELOG.md
- src/realm/group.hpp
In this PR:
- `_impl::GroupFriend::get_top_ref()` was added.
- `const Group&` overload of `_impl::GroupFriend::get_alloc()` was added.
- Type of allocator argument changed from `Allocator&` to `const Allocator&` in `_impl::GroupFriend::get_version_and_history_info()`.
Motivation: For the purpose of migration, I needed to be able to fetch the history type and history schema version for a server-side Realm file opened via `Group::open()` in read-only mode. To this end, I needed to be able to call `_impl::GroupFriend::get_version_and_history_info()`, which takes allocator and `top_ref` arguments.
@jedelbo @finnschiermer
> Add _impl::GroupFriend::get_top_ref()

- src/realm/views.cpp
- test/test_query.cpp
Thanks to @bdash for pointing out that the behaviour of chained sorts was incorrect.
This fixes `sort(a).sort(b)`  to be equivalent to `sort(b, a)` instead of incorrectly being `sort(a, b)`
(Previous releases of core would consider `sort(a).sort(b)` to just be `sort(b)`.)
The use case is that user queries should respect the last sort operation to be the most important.
I didn't add a note to the changelog since this feature hasn't been released yet.
> Chained sort behaviour fix

- test/fuzz_group.cpp
As discussed, it is currently not supported to roll back a `merge_rows` instruction. This operation is only used by sync and will be deprecated soon. We shouldn't fuzz it because we can generate "impossible" transactions that will be false positive crashes.
> Remove the merge_rows instruction from fuzz testing

- CMakeLists.txt
- src/realm/table.cpp
The CMake regex for checking if we are compiling with clang was too strict and not adding compilation flags when it should have. Adding the flags produced a warning when compiling for watchOS which is fixed here as well.
This is cherry-picked from #2700 to separate ideas.
> Use strict warnings when using clang

- src/realm/CMakeLists.txt
This makes Xcode generated projects display the list of header files. Previously only the sources were available from an Xcode project.
According to [this article](https://www.johnlamp.net/cmake-tutorial-2-ide-integration.html), "Both Xcode and CMake know not to compile header files so there would be no actual effect on the build."
CMake organises the headers separately from the sources as shown below:
> Add headers to cmake generated xcode projects

- CHANGELOG.md
- src/realm/util/features.h
- src/realm/util/terminate.cpp
This solves the deprecation warning on OSX 10.12 by upgrading to the recommended `os_log` function while still keeping compatibility for building on older systems.
> Fix deprecation warning about asl_log on new OSX

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/group_shared.cpp
- test/test_replication.cpp
The root cause of the error is found to be the fact that SlabAlloc::attach_file would return 0 in case the caller is not session initiating. The fix is to read the stored history schema version in a read transaction.
Fixes #2724
> Fix history schema version check when opening a second SharedGroup

- build-afl.sh
- test/fuzzy/README.md
- test/fuzzy/simple_start.sh
- test/fuzzy/simple_stop.sh
- test/fuzzy/start_parallel_fuzzer.sh
- test/fuzzy/stop_parallel_fuzzer.sh
Update the `simple_start.sh` and `simple_stop.sh` scripts to work with the CMake system.
> Fix AFL scripts to work with CMake

- src/realm/column.hpp
- Enable inline checking of vectors in debug mode by defining `_GLIBCXX_DEBUG`
- This catches and fixes a problem with the `ColumnRandIterator<ColumnDataType>` not being const when the vector code calling it expects it to be. Specifically we get:
```
In file included from /usr/include/c++/5/debug/debug.h:127:0,
from /usr/include/c++/5/bits/stl_iterator_base_funcs.h:65,
from /usr/include/c++/5/bits/stl_algobase.h:66,
from /usr/include/c++/5/bits/char_traits.h:39,
from /usr/include/c++/5/string:40,
from /usr/include/c++/5/bits/locale_classes.h:40,
from /usr/include/c++/5/bits/ios_base.h:41,
from /usr/include/c++/5/iomanip:40,
from /home/parallels/Documents/code/realm-core/src/realm/index_string.cpp:20:
/usr/include/c++/5/debug/functions.h: In instantiation of ‘bool …
```
> Use strict vector checks in debug mode

- Jenkinsfile
Without this fix the initial CI stage will fail on `git describe --tags`
> Re-introduce the cloning of tags refspecs in CI

- CHANGELOG.md
- src/realm/table.cpp
- test/fuzz_group.cpp
- test/fuzzy/start_parallel_fuzzer.sh
- test/test_lang_bind_helper.cpp
If a transaction containing a call to optimise is rolled back we would crash when trying to refresh the accessor tree because we were still operating on a `StringEnumColumn` while the underlying spec had been reverted to a `StringColumn`. This can only be triggered by cancelling a transaction, it can't be triggered by advancing a transaction because there is no way to "unoptimise" a table (ie. once a column has changed to a `StringEnumColumn` there is no way to undo this). 
It looks like the only code calling `Table::optimize` is Object-Store's version of [compact](https://github.com/realm/realm-object-store/blob/b6b206760c0f1da77ff59eebcec8f5674084990f/src/shared_realm.cpp#L630).
Replaces #1789. Possibly (but unlikely) related to #2746.
> Fix crash on rollback of optimise

- CHANGELOG.md
- src/realm/table.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/test_lang_bind_helper.cpp
It's very hard to produce a call to `swap_rows()` at a time where this matters from the Cocoa binding, but it is theoretically possible and might be easier from other bindings.
> Update TableViews in Table::swap_rows()

- test/bench/benchmark_version
- test/bench/gen_bench.sh
- test/bench/gen_bench_hist.sh
- test/bench/parse_bench_hist.py
- test/bench/report_generator.py
- test/bench/revs_to_benchmark.txt
- test/bench/util/build_benchmarks.sh
- test/bench/util/build_core.sh
- test/benchmark-common-tasks/CMakeLists.txt
- test/benchmark-common-tasks/collect_stats.py
- test/benchmark-common-tasks/compatibility_makefile
- test/benchmark-common-tasks/stats.cpp
On request, this is a squashed version of #2700 (minus #2713). I've kept the formatting commit because it is non-functional changes only which should make the review easier.
These changes add the infrastructure to support tracking single statistics of a build. The initial statistics included are:
- lines of code
- size of static library
- size of various realm files
You can view these new graphs in the performance reports generated for this pull request.
> Add single stats to performance reports

- tools/release-init.sh
- tools/release-tag.sh
`sed -r` is not supported on Mac, the equivalent is `sed -E` which is not supported on Linux 😢 I switched to use `egrep` which is available on both.
`sed -i -e` was also needed to make the inplace replacement command work on both systems.
> Make the release script work on Mac and Linux

- Jenkinsfile
This is just cherry-picking 0b150af3812523aa7db to get the release to build.
> Use the CPH macOS slaves since the LV ones use a buggy version of CMake

- CHANGELOG.md
- CMakeLists.txt
- Jenkinsfile
- tools/build-cocoa.sh
- tools/cross_compile.sh
* Don't build shared libraries.
* Ensure that the files are copied into the expected location.
* Use .tar.gz for the intermediate archives, as they're much faster to work with.
* Have `-c` skip creating the .tar.xz archive, since it's typically not needed when `-c` is used.
I'm not 100% sure that build-cocoa.sh is the only thing that cares about the value of `CPACK_GENERATOR`. If it isn't, we'll need to take a different approach.
These changes reduce the time taken for `./tools/build-cocoa.sh -m -b -c /tmp/path` when no source changes have been made from ~75 seconds to ~10 seconds.
> Some improvements to build-cocoa.sh

- tools/build-cocoa.sh
- tools/cmake/tvos.toolchain.cmake
- tools/cmake/watchos.toolchain.cmake
cross_compile.sh does additional packaging work which is required to actually produce a working library, so use that from `build-cocoa.sh` as the Jenkinsfile does.
> Fix building for iOS/watchOS/tvOS with build-cocoa

- CHANGELOG.md
- CMakeLists.txt
- Jenkinsfile
- tools/build-cocoa.sh
- tools/cross_compile.sh
Fixes conflicts in CHANGELOG.md by creating the 2.9.0 release section as on master. This should allow future commits to master to merge to develop automatically without conflict.
Replaces #2770, #2771, and #2773.
> Merge master to develop

- src/realm/CMakeLists.txt
- test/CMakeLists.txt
Not sure if I set up this PR correctly, or who I should add, but I did make sure the test suite builds and runs the overload test correctly.
> Add overload.hpp and test back into CMakeLists

- CMakeLists.txt
- Jenkinsfile
- test/fuzz_group.cpp
- test/test_shared.cpp
- test/test_thread.cpp
- tools/cmake/SpecialtyBuilds.cmake
- Add support for building with thread and address sanitizers via cmake
- Automate these build modes so CI will run them for each PR
- Fix several errors/races in unit tests reported in these modes
- Track which unit tests are run by enabling `UNITTEST_PROGRESS` when testing
> Automate Address & Thread sanitization

- Jenkinsfile
This PR adds a `jobWrapper` step around the whole job, which will allow to print stacktraces before the build failure analyzer is executed. `jobWrapper` defined in the `ci` repo, in order to make it usable in other repos.
> Print stacktraces before the end of the job in order to give a chance to the BFA plugin

- test/bench/benchmark_version
- test/benchmark-common-tasks/collect_stats.py
- test/benchmark-common-tasks/main.cpp
- test/benchmark-common-tasks/stats.cpp
This is built on top of the single stats work (#2714), so it is tracked to merge into that branch.
This adds a graph showing the size of a Realm file with various numbers of transactions per release. It is meant to show how moving the transactions into the realm file has increased the overall size, it should shed light on #2343.
> Track realm file sizes with increasing transactions

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/impl/transact_log.hpp
- src/realm/replication.cpp
- src/realm/table.cpp
- test/test_lang_bind_helper.cpp
As with the old size in LinkListClear, this is needed only so that rolling back the clear can produce an insertion with the correct number of rows rather than zero, which is required for producing notifications for rollbacks.
The sync implications of this should be simple, as the similar case of clearing a LinkList is already handled, but if producing a correct value here is actually a problem then that's not the end of the world (it would allow removing some current hacks working around the lack of the size in the clear instruction in the non-rollback case).
> Add the old table size to ClearTable instructions

- test/test_utf8.cpp
The automatic conversion from `char*` to `StringData` uses the constructor that assumes the data is null terminated. Since these strings are randomly generated, this is not guaranteed and we would end up reading garbage data outside the string bounds which triggered warnings from valgrind and the address sanitiser when comparing the strings. This is solved by using the correct `StringData` constructor by passing in the length of the string. We can then run the test under valgrind.
> Fix uninitialised read in a unit test

- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_mutex.hpp
- test/test_thread.cpp
> Escape backslashes when creating named kernel objects

- CHANGELOG.md
- src/realm/spec.cpp
- src/realm/spec.hpp
- src/realm/table.hpp
- test/test_group.cpp
Fixes a use-after-free when a TableRef for a table with a subtable column outlives the owning Group.
This was actually hit by an existing test, but valgrind and asan did not report it due to that the invalid access was to memory on the stack. Moving the `Group` to a heap allocation is enough to make valgrind report the following error:
```
Invalid read of size 8
at 0x1010BC85C: realm::Allocator::get_replication() (alloc.hpp:369)
by 0x10139D0C6: realm::Spec::~Spec() (spec.cpp:29)
by 0x10139D1D4: realm::Spec::~Spec() (spec.cpp:27)
by 0x1013A524A: realm::Spec::SubspecPtr::~SubspecPtr() (memory:2537)
by 0x1013A00F4: realm::Spec::SubspecPtr::~SubspecPtr() (spec.hpp:137)
by 0x1013A4EEB: std::__1::__vector_base<realm::Spec::SubspecPtr, std::__1::allocator<realm::Spec::SubspecPtr> …
```
> Clear Spec's Subspec array when it is detached

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/exceptions.hpp
- src/realm/group_writer.cpp
- test/test_alloc.cpp
If approved, this will replace #2791. 
It checks the point of addition for overflow in a `size_t` or `ref_type` during allocation and throws a new exception instead of wrapping the addresses.
I added some debug prints to the existing assertions that we have reports of to help us understand what is going on if they aren't stopped by this.
Related to #2723.
> Throw an exception instead of overflowing large refs

- src/realm/group_shared.cpp
We now release slab immediately after commit. Without this change, slab is kept allocated for each open realm file between commits. Even though the data in the slab is never referenced again, it is "dirty" and will count against the kernels limit on dirty pages (require backing in physical memory). This may be of importance in settings where many realm files are open.
Inspired by #2812, though it is not known at the moment if it fixes it.
> Release slab as soon as possible after commit

- src/realm/table.cpp
Other explicit instantiations were added in #2624, but `BinaryData` was overlooked.
Needed to address realm/realm-object-store#526.
> Add an explicit instantiation of Table::find_first for BinaryData

- CHANGELOG.md
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
The `FlushViewOfFile` function returns immediately without waiting for the data to be written to disk.
> Improve durability on windows

- test/test_metrics.cpp
The CI machines could take longer if they are running multiple jobs. These tests are only meant to check that the timers are in the right ballpark.
> Relax timing tests

- CHANGELOG.md
- src/realm/column_type_traits.hpp
These traits are not always true. Columns holding strings can be of type `StringColumn` or `StringEnumColumn`, the leaf type depends on how big the strings are, and a sum operation doesn't make sense.
These column type traits are used in the query system and the relevant functions that make use of this information should all be overridden for the string type. If a specialised function is not provided, I would rather get a compiler error because these types are undefined than potentially use the wrong type.
> Removed incorrect and unused string type traits

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group_shared.cpp
- src/realm/util/file.hpp
We need to check for errors when writing to the output stream. Our implementation of `File::Streambuf` flushes the file buffer in the destructor and silently ignores exceptions thrown there intentionally (it is bad practice to throw exceptions from a destructor because it may cause an application abort if this happens more than once). Instead of letting the destructor trigger the disk sync, we can call `std::streambuf::pubsync()` manually which will throw exceptions if applicable. 
I tested this by creating a 1MB ramdisk and mostly filling it with a file (`mkfile -v 290k testfile`) then running a compact operation on a realm file that fills most of the rest of the disk. I observed that the compact version of the file was written to fill the rest of the disk but cut off when there was no …
> Compact exceptions

- src/realm/utilities.cpp
I got a sporadic failure on the t-san check with the following trace:
```
/home/jenkins/workspace/realm_realm-core_PR-2845-LO6ERV62KWBA3GBMEDDVGR24XM4VCQIMVORXIIZMCO4XFNUOCKJA@6/test/test_thread.cpp:943: Begin Thread_CondvarAtomicWaitUnlock
==================
WARNING: ThreadSanitizer: data race (pid=1352)
Atomic read of size 1 at 0x0000016c6960 by thread T4 (mutexes: write M24502):
#0 pthread_mutex_lock <null> (libtsan.so.0+0x000000037286)
#1 realm::util::Mutex::lock() ../src/realm/util/thread.hpp:489 (realm-tests+0x000001281fb9)
#2 realm::util::LockGuard::LockGuard(realm::util::Mutex&) ../src/realm/util/thread.hpp:526 (realm-tests+0x000001281fb9)
#3 realm::fastrand(unsigned long, bool) /home/jenkins/workspace/realm_realm-core_PR-2845-LO6ERV62KWBA3GBMEDDVGR24XM4VCQIMVORXIIZMCO4XFNUOCKJA@6/ …
```
> Fix reported race in fastrand

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_metrics.cpp
These were implemented in the object-store [here](https://github.com/realm/realm-object-store/blob/master/src/parser/query_builder.cpp#L55).
I'll make a PR to the object store to remove them and link it to this change too.
> Copy object store's true and false expressions down to core

- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- test/test_lang_bind_helper.cpp
with the new APIs, binding will be able to delete/replace the realm file
in a thread/process safe way.
close #2165
To replace #2835
> Add call_with_lock and get_core_files

- clang.Dockerfile
- doc/development/sanitizers.md
This is useful especially to use the advanced sanitizers available in Clang 5
To use this:
1. Build the image
```
docker build -f clang.Dockerfile -t realm-core-clang:snapshot .
```
2. Run the image
```
docker run -ti -v $(pwd):/tmp -w /tmp realm-core-clang:snapshot bash
```
Now you can build core and run the tests as usual. An example for the address sanitizer:
```
mkdir build
cd build
cmake -G Ninja -D REALM_ASAN=ON ..
ninja
cd test
./realm-test
```
> Add a Dockerfile for Clang 5

- CHANGELOG.md
- src/realm/exceptions.hpp
- src/realm/group_shared.cpp
- src/realm/util/file.cpp
By request, we now specialise `OutOfDiskSpace` from a generic runtime exception.
This can occur if the disk is full, or the user exceeds his disk quota.
I've tested it for when compact fails on a full disk (mac) since this is the case it is requested for.
@rrrlasse can you especially double check the windows section please?
> Specialised exception for OutOfDiskSpace

- src/realm/column.cpp
- src/realm/column.hpp
- src/realm/column_mixed.cpp
- src/realm/column_mixed.hpp
- src/realm/column_mixed_tpl.hpp
- src/realm/column_table.cpp
- src/realm/column_table.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/lang_bind_helper.cpp
- src/realm/lang_bind_helper.hpp
- src/realm/query_engine.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_ref.hpp
- test/test_column_mixed.cpp
- test/test_destructor_thread_safety.cpp
- test/test_shared.cpp
- test/test_table.cpp
This is a quickfix for https://github.com/realm/realm-core/pull/2853
It solves the problem(s) by
* Introducing locking around management of the subtable map
* Ensuring that pointers to subtables are transported as TableRefs or ConstTableRefs
to prevent deletion while there is still references around.
Work in progress.
This is not the optimal way of fixing #2853, which would be to avoid locking and use std::shared_ptr and weak_ptr instead of bind_ptr, but that is too big for now.
> Making subtable management thread-safe

- test/test_lang_bind_helper.cpp
The macro is always defined as either 0 or 1.
I found this because I was running the unit tests without encryption enabled at compile time and it produced a failure in that test.
> Fix encrypted unit test when running without encryption

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/query_engine.hpp
- test/test_query.cpp
Fixes #2867 where running a case insensitive "equals" query for null would return nothing even if nulls exist. The problem is that `case_map` function run on a null `StringData` would return the empty string (because of how we store our null `StringData` as an empty string with size 0). So I explicitly handle the case where the needle is null.
Also fixes another edge case that I saw where doing a case insensitive "contains" query for null would not return results that were in fact null. The case sensitive version of this query returns all results (including nulls).
These edge cases are tricky and it is another data point that we should spend the time to implement fuzz tests on our query code to verify results (see #1932).
> Fix null insensitive queries

- CHANGELOG.md
After release of 4.0 the fix for 2871 was merged into the release note for 4.0 - but it was only merged after release.
> fixed a bug in the changelog

- CMakeLists.txt
- Jenkinsfile
- src/realm/CMakeLists.txt
This was producing .cmake files in the packages which were not usable from downstream projects
> Don't add the shared library to the CMake export set

- packaging/generic/base-image/Dockerfile
- packaging/generic/build-image/Dockerfile
- packaging/generic/build-image/inside/build-package
- packaging/generic/build-image/inside/docker-entrypoint.sh
Centos 6 includes the oldest libc version we currently support (2.12), so it's a good idea to build the generic Linux image with it.
> Build the generic Linux build on Centos 6

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
@ironage found a race :-)...this is an initial fix.
The flow in compact() allowed another thread (or process) to observe the shared variable "num_participants" as 1 at a point during compact, where that observation would lead the other thread to assume it could trust the lockfile. However the lockfile becomes invalid after compact.
The fix is to hold the interprocess mutex all the way through compact() ensuring that all changes to num_participants are done before it is exposed to other threads.
> Fix a race between SharedGroup::compact() and SharedGroup::do_open()

- src/realm/CMakeLists.txt
So sync and java binding don't have to download openssl again.
And it avoids sync & binding using the different openssl version.
needed by https://github.com/realm/realm-sync/pull/1722
> Pack openssl with android build

- CHANGELOG.md
- src/realm/util/file.cpp
man posix_fallocate states:
```
posix_fallocate() returns zero on success, or an error number on failure.  Note that errno is not set.
```
With this in mind, we should report the return value and not the value in `errno`.
Additionally, `EINTR` is reported as a return code in fedora 24 (but strangely not mentioned in ubuntu 16). If it is interrupted, we can retry. It is hard to guess what the result of an interrupted `posix_fallocate` call would result in if not retried; the file would not be the expected size so this may fix errors like #2258.
> Make posix_fallocate robust against interruption, report right errors

- Jenkinsfile
This PR allows to:
* fail builds if the S3 operation fails. Before the error code was swallowed by `find`
* remove the dependency on `s3cmd`
> Improve the S3 operations

- CHANGELOG.md
- src/realm/util/safe_int_ops.hpp
- test/test_safe_int_ops.cpp
- test/test_util_stringbuffer.cpp
Adds unit tests for the safe int ops functions.
This revealed a bug in `int_multiply_with_overflow_detect()`.
@simonask I started this because you said there was an error on [line 457](https://github.com/realm/realm-core/blob/master/src/realm/util/safe_int_ops.hpp#L457) but I couldn't see anything wrong there - can you double check?
> Fix `int_multiply_with_overflow_detect()`

- CHANGELOG.md
- src/realm/table.cpp
Table::set_int() did not check if the target column was indeed type_Int. It will now assert like the other set methods.
> Missing type check in Table::set_int()

- Jenkinsfile
- test/test_metrics.cpp
This should fix `realm-core-Release-v4.0.3-Android-armeabi-v7a-devel.tar.gz` not being published in releases. This is the binary we run tests on so there was a different code path which missed adding it to the publishing stash.
> Publish artifacts from android tests too

- CHANGELOG.md
- src/realm/column_table.cpp
- src/realm/column_table.hpp
- test/test_lang_bind_helper.cpp
This case was found by our fuzz testing friends:)
The problem is that a subtable accessor could be given the wrong `m_ndx_in_parent` after a `move_row` operation.
I also added missing accessor lock on `SubtableColumnBase::adj_acc_move_row`.
Interestingly, in release mode this can cause a familiar error during commit: 
`../src/realm/group_writer.cpp:392: [realm-core-4.0.3] Assertion failed: ref + size <= after_ref with (ref, size, after_ref, ndx, m_free_positions.size()) =  [232, 312, 232, 2, 4]`
In debug mode it can cause:
`../src/realm/alloc_slab.cpp:440: [realm-core-4.0.3] Assertion failed: false && "Double Free"`
Depending on which operations follow.
> Subtable move_row

- CHANGELOG.md
- CMakeLists.txt
- src/realm/CMakeLists.txt
The `install` command for `realm-parser` was using `EXPORT realm-parser` instead of `EXPORT realm` and this caused the `install(EXPORT realm)` command to not pick up realm-parser and create an `IMPORT` target for it in the exported `realm-config.cmake` file.
> Fix realm-parser CMake export

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- test/test_table.cpp
This PR improves the performance in situations where version bumping due to changes are not really required, because any query depending on seeing such changes would note an earlier bump anyway. In this case, we now prune version bumping earlier than before. The hope is that this improves performance in scenarios with many changes without any queries in between. It is likely only noticeable if there are many tables with links or backlinks to each other.
> improve performance of data change management

- CHANGELOG.md
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
This PR uses a rowing "pointer" as basis for first-fit allocation. There is some chance that this approach will work better than the current approach in scenarios with high fragmentation. This is experimental.
> Use a rowing ptr as basis for allocation

- CHANGELOG.md
- tools/build-android.sh
Another fix to the packaging steps because the parser libs were found missing from the android packages (`realm-core-android-v5.1.1.tar.gz`).
> Android parser libs

- Dockerfile
- test/bench/revs_to_benchmark.txt
- test/benchmark-common-tasks/collect_stats.py
- Update the versions to benchmark with recent versions
- Exclude pegtl and win32/kalven-sha2 from source code count
- Include cheetah in Docker images to build old core versions
> Performance scripts update

- CHANGELOG.md
- packaging/centos-6/build-image/inside/build-package
- packaging/centos-7/build-image/inside/build-package
- packaging/ubuntu-1604/build-image/inside/build-package
The static libraries in the dev-dbg linux packages were actually dynamic libraries.
> Fix dev-dbg linux packages

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/data_type.hpp
- src/realm/exceptions.hpp
- src/realm/parser/collection_operator_expression.hpp
- src/realm/parser/expression_container.cpp
- src/realm/parser/expression_container.hpp
- src/realm/parser/parser.cpp
- src/realm/parser/parser.hpp
- src/realm/parser/parser_utils.cpp
- src/realm/parser/parser_utils.hpp
- src/realm/parser/property_expression.cpp
- src/realm/parser/property_expression.hpp
- src/realm/parser/query_builder.cpp
- src/realm/parser/query_builder.hpp
- src/realm/parser/value_expression.cpp
- src/realm/parser/value_expression.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_conditions.hpp
- src/realm/query_engine.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- src/realm/views.cpp
- src/realm/views.hpp
- test/test_metrics.cpp
- test/test_parser.cpp
This adds several stability fixes and support for comparisons between two properties (#2964).
To support two property expressions, a structural refactoring was required where each expression type is broken out to a separate file and controlled by a new `ExpressionContainer` class.
> Query serialization part 2

- CHANGELOG.md
- src/realm/column_string_enum.cpp
- test/test_lang_bind_helper.cpp
This was discovered by external fuzz testing.
The method `get_key_ndx_or_add()` would add the default string to the keys and not to the index if the number of rows to insert was zero.
This does not affect our users since enum columns haven't yet been released (see https://github.com/realm/realm-object-store/pull/501).
> Fix enums add zero rows

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/parser/collection_operator_expression.hpp
- src/realm/parser/expression_container.cpp
- src/realm/parser/expression_container.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- src/realm/parser/parser.cpp
- src/realm/parser/parser.hpp
- src/realm/parser/parser_utils.cpp
- src/realm/parser/parser_utils.hpp
- src/realm/parser/property_expression.cpp
- src/realm/parser/property_expression.hpp
- src/realm/parser/query_builder.cpp
- src/realm/parser/query_builder.hpp
- src/realm/parser/subquery_expression.cpp
- src/realm/parser/subquery_expression.hpp
- src/realm/parser/value_expression.cpp
- src/realm/parser/value_expression.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/util/serializer.cpp
- src/realm/util/serializer.hpp
- test/test_metrics.cpp
- test/test_parser.cpp
This adds support for subquery expressions and backlinks to the query serialiser and parser.
It also sets up the architecture for key path aliasing which could be useful for querying over named backlinks or when bindings allow referencing properties by other user defined names.
This is part of https://github.com/realm/realm-core/issues/2943
> Query serialisation part 3

- test/test_destroy_guard.cpp
Fixes #2870.
I generated the full stack with symbols by using `ASAN_SYMBOLIZER_PATH=path-to/clang5/bin/llvm-symbolizer ASAN_OPTIONS=symbolize=1`
The problem is that the variable that the destroy guard was reset to was initialised on the stack after the destroy guard itself. When the destructors are called, `foo_2` was destructed before the guard and this creates an access to bad memory. The fix is to just initialise `foo_2` before the guard.
<details>
```
=================================================================
==26641==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffdce87fe40 at pc 0x0000007bf16d bp 0x7ffdce87fc80 sp 0x7ffdce87fc78
READ of size 8 at 0x7ffdce87fe40 thread T0
#0 0x7bf16c in (anonymous namespace)::Foo::destroy() …
```
> Fix asan issue reported by clang 5

- src/realm/util/file.cpp
The allocation size was not adjusted for the additional pages needed for encryption headers, resulting in the call to `m_file.prealloc(initial_size)` during file initialization truncating away the previously-written data. This corrects that oversight, and also makes `File::prealloc()` a no-op if the size is smaller than the file's current size, to match the `posix_fallocate()` behavior.
No changelog entry because this was just introduced a few hours ago in https://github.com/realm/realm-core/pull/2973 and has not yet appeared in a release.
> Fix creating encrypted files on macOS

- packaging/ubuntu-1604/base-image/Dockerfile
Ubuntu 16 packaging in the Dockerfile is now [failing consistently](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/release%2F5.3.0/6/pipeline/84) with this error message:
```
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
ERROR: Failed to build gem native extension.
current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20180215-3941-z0q39.rb extconf.rb
checking for ffi.h... no
...
```
I attempt to fix this by manually install `libffi-dev` onto the image.
> Add libffi-dev to ubuntu16 dockerfile dependencies

- src/realm/array_basic_tpl.hpp
The warning is emitted numerous times while compiling core, cluttering up the output. Lasse's analysis in https://github.com/realm/realm-core/issues/2665 determined that it is a false positive, so there's no value to everyone suffering through it.
This has been bugging me every time I test on Linux.
> Silence a false-positive strict aliasing warning

- src/realm/query.cpp
- src/realm/table.hpp
- test/test_query.cpp
@bdash can you verify this fix? It's a bit hard to see what's going on.
In the old code, the `or_node` variable was true when the second Or() was invoked (because it saw the first Or() node in `current_group.m_root_node.get()`. So all three conditions of the query ended up in `m_conditions` of the first Or().
@kneth @beeender please carefully read the source code comment I have added to table.hpp for the link() and backlink() methods.
> Fix bug in Queries with two OR nodes at different nesting levels

- Jenkinsfile
As discovered in #2997, we should be testing mac builds on CI.
This PR should __fail__ until rebased on #2997.
> Test mac debug builds on CI

- CHANGELOG.md
- src/realm/util/file.cpp
- test/test_file.cpp
This is to fix https://github.com/realm/realm-core/issues/3005
I have verified that without the fix, the added unit test fails on HSF+ and gives a `EINVAL` on APFS.
This is using the code supplied by @bdash in #3005 with the suggested optimisation of only calling `fstat` once.
TODO: Before merging, I will check the behaviour of calling prealloc on a full ramdisk of each type.
> prealloc on apple

- CHANGELOG.md
- CMakeLists.txt
- src/realm/CMakeLists.txt
- test/CMakeLists.txt
- test/benchmark-common-tasks/CMakeLists.txt
- test/benchmark-crud/CMakeLists.txt
- test/fuzzy/CMakeLists.txt
- test/util/CMakeLists.txt
The build targets in CMake have been renamed. The file names of the resulting build products are unchanged (or should be).
The following targets are now produced and exported by the build system:
- `Realm::Core` (previously `realm`)
- `Realm::CoreShared` (previously `realm-shared`)
- `Realm::QueryParser` (previously `realm-parser`)
- `Realm::QueryParserShared` (previously `realm-parser-shared`)
- `Realm::RealmConfig` (previously `realm-config`)
- `Realm::RealmImporter` (previously `realm-importer`)
- `Realm::RealmTrawler` (previously `realm-trawler`)
- `Realm::realmd` (previously `realmd`)
Aliases have been set up for the old names to avoid excessive breakage. However, the targets exported in `realm-config.cmake` are the new ones.
> Rename targets to modern conventions, and put them in the Realm:: namespace

- CHANGELOG.md
- src/realm/group_shared.cpp
It's not used otherwise, and eats up a fd.
> Only open the balance mutex if async writes are enabled

- packaging/generic/build-image/inside/build-package
The rename was illegal because the `realm-config.cmake` file inside the tarball refers to the `lib64` dir.
There is probably a way to configure CMake to not put things in `lib64` if it is really necessary.
> Don't rename lib64 to lib in tarball

- CMakeLists.txt
A little while ago I made Sync's unit tests run much faster on Windows by slightly reducing the amount of debug facilities that MSVC enabled by default (including very expensive iterator checks and a stack-pointer validity check for every function call).
I have copied those changes into Core's build system.
> Speed up unit tests on Windows

- tools/cross_compile.sh
The benefit of doing it this way is that we also get the `realm-config.cmake` file included in the tarball, which means that downstream projects can use them out of the box.
Note: This also adds the `-devel` suffix for the tarballs. If anybody knows how to get rid of that (or whether we actually want to get rid of it), let me know.
> Generate tarballs for Apple platforms with CPack instead of manually

- CHANGELOG.md
- src/realm/util/file.cpp
- test/test_file.cpp
On APFS we observe that sometimes `fcntl(F_PREALLOCATE)` fails. It seems to be related to timing. If this happens we'll fall back to manually consuming this space like we do for windows/android.
See https://github.com/realm/realm-core/issues/3005
> If prealloc fails on APFS, fallback to manually allocated the file space

- CMakeLists.txt
I messed up in #3020 by forgetting to set the `NAMESPACE Realm::` option for the generated `realm-config.cmake`, meaning that consumers of Core would have to use the target `Core` instead of `Realm::Core`. We're all learning.
This fixes it.
> Missing NAMESPACE for generated realm-config.cmake

- CHANGELOG.md
- src/realm/parser/collection_operator_expression.hpp
- src/realm/parser/expression_container.cpp
- src/realm/parser/expression_container.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- src/realm/parser/parser.cpp
- src/realm/parser/parser.hpp
- src/realm/parser/parser_utils.cpp
- src/realm/parser/parser_utils.hpp
- src/realm/parser/property_expression.cpp
- src/realm/parser/query_builder.cpp
- src/realm/parser/value_expression.cpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- test/test_parser.cpp
- Allow an arbitrary prefix on backlink class names of @links queries. This will allow users to query unnamed backlinks using the `@links.Class.property` syntax because we can now hide the `class_` prefix from the binding level. It's a non-breaking change because the feature has to be explicitly set by bindings.
- Case insensitive `nil` is now recognised as a synonym to `NULL`. It's NSPredicate syntax and we had some users trying to use it.
- Add support for `@links.@count` which gives the count of all backlinks to an object. This fixes  #3003.
> Parser improvements

- CHANGELOG.md
- Jenkinsfile
Cocoa has dropped support for Xcode 8.2, so it's no longer necessary to keep building core with it for the older bitcode format.
> Switch to building Cocoa binaries with Xcode 8.3.3

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/table.cpp
This should enable offline file-compaction of sync'ed Realms (both on client and server).
> Include history refs in Group::write()

- src/realm/CMakeLists.txt
This should clean up the mess of linker errors on Linux with downstream components built with varying versions of GCC.
The problem was this:
- GCC 4.9 has a non-compliant C++11 ABI.
- Published Core artifacts are built with GCC 4.9
- Thus, downstream components must either be built with GCC 4.9, or set `_GLIBCXX_USE_CXX11_ABI=0` when building.
- This communicates to downstream components in `realm-config.cmake` whether Core was built with the old or the new ABI. Downstream components building with Core via CMake should now automatically gain the proper compiler flags to select the C++11 ABI.
I also took this chance to clean up some compiler flags of the `CoreObjects` target. `OBJECT` libraries in CMake aren't normal libraries, so they don't propagate compiler flags.
> Set _GLIBCXX_USE_CXX11_ABI=0 for dependents using realm-config.cmake

- CHANGELOG.md
- CMakeLists.txt
This was incorrectly dropped in the switch to the cmake build.
> Restore -fvisibility-inlines-hidden for Cocoa builds

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_lang_bind_helper.cpp
I have been observing a few warning when building core, and I just want to get rid of them.
> Fixing a few compiler warnings.

- CHANGELOG.md
- src/realm/group.cpp
It will never actually be used and just pointlessly makes the file larger.
Motivated by https://github.com/realm/realm-cocoa/issues/5799.
> Don't preserve non-sync history when writing to a new file

- src/realm/group_writer.cpp
These attempt to check all the places where we could accidentally store a negative value into the freelist lengths, as that appears to be happening somehow.
> Add some additional sanity checks to freelist management

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_blob.cpp
- src/realm/array_blob.hpp
- src/realm/array_blobs_big.cpp
Moving some code out of ArrayBlob that in reality should always be executed in context of an Array object. This also removed a cast that was really confusing.
> Refactoring ArrayBlob

- CHANGELOG.md
- src/realm/parser/query_builder.hpp
- test/test_parser.cpp
Requested by https://github.com/realm/realm-js/issues/1808
The error message was probably supposed to be something like "vector index out of bounds" but somehow got lost in the move from object store to core.
> Better error messaging when parsing queries which request args OOB

- CHANGELOG.md
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_replication.cpp
- test/test_table.cpp
This just does the bare minimum to support the combinations needed for creating objects for sync without double-updating the sync object id or objectstore pk columns.
> Add Table::add_row_with_keys()

- CHANGELOG.md
- src/realm/column_link.hpp
- src/realm/table.cpp
Removing and then re-adding the backlink is potentially very slow. It's unclear if this is actually the cause of the problem we're seeing, but it's an easy improvement.
> Add a fast-path for setting a link to its current value

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group.hpp
This PR allows us to distinguish the amount of memory used for
* State
* Transaction log
* Freelists
respectively.
> improvements to compute_aggregated_byte_size

- CHANGELOG.md
- src/realm/group_shared.hpp
This appears to have been the cause of some longstanding rare test failures that turned into very consistent test failures with the allocator changes.
> Don't mark space as free in rollback() until we're actually done with it

- packaging/centos-6/build-image/Dockerfile
- packaging/centos-6/build-image/inside/docker-entrypoint.sh
- packaging/centos-7/build-image/Dockerfile
- packaging/centos-7/build-image/inside/docker-entrypoint.sh
- packaging/generic/build-image/Dockerfile
- packaging/generic/build-image/inside/docker-entrypoint.sh
Centos6 removed the packages for devtoolsets 3, 4 and 5
devtoolset-6 still uses glibc 2.12 and ships with gcc 6.3
> Update the devtoolset from 3 to 6

- CHANGELOG.md
- src/realm/util/serializer.cpp
- test/test_parser.cpp
Found by @simonask in https://github.com/realm/realm-core-private/pull/181 in a Visual Studio debug build. This problem does not manifest on my dev system (mac/clang++) and since the "undefined behaviour" is up to the implementation of `std::isalnum` I would hope that release builds do the sane thing for negative inputs and just return false. So I'm not sure this is ever a problem in the wild.
I also found that the test to exercise this part of serialisation was incorrect due to an argument mixup and C++ automatically type converting them :(
> Fix undefined behaviour in the parser when serialising some unprintable chars

- CMakeLists.txt
- src/realm/CMakeLists.txt
This turns on iterator debugging (and other debug checks) for Core and for dependents on Core.
Supported compilers are GCC, Clang and MSVC.
Invoke CMake like this:
```
$ cmake <path> -DCMAKE_BUILD_TYPE=Debug -DREALM_DEBUG_EXTREME=ON
```
Users of the resulting library will also be built with extreme debugging.
> Add build-time option REALM_DEBUG_EXTREME

- test/util/CMakeLists.txt
Some compilation environment already does the right thing, but some other would fail to find `clock_gettime()`. This PR makes the dependency explicit.
> Explicitly depend on librt on Linux

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
This will allow Sync to write a file with new encryption key, but
will full content, ie. including history.
> Allow version number on Group::write

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- src/realm/util/backtrace.cpp
- src/realm/util/backtrace.hpp
- src/realm/util/terminate.cpp
- test/CMakeLists.txt
- test/test_util_backtrace.cpp
This feature has been requested (and implemented) by the Sync team, for the purposes of aiding robustness and debuggability in server environments (after-the-fact crashes in particular).
Included in this PR:
- A new utility class, `util::Backtrace`, which captures and encapsulates a stack trace. It is exceedingly paranoid about failures, in order to avoid a snowball effect in error scenarios.
- A wrapper base class for exceptions, `ExceptionWithBacktrace<T>`, where `T` is a fundamental exception type, such as `std::exception` or `std::runtime_error`. Custom exception types can inherit from `ExceptionWithBacktrace<T>` to get backtrace information included "for free". The `what()` method of derived classes will include the backtrace of where the exception was thrown. If the exception …
> Record backtrace when throwing certain exceptions

- CHANGELOG.md
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- test/test_shared.cpp
This is to support changing encryption keys in a robust manner handled by core itself.
> Add an optional output key to compact

- CHANGELOG.md
- Jenkinsfile
- tools/cross_compile.sh
The watch series 4 is a different architecture from previous watches so we need to add a slice for it to the watchos build. Awkwardly, this means that we need to use different versions of Xcode for different slices, as Xcode 9 can't use libraries built by Xcode 10.
This will currently fail to build on CI because Xcode 10 is not yet deployed on the workers.
> Build an arm64_32 slice for watchOS with Xcode 10

- CHANGELOG.md
- src/realm/views.cpp
- src/realm/views.hpp
- test/test_query.cpp
When a sort or distinct over links was done on an already-sorted TableView, the link translation map was done using the unsorted rows, resulting in the second sort/distinct being done with the incorrect values.
This appears to have been broken since the functionality was first introduced and is not a regression.
Reported at https://github.com/realm/realm-cocoa/pull/5936.
> Fix incorrect results for sort/distinct over a link after a sort

- CHANGELOG.md
- src/realm/util/allocator.hpp
As it turns out, MSVC has a buggy placement `operator new[]`. It trashes memory and returns an unaligned pointer!
I have reworked `util::make_unique<T[]>` to manually construct elements using the single-element placement new.
> Avoid array placement new

- Jenkinsfile
Fixup for Jenkinsfile in #3112. It accidentally overwrote some stashes, causing only `runtime` tarballs to be uploaded, but we need the `devel` ones.
> Fixup: Don't overwrite stashes

- CHANGELOG.md
- src/realm/group_writer.cpp
A corrupted freelist could lead to wrong allocations of space in the file potentially causing valid data to be overwritten. The added asserts will cause the process to fail earlier in cases where the wrong allocations are unaligned, potentially preserving more of the file.
> assert to protect file integrity in case of corrupted freelist

- src/realm/util/buffer.hpp
- src/realm/util/features.h
As a temporary measure until we get C++17 `[[nodiscard]]`.
The intent is to annotate functions where it is usually a bug to ignore the return value. If the return value of a function annotated with `REALM_NODISCARD` is ignored, the compiler will emit a warning.
> REALM_NODISCARD macro

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/group_shared.cpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
- test/test_lang_bind_helper.cpp
This PR builds on the experience that it is quite fast to calculate the size of the history and freelist part of the full state AND relatively fast to calculate the free space size. The state size is now calculated as `filesize` - `free space size` - `history size` - `freelist size`
Fixes https://github.com/realm/realm-core-private/issues/259
> Optimize get free space size

- CHANGELOG.md
- src/realm/util/allocator.hpp
- test/test_alloc.cpp
GCC 4.9 requires some allocator interface methods to be defined, even though the standard says they are optional. Newer compilers do not have this requirement.
I have also added some more tests.
> STLAllocator: Fixups for GCC 4.9

- src/realm/string_data.cpp
- src/realm/string_data.hpp
- test/test_string_data.cpp
Fixes #2929 
I have copied what libc++ does for `std::string`. On 64-bit platforms, CityHash64 is used. On 32-bit platforms, Murmur2 is used.
CityHash is competitive with very fast hash functions, such as XXHash.
Note: This can all go away once we switch to C++17, where the standard library is required to provide an implementation of `std::hash` for `std::string_view`.
The problem this solves is that we can't currently use `StringData` as the key type in `std::unordered_map`, but have to always use `std::string`, which is suboptimal because it needs to own its data.
To reviewers: Please do not feel obligated to review the details in the implementation of CityHash64. It's pretty long. ;-) It should be a straight up copy of the implementation in libc++ (with adjustments for code style).
> std::hash implementation for StringData

- src/realm/views.cpp
- src/realm/views.hpp
This is needed for partial sync to be able to postpone LIMIT to after permission checks.
> Add method DescriptorOrdering::remove_all_limits()

- src/realm/group.cpp
In this way we can catch cases of invalid top ref at an earlier
point.
> Add release mode asserts in Group::attach

- CHANGELOG.md
- src/realm/column_string_enum.cpp
- src/realm/query_engine.hpp
- src/realm/string_data.cpp
- src/realm/util/features.h
- src/realm/util/file.cpp
- src/realm/util/memory_stream.hpp
- test/test_thread.cpp
- test/test_upgrade_database.cpp
- Adds `REALM_FALLTHROUGH` in the appropriate places.
- Fixes some integer comparison.
- Replaces `readdir_r()` with `readdir()`. `readdir_r()` is deprecated in glibc.
- Fixes a bunch of shadowing warnings.
> Fix warnings reported by GCC 8

- CHANGELOG.md
- src/realm/group_writer.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
> Fix problem with posix_fallocate on AWS Lambda

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/group_shared.cpp
- src/realm/util/file.hpp
This will leave it up to the user to decide what to do
> Throw on invalid file

- CHANGELOG.md
- src/realm/util/file.cpp
This fixes a potential problem introduced in #3174, which could theoretically result in `DirScanner` skipping entries under certain error conditions.
This is likely the root cause for realm/realm-sync#2699.
The hypothesis is as follows: If `readdir()` temporarily sets `errno`, or `errno` was already set to `EAGAIN` from a previous system call, the retry loop would skip over valid directory entries even if no error occurred. This is fixed by checking the return value of `readdir()` before checking `errno`.
> Fix potential problem in readdir() error handling

- CHANGELOG.md
- src/realm/table.cpp
The add_row_with_key instruction can't express a null int key, so instead we emit a row insert plus set null. This needs to set the variant as SetUnique for sync to handle this properly.
I don't think this bug has any observable effects for a non-sync realm so there's nothing to test here.
> Emit the correct instruction for add_row_with_key(none)

- CHANGELOG.md
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
Prevent destruction of mutex as part of main thread shutdown, while it is still in use by other threads.
> fix for premature destruction of mutex

- CHANGELOG.md
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_all.cpp
- test/test_metrics.cpp
- test/test_transactions.cpp
There is a race between setting the governor and the governor running (caught by tsan here: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-3238/1/pipeline).
The problem was one function that was not being run under the protection of the mutex. I changed the governor interface to return a `std::function` which can be invoked without the mutex. This lets us protect the governor, but also allows the potentially long operations of getting the limit from various system files to be run asynchronously without blocking Realm encryption/decryption.
I don't think this race hits users because as far as I know, no binding is setting a custom governor. But the tsan tests should run clean.
> Fix a race setting the encryption governor

- CHANGELOG.md
- src/realm/metrics/query_info.cpp
- src/realm/metrics/query_info.hpp
- test/test_metrics.cpp
This was forgotten in the original implementation. The query text is only really useful if tied together with the table name that it was run against.
> Expose metrics query table name

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/group_shared.cpp
- test/test_replication.cpp
Fast way for Sync to make a snapshot file.^
Fixes #3243
> Add option to Group::write to strip history

- Jenkinsfile
- tools/cmake/SpecialtyBuilds.cmake
This enables downstream projects to use TSAN themselves. The build is produced for linux with clang 6 and only on core publishing runs.
It is a dependency of https://github.com/realm/realm-sync/pull/2852
> Publish a TSAN build

- CHANGELOG.md
- src/realm/array.hpp
- test/test_query.cpp
If the arrays holding the values are aligned differently (one on 16
byte boundary and one not), it will cause a segmentation fault when
using the SSE instructions.
Fixes #3253
> Fix error in two column query

- CHANGELOG.md
- Jenkinsfile
Xcode 8.3.3 will be going away from the CI machines soon (it no longer runs on macOS 10.14) so we need to move up to the oldest version still supported.
> Switch to building releases for Apple platforms with Xcode 9.2

- CHANGELOG.md
- src/realm/group.cpp
- test/test_replication.cpp
If Group::write() was called on a realm with client history without
specifying a version number, the history would be dumped, but not
included in the top array. This would lead to a memory leak.
Fixes https://github.com/realm/realm-sync/issues/2911
> Fix error in Group::write

- CHANGELOG.md
- src/realm/views.cpp
Table comparison is the wrong thing to do here because the implementation of `Table::operator==` checks for data equality across all rows. What was meant is that this is the same table, regardless of the data contained in it. A more lightweight check is now used just verifying name equality.
It's causing the object store tests to fail in https://github.com/realm/realm-object-store/pull/782
> Fix an incorrect debug mode assertion

- CHANGELOG.md
- src/realm/group_writer.cpp
- test/test_lang_bind_helper.cpp
Problem with previous algorithm was that it produced more small blocks
than could afterwards be consumed. So we would have an ever increasing
number of small blocks.
Instead of using the first block that is just big enough the algorithm
is changed so that we will accept either a perfect match or a block that
has at least twice the size as the size that is requested.
> Fix unbound growth of freelist

- CHANGELOG.md
- src/realm/timestamp.hpp
- test/test_column_timestamp.cpp
Added the ability to convert a std::chrono::time_point to a Timestamp and
vice versa. This allows us to make calculations using std::chrono::duration.
> Allow convertion of a Timestamp to a std::chrono::time_point

- CHANGELOG.md
- src/realm/alloc_slab.hpp
Fixes https://github.com/realm/realm-sync/issues/2961
> bugfix: move constructor for Slab must cleanup

- test/test_metrics.cpp
> Prevent promise to be set twice in Metrics test

- CHANGELOG.md
- src/realm/util/features.h
Added because they are needed in the context of the sync repository.
> New feature test macros for ASAN and TSAN

- src/realm/util/file.cpp
- test/test_util_file.cpp
- test/util/test_path.hpp
On Windows, Realm files and directories cannot be created if the path includes non-Latin characters (see https://github.com/realm/realm-js/issues/2319). Attempting to do so leads to errors such as `Unable to open a realm at path <path>: make_dir() failed: No such file or directory Path:.`. This PR allows Realms to be created in paths with non-Latin characters by using APIs such as [`_wmkdir`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mkdir-wmkdir?view=vs-2019) instead of `_mkdir`.
> Add Unicode path support for Windows

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group_writer.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
Fixes https://github.com/realm/realm-core/issues/3283
`util::File` now stores it's associated path if applicable.
I went through all the assertions in `alloc_slab.cpp` and added the path to the extended assertion message. For example:
`48  ??? 0x0000000000000001 0x0 + 1!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.2019-06-12 13:46:37.820598-0700 realm-tests[49951:493228] /Users/js/Documents/code/realm-core/src/realm/alloc_slab.cpp:581: [realm-core-5.20.0] Assertion failed: false && ref + size <= next->first with (ref, size, next->first, next->second, get_file_path_for_assertions()) =  [576, 16, 624, 24, "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/Group_SubtableDescriptors.1.path.realm"]`
> Add Realm path to allocator assertions

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- src/realm/metrics/metric_timer.cpp
- src/realm/metrics/metric_timer.hpp
- src/realm/metrics/metrics.cpp
- src/realm/metrics/metrics.hpp
- src/realm/metrics/query_info.cpp
- src/realm/metrics/query_info.hpp
- src/realm/metrics/transaction_info.cpp
- src/realm/metrics/transaction_info.hpp
- test/test_metrics.cpp
`SharedGroup:: get_metrics()` and all of the `Metrics` methods should be available to core users regardless of if the feature has been enabled or not with `REALM_METRICS`. This allows users to query the core metrics without worrying about guarding their code with `REALM_METRICS` compile time defines.
Since by default, `REALM_METRICS` is enabled, this change does not affect any bindings.
> Fix `REALM_METRICS` compile time inconsistency

- .gitignore
- CHANGELOG.md
- CMakeLists.txt
- Package.swift
- src/realm/CMakeLists.txt
- src/realm/util/features.h
- src/realm/version.hpp
- src/realm/version_numbers.hpp.in
- tools/release-init.sh
This is required for Cocoa to support SPM, as it only supports purely building from source with only SPM-based dependencies.
SPM doesn't have any concept of a "configure" step, so I pushed the part of version.hpp that cmake modifies into a separate header that isn't included when building with SPM and instead hardcoded the version number in package.swift. It can't simply read the version from dependencies.list because the package is evaluated in a sandbox with no access to any other files in the repository. The release script takes care of updating this additional copy of the version, so this shouldn't be a problem.
> Add a Swift Package Manager package

- CHANGELOG.md
- src/realm/views.cpp
Table equality is evaluated by comparing every row, which is a very expensive operation. The intent of the code which checks for table equality can be replaced by checking the table name.
This was discovered by a [customer](https://github.com/realm/engineering/issues/70) using the `includeLinkingObjects` feature of subscriptions.
> Better performance of an IncludeDescriptor

- CHANGELOG.md
- src/realm/metrics/query_info.cpp
- test/test_metrics.cpp
Query metrics are trying to serialize every query being run, and some do not have serialization support until core 6. For these, it is better to report an error string for the metric type instead of propagating the exception up the stack.
Fixes https://github.com/realm/realm-sync/issues/3031
> Fix metrics for unserializable queries throwing exceptions

- CHANGELOG.md
- src/realm/query_engine.hpp
- test/test_query.cpp
The query node incorrectly assumed that the start index would always be greater than the last-seen start index, which is correct for normal queries on a table but incorrect when the query is constrained by a linklist, as it then uses the linklist's order instead.
Fixes #3307.
> Fix queries on indexed int columns which are not in table order

- CHANGELOG.md
- src/realm/query_engine.hpp
The results of the index search are stored in a temporary `IntegerColumn` which is created and populated during `init()`. However, we only freed this memory in the destructor of the `IntegerNode` (which has a lifetime of the Query object). We also need to deallocate the results when the query is run again which is every `init()`.
I also changed the results to be a unique pointer to an integer column, which is an optimization so that an empty `IntegerColumn` is not constructed and destructed unnecessarily when the query node is created.
I believe this will fix https://github.com/realm/realm-cocoa/issues/6186 and maybe https://github.com/realm/realm-cocoa/issues/6167
> Fix a memory leak when indexed int queries are run more than once

- Jenkinsfile
- src/realm/row.hpp
- test/test_destructor_thread_safety.cpp
- test/test_index_string.cpp
- test/test_lang_bind_helper.cpp
- valgrind.Dockerfile
Our old valgrind job hasn't run for a long time because it was not dockerized. But we had a small memory leak recently and this would have helped us catch that. So this PR will make valgrind run on every release during the extended check phase.
The Jenkinsfile diff is mostly unreadable, but the change there is just to remove a top level `timeout` wrapper which was useless because the surrounding `jobwrapper` already has a [hard coded](https://github.com/realm/ci/blob/master/vars/jobWrapper.groovy#L5) timeout of 2 hours.
I've verified that a leak will fail the valgrind check, and will print the leak to the console. It takes about 40 minutes to test a `RelWithDebInfo` build, which is why I decided to put it into the extended release checks rather than for every PR since right now our PR's …
> Valgrind test

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
Otherwise we can continue to use the single write history
object although we are in a read transaction.
> Clear cached history object in commit_and_continue_as_read

- .idea/.gitignore
- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/util/fifo_helper.cpp
- src/realm/util/fifo_helper.hpp
- src/realm/util/interprocess_condvar.cpp
An attempt at fixing https://github.com/realm/realm-java/issues/5715
Object Store needs to be modified to use the same logic which is why it is moved to a separate header file.
Draft PR until I can verify this actually seems to work on Android (which is tricky).
TODO
> Make FIFO files world readable on Android.

- CHANGELOG.md
- src/realm/table.cpp
> Update stored 'next sequence number' during migration

- src/realm/query_conditions.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
std::string::data can now return char* instead of const char*. This
caused template argument matching that expected const char* to fail.
Solution: Use c_str() at the call site to force const char*.
Also, fixed it so that the error would be compile-time instead of
run-time.
> Fix C++17 run-time error in realm

- src/realm/array.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/benchmark-common-tasks/main.cpp
- test/test_query.cpp
Add TimestampNode specializations for: Equal, NotEqual, NotNull.
Here's the timestamp benchmarks for the naïve generic search: 
```
QueryTimestampGreater (MemOnly, EncryptionOff):     min  23.37ms (-50.62%)           max  25.34ms (-57.52%)           med  24.10ms (-56.46%)           avg  24.05ms (-55.09%)           stddev   588us (-86.42%)
QueryTimestampGreater (MemOnly, EncryptionOn):      min  23.34ms (-51.32%)           max  24.95ms (-64.54%)           med  23.79ms (-57.59%)           avg  23.81ms (-57.64%)           stddev   522us (-92.59%)
QueryTimestampGreater (Full   , EncryptionOff):     min  23.38ms (-50.77%)           max     25ms (-58.04%)           med  23.91ms (-56.68%)           avg  23.86ms (-54.99%)           stddev   517us (-88.96%)
QueryTimestampGreater (Full   , …
```
> Optimize timestamp queries: ==, !=, !NULL

- CHANGELOG.md
- src/realm/array.hpp
- test/test_column.cpp
- test/test_query.cpp
Fixed a bug where the reported match value was incorrect in some cases. This affects, sum() and average() query functions. This does not affect find_first() or find_all() because the index of the match is correct.
I thought this was only reproducible on 32 bit, but I got the added test to fail on 64 bit machines as well.
> Fix a query bug in average()/sum()

- CHANGELOG.md
- src/realm/exceptions.hpp
- src/realm/metrics/query_info.cpp
We run a lot of permissions queries in query based sync and these are currently not serializable because they use a `LinksToNode` to associate to a specific user and we don't have stable id's in core yet.
When query metrics are turned I noticed durning a cloud perf, that a not insignificant amount of time was being spent acquiring the backtrace for all these permissions queries which could not be serialized (~6% for a session which was servicing QBS). The simple thing to do is to not get the backtrace since it is not a critical error and is not used anyways.
> No backtrace for query serialization errors

- CHANGELOG.md
- src/realm/metrics/metric_timer.cpp
- src/realm/metrics/metric_timer.hpp
- src/realm/metrics/query_info.cpp
- src/realm/metrics/query_info.hpp
- src/realm/metrics/transaction_info.cpp
- src/realm/metrics/transaction_info.hpp
- test/test_metrics.cpp
This unit change is motivated by how we view these when enabled in grafana. We should report in the most precise units available and allow a view to convert the results into something less precise if desired.
There is also some question of if very small second double values (eg. 0.00000001) were being lost in the statsd->prometheus translation somewhere.
This will require some small code changes when sync updates, but I don't really consider this to be a breaking change because the stats work is still under development, so I marked it as internal.
> Changed metrics timers to report in nanoseconds

- src/realm/util/fifo_helper.cpp
This code was copied from ObjectStore, which uses a different define than Core. The correct define is now used.
The code path in question was only relevant for Android Blackberry devices though.
> Use correct define

- CHANGELOG.md
- src/realm/data_type.hpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- test/benchmark-common-tasks/main.cpp
- test/test_query.cpp
Although not timestamp specific, these changes are for https://jira.mongodb.org/browse/RCORE-4
There are three optimizations here:
1) If comparing to a constant value (applies to `Value<T>`) then do not evaluate this condition every time, only once.
2) If comparing to a link chain property which contains only unary links (ie there are no lists in the path) then we know there will only be one result or null; do not construct and destruct dynamic memory (vectors) for the results.
3) The default storage size of a `Value<T>` constructed by default or for a constant is changed from 8 to 1. Previously, a `Columns` expression would get the next 8 values in the column but only actually use the first one, so we save 7 memory fetches here.
Benchmark results on master:
```
QueryStringOverLinks …
```
> Optimize queries comparing a constant value over links

- CHANGELOG.md
- src/realm/array_string.hpp
- src/realm/array_string_long.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/test_query.cpp
BinaryData::size() includes the nul terminator while StringData::size() does not, so the BinaryData -> StringData conversion was incorrect and resulted in queries never matching when the low-level storage was ArrayBigBlobs.
Reported at https://github.com/realm/realm-cocoa/issues/6249.
> Fix incorrect results for long string or-equal queries

- CHANGELOG.md
- src/realm/util/serializer.cpp
- test/test_parser.cpp
The timestamp optimization (https://github.com/realm/realm-core/pull/3351) started using a different code path for serialization of timestamps in a query. Thanks @kneth for the reproduction! Fixes #3388.
> Fix timestamp null description

- CHANGELOG.md
- src/realm/util/file.hpp
Part of fixing https://jira.mongodb.org/browse/SYNC-26
> Include stacktrace for exception util::File::AccessError and it's derivatives

- CHANGELOG.md
- src/realm/version_id.hpp
Motivated by some changes in object store which compare two const VersionID objects. It must have been an oversight that these methods were not const in the first place.
> VersionID comparison operators are now const qualified

- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group.cpp
- test/test_lang_bind_helper.cpp
This PR reduces the amount of scratch memory initially allocated for slab. It also no longer does a reservation of virtual address space to have it readily available for later expansion of the slab area. This significantly reduces use of virtual address space during write transactions, especially for write transactions with little data.
> Reduce initial size of memory mappings used for slab

- CHANGELOG.md
- src/realm/table.cpp
- test/expected_json_nulls.json
- test/test_json.cpp
The change in Table::to_json_row just checks for null before proceeding to serialize values as per normal. The diff looks awful, but everything is just indented without modification.
> Fix json serialisation of null values

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/query_expression.hpp
Fixes https://github.com/realm/realm-core/issues/3393
The issues are:
```
In file included from /home/jenkins/workspace/realm_realm-core_release_5.23.5@2/src/realm/query_expression.cpp:19:0:
/home/jenkins/workspace/realm_realm-core_release_5.23.5@2/src/realm/query_expression.hpp: In member function 'void realm::SimpleQuerySupport< <template-parameter-1-1> >::evaluate(size_t, realm::ValueBase&)':
/home/jenkins/workspace/realm_realm-core_release_5.23.5@2/src/realm/query_expression.hpp:2121:32: warning: declaration of 'only_unary_links' shadows a member of 'this' [-Wshadow]
constexpr bool only_unary_links = false;
^
```
^ Fixed by changing the local variable name.
```
/home/jenkins/workspace/realm_realm-core_release_5.23.5@2/src/realm/group.cpp: In constructor …
```
> Fix several warnings

- src/realm/parser/query_builder.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/table.hpp
- test/test_query.cpp
We generally want users of Core to use the checking smart ptr, TableRef, instead of a raw Table&.
> IncludeDescriptor() should take TableRef, not Table&

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/query.cpp
- test/test_query.cpp
**Modify assert in Query::and_query**
In Core-5 you could get away with just comparing the pointers to the
linklist as the accessor object would be cached and reused. This is
not the case on Core-6 so now we just ensure that the tho lists are
referring to the same column in the same object.
**Fix opening a file with the size being a multiplum of 64MB**
**Add ConstObj::get_object_id()**
> Various updates

- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj_list.cpp
- src/realm/obj_list.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
This is motivated by the following cocoa perf test:
```
- (void)testEnumerateAndAccessQuery {
RLMRealm *realm = [self getStringObjects:500000];
[self measureBlock:^{
for (StringObject *so in [StringObject objectsInRealm:realm where:@"stringCol = 'a'"]) {
(void)[so stringCol];
}
}];
}
```
```
Before:
/src/realm-cocoa/Realm/Tests/PerformanceTests.m:60: Test Case '-[PerformanceTests testEnumerateAndAccessQuery]' measured [Time, seconds] average: 0.429, relative standard deviation: 1.735%, values: [0.418693, 0.432813, 0.440526, 0.442753, 0.421909, 0.428277, 0.428224, 0.422819, 0.424795, 0.431140], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "core 5", baselineAverage: 0.283, maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, …
```
> Improve performance of reading query results

- src/realm/CMakeLists.txt
- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- src/realm/cluster_tree.hpp
- src/realm/column_binary.cpp
- src/realm/query.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_tpl.hpp
- src/realm/util/file.hpp
- src/realm/util/function_ref.hpp
- test/test_lang_bind_helper.cpp
- test/test_query_big.cpp
- test/test_table.cpp
FunctionRef is a simple type-erased function wrapper which holds a pointer to the wrapped thing rather than copying it.
This ended up not having any runtime performance benefits (at least with libc++) because in practice most of the objects wrapped in std::functions are small enough to fit in the small-function buffer and not need an extra heap allocation. However, it does knock 15% off the size of the library due to how much simpler it is than the std::function machinery and helps compile times a bit too.
_      | Compile Time | Library Size | Test Executable Size | Realm.framework
-------|--------------|--------------|----------------------|----------------
Before |         710s |      7385 KB |            18907 KB  |       9948 KB
After  |         663s |      6293 KB |            18305 …
> Introduce and use FunctionRef where it is safe

- CHANGELOG.md
- src/realm/column_binary.hpp
- src/realm/column_timestamp.hpp
- src/realm/column_type_traits.hpp
- src/realm/mixed.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/util/file.cpp
- test/test_query.cpp
Change-Id: Ia8888fcf8530fd9b14740cab7228d320a0832887
> Use search index also when following links

- CHANGELOG.md
- src/realm/array.hpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- test/benchmark-common-tasks/main.cpp
Creating a `Cluster` isn't particularly slow, but in the hot loop in `ClusterNodeInner::get()` it still ended up being most of the run time. The benchmark results of this change are:
```
Req runs:   10  IterateTableByIndexNoPrimaryKey (MemOnly, EncryptionOff):     min  84.32ms (-53.58%)           max  87.02ms (-53.27%)           med  84.90ms (-53.90%)           avg  85.18ms (-53.65%)           stddev  1.01ms (-44.11%)      
Req runs:   10  IterateTableByIndexIntPrimaryKey (MemOnly, EncryptionOff):     min  69.98ms (-58.83%)           max  73.74ms (-57.01%)           med  71.84ms (-57.87%)           avg  71.42ms (-58.13%)           stddev  1.10ms (+114.74%)     
Req runs:   10  IterateTableByIndexStringPrimaryKey (MemOnly, EncryptionOff):     min 110.29ms (-47.42%)           max 111.85ms …
```
> Improve performance of looking up table entries by index

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_backlink.cpp
- src/realm/array_backlink.hpp
- src/realm/array_binary.cpp
- src/realm/array_binary.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer.hpp
- src/realm/array_key.hpp
- src/realm/array_string.cpp
- src/realm/array_string.hpp
- src/realm/array_timestamp.cpp
- src/realm/array_timestamp.hpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.hpp
- src/realm/table.hpp
Currently just calls verify() on each of the columns and adds a verify() function to ArrayBacklink that checks that the backlink invariants hold.
> Implement ClusterTree::verify()

- src/realm/array_backlink.cpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.hpp
- src/realm/group.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_group.cpp
- test/test_links.cpp
This is a functional requirement for KVO notifications to work well: something like `realm.delete(obj.listProp)` should produce a single array change reporting that all of the objects were removed. This can't be done at a higher level with how KVO's willchange/didchange design works.
To achieve this I moved to more like how core 5 did deletion, with separate link nullification and deletion passes so that we can figure out the complete list of mutations. I didn't try to take it all the way to the core 5 design of resolving the entire cascading delete on one notification; that seemed hard and sending one notification per cascade is probably nearly always fine (and no one is actually using cascading deletes right now...).
Along the way I also fixed a bug in cascading deletes without …
> Send cascade notifications in batches

- src/realm/bplustree.hpp
- src/realm/list.hpp
- test/test_links.cpp
There's a few spots where we want to be able to efficiently find all of the indexes in a list that a value appears.
> Add Lst::find_all()

- CHANGELOG.md
- src/realm/util/file_mapper.cpp
This has two main benefits: it allows the OS to perform timer coalescing and schedule the wakeup to align with other timers, which improves battery life, and it uses the Background QOS priority, which tells the OS it should deprioritize running our task when the device is under heavy load.
> Use a dispatch timer for the encrypted page reclaimer on Apple platforms

- CHANGELOG.md
- src/realm/column_table.cpp
- src/realm/table.hpp
The following sequence of events would double-delete the Table:
1. Thread A enters SubtableColumnBase::SubtableMap::refresh_accessor_tree(), holding m_subtable_map_lock.
2. Thread B releases the last reference to a Table in that SubtableMap.
3. Thread B blocks on acquiring m_subtable_map_lock in unbind_ref().
4. Thread A reaches that Table in the iteration and acquires a strong reference (0 -> 1).
5. Thread A finishes with that Table and releases the reference (1 -> 0).
6. Thread A deletes the Table due to the refcount going to 0.
7. Thread A releases m_subtable_map_lock.
8. Thread B acquires m_subtable_map_lock.
9. Thread B rechecks the (now deleted) Table's refcount and sees 0.
10. Thread B tries to delete the already deleted Table.
Fix this by not acquiring and releasing a strong …
> Fix a race condition in subtable accessor deletion

- src/realm/table.cpp
- test/test_group.cpp
find_first must return ObjKey() if the object is not created.
> Check object existence in Table::find_first<String>

- CHANGELOG.md
- src/realm/column.hpp
- test/test_table.cpp
Not handling NaN in the sort comparator results in it violating one of std::sort's preconditions (that the data have a total ordering), which with libc++'s implementation can result in out-of-bounds reads.
Fix this by generalizing the behavior for nulls (which we store as a tagged NaN) to all NaNs and using int comparisons to sort so that the NaNs are ordered.
See https://github.com/realm/realm-cocoa/issues/6357.
> "Fix" sorting float columns containing NaN

- src/realm/impl/transact_log.hpp
Column keys store a int64_t value, and think this would cause problems on 32 bit machines. I haven't been able to prove this with a test yet though.
> Core6: Use the right sized type for parsing column keys

- test/test_lang_bind_helper.cpp
Test that a lot of threads can concurrently create and execute queries against the same frozen transaction.
Also check that they can concurrently create and destroy object accessors for the frozen transaction.
> Test concurrent Querying against frozen transaction

- src/realm/table_view.cpp
- src/realm/table_view.hpp
Add explicit race detection in the heaviest part of TableView (the do_sync method).
> explicitly check for races in do_sync()

- src/realm/util/file.hpp
- test/test_thread.cpp
The latest Visual Studio 2019 comes with the implementation of the final `std::filesystem` draft and so the `<filesystem>` include is present. The `<experimental/filesystem>` include is now deprecated and we must silence the deprecation notice. We should migrate to `<filesystem>` once we switch to C++ 17.
> Fix <filesystem> error on latest Visual Studio

- CHANGELOG.md
- src/realm/query_engine.cpp
- test/test_query.cpp
NOT queries cache information about what range of rows has already been checked, and when checking a range of rows immediately before the cached range which does not contain any matches, find_first() would return the first row within the cached range which matched. Since this wasn't not_found, this was considered a match even though it wasn't in the range [start, end).
See https://github.com/realm/realm-cocoa/issues/6289.
> Fix incorrect query results for NOT on a LinkList

- src/realm/table_ref.cpp
- src/realm/table_ref.hpp
- test/test_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_metrics.cpp
This enables slightly better codegen and lowers the (small) overhead of passing
them around instead of raw pointers.
Change-Id: I3a5ae4b871fdee4ef312e424223e49ed554cd30d
> Make TableRef's constructors explicitly noexcept

- src/realm/cluster.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_group.cpp
Don't add indexes to string columns when setting them as the primary key (and remove any existing index) to match the behavior of creating new tables with string PKs.
Don't use ObjectIDs to validate PK uniqueness for non-indexed columns as changing the PK makes it so that the PK and object keys are no longer connected. This probably isn't otherwise an issue because ObjectIDs are only used for synced realms, and the PK can't be changed on synced tables anyway.
> Fix changing primary keys in existing tables

- src/realm/column.hpp
- test/test_table.cpp
The original implementation assumed that you could compare floats/doubles as ints, which apparently is not the case.
> Fix the float sorting algorithm

- CHANGELOG.md
- src/realm/obj.cpp
- test/test_group.cpp
This issue is causing the following assertion failure in the js tests when upgrading to core v6.0.0-beta.2: 
```
transaction() for: /var/tmp//realm_Y7NFqw/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm
read_group() for: /var/tmp//realm_Y7NFqw/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm
../src/realm/mixed.hpp:152: [realm-core-6.0.0-beta.2] Assertion failed: m_type
0   realm.node                          0x00000001061183dc _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   realm.node                          0x0000000106118696 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 390
2   realm.node …
```
> Fix rebuilding pk columns with a null key

- src/realm/alloc_slab.cpp
> fix wrong hint in map insertion in slab alloc

- src/realm/obj.cpp
- test/test_table.cpp
This can in many cases make the reading logic simpler in cases where you
have already assured that the value is not null.
> Read int from nullable column using get<Int>

- test/test_metrics.cpp
In the two affected tests, it was possible for the page reclaimer to collect workload data before the tests started and then report the collected data to the new governor installed by the tests. This would cause the governor to work on the stale data and they'd be reported to the metrics system, causing the tests to fail.
By requiring 2 calls to the new governor before reporting, we can ensure that the data used are collected during the actual test - not stale data previous tests.
> fix a race involving the page reclaimer and 2 unittests for the metrics

- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
Warning:
```
../src/realm/decimal128.cpp: In function ‘realm::Decimal128 realm::to_decimal128(const BID_UINT128&)’:
../src/realm/decimal128.cpp:234:42: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘class realm::Decimal128’ from an array of ‘const struct BID_UINT128’ [-Wclass-memaccess]
234 |     memcpy(&tmp, &val, sizeof(Decimal128));
|
```
> Silence g++ warning about memcpy on non-trivial type

- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/keys.hpp
- src/realm/list.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.hpp
- src/realm/util/file.hpp
- src/realm/util/optional.hpp
- src/realm/util/thread.hpp
This is required for std::vector<> to actually use the move constructors rather than copying. A bunch of these probably don't matter, but it was easier to use clang-tidy to just fix them all than to figure out which ones actually do need it.
The specific motivation for this is that adding a ColKey member to Property made Property no longer nothrow_move_constructable which resulted in some nontrivial copies instead of moves.
> Mark all move constructors/assignment operators as noexcept

- src/realm/alloc.hpp
Improve performance of alloc::translate by avoiding a few memory accesses.
Potentially also fix a thread sanitizer false positive (the now removed reloads would always reload
the exact same value, but the thread sanitizer might not see that).
Inspired by https://github.com/realm/realm-core/pull/3584
> optimize alloc::translate, also possibly remove a tsan false positive

- src/realm/list.cpp
- src/realm/obj.hpp
- test/test_table.cpp
And beef up the list of primitives tests to cover more types.
> Add missing symbol for Obj::set<Optional<ObjectId>>

- src/realm/array_object_id.hpp
- src/realm/decimal128.hpp
- src/realm/object_id.cpp
- src/realm/object_id.hpp
- src/realm/table.cpp
- test/test_table.cpp
The migration code for converting columns between optional and non-optional was not implemented for the new data types.
set_null() on ObjectId would crash if the array was in a read-only mapping due to missing copy_on_write().
> Fix a few things with Decimal128 and ObjectId

- src/realm/array.hpp
- src/realm/bplustree.cpp
If we are replacing the root with an inner node, that node may not be writeable.
> Make copy_on_write when setting context flag in BplusTree<ObjKey>

- src/realm/alloc.hpp
- src/realm/array.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer.hpp
- src/realm/impl/transact_log.hpp
- src/realm/util/hex_dump.hpp
- src/realm/util/safe_int_ops.hpp
- test/experiments/query_expr.hpp
- test/test_safe_int_ops.cpp
- test/util/super_int.hpp
1. C++ now guarantees two's complement
2. Use platform-provided overflow detection
> Clean up safe_int_ops.hpp

- CHANGELOG.md
- src/realm/util/features.h
- src/realm/util/terminate.cpp
We have to check if os_log is available at runtime, not at compile time.
Fixes https://github.com/realm/realm-cocoa/issues/6403.
> Fix a crash on startup on macOS 10.10 and 10.11

- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
Cloning a Query involved passing around a Transaction to the tree of query nodes that was never actually used for anything. This was a remnant of the core 5 logic where we held onto references to Columns which had to be updated when performing handover, but query nodes no longer hold onto any persistent references that tie them to a specific Transaction.
There's one semi-exception: subqueries. Fortunately, we already don't actually support subqueries which would require handing over any members in the child query. A subquery derived from a LnkLst or TableView isn't really a meaningful concept, can't be expressed in the query language, and would have given incorrect results if assembled manually.
> Simplify query node cloning

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_basic_tpl.hpp
- src/realm/array_blob.cpp
- src/realm/array_decimal128.cpp
- src/realm/array_integer.hpp
- src/realm/array_object_id.cpp
- src/realm/array_string_short.cpp
- src/realm/array_unsigned.cpp
- src/realm/array_unsigned.hpp
- src/realm/node.cpp
- src/realm/node.hpp
Now the size, width, and value bounds cache members are kept consistent with
the data in the array header. Previously Array::alloc() only update the
header, forcing every caller to update the cache members manually.
> Array::alloc() shouldn't break class invariants

- src/realm/query_expression.hpp
- src/realm/utilities.hpp
- test/test_parser.cpp
The code to fall back to the old query engine needed to be updated for each new type which is added. This shifts the checks around a bit to not need this, as the set of types which support fallback is presumably fixed while the non-supported types will grow.
> Fix column comparison queries on Decimal128/ObjectId

- test/test_lang_bind_helper.cpp
- test/test_shared.cpp
TSAN doesn't understand when we double map a page and use the same memory from
different threads at different addresses.
> Remove TSAN false positives caused by double-mapped paged

- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
- src/realm/object_id.cpp
- src/realm/object_id.hpp
- src/realm/util/to_string.cpp
- src/realm/util/to_string.hpp
We want to be able to validate is a string is a valid decimal128 without conflating NaN and invalid syntax. A bool-returning function also makes the code using it a bit less awkward than catching an exception would be.
The NSNumber API needs a 3-way compare function and I think it makes sense to push that logic down to here. Implementing the comparison operators on top of that cuts down on some duplicated code.
Using `util::to_string()` rather than `ostringstream` reduces the compiled size a bit.
> Add some helper functions for Decimal128

- src/realm/CMakeLists.txt
- src/realm/array_backlink.cpp
- src/realm/array_key.cpp
- src/realm/array_key.hpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- src/realm/table.hpp
- test/test_unresolved_links.cpp
Verify Link lists by ArrayKey::verify() and not at part of backlink verification.
Verify single links too.
Take unresolved links info account.
> Improve verification of link and linklist columns

- src/realm/alloc.cpp
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/node_header.hpp
- src/realm/util/file_mapper.hpp
- test/test_destroy_guard.cpp
- test/test_lang_bind_helper.cpp
- test/test_table.cpp
This PR removes the requirement to have a contiguous memory mapping of the entire realm file.
It works by dynamically detecting whenever an attempt is made to access a memory block that crosses a memory mapping boundary. It then adds a dedicated additional memory mapping for that particular memory block (the "cross-over" mapping).
Note to reviewer: this is tricky code because a) it has to provide "mostly lock-free" concurrent access to the ref translation table and b) the translation code is the hottest code path in Core.
The code is very carefully tuned to avoid performance degradation.
> Remove contiguous mapping requirement

- src/realm/cluster.cpp
The object store notification code needs these to report cascaded deletions of embedded objects. We don't want to emit sync instructions for this, but the sync replication code can handle filtering them out.
> Emit remove_object() instructions for embedded objects

- Jenkinsfile
- Package.swift
The decimal128 library needs to be added to the spm package. I also made it so that the spm build is actually tested on CI so that this sort of thing'll be caught in the future.
> Fix the Swift package build

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/cluster_tree.hpp
- src/realm/group.hpp
Work around an issue with MSVC in Visual Studio 2019 where Release optimizations crash the compiler because of a regression in 64bit atomic loads on 32bit Windows.
Many thanks to @RedBeard0531 who actually researched the issue and the fix.
> [MSVC] work around a compiler regression in VS2019

- test/test_lang_bind_helper.cpp
> reenable 'LangBindHelper_CompactLargeEncryptedFile' unittest on Android

- CMakeLists.txt
- src/realm/util/config.h.in
- src/realm/util/file.cpp
This is a more narrowly scoped solution. It doesn't change any other code to
support 64-bit file offsets. This also means that consumers don't need to set
a compatible _FILE_OFFSETS_BITS in order to call core functions that take
off_t arguments.
> Stop defining _FILE_OFFSETS_BITS and use readdir64 instead where available

- src/realm/cluster.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/impl/transact_log.cpp
- src/realm/impl/transact_log.hpp
- src/realm/table.hpp
Only call one function in the replication interface when creating
a table and when creating an object.
The following functions will be called:
add_class (table key, name, embedded)
add_class_with_primary_key (table key, name, pk_type, pk_name, pk_nullable)
create_object (table, GlobalKey)
create_object_with_primary_key (table, GlobalKey, pk value)
Should be seen in relation to https://github.com/realm/realm-sync/pull/3280
> Simplify table and object creation replication interface

- Jenkinsfile
- src/realm/obj.cpp
Fixes https://github.com/realm/realm-core/issues/3103
The new functionality is added in https://github.com/realm/ci/pull/288, but this core PR adds more descriptive names to each warning collection phase. Builds are failed if warnings are detected, and reported along with the source code line. Previously, it was very tedious to find out why a build was failing and what the warning was because you'd usually have to manually look through the entire log of the build for the output. Now you'll see the output as below:
> test new warnings plugin

- CHANGELOG.md
- src/realm/util/file.cpp
Fixes https://github.com/realm/realm-cocoa/issues/6508.
This fix was tested manually on an external ExFAT storage device from a mac where I could also replicate the reported bug.
Using `fcntl` is an optimization, so this fix is a "defensive" way to allow for yet another error case. But another way to fix this, would be to always try the fallback if anything fails, regardless of the error. If reviewers would prefer the latter, I'd be happy to open it up further.
> fcntl not supported on some filesystems

- src/realm/string_data.hpp
This is important for the primary use case of being a universal receiver argument type:
```cpp
std::string make_string();
void take_string(StringData input);
take_string(make_string()); // <--- should compile!
```
See https://quuxplusone.github.io/blog/2019/03/11/value-category-is-not-lifetime/ for more details about why this should be considered an anti-pattern.
> Allow constructing a StringData from a temporary std::string

- CHANGELOG.md
- src/realm/table.cpp
The initial value for TableKeys and ColKeys in the m_opposite_xxx members of the table accessor was incorrectly set to 0 instead of -1.
> fix incorrect init of m_opposite_xx subarrays in Table

- CHANGELOG.md
- src/realm/table.cpp
If the upgrade process was interrupted after the normal columns had been migrated
but before migration of the link columns, then the process would crash when it was
resumed.
> Fix potential issue with interrupted upgrade

- CHANGELOG.md
- src/realm/keys.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.hpp
- test/test_link_query_view.cpp
The optimization added in #3432 to use the search index when performing equality queries over a link assumed that Queries would be evaluated in ascending table order, which is not always the case when the query is being performed on a link list.
Fixes realm/realm-cocoa#6540.
> Fix incorrect query results on a LnkLst that does not match table order

- src/realm/table.cpp
The initial value for TableKeys and ColKeys in the m_opposite_xxx members of the table accessor was incorrectly set to 0 instead of -1.
Also added some resilience to Table::has_any_embedded_objects().
> fixes related to m_opposite_xxx subarrays in Table for v10

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.hpp
- src/realm/object-store/list.cpp
- src/realm/table_view.hpp
- test/benchmark-common-tasks/main.cpp
- test/test_transform.cpp
Move m_obj attribute to ConstLstBase class.
Prevent creating ConstLst objects.
Remove ConstLnkLst
Remove move-constructors - not obvious where they could be useful.
> Reduce overengineering of Lst implementation

- CHANGELOG.md
- src/realm/table.cpp
- test/test_table.cpp
- test/test_unresolved_links.cpp
Fixes https://jira.mongodb.org/browse/RSYNC-128
> Erase embedded objects when parent object is erased by sync

- CHANGELOG.md
- src/realm/list.hpp
- test/test_lang_bind_helper.cpp
find_first() doesn't require bounds checking, so we don't call size() before it and it needs to handling updating itself.
Fixes https://github.com/realm/realm-cocoa/issues/6606.
> Add missing update_if_needed() to ConstLst::find_first()

- src/realm/table.cpp
- src/realm/table.hpp
- test/test_table.cpp
The object store code which calls this needs to know if it's populating a new object or modifying an existing one. Currently it does that by looking up the object first and only calling create_object_with_primary_key() if it doesn't exist, which results in some duplicated code and a redundant lookup.
> Report whether create_object_with_primary_key() created a new object

- CHANGELOG.md
- src/realm/db.hpp
- src/realm/group.cpp
https://github.com/realm/realm-cocoa/issues/6629 reported a case where the transaction log parsing managed to be an overwhelming majority of the runtime.
The parsing done for schema change notifications only needs to be done if there's actually a schema change handler set.
Passing a non-null NullInstructionObserver when no observer is supplied results in the transaction log being parsed just for the null observer, which obviously doesn't do anything useful with it.
> Avoid parsing the transaction log when it isn't needed

- CHANGELOG.md
- Jenkinsfile
- tools/build-cocoa.sh
- tools/cmake/Utilities.cmake
- tools/cmake/ios.toolchain.cmake
- tools/cmake/tvos.toolchain.cmake
- tools/cmake/watchos.toolchain.cmake
This PR adds the functionality needed to produce an `xcframework` which will be consumed Cocoa. It works by adding an additional step in `tools/build-cocoa.sh` that grabs builds of `librealm` for each architecture,  platform and build type, then places them in a temporary folder and performs `xcodebuild create-xcframework`. This will produce two `.xcframeworks` that are then added to the `core` folder.
The two `.xcframeworks` produced are:
- `realm-core-dbg.xcframework`
- `realm-core.xcframework`
> Add ability to produce xcframework

- CHANGELOG.md
- src/realm/table.cpp
The bug would surface if the upgrade process was interrupted and then
resumed.
Fixes https://github.com/realm/realm-cocoa/issues/6644
> Fix upgrade bug when having string primary key column

- CHANGELOG.md
- src/realm/db.cpp
- test/test_shared.cpp
SlabAlloc::detach() sets m_youngest_live_version to 0 and attach() doesn't touch it (as it comes from the lockfile rather than anything it has access to), so compact needs to set m_youngest_live_version after attaching the allocator to the new Realm file. Failing to do this resulted in the first ref translation table being deallocated after the first write transaction even if it was still in use, resulting in a use-after-free for whatever was using it.
Fixes https://github.com/realm/realm-cocoa/issues/6652. Fixes https://github.com/realm/realm-cocoa/issues/6628. Fixes https://github.com/realm/realm-cocoa/issues/6555.
> Fix reattaching the allocator after compact

- CHANGELOG.md
- Jenkinsfile
- tools/build-cocoa.sh
- tools/cmake/Utilities.cmake
- tools/cmake/ios.toolchain.cmake
- tools/cmake/tvos.toolchain.cmake
- tools/cmake/watchos.toolchain.cmake
- tools/cross_compile.sh
Xcode 12 finally added a 64-bit watchOS simulator, so we now need to build for that platform as well. This uses the same logic as we used when they added 64-bit watchOS devices; the new arch needs to be built with Xcode 12, but the old arches need to continue to be built with Xcode 11 due to bitcode not being backwards-compatible.
> Add support for the 64-bit watchOS simulator

- CMakeLists.txt
- src/realm/array.hpp
- src/realm/group_writer.hpp
- src/realm/impl/transact_log.hpp
- src/realm/replication.hpp
- src/realm/util/base64.hpp
- src/realm/util/buffer.hpp
- src/realm/util/sha_crypto.hpp
- test/util/jsmn.hpp
When using xcframeworks Cocoa can no longer use -isystem to ignore warnings from core headers, so these now pop up when building Cocoa.
> Fix warnings when building with -Wdocumentation

- CHANGELOG.md
- src/realm/list.cpp
Only the constructor was being instantiated rather than the entire class. This worked by coincidence most of the time, but when building a shared library with LTO enabled dead code stripping would drop all of the member functions not called elsewhere in the library.
Fixes https://github.com/realm/realm-cocoa/issues/6625.
> Explicitly instantiate Lst templates correctly

- CHANGELOG.md
- src/realm/cluster.cpp
- test/test_shared.cpp
Iterators should not throw when copied, even if they are no longer valid.
Potentially fixes https://github.com/realm/realm-cocoa/issues/6597.
> Don't throw when copying an invalidated ConstIterator

- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/transform.cpp
- test/test_changeset_encoding.cpp
A bunch of places were missing checks on `prior_size` for array instructions, and this revealed that `ArrayMove::prior_size` was never populated.
> [HELP-17413] Sync: Validate prior_size more aggressively

- src/realm/parser/query_builder.cpp
- src/realm/query.cpp
- src/realm/query_expression.hpp
- src/realm/util/features.h
480k reduction on realm-java arm64 build with parser
* pull throwing of exceptions out to non-templated functions
* convert templated functions in query_builder.cpp to return Query so the code
to add it to the tree is only needed once.
* FORCEINLINE overloads for invalid combinations
* Counterintutively, this actually shrinks the binary because the compiler
is able to directly call the `throw_foo_error` function, which propagates
the information about it never returning. It is also able to redirect
branches that lead there to the same instructions, which it wasn't able to
do previously because each template instantiation was considered a
different function, even though they did the same thing.
> Reduce binary size of query_builder.cpp and query.cpp

- test/CMakeLists.txt
In a Xcode 11.6 build (generated with cmake 3.18.2), I was getting signing errors which prevented me from running the CoreTests target. Looks like we needed to let Xcode copy the test resources itself which allows it to sign them. I'm not sure if this is a requirement of the new Xcode, or a mixup in the cmake code, because the first time I have run the monorepo branch locally.
> fix Xcode signing of core test assets

- CHANGELOG.md
- Jenkinsfile
- src/realm/util/interprocess_mutex.hpp
- test/main.cpp
- test/test_file.cpp
- test/test_group.cpp
- test/test_util_file.cpp
- test/util/test_path.cpp
- test/util/test_path.hpp
- tools/run-tests-on-exfat.sh
exFAT doesn't actually allocate an inode for a file until it's non-empty, which results in our checks based on that to fail. The most immediate implication of this was that all interprocess mutexes ended up sharing a single local mutex and deadlocking if more than one is ever locked at once.
exFAT also doesn't support some file permissions-related things so a few tests need to be skipped when running on it, but none of them appear to be functionality we depend on.
Fixes https://github.com/realm/realm-cocoa/issues/6691.
> Fix deadlocks on exFAT

- CHANGELOG.md
- Jenkinsfile
- tools/build-cocoa.sh
- tools/cross_compile.sh
The addition of the arm64 simulators for apple silicon machines invalidates the whole concept of simulator+device universal libraries, so this updates the build scripts to not rely on them. Instead of a single job which produces a combined simulator+device library, they are now separate jobs and the universal library (without the arm64 slice) is assembled during the packaging step. The xcframework package consumes these directly without lipoing anything.
Building the arm64 simulator slices just requires switching to Xcode 12. Fortunately, while libraries for devices built with Xcode 12 don't work with Xcode 11 (because bitcode is not backwards-compatible), it works fine for simulator libraries and we can just build for all simulator platforms with 12.
`xcodebuild -create-framework` …
> Add arm simulator slices to the xcframework

- test/bench/report_generator.py
- test/bench/revs_to_benchmark.txt
Aims to fix the error: `parse error while processing semver of v6.0.18-316-gd49905aedinvalid literal for int() with base 10: 'gd49905aed'` as seen in the performance report logs of https://github.com/realm/realm-core/pull/3852
> performance report bug

- CHANGELOG.md
- src/realm/util/file.cpp
- test/test_lang_bind_helper.cpp
When deleting a Realm file which doesn't actually exist we'll call DB::call_with_lock() without the management directory existing. Fortunately the directory not existing indicates that no readers exist, so this is fine when acquiring an exclusive lock.
> Allow calling DB::call_with_lock() when the management directory doesn't exist

- src/realm/cluster.cpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/dictionary_cluster_tree.hpp
- src/realm/spec.cpp
- src/realm/spec.hpp
- src/realm/sync/changeset.cpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instructions.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_changeset_encoding.cpp
- test/test_dictionary.cpp
- test/test_sync.cpp
- test/test_transform.cpp
It was a mistake to make the type encoded in the column key indicate the key type - it should reflect the value type.
> Make column type indicate value type of dictionary

- CHANGELOG.md
- tools/build-cocoa.sh
#3859 accidentally made it so that the package used by realm-js and cocoapods did not include a macos library.
> Actually include the macos libraries in the package

- Jenkinsfile
- tools/build-cocoa.sh
The macos parser library was accidentally being deleted by the code cleaning up the pre-merge simulator/device libraries. This also adds a xcframework package for the parser library as JS and .NET will need that for catalyst and arm64 simulator support.
> Add macosx parser libraries to the release package

- src/realm/keys.hpp
- src/realm/mixed.hpp
- src/realm/sync/instruction_replication.cpp
- test/test_dictionary.cpp
- test/test_sync.cpp
This PR fixes some holes in tombstone handling for Dictionaries and Mixed.
Also added some commented-out unit tests in preparation for solving the problem that Dictionaries (as well as lists of Mixed and TypedLink) expose tombstones.
> [RSYNC-124] Dictionary / Mixed tombstone handling

- CHANGELOG.md
- src/realm/util/features.h
- src/realm/util/file.cpp
- src/realm/util/file.hpp
Opening the pipe in read-only mode results in the OS process which launches apps deadlocking when unsuspending the app on iOS 10-12, so opening it in read-write mode.
This also makes the emulation only be used on device, as using it in the simulator makes it so that the file can't be opened in Studio at the same time.
> Fix a deadlock when unsuspending apps on iOS 10-12

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_query.cpp
If we use the wrong allocator to translate refs belonging to a table
m_ref_translation_ptr may not point to the most recent mapping.
Fixes https://github.com/realm/realm-java/issues/7118
> Fix use of wrong allocator when running query over links

- CHANGELOG.md
- src/realm/query.cpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/benchmark-common-tasks/main.cpp
The relevant benchmarks:
```
Req runs:   96  QueryChainedOrStrings (MemOnly, EncryptionOff):                   min   5.05ms (-0.43%)            max      6ms (+8.36%)            med   5.17ms (-0.46%)            avg   5.17ms (-0.77%)            stddev   103us (+9.04%)       
Req runs:  231  QueryChainedOrStringsIndexed (MemOnly, EncryptionOff):            min   2.05ms (-0.01%)            max   3.30ms (+29.51%)           med   2.17ms (+1.65%)            avg   2.25ms (+3.88%)            stddev   212us (+91.60%)      
Req runs:   26  QueryNotChainedOrStrings (MemOnly, EncryptionOff):                min  17.80ms (-1.37%)            max  18.97ms (-0.73%)            med  18.25ms (-1.32%)            avg  18.30ms (-1.21%)            stddev   254us (-10.64%)      
Req runs:   26 …
```
> Improve performance of NOT IN on indexed properties

- test/test_transactions.cpp
This test is only run on master and not on PRs so it's been failing ever since the file format version was bumped.
> Update a failing test

- src/realm/alloc_slab.cpp
If we have a +-1 error this could give a different error signature.
> Allocate one extra element in ref translation table

- CHANGELOG.md
- src/realm/util/function_ref.hpp
Mutable lvalue function refs were getting wrapped in another function ref rather than copied because the templated constructor was the best match. This didn't cause any correctness problems but was sometimes annoying when debugging
and caused a small perf hit (~5% on the benchmarks where the difference is statistically significant).
> Fix FunctionRef copying

- CHANGELOG.md
- src/realm/query_engine.cpp
- test/test_query.cpp
When one run of a query on an indexed string column matched multiple objects and then a subsequent one matched one, m_index_matches was not set back to null and so would incorrectly continue to be used in index_based_aggregate().
This would result in either incorrect results (if the first matching object was mutated to no longer match) or throwing "key not found" if the first matching object was deleted.
Fixes https://github.com/realm/realm-cocoa/issues/6536.
> Correctly update queries on indexed string columns going from multiple matches to one

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/test_table.cpp
Constructing a ObjKey from a value read in the index went wrong.
FIxes https://github.com/realm/realm-dotnet/issues/2025
> Fix index lookup

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_table.cpp
Queries for null on a non-nullable property shouldn't be returning anything. This is a small optimization for these types of queries on string/timestamp/binary and a fix for int.
> fix int null query on indexed non-null column

- CHANGELOG.md
- src/realm/query_engine.cpp
- test/test_query.cpp
FIxes https://github.com/realm/realm-cocoa/issues/6830
> Correctly update case insensitive queries on indexed string columns

- test/test_parser.cpp
We occasionally saw seconds roll over for example: `./test/test_parser.cpp:3966: ERROR in Parser_ObjectIdTimestamp: CHECK_EQUAL(generated_pk.get_timestamp().get_seconds(), ts_now.get_seconds()) failed with (1600870617, 1600870618)`
> fix a sporadic test failure

- CHANGELOG.md
- src/realm/column_type_traits.hpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
- test/test_table.cpp
- test/test_types_helper.hpp
I've created some test type wrappers that will allow us to more easily template our tests for every type, in the hopes that this will reduce the likelihood of having uncovered corner cases like this.
The templated tests revealed an inconsistency that we don't provide query expression support for BinaryData == or != for `null` so I added those in as well.
The first commit is the cherry-picked fix from https://github.com/realm/realm-core/pull/3947 (so that the merge from master to v10 isn't so bad).
> Fix ObjectId indexed query for null

- src/realm/util/thread.hpp
I have found this in realm-core 5.4.2 and it's still present.
> Fix missing semicolon in src/realm/util/thread.hpp

- CHANGELOG.md
- src/realm/column_type_traits.hpp
- src/realm/list.hpp
- test/CMakeLists.txt
- test/test_table.cpp
- test/test_types_helper.hpp
The bug is because the comparison ends up evaluating `Optional<Float>{} == Float(NaN)` which is false. The fix is to use the checks in column_type_traits.hpp which handle null from Optional types correctly.
I'm also pulling in some of the new test helper code from v10 because it makes writing generalized type tests much easier.
> fix list of primitives is_null() for optional float and double

- src/realm/CMakeLists.txt
- src/realm/exec/CMakeLists.txt
The SDKs don't need those targets when using Core as a submodule.
> Don’t build exec targets in LIB_ONLY builds

- Jenkinsfile
- src/realm/object-store/CMakeLists.txt
- src/realm/sync/CMakeLists.txt
- tools/build-cocoa.sh
- tools/cross_compile.sh
This PR merges core, sync & object-store libraries, creating a librealm-monorepo.a binary when building with `build-cocoa.sh`. This binary will be packaged as an xcframework. The parser library will also still be packaged as its own xcframework.
> Package monorepo as xcframework

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_blobs_small.hpp
- src/realm/array_unsigned.cpp
- src/realm/array_unsigned.hpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/index_string.hpp
- src/realm/spec.cpp
- src/realm/spec.hpp
- src/realm/table.cpp
- src/realm/table.hpp
Since core 6, we do not actually filter accessor updates based on the "baseline" argument provided to update_from_parent(), because the argument provided "at the top" when initiating accessor update is always forced to 0.
This PR simply removes all the redundant parameter passing and filtering code that is now trivially true.
> eliminate use of 'baseline' in filtering accessor updates

- CMakeLists.txt
- src/realm/sync/CMakeLists.txt
- tools/cmake/RealmConfig.cmake.in
- Make it possible for integrators to use a custom Zlib
This is needed for Node.js, which exports its own zlib headers and symbols
- Don’t use find_package(ZLIB) on Apple platforms
Instead link with `-lz` and let Xcode sort it out
- Don’t define export or package targets if in a submodule build
> Zlib ergonomics

- CHANGELOG.md
- src/realm/keys.hpp
- src/realm/query.cpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/benchmark-common-tasks/main.cpp
- test/test_table.cpp
Fix a bug when evaluating SizeListNode for `Lst<Optional<Int>>` type which applies to `Query::size_*()` methods. This is because we were instantiating BPTree<Int> where we should be using BPTree<Optional<Int>> because it stores a magic null value in the list and subtracts one from the size.
The change to `SizeListNode` removes one dimension of template instantiation which reduces about 200k from the release library size. The type check is now done at run time, but the benchmark added shows a negligible impact.
```
Req runs:    6  QueryListOfPrimitiveIntsSize (MemOnly, EncryptionOff):     min  70.96ms (-0.06%)            max  75.05ms (-1.02%)            med  72.46ms (+0.77%)            avg  72.70ms (+0.39%)            stddev  1.65ms (-8.56%)
```
Base monorepo branch size report:
``` …
```
> SizeOfList updates for v6

- CHANGELOG.md
- Package.swift
Xcode's Archive command has started building packages for all platforms they claim to support even if the app doesn't consume those platforms. In our case, this results in errors when building for 32-bit iOS because that platform does not fully support C++17. Fix this by setting the deployment target for iOS to 11, which dropped support for 32-bit.
> Set the supported platforms for the Swift package

- CHANGELOG.md
- src/realm/array_basic.hpp
- test/test_set.cpp
- test/test_types_helper.hpp
> Fix Set::erase_null() for float/double

- test/object-store/realm.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/file.cpp
- test/object-store/sync/metadata.cpp
- test/object-store/sync/session/connection_change_notifications.cpp
- test/object-store/sync/sync_manager.cpp
- test/object-store/sync/user.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_utils.cpp
- test/object-store/util/test_utils.hpp
this is causing the bulk of the object-store sync tests to fail on windows because they can't find `/tmp`. It looks like https://en.cppreference.com/w/cpp/filesystem/temp_directory_path will give us the correct info on each platform and fall back to `/tmp` if there is no correct info.
> ROBJSTORE-134 do not hardcode temp directory in object-store tests

- test/object-store/bson.cpp
The bson corpus tests capture the cheir check function as a function pointer. On some compilers this means that when the function is being called during the check, the lifetime of the lambda representing the check has already expired.
> ROBJSTORE-135 Fix type deduction for arguments to corpus_check lambdas

- CHANGELOG.md
- src/realm/array_backlink.hpp
- src/realm/array_basic.hpp
- src/realm/array_binary.cpp
- src/realm/array_binary.hpp
- src/realm/array_bool.hpp
- src/realm/array_decimal128.hpp
- src/realm/array_fixed_bytes.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer.hpp
- src/realm/array_key.hpp
- src/realm/array_list.hpp
- src/realm/array_mixed.hpp
- src/realm/array_string.cpp
- src/realm/array_string.hpp
- src/realm/array_timestamp.hpp
- src/realm/array_typed_link.hpp
- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/node.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
- test/test_query.cpp
- test/test_query_big.cpp
- Optimized column comparisons of different types as TwoColumnsNode can be used instead of the generic Compare expression for more cases
- Removed the column type template dimension from TwoColumnsNode which reduces the library size by ~120k
- Simplified the column vs column Query interface so that instead of `Query::equal_<int/double/float...>(ColKey, ColKey)` there is just `Query::equal(ColKey, ColKey)`
The cost of all this is performing an extra type check at runtime when evaluating the query, but it doesn't seem to have a noticeable performance impact.
> Enable cross type comparisons in a TwoColumnsNode

- CHANGELOG.md
- src/realm/keys.hpp
- test/test_group.cpp
If column keys are not unique we end up finding the wrong backlink column during upgrade.
Fixes https://github.com/realm/realm-java/issues/6992
> Ensure column keys in virgin tables are unique on 32bit devices

- src/realm/object-store/impl/windows/external_commit_helper.hpp
fix SharedMemory on Win32 targets
https://github.com/realm/realm-object-store/pull/1129/files into core-6
don't close the mapped file handle cause the mapped file can not be opened from another process. This fixes the sharing of memory needed to synchronize realm file access between windows processes
Contained in branches:
core-6-fix-sharedmemory-win32
Contained in no tag
Derives from no tag
> fix SharedMemory on win32

- src/realm/alloc.hpp
- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/db.cpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/impl/transact_log.cpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/list.hpp
- src/realm/object-store/results.cpp
- src/realm/query.cpp
- src/realm/query_expression.hpp
- src/realm/set.hpp
- src/realm/sync/instruction_applier.cpp
- src/realm/table_view.hpp
- test/object-store/transaction_log_parsing.cpp
- test/test_links.cpp
- test/test_table.cpp
- test/test_unresolved_links.cpp
There were some issues with the current interface hierarchy surrounding collections:
- `LnkLst` derived publicly from `Lst<ObjKey>`, but uses a different "index space", because `LnkLst` hides tombstone links (unresolved links), while `Lst<ObjKey>` doesn't. This meant that it was easy to accidentally call a method on `LnkLst` and get or use indices that don't make sense or are out of bounds. `LnkLst::find_first` and `LnkLst::find_all` had this problem.
- `Lst<T>` could not be marked `final` due to the inheritance, which prevents devirtualization (inlining, direct method call, etc.).
- Several methods were statically overridden, rather than dynamically, resulting in dispatch based on the type of pointer you had, rather than the actual type of the instance. This could lead to similar bugs.
- …
> Collection, Lst<T>, LnkLst interface cleanup / refactor

- test/test_file_locks.cpp
When building with TEST_DURATION >= 1 num_rounds is declared as int, but later it’s compared to size_t so let’s just change the type
> Fix File_NoSpuriousTryLockFailures2 warnings

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/object-store/sync/sync_session.cpp
We now can run the Cocoa sync tests with thread sanitizer enabled, which unsurprisingly revealed a few bugs.
If a SyncSession is created before the corresponding RealmCoordinator there was a data race on the transaction callback.
App's route members are set on a background thread after fetching them from the server and so need synchronization.
> Fix several data races in object store sync code

- Jenkinsfile
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- test/object-store/CMakeLists.txt
We hadn't built the Android tests for a while on the monorepo branch so they ended up broken. For one thing, Object Store tests need libuv, so we had to fetch that for Android.
I refactored the warnings in the Jenkinsfile so that the issue analyzer always ignores external libraries (libuv produced a number of warnings). I also refactored the `doAndroidBuildInDocker()` function so that it can build just the libraries, build the libraries and tests, and build the libraries and tests and also run them.
Now for each PR we'll build the Android libraries and the tests, and on release builds we'll also run the tests. Previously we only built the libraries on each PR and that didn't alert us to the tests breaking on Android.
> Build Android tests on every PR

- src/realm/binary_data.hpp
- src/realm/mixed.hpp
- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- src/realm/query_conditions.hpp
- src/realm/util/serializer.cpp
- test/test_array_mixed.cpp
- test/test_parser.cpp
- test/test_query.cpp
- test/test_query2.cpp
I concluded that it was not possible to guess the type of the argument from the type of the other sub-expression. If we take `.@avg`, the type is `double`, but the argument could be given as `int`. Even if the property we calculate the average of is `int` then it should be possible to compare with `double`.
> Improve handling of Arguments

- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
support list of primitives string or binary element length (as opposed to size of the entire list) and making sure it is done in a way that doesn't limit people from having properties called "len" or "length".
> bison element length operator support

- src/realm/parser/driver.cpp
- test/object-store/sync/app.cpp
- test/test_parser.cpp
It came as a total surprise that we accepted `a == "45"` if `a` is an int property.
> Fix OR query and conversion of string constants to numbers

- src/realm/parser/driver.cpp
- test/test_parser.cpp
The majority of this PR is just enhanced error checking and making readable error messages.
The recent improvements to the query system has enabled more queries that previously we restricted: ALL/NONE conditions through a link path that contains multiple lists or backlinks.
> bison error checking for any/all/none

- CHANGELOG.md
- src/realm/group.cpp
Cherry-picking https://github.com/realm/realm-core/pull/4098
> fix a race allowing access to incomplete init of table accessor

- CHANGELOG.md
- Jenkinsfile
- tools/build-cocoa.sh
'realm-*-cocoa*.tar.xz' does not match the xcframework package so it wasn't actually published. The non-xcframework package also accidentally included the parser xcframework.
> Fix publishing Cocoa releases

- evergreen/config.yml
- src/realm/sync/dump_command.cpp
The changes in #4123 didn't update dump_command.cpp to work with the new DataType types. This fixes that file so that compile succeeds again.
> Fix dump command compile after changes in #4123

- src/realm/list.hpp
- src/realm/set.hpp
- test/object-store/list.cpp
- test/test_links.cpp
Copy-constructing a stale collection accessor would cause init_from_ref to be called with a stale ref.
This asserts that the source accessor is not stale when copy-constructing.
It's hard to see what the right approach should be here. The internal `BPlusTree<T>` in the copied `Lst<T>` cannot be initialized if the source instance is stale, so the "staleness" should probably be copied over instead and then update_if_needed when needed. This requires wrestling a bit more with the internals of collections.
Problem since #4057.
Fixes #4114
> Collections: Handle copy-construction of stale accessor

- CHANGELOG.md
- src/realm/object-store/sync/sync_user.cpp
refresh_custom_data() is async and so the lambda needs to capture by value rather than capturing a reference to the stack variable.
> Fix a dangling reference in SyncUser::refresh_custom_data()

- evergreen/config.yml
- evergreen/install_baas.sh
- evergreen/wait_for_baas.sh
This adds a script that will download/build/start/configure the latest copy of the stitch server deployed to production on OSX/Linux machines and integrates it with the evergreen config on OSX/Linux builders.
> RCORE-391 Run object-store tests against local baas in evergreen

- evergreen/abspath.sh
- evergreen/build_libuv.sh
- evergreen/config.yml
- evergreen/install_baas.sh
This adds support for clang-11 on the ubuntu 20.04 images, and adds an ASAN/TSAN build variant as well as a task to run clang-format to the evergreen project.
> RCORE-388 Add special clang-11 builders and clang-format task

- src/realm/sync/changeset.cpp
- src/realm/sync/transform.cpp
VS 2019 claims that the stack is corrupted around local variables constructed with `util::overloaded{ ... }`. It might be, but if so it is a miscompilation.
The workaround works for some reason.
Found by @nirinchev in realm-dotnet.
> Work around compiler bug on MSVC around overloaded{}

- CHANGELOG.md
- tools/build-cocoa.sh
The xcframework was accidentally using the files which had the arm64 slices removed for the non-xcframework packaging. I shifted the order of things around a bit to fix this and also adjusted what exactly was being packaged for the far library version to only include the platforms supported by realm-js.
> Include arm64 simulator slices in the xcframework

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/obj.cpp
- test/test_unresolved_links.cpp
Fixes https://jira.mongodb.org/browse/HELP-20152
> Fix issue with resurrection of tombstones 

- evergreen/config.yml
This just adjusts the evergreen config so that our ARM64 build works.
PQ: https://spruce.mongodb.com/version/5fd148d8c9ec4447070503e5
> RCORE-449 Fix arm v8 build on evg

- src/realm/object-store/results.cpp
- test/object-store/results.cpp
This was a regression from https://github.com/realm/realm-core/pull/4157
Unfortunately another case where different representations of nullability create inconsistencies.
> fix nullabiliy for internally nullable types from results of a list

- src/realm/object-store/sync/mongo_collection.cpp
- test/object-store/sync/remote_mongo_tests.cpp
This was actually mostly harmless because real consumers wouldn't actually
pass in a null string_view, or one where reading from line[0] would trap, and
the later lines of the function are no-ops for an empty line. However, the
read of line[0] triggered an assert in a debug build with MS STL string_view,
which is how this was found.
* ~[ ] 📝 Changelog update~ (Doesn't have any user-facing impact)
> Add missing return in empty-line case of watch() decoder

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
Newly created notifiers copied their Query from the source Realm on the worker thread without locking the source Realm, which could race with things that invalidated the source Realm.
To fix this, switch to copying the required data to a temporary Transaction owned by the notifier while still on the source thread. This increases the amount of work done on the source thread to create a notifier (as it has to create a new Transaction each time), but eliminates the need to hold the lock while parsing the transaction logs for new notifiers, so it may turn out to be a net reduction in main-thread blockage.
Fixes https://github.com/realm/realm-core/issues/3761.
> Fix a race condition in notifier initialization

- evergreen/config.yml
- test/CMakeLists.txt
- test/benchmark-common-tasks/CMakeLists.txt
- test/benchmark-common-tasks/main.cpp
- test/benchmark-crud/CMakeLists.txt
- test/benchmark-crud/main.cpp
- test/object-store/benchmarks/CMakeLists.txt
- test/test_query.cpp
- test/util/benchmark_results.cpp
- test/util/benchmark_results.hpp
This refactors the evergreen config a bit and adds tasks that run a few of the benchmarks and uploads their results to evergreen. I also updated the benchmark_results infrastructure to output results in a format evergreen understands.
> RCORE-369 Add initial benchmark tasks to evergreen

- src/realm/object-store/c_api/conversion.hpp
- src/realm/object-store/c_api/notifications.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/c_api/util.hpp
- src/realm/realm.h
- test/object-store/c_api.c
- test/object-store/c_api.cpp
The following are renamed:
* `realm_table_key_t` -> `realm_class_key_t`
* `realm_col_key_t` -> `realm_property_key_t`
* `realm_obj_key_t` -> `realm_object_key_t`
Furthermore, they are all changed from being structs containing an integer value to become plain typedefs on the integer type. This allows the introduction of the global constants `RLM_INVALID_CLASS_KEY`, `RLM_INVALID_PROPERTY_KEY`, and `RLM_INVALID_OBJECT_KEY`.
> C API: Simplify key types, rename to high-level concepts

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/test_dictionary.cpp
Fixes https://github.com/realm/realm-core/issues/4248
> Reject dictionary insert/erase with keys that have a '.' or start with a '$'

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
- test/test_thread.cpp
This reverts commit 7be1f6aabc07e28f95f5c5625c14ad18fa1a4cf8.
> Revert "Reimplement Windows version of InterprocessCondVar (#4224)"

- .gitignore
- tools/coverage.sh
Updates `tools/coverage.sh` to do something useful with the monorepo.
> Fix coverage tools

- CHANGELOG.md
- src/realm/null.hpp
- src/realm/parser/collection_operator_expression.hpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
- test/test_query.cpp
This actually makes the query expressions work for any comparable column type, but I only added it to the parser for Timestamp and that's probably all that Cocoa will expose (querying for the minimum string has well-defined results but is pretty weird). Should be a trivial merge over to the bison branch since the only parser change was adding Timestamp to the list of supported types.
I shuffled some code around in ListColumnAggregate to detemplate some of the code in evaluate that didn't need to be templated and to eliminate the need for accumulate(Optional<T>) in each operation. BaseAggregateOperation turned out to not simplify the subclasses, and removing it was a net reduction in code.
The new tests are pretty minimal because there isn't actually any Timestamp-specific code to test.
> Add support for min/max queries on Timestamp lists

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_query.cpp
This is only questionably useful and no one has ever asked for it, but supporting it simplifies some of the Cocoa code that otherwise has to specifically exclude link columns and it seems to be completely trivial.
> Allow comparing link columns in queries

- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- test/test_parser.cpp
Better error messages for bounds checking when using the MixedArguments, and standard with other argument types.
Requested by @nirinchev
> better error messaging for MixedArguments bounds checking

- CHANGELOG.md
- src/realm/set.hpp
- test/test_set.cpp
It is not legal to use a StringData object belonging in an ArrayString that is modified. The string data will move around.
Fixes https://github.com/realm/realm-core/issues/4288
> Update set operations to work for String sets

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
- test/test_thread.cpp
The first commit is a clean un-revert to leave the code in the same state as the end of the last PR. The second commit is the new changes. This split is for review convenience, but I will squash to a single commit before merging.
As discussed with @finnschiermer, the issue was that because Mutexes are owned by threads rather than processes, the old code (accidentally) required that the ICV was destroyed on the same thread that created it. This was revealed by the dotnet testing because it (presumably) was destroying a Realm on a background GC thread. This changes it to use a single dedicated background thread (the `MutexOwningThread`) for locking (technically `try_lock()`ing) and unlocking the mutex used for claiming a process id. That is the only mutex that would otherwise be unlocked on …
> Unrevert windows ICV changes and fix them

- Package.swift
Xcode has a built in module called `FFI`, which conflicts with our `FFI` target in the `swift.package`. To solve the conflict I have renamed `FFI` to `RealmFFI`.
> Rename FFI target in SPM to RealmFFI

- CHANGELOG.md
- src/realm/global_key.hpp
- src/realm/table.cpp
- src/realm/table.hpp
For some yet unknown reason, the stored sequence_number could have the value 0x400000000000000. This would break the assertion in GlobalKey::get_local_key().
The implementation is now changed so that the generated sequence number is only 32 bit. So even if we find this stray number, the assertion will not be broken.
We also ensure that the sequence number is not updated if the table has a primary  key column. If we set the sequence number to be one bigger than the biggest ColKey, then it will in many cases be out of range.
Fixes #4295
> Fix ObjKey generation after file format upgrade

- src/realm/sync/inspector/print_changeset.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/sync/noinst/protocol_codec.hpp
If changeset is bigger than 1024 it will be compressed and BASE64 encoded
We have received some trace output from customers that ends out being useless as the dump of changeset is clamped to only output the first 1024 bytes.
> Be sure to dump entire changeset when log level is trace

- evergreen/config.yml
The object-store tests do not start on windows because of a runtime linker problem right now - so this just disables them for now.
> RCORE-390 Disable object-store tests on windows for now

- test/object-store/sync/app.cpp
This fixes the compile break introduced in #4263.
> Fix compile of object-store tests

- Package.swift
ObjectStore doesn't use the parser for anything but having the dependency results in some symbols from it ending up in the final library.
> Remove QueryParser dependency from ObjectStore

- evergreen/config.yml
Fixes an issue where clang-format was run against the wrong base commit in evergreen pull request lint tasks.
> RCORE-523 Run clang-format against merge-base

- CHANGELOG.md
previously reverted comment should remain intact as the version was released already
original PR - #4263
> Fixing changelog for app::Response changes

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
This just changes where we log in the sync client so that the error message sent from the server gets logged instead of just logging its size.
> RCORE-425 Log error messages from server

- test/test_sync.cpp
In the realm-sync repo, dangling links in lists of links weren't included in the prior_size field of array mutation instructions which would cause the server to reject operations on those lists with an error. This behavior was fixed in the monorepo (now merged into the master branch) - this PR only copies the test that was added to the v10 branch of the realm-sync repo to realm-core so that we have a test case for this issue going forward.
> RCORE-444 Add test for dangling links being included in prior_size

- src/realm/object-store/impl/realm_coordinator.cpp
`m_notifier_skip_version` is set to 0 before this point and `skip_version` is the actual value which should be checked.
TSan complained about a data race on the member variable as we've dropped the lock at the point of the assert.
> Fix an incorrect assertion

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/util/websocket.cpp
- src/realm/util/websocket.hpp
- test/object-store/sync/app.cpp
- test/test_util_websocket.cpp
This changes our WebSocket implementation so that it captures the error code and error message from the server and surfaces it to the user as a SyncError. This fixes the case where a very large changeset (16MB) would cause the sync client to get disconnected with just a connection reset.
> RCORE-422 surface errors from WebSocket close messages to user

- test/object-store/sync/app.cpp
I noticed the test I changed in this PR was failing pretty reliably in https://evergreen.mongodb.com/task/realm_core_stable_ubuntu2004_asan_object_store_tests_022161f01fa8cfb085287a0c3d4998f562ed28e2_21_01_26_14_51_15. This just changes the test to ignore other transient errors that aren't related to the error category the test is exercising.
> RCORE-538 Fix flakey websocket error handling test

- CHANGELOG.md
- src/realm/object-store/collection_notifications.hpp
- src/realm/object-store/impl/collection_change_builder.cpp
- src/realm/object-store/impl/collection_change_builder.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/impl/set_notifier.cpp
- test/object-store/dictionary.cpp
- test/object-store/list.cpp
- test/object-store/set.cpp
This is an enhancement to fire notifications when an empty collection has been deleted because the underlying object was deleted. This was already working for the case where there were items in the collection, so this is just an enhancement to for people who would expect to be notified when the object itself is deleted. Even though it is a behavioural change, I don't think it is breaking because there are no changes reported in the notifier. It is up to the SDK's if they would like to somehow expose the new `collection_root_was_deleted` flag somehow if that is appropriate. Fixes #4228.
> Trigger collection notifications when the source object is deleted

- evergreen/config.yml
- src/realm/sync/print_changeset_command.cpp
This adds builders to the evergreen config that compile/test in release mode as well as debug mode. Also fixes a command-line tool that didn't compile in release mode.
> RCORE-550 Add release builds to evergreen

- evergreen/abspath.sh
- evergreen/config.yml
- test/test_all.cpp
- test/util/unit_test.cpp
- test/util/unit_test.hpp
This adds a reporter to the core/sync unittest framework so that individual test results get reported to evergreen rather than just the whole suite passing or failing.
> RCORE-387 Add reporter for core/sync tests to report test results to evergreen

- evergreen/config.yml
- test/CMakeLists.txt
This adds running the long-running tests (TEST_DURATION=2) to evergreen. If this gets approved, I will change the evergreen project config so that pull requests only run tasks with the `for_pull_requests` tag, which will exclude the long-running tasks. The long-running tasks will run on waterfall builds (after merge). I'll work with @fealebenpae to make sure we get notifications if they fail.
> RCORE-341 Run long-running core tests in evergreen

- evergreen/config.yml
This is just a small tweak to the distro we use to build the release builds on MacOS. It turns out the macos-1014-test distro doesn't actually have any hosts defined in it right now.
> Fix distro used for MacOS release builds

- CHANGELOG.md
- CMakeLists.txt
Turns out we were statically linking against `libz` on Android all this time. We only noticed this when we attempted upgrading to NDK r22 and it turned out the `libz.a` there is broken. This PR forces CMake to only consider the dynamic `libz.so` when running the `FindZLIB` module.
> Link dynamically against libz on Android

- src/realm/util/file.hpp
- src/realm/util/network.hpp
Upgrading to NDK 22 on Android resulted in a few new warnings. Not sure if they are worth fixing and I can ignore them with `-Wno-dtor-name`, but these changes should fix them.
> Fix dtor-name warnings

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- test/test_parser.cpp
As discovered by Christian in https://github.com/realm/realm-core/issues/4398 the properties in the backlink syntax `@links.Class.property` were not being translated by the mapping so aliasing didn't work in that case.
> translate property aliases in backlinks queries

- doc/protocol/protocol_1.md
The need for this clarification was realized in the course of work on [REALMC-7986](https://jira.mongodb.org/browse/REALMC-7986).
See also https://github.com/10gen/baas/pull/3776#issuecomment-774946853.
> Protocol spec: Explicitly prohibit overlapping sessions for same file ident

- evergreen/config.yml
We need to upload the test results in a teardown task so that it runs regardless of whether a test fails.
> RCORE-563 Fix uploading test results on test failure in evergreen

- CHANGELOG.md
- src/realm/mixed.hpp
- src/realm/object-store/object_accessor.hpp
- test/object-store/object.cpp
The `objectaccessor` object update logic doesn't emit change notifications when changing the Mixed types. It results in a confusing behavior where the final user might be expecting a notification. For example, changing from Mixed(true) to Mixed(1) won't emit a notification.
This PR adds a logic in the object store to trigger changing mixed attributes on Mixed type changes.
Fixes #4404
> Change listeners not triggered on certain Mixed attribute changes

- test/test_transactions.cpp
This test was missed during the file format bump to 21 because it is gated with TEST_DURATION=1 and so isn't part of the normal test suite.
> bump file format in test

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- test/test_query.cpp
This is an alternative to #4415
> Use right allocator when performing queries over links

- src/realm/object-store/c_api/util.hpp
- src/realm/object-store/schema.cpp
Quick adoption of #4413 in the C API.
> Use Schema::find(TableKey) in C API functions

- CHANGELOG.md
- CMakeLists.txt
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
The following sequence of events could produce the assertion failure "!skip_version.version":
1. Add a notifier and let the initial run complete
2. Make a commit and let the notifier start running
3. The notifier reads and clears the skip version, releases the lock, and then  calls get_version_id_of_latest_snapshot() with the lock not held. In between  releasing the lock and the call to get_version_id_of_latest_snapshot(),  perform another write.
4. In the next notifier run, the skip version is set but we're already at the  latest version, so the assertion that the skip version is unset for a  spurious wakeup fails.
Pushing the unlock until after the call to get_version_id_of_latest_snapshot() makes this sequencing impossible.
Enabling the static thread safety checks (which were enabled …
> Fix incorrect locking in RealmCoordinator::run_async_notifiers()

- src/realm/object-store/impl/transact_log_handler.cpp
Cocoa does not rely on any change indices when mutating a `Set`. So I have modified `KVOAdapter::before` to ignore any calculations that need to be performed when a given column is a `Set`.
Addresses: https://github.com/realm/realm-cocoa/pull/7051#discussion_r573298745
> Don't calculate change indices for Sets

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_engine.hpp
- test/test_parser.cpp
- test/test_query2.cpp
This was requested by .NET in relation to https://jira.mongodb.org/browse/RCORE-316 and https://github.com/realm/realm-core/pull/4395
Users might query an argument of TypedLink, and if they do, we can check that the link table matches and do the object key comparison or else throw a more informative message.
> Fixed parsing queries comparing links/lists to TypedLink args

- src/realm/sync/apply_to_state_command.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
This fixes the apply2state command for the cloud team by letting it override the timestamps on changesets generated by local transactions.
> RCORE-498 Allow overriding changeset timestamps for testing

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/sync/noinst/client_history_impl.cpp
There were two bugs here:
1. The logic for whether we block until notifiers are ready when beginning a write transaction and whether we set `m_notifier_skip_version` in `commit_write()` (which depends on us having blocked when starting the write) were mismatched. We don't block for notifiers without callbacks as the only purpose of those notifiers is to rerun the query on a background thread to avoid spending time on the main thread, so waiting would be counterproductive. This means that we also need to not set the skip version if we only have notifiers without callbacks. This probably did not cause any functional
problems, but violated some of the invariants of notification skipping and so assertions checking those invariants failed.
2. The latest snapshot version needs to be acquired …
> Fix more version skipping logic errors

- src/realm/object-store/set.cpp
- src/realm/object-store/set.hpp
- src/realm/set.cpp
- src/realm/set.hpp
This exposes set_equals and assign_symmetric_difference on the OS Set and adds set_equals to LnkSet.
> Add missing set methods

- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/results.cpp
- test/object-store/dictionary.cpp
This is a preliminary implementation of #4232. It is currently not possible to deliver key based notifications on deleted entries as the kay values are not available when the basic notifications are sent out. Instead the indices are delivered.
> Key based notifications on Dictionary

- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/results.cpp
- test/object-store/results.cpp
Results::index_of() was reported (on slack) broken for results produced by `object_store::Dictionary::get_keys()`
> fix Results::index_of() for dictionary keys

- CHANGELOG.md
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/impl/results_notifier.hpp
- test/object-store/results.cpp
The previous check would only skip rerunning the query (and sort etc.) if both none of the tables in the query were modified and if the query used every table reachable from the source table, which in many cases meant that it simply reran
after every commit. Instead we want to only rerun if any of the tables used by the query were modified, and only check the objects from the previous run for modification otherwise.
> Fix the check for if ResultsNotifier needs to rerun queries

- CHANGELOG.md
- src/realm/dictionary.hpp
- src/realm/list.hpp
- src/realm/mixed.hpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/list.cpp
- src/realm/object-store/list.hpp
- src/realm/object-store/object_schema.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/object-store/set.cpp
- src/realm/object-store/set.hpp
- src/realm/object-store/thread_safe_reference.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- test/object-store/frozen_objects.cpp
- test/object-store/list.cpp
In addition to eliminating some duplicated code and mostly simplifying things, this also fixes a pile of bugs with Results wrapping a Dictionary of links and makes the API less error-prone. It was possible to construct a Results from a CollectionBase with a type of Object (as Dictionaries did) and some things worked, but many functions did not work properly as the Collection mode was only intended for non-objects.
> Consolidate the code for Collection, LinkList and LinkSet in Results

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- test/test_shared.cpp
SlabAlloc::m_youngest_live_version was only updated when committing a write transaction via that SlabAlloc, which resulted in it having the incorrect value if the write was made via a different DB instance. This lead to old ref translations being marked with the wrong version, and then they'd be deleted while they were still in use.
Fixes https://github.com/realm/realm-cocoa/issues/7086.
> Fix stale version tracking in SlabAlloc leading to a use-after-free

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/impl/transact_log.hpp
- src/realm/keys.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/dictionary.cpp
- test/object-store/set.cpp
- test/object-store/transaction_log_parsing.cpp
- test/test_lang_bind_helper.cpp
The change checker was handling dictionaries and sets as if they were lists. This could lead to an exception `KeyNotFound("No such object");` as described in https://github.com/realm/realm-core/issues/4465
This also turned up the case that the notifiers did not account for links through `Mixed(TypedLink)` values which can link to any table. This is because we build up the links to check by traversing the forward link columns in each table, but these do not have the information about TypedLinks. The way I found to fix this is to rely on backlink columns being present at the destination table for each kind of TypedLink because those are added dynamically as needed. This means we don't actually add the Mixed column to check in the case that there are no outgoing links because the backlink …
> Fix notifications on dict/set of links

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/list.hpp
- src/realm/object-store/results.cpp
- test/object-store/collection_fixtures.hpp
- test/object-store/dictionary.cpp
- test/object-store/primitive_list.cpp
- test/object-store/results.cpp
I moved the list of primitives templated test types into a shared test file so they can be reused. It looks like this effort was started already previously, but not completed because there was already a stale copy of the code there. Then I transformed and improved the Dictionary tests to use the types. This turned up a few bugs.
> Dictionary bugfixes and increased test coverage

- CHANGELOG.md
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/util/interprocess_condvar.hpp
Previously if a notification came in between the time when the ECH was
contructed and when the background listener thread acquired the lock,
that notification would be missed. Now, the ECH looks at the
notification count on the constructing thread prior to launching the
background thread. If a notification comes in, the listener thread will
see a different notification count and will not wait on the condvar
prior to calling on_change().
> Avoid race when starting ExternalCommitHelper on windows

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
This was originally disabled because the design of UUID said they shouldn't be supported. The underlying comparisons did actually work though because they are needed for sorting and they are already enabled in queries outside of the parser. We enable it for consistency with typed queries as requested by https://github.com/realm/realm-core/issues/4475. Granted there may also be some niche cases where users are building UUIDs manually and want to use these comparisons in their queries.
> Enable relational comparison of UUID

- CHANGELOG.md
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/property.hpp
- test/object-store/dictionary.cpp
This PR allows passing null entries on RealmDictionaries of RealmModels when constructing an object through the ObjectBuilder. 
The issue causes a crash when it tries to unbox an empty JavaValue to then pass it to a Dictionary of RealmModels.
Fixes #4537
> Object store - Allow optional object fields on Object Builder

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/impl/simulated_failure.cpp
- src/realm/impl/simulated_failure.hpp
- src/realm/util/file.cpp
- src/realm/util/file_mapper.cpp
- test/test_alloc.cpp
Shuffle things around so that we don't mutate any member variables until after we've created all the new mappings, which ensures that everything is left in a valid state if creating a mapping fails. Allocation failures other than creating a new mapping can still make things be invalid, though. While shuffling the code around I noticed that the special cases were actually just doing the same thing as the normal case, so it ended up being a net reduction in code assuming I didn't misunderstand anything.
This makes the following particularly stupid test successfully run to completion rather than crashing shortly after the first thread gets an alloc failure:
```
ONLY(ManyWriters)
{
SHARED_GROUP_TEST_PATH(path);
std::unique_ptr<Replication> hist_w(make_in_realm_history(path));
DBRef db = …
```
> Improve exception safety in SlabAlloc::update_reader_view()

- CHANGELOG.md
- src/realm/aggregate_ops.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary_cluster_tree.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/results.cpp
- test/object-store/collection_fixtures.hpp
- test/object-store/dictionary.cpp
- test/object-store/primitive_list.cpp
- test/test_parser.cpp
Adding more tests for object-store dictionary. Fixed a few small issues, with the main thing being aligning the aggregate implementation of Dictionary values to use `aggregate_ops` which produces consistent results with aggregates on a mixed column. Notably, this changes the previous behaviour of throwing when encountering different numeric types, into accumulating them into a Decimal128.
> fix dictionary of mixed aggregates

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/table.hpp
- test/test_parser.cpp
Fixes https://github.com/realm/realm-core/issues/4550
> enable name aliasing in the query parser's sort and distinct

- src/realm/sync/noinst/client_impl_base.cpp
Add trace logging of the upload changeset similar to what we do for the download one:
https://github.com/realm/realm-core/blob/dae6b8dcd8839e52024007990241bd5a8d2223c2/src/realm/sync/noinst/protocol_codec.hpp#L280-L287
The intention here is to simplify debugging when we need to know precisely what the client attempts to send to the server.
> Parse and print upload changeset similar to download.

- CHANGELOG.md
- src/realm/set.hpp
- test/test_set.cpp
The context flag was wrongfully cleared which meant that information about the current layout of the binary array was lost.
> Fix issue with Set<Binary>::clear()

- CHANGELOG.md
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/object_changeset.cpp
- src/realm/object-store/results.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
- test/object-store/results.cpp
When I first implemented notifications I wasn't sure how to handle writes refreshing the Realm while inside notification callbacks and eventually settled on just not handling it and accepting that doing that would result in incorrect notifications. This resulted in some things being in an invalid state when it happened, which makes the asserts added in #4449 failing. Fortunately, it turns out that the refactoring to enable notification skipping also gave a pretty straightforward route to deliver correctish notifications. The new behavior is that when a Realm is refreshed in the middle of sending notifications, we recursively send notifications from within that notification block, and merge the new changes into the existing changes to be delivered for any callbacks we didn't reach.
Fixes …
> Improve handling of write transactions inside notification callbacks

- android.Dockerfile
#4407 broke adb on Jenkins because of filesystem permission issues in the container.
> Fix running Android tests

- test/object-store/mongodb/functions/sumFunc/source.js
- test/object-store/sync/app.cpp
This fixes the object-store test failures in evergreen after the the cloud team merged in https://github.com/10gen/baas/pull/3962
> Realm server-side functions no longer require parseInt

- src/realm/object-store/util/bson/bson.cpp
- test/object-store/bson.cpp
This PR adds the proper encoding for UUID in bson.cpp
> UUID Bson Serialization

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/util/file.hpp
- test/test_transactions.cpp
Verify that all of the pointers in old ref translation tables are still pointing to valid things and that we haven't accidentally unmapped something which should still be in use. This was one of my attempts at tracking down https://github.com/realm/realm-cocoa/issues/7175 that unfortunately didn't reveal anything but seems useful nonetheless.
> Add some additional debug validation to SlabAlloc

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query.cpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- test/test_query2.cpp
Functionality requested by SDKs
> Support equal/not_equal on a link column against a Mixed value

- CHANGELOG.md
- src/realm/query.cpp
- src/realm/query_conditions_tpl.hpp
- src/realm/table.cpp
- test/test_query2.cpp
Fixes https://github.com/realm/realm-core/issues/4571
The min of a mixed column shouldn't be null. Null should be ignored during aggregation in the same way as for other types.
> Fixed min/max queries of Mixed columns.

- CHANGELOG.md
- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.hpp
- src/realm/object-store/results.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/table.hpp
- test/object-store/dictionary.cpp
- test/test_dictionary.cpp
- test/test_query2.cpp
Instead of adding more duplicated code, the query code was changed from handling a LnkLst and a LnkSet to handling a CollectionBase which does the same things and allows adding in the dictionary too. The assumption here is that the constraining collection can also be cast to a ObjList and this is covered by assertions. 
Since dictionaries do not implement the ObjList interface, an adapter class is created `DictionaryLinkValues` which is the functional equivalent to `LnkSet` and `LnkLst`. This abstraction almost works, except that it cannot provide a `BPlusTree<ObjKey>* get_mutable_tree()` because links are stored in a mixed. This has consequences for unresolved link maintenance that I am unsure about and needs to be resolved before merging. 
@jedelbo do you know if it is necessary to …
> Add support for constraining a query to a dictionary of links.

- test/util/benchmark_results.cpp
The measurement `result.rep` is the total number of samples obtained for a benchmark. This can vary between runs because the benchmark suite dynamically determines the number of runs based on how long they take. It is informational only and used to compute the min/max/avg/med results, but should not distinguish benchmarks from one another. The way evergreen interprets arguments is to use each "arg" as part of the unique id for the timeseries reporting. This causes the graphs to incorrectly interpret different count runs as distinct benchmarks (see below image). This change removes the count argument which will cause all runs of different counts to be combined, going forward.
> remove count arg from evergreen benchmarks

- test/object-store/main.cpp
- test/object-store/primitive_list.cpp
Example of a simulated failure in object-store tests is [here](https://spruce.mongodb.com/task/realm_core_stable_ubuntu2004_object_store_tests_patch_91ad3b7380d17f49e7f93150dfba5196f169eff3_607782f80ae60619ccad3a6b_21_04_15_00_04_09/tests?execution=0&sortBy=STATUS&sortDir=ASC).
> report object store tests to evergreen

- Jenkinsfile
This was done before, but was probably undone due to a bad merge in https://github.com/realm/realm-core/pull/4153
> enable MongoDB sync tests in Jenkins

- CHANGELOG.md
- src/realm/query.cpp
- test/object-store/dictionary.cpp
> Query::find_all should disregard null links when no conditions

- CHANGELOG.md
- src/realm/collection.hpp
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/dictionary.hpp
- src/realm/list.hpp
- src/realm/obj_list.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/set.hpp
- src/realm/table_view.hpp
- test/object-store/dictionary.cpp
LinkCollectionPtr is a std::unique_ptr<ObjList> which more precisely captures that it is a collection of links.
Fixes #4640
> Query now holds a LinkCollectionPtr in m_source_collection

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- test/object-store/sync/app.cpp
- test/object-store/util/test_utils.cpp
- test/object-store/util/test_utils.hpp
This is to address: https://jira.mongodb.org/browse/RCORE-473
I added back the old WaitingForAccessToken state to the sync session, though the definition of an access token has changed a bit so the flow is much simpler.
Without the changes in this PR, I also did a manual test of logging in a user, then waiting more than 30 minutes to let the access token expire and then using it to start a sync session and the error handling and reconnection all worked for me. So the only thing I can claim to have fixed here for sure is that there are less errors logged (both client side and server side). However, the alarming (though harmless) error logs seems to be what users are concerned about (https://github.com/realm/realm-js/issues/3667).
That being said, the test added does trigger the new code, …
> anticipate access token refresh

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- test/object-store/results.cpp
The problematic sequence here was:
1. Main thread commits version X
2. Worker thread begins processing version X makes it through the skip version logic. This updates all of the notifiers to version X.
3. Main thread begins another write transaction. This does not block as the notifiers are up-to-date even though the worker thread is still in run_async_notifiers().
4. Main thread suppresses a notification callback (setting skip_version) and then commits version X+1.
5. Worker thread moves on to the non-skip part of the logic for version X. There wasn't any more versions left after the skip version when this iteration started, so it runs the notifiers on zero changesets.
6. Notifier clears skip_next.
7. Worker thread processes version X+1. The suppressed notification incorrectly produces a …
> Fix another notification skipping race condition

- CHANGELOG.md
- CMakeLists.txt
- src/realm/util/interprocess_condvar.hpp
clock_gettime() requires a newer version of macOS than our minimum deployment target, so we need a fallback for older versions of macOS. This would cause a crash at runtime if it was hit, but the function is currently only used on Windows.
> Fix availability warnings when building for Apple platforms

- src/realm/bplustree.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/test_bplus_tree.cpp
- test/test_lang_bind_helper.cpp
- test/test_table_view.cpp
In ConstTableView constructor taking a const ConstTableView as src parameter
the copy assignment function was called in both the "Copy" and the "Move" case.
If the move assignment functions should be used, the src parameter should refer
to a writeable object as the content of m_key_values would be moved out of it.
> Ensure proper move operation is used for PayloadPolicy::Move

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/app.cpp
This was caught by the cocoa tests (https://github.com/realm/realm-core/pull/4638#issuecomment-832227309)
The fix is straightforward; the hardest part was coming up with a test case to trigger it.
> add missing WaitForAccessToken state handling

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/group.cpp
- test/test_shared.cpp
DB::write_copy would break if the realm did not have a history. When we write the copy, we will only write a history if it is a Client Sync history. So if we start with a file with InRealm history, then the copy will not have a history and cannot subsequently be used to copy from.
> Fix DB::write_copy() of realms without history

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
New behavior was seen as breaking.
> Restore original behavior of Realm::write_copy

- CHANGELOG.md
- src/realm/mixed.cpp
- src/realm/query_expression.hpp
- test/test_dictionary.cpp
Fixes an issue where the string used as argument could have been deleted when the query is run. This could happen if you constructed the Query in a way like this:
```
auto q = foo->colum<Dictionary>(col).equal(str, true).find_all();
```
and `str` would be deleted before the query was run
> Be sure to copy string values when Mixed is used in Query

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/realm.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
We need to defer adding the completion handler if the session doesn't exist for any reason, and not just if it doesn't exist because the state is currently Inactive.
A trivial fix that turned out to be fairly involved to test.
> Fix a crash when calling Realm::get_synchronized_realm() while waiting for an access token

- src/realm/index_string.cpp
- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/sort_descriptor.cpp
Reverts some functionality introduced by feaa559e538b59. 
Values should be sorted consistently. We use utf8_compare in SortDescriptor.
Add new function that can be used by string index. String index requires
that strings are compared as signed bytes. It should match the way the
keys are compared.
> Revert Mixed::compare to use utf8 compare for strings

- src/realm/object-store/shared_realm.cpp
- test/object-store/thread_safe_reference.cpp
Add a test of using thread safe references on an immutable Realm.
Removed the function 'check_can_create_any_transaction()' as it is
non needed anymore, since any open realm, immutable or not, now
supports read transactions.
> finishing read-only thread safe reference

- CHANGELOG.md
Add the missed changelog update for #4688
> changelog entry for fix of thread-safe references on immutable Realms

- CHANGELOG.md
- src/realm/mixed.cpp
- src/realm/set.hpp
- test/object-store/set.cpp
- test/test_set.cpp
- test/test_sync.cpp
- test/test_types_helper.hpp
The way we handle sets should be consistent with the way they are handled on the server side.
> Use same rules for handling numeric values in sets as MongoDB uses

- CHANGELOG.md
- src/realm/array_key.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/object_accessor.hpp
- src/realm/table.cpp
- test/object-store/object.cpp
- test/object-store/transaction_log_parsing.cpp
`obj.is_null(ColKey(link.col_key)` returns false for an unresolved link, but `obj.get<ObjKey>(ColKey(link.col_key))` returns a null ObjKey for an unresolved link. This mismatch caused the change checker to try to descend down an unresolved link.
It is essentially the single link version of the same error we fixed for link lists earlier: https://github.com/realm/realm-core/pull/4175
I believe it should fix this report https://github.com/realm/realm-js/issues/3611#issuecomment-823014128 as well as https://jira.mongodb.org/browse/HELP-24406 and https://jira.mongodb.org/browse/HELP-23982
> Guard against unresolved links in the change checker

- CHANGELOG.md
- src/realm/object-store/schema.cpp
- test/object-store/migrations.cpp
We had a report of migrating to an embedded table not working when it should. Debugging revealed that the changed to embedded was being processed before a link column which pointed to the table was removed. Removing the link column first will remove the incoming links which allows the embedded change to succeed.
> fix an edge case of embedded table migrations

- test/object-store/main.cpp
This should make assertions show up in the logs on evergreen when there is a failure.
Targeting this branch for now to see if it can help track down the failure on ubuntu there.
> print error info when object-store tests fail on evergreen

- .devcontainer/devcontainer.json
The `mongodb/config.json` was moved to `realm-core/test/object-store` in a prior PR.
This PR fixes the path in `.devcontainer` to point to the correct folder.
Also sets the `cmakePath` and `generator` within the settings.
> Adjust stitch path in .devcontainer settings.

- evergreen/bloaty_to_json.py
- evergreen/config.yml
This adds some very basic bloaty integration to evergreen. On the Ubuntu release builder, we'll run bloaty against librealm-ffi.so, collecting the `sections` and `shortsymbols` outputs in both CSV/text file format. There's also a new python script that will transform the CSV files into json format with metadata about where/how it was generated in evergreen that gets uploaded to MongoDB so we can visualize this data later on with charts and graphs. All the generated files also get uploaded to S3 and attached to the task in evergreen so we can go look at them later.
> RCORE-440 Add basic bloaty integration to evergreen

- src/realm/sync/transform.cpp
- test/test_transform.cpp
This fixes an issue found by the cloud team. The Clear instruction - when operating on the same path - needs to discard any SetInsert/SetErase instructions being merged in. Otherwise you could end up with diverging states as shown below:
Client 1: 
CreateObject{}, Clear{setField}
Client 2: 
CreateObject{}, Clear{setField}, SetInsert{setField, "a"}
In this case, the clients resolve to the following states: 
Client 1: CreateObject{}, Clear{setField}, CreateObject{}, SetInsert{setField} --> { setField: ["a"] }
Client 2: CreateObject{}, Clear{setField}, SetInsert{setField, "a"}, CreateObject{}, Clear{"setField"} --> { setField: [] }
> RCORE-724 Fix merge issue between SetInsert/SetErase and Clear

- evergreen/config.yml
This adds a task to the OSX builders in evergreen to run the swift build so we catch compile errors there early.
> RCORE-725 Run swift build/test in evergreen

- evergreen/config.yml
- evergreen/install_baas.sh
- test/object-store/CMakeLists.txt
- test/object-store/object.cpp
- test/object-store/sync/app.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
This changes the object-store tests to create their apps in baas dynamically via a C++ admin api rather than importing static apps prior to running the tests. This will let us more easily write tests with arbitrary schemas, functions, and features enabled.
> RCORE-719 create baas app dynamically

- CHANGELOG.md
- src/realm/object-store/object_accessor.hpp
- test/object-store/object.cpp
We normally treat null as being equivalent to an empty array when assigning to a collection. Inside Object::create(), however, we were using the non-collection code path if the collection's value type was nullable, which results in either assertion failures or weird crashes if assertions are disabled.
> Fix a crash when setting a nullable collection to null

- CHANGELOG.md
- src/realm/object-store/impl/epoll/external_commit_helper.cpp
I opted for the minimal fix, rather than changing to use either futex or interprocess mutex+condvar. @cmelchior confirmed that this fixes the bug in the repro. Without this commit, running the object-store tests would hang on my (WSL2 - linux-5.10.16) machine. Now they pass.
> Fix #4666 by draining pipe prior to writing to it

- evergreen/config.yml
- evergreen/install_baas.sh
- evergreen/wait_for_baas.sh
Makes sure the AWS key info is available to start baas in object-store tests.
> Set AWS keys for baas secrets in evergreen

- CHANGELOG.md
- src/realm/cluster_tree.cpp
- src/realm/sync/apply_to_state_command.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_applier.hpp
- src/realm/sync/noinst/reopening_file_logger.cpp
- src/realm/sync/noinst/reopening_file_logger.hpp
- src/realm/sync/server_command.cpp
- src/realm/util/duplicating_logger.cpp
- src/realm/util/duplicating_logger.hpp
- src/realm/util/file.hpp
- src/realm/util/interprocess_mutex.hpp
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
- src/realm/util/timestamp_logger.cpp
- src/realm/util/timestamp_logger.hpp
- src/realm/util/to_string.cpp
- src/realm/util/to_string.hpp
- test/object-store/sync/app.cpp
- test/object-store/transaction_log_parsing.cpp
- test/object-store/util/test_file.hpp
- test/object-store/util/test_utils.cpp
- test/test_util_logger.cpp
- test/test_util_to_string.cpp
- test/util/compare_groups.cpp
- test/util/unit_test.cpp
We have two different almost-compatible implementations of string formatting, one originally written for sync logging, one for object store. This makes Logger use util::format internally and extends util::format to support arbitrary types rather than just a fixed set. In addition to eliminating some duplicated code, this significantly reduces the compiled size of the library:
| Binary                         | Before (KB) | After (KB) | Change (KB) |
| ------------------------------ | ----------- | ---------- | ----------- |
| macOS static library (debug)   | 296192      | 294467     | 1725        |
| macOS static library (release) | 16174       | 15765      | 409         |
| iOS app archive                | 91648       | 90228      | 1420        |
| sync tests executable          | 9968 …
> Unify the string formatting code

- src/realm/sync/changeset.cpp
- src/realm/sync/instruction_applier.cpp
This disables msvc runtime checks in a few more places because we're seeing stack corrupted assertions similar to the one in https://github.com/realm/realm-core/issues/4624. I am assuming those are again false negatives, although I would appreciate if someone familiar with what's going on there takes a more comprehensive look.
> Disable supposedly false negative runtime checks for msvc

- CHANGELOG.md
- src/realm/obj.cpp
- test/object-store/sync/app.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
If you are replacing an embedded object with a new one, rather than simply updating all its fields, we need to emit a sync instruction to set the old embedded object to null so that its fields get cleared before setting the new object's fields. Without doing this, any array instructions on the new object could have a corrupted prior_size because from the sync protocol's perspective, they'll be operating on a non-empty array.
> RCORE-734 Emit set(null) instruction before replacing embedded object

- CHANGELOG.md
- evergreen/config.yml
- src/realm/sync/server.cpp
- src/realm/util/to_string.hpp
- test/object-store/CMakeLists.txt
- test/object-store/util/test_file.hpp
- test/test_all.cpp
Logging a DataType formed an infinite loop (until stack overflow) due to the wrong conversion being picked. This was not caught on CI because we didn't actually run any tests with sync logging enabled, so enable it for the object store tests.
Ideally the *sync* tests would test the logging, but I couldn't find a convenient way to enable logging for all of them.
> Fix crashes when sync trace logging is enabled

- evergreen/config.yml
Evergreen's expansions syntax means we can't use bash arrays as it eats anything using ${. Using a simple variable expansion will result in things breaking if a target name has a space in it, but the rest of the script isn't space-safe anyway.
https://evergreen.mongodb.com/task/realm_core_stable_ubuntu2004_asan_long_running_core_tests_patch_ed9fbb907e0b5e97e0e2d5b8efdc0951b2eb980c_60bffbb461837d355b954238_21_06_08_23_23_03 is a patch run with these changes which is building the right thing.
> Fix setting the cmake target for evg tasks

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/app.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
Fixes https://github.com/realm/realm-core/issues/4745
The auto refresh would recursively try to refresh the token every 10 seconds which would loop endlessly on a user who had been revoked by an admin. Eventually this would have caused a stack overflow.
> Do not try to auto refresh a token on a revoked user

- src/realm/data_type.hpp
- src/realm/util/logger.hpp
- test/test_util_to_string.cpp
Nothing particularly exciting here, but we should have at least some minimal tests which hit all the to_string codepaths.
> Add some more string formatting tests

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- test/test_shared.cpp
Proposed fix for https://github.com/realm/realm-core/issues/4762
A call to realm::delete_files concurrently with opening the same realm file had a race, where the management directory could be removed from under the feet of DB::do_open. This could happen both before do_open acquires the exclusive lock and after, right before acquiring a shared lock.
The fix moves creation/deletion of the management directory such that it is protected by the exclusive lock.
It is still possible (but a different problem) for realm::delete_files() to interfere with do_open() such that the lock file is not re-initialized. However, this is highly unlikely to have any impact, since it can only happen when cleaning up after previous use of the realm file, and in that case re-initialization of the lock file …
> fix for delete/open race

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/object-store/impl/deep_change_checker.cpp
- src/realm/object-store/impl/deep_change_checker.hpp
- test/object-store/primitive_list.cpp
- test/object-store/transaction_log_parsing.cpp
We forgot to handle list of Mixed when checking for deep changes in the notification logic.
It's the same code as Set<Mixed> so I extracted it to a templated method. It couldn't be generalized to work on a CollectionBase pointer because this base class doesn't have an iterator interface at that level, and unfortunately it is not trivial to add.
Reported by https://github.com/realm/realm-core/issues/4767
> fix notifications on list of primitive mixed

- evergreen/bloaty_to_json.py
- evergreen/config.yml
This is a small internal change to the evergreen config/bloaty processing script that adds compile units to the info we collect/store/track from bloaty. It was sitting in a branch for weeks and weeks since I last looked at bloaty stuff and figured I'd get it committed so I don't just forget about it permanently.
> RCORE-440 Track compileunits output from bloaty

- CHANGELOG.md
- Package.swift
Renamed targets on SPM file from `Core`, `QueryParser` to `RealmCore` and `RealmQueryParser` to avoid conflicts with other libraries products
This is related to this issue https://github.com/realm/realm-core/issues/4763
> Renamed targets on SPM file from `Core`, `QueryParser` to `RealmCore` and `RealmQueryParser`

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_manager.cpp
Prevents a retain cycle on Apple devices where the sync manager would hold a strong reference to sync client which (through a lambda) would hold a strong reference to the sync manager. We're turning the sync manager reference to a weak one.
I'm not sure how to write tests for that and I'm sorry for the whitespace changes in the readme.
Fixes https://github.com/realm/realm-dotnet/issues/2482
> Don't pass a shared_ptr to SyncManager to the sync client

- src/realm/util/platform_info.cpp
Windows 8.1 didn't support ARM64
> Fix building with the Windows 8.1 SDK

- evergreen/config.yml
To be a good evergreen citizen, this sets the timeout for most of our tests to 30 minutes to make sure we don't accidentally hog machines for hours and hours.
> Set evergreen test tasks to time out after 30 minutes

- .clang-format
- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/deep_change_checker.cpp
- src/realm/object-store/impl/deep_change_checker.hpp
- src/realm/object-store/results.hpp
- test/object-store/benchmarks/main.cpp
- test/object-store/benchmarks/results.cpp
- test/object-store/transaction_log_parsing.cpp
Prompted by [a report of a performance regression in notifier performance in v11](https://github.com/realm/realm-cocoa/issues/7316), I wrote a few new benchmarks and optimized some stuff. I haven't yet reproduced the regression the user reported, but I did find a regression in notifier creation perf (which is moderately important as it happens on the main thread) and found some room to optimize things which might be similar to what the user was hitting.
It may be easiest to review this by looking at the commits individually as they're each doing fairly distinct things.
Test | v10.8.1 | master | This PR
-|-|-|-
Create notifier | 409 us | 12.5 ms | 333 us
Chained object links (depth 0) | 25 us | 22 us | 24 us
Chained object links (depth 1) | 314 ms | 337 ms | 10 ms
Chained object links …
> Improve performance of some notifier things

- CHANGELOG.md
- src/realm/keys.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/object_notifier.cpp
- src/realm/object-store/impl/object_notifier.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/impl/results_notifier.hpp
- src/realm/object-store/object_store.cpp
- src/realm/query.cpp
- src/realm/table.cpp
- test/object-store/frozen_objects.cpp
- test/object-store/object.cpp
- test/object-store/realm.cpp
- test/object-store/sync/app.cpp
- test/test_query2.cpp
- test/test_table.cpp
`m_table_key = {}` calls `TableKey::operator=(uint32_t)` instead of the intended `TableKey::operator=(TableKey)`, which results in it setting `m_table_key` to zero instead of the null value. This then breaks the subsequent checks for `(bool)m_table_key`, as `TableKey(0)` is true. As this is extremely error-prone and that `operator=` appears to never be intentionally used, I fixed this by removing it.
While trying to track this down I also found and fixed a few other things. We were holding the callback lock while doing a significant amount of work on the background thread, which is bad as it can block the main thread. Fixing this just required shuffling around where exactly we access the data from the callbacks a bit. `CollectionNotifier::set_table()` is now kinda redundant and could be …
> Fix an assertion failure in ObjectNotifier

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
Ensure we have only one `write_copy` method.
Fixes #4801
> Merge Realm::write_copy_without_client_file_id and Realm::write_copy

- CHANGELOG.md
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/list.hpp
- src/realm/object-store/set.hpp
- test/object-store/dictionary.cpp
The relevant collection type (List, Set, Dictionary) should be included in the
error message.
Fixes #4805
> Improve error messages when accessing an invalidated collection object

- CHANGELOG.md
- src/realm/sync/changeset.cpp
- src/realm/sync/instruction_applier.cpp
- test/test_sync.cpp
The segfault was discovered by additional tests enabled in https://github.com/realm/realm-core/pull/4706.
It looks to have been introduced by https://github.com/realm/realm-core/pull/4178 to fix another MSVC issue in debug mode. Instead of reverting that change which would bring up the old debug mode issue, this changes the code to not rely on the `mpark::visit(overload` pattern with an auto case as this seems to be a combination of code that shows a bug in MSVC 2019 and/or mpark.
I have observed that there are other ways to "fix" the issue, such as removing the lifetime extension idea and adding an explicit case for GlobalKey:
```
auto get = overload{
[this](InternString str) -> PrimaryKey {
return get_string(str);
},
[](const GlobalKey& key) -> PrimaryKey {
return key;
},
[](auto …
```
> Fix a segfault in code produced by Visual Studio 2019

- CHANGELOG.md
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_applier.hpp
This adds information about what table/object/path the current instruction was mutating along with the changeset header information when the InstructionApplier throws an exception.
With this change, errors during download integration will look like:
```
ERROR: Failed to parse, or apply received changeset: ArrayInsert: Invalid prior_size (list size = 1, prior_size = 0) (instruction target: table_name[ObjectId{...}].field_name.path[0].to[0].embedded_field, version: server_verison, last_integrated_remote_version: client_version, origin_file_ident: file_ident, timestamp: changeset timestamp)
```
Instead of
```
ERROR: Failed to parse, or apply received changeset: ArrayInsert: Invalid prior_size (list size = 1, prior_size = 0)
```
* [N/A] 🚦 Tests (or not relevant)
> Include context about what object/changeset caused the exception in InstructionApplier logs

- CHANGELOG.md
- src/realm/list.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/object-store/sync/app.cpp
This is similar to RCORE-734, but with lists. If you have a list of embedded objects `a = {b: [{c: [1, 2]}]}` and update them in the sdk like this `a.b[0] = { c: [ 3, 4 ] }`, you'll end up replacing the object at `a.b[0]` without clearing the old one, so any arrays in the sub-object won't be empty when they get updated on other devices.
In RCORE-734 we fixed this by setting the object to null before doing the replacement. We can't set the array element to null, so instead this transforms the Update into an ArrayErase/ArrayInsert.
> RCORE-788 Fix prior_size issues when replacing an embedded object in a list

- CHANGELOG.md
- how-to-build.md
- src/realm/object-store/sync/generic_network_transport.cpp
- src/realm/object-store/sync/generic_network_transport.hpp
- test/object-store/sync/app.cpp
> Create custom error code for InvalidPassword response

- CHANGELOG.md
- Package.swift
- src/realm/CMakeLists.txt
- src/realm/error_codes.cpp
- src/realm/error_codes.hpp
- src/realm/status.cpp
- src/realm/status.hpp
- src/realm/status_with.hpp
- test/CMakeLists.txt
- test/test_status.cpp
This ports the Status/StatusWith types from the MongoDB server codebase into realm. Status is a type that represents an error - or the lack-thereof - with an error code and an error message. This is just the initial implementation. There are some features that I are missing and I've kept the error codes both manually defined (in Mongo they're generated from a YAML file) and minimal until we can tackle the "Unify Error Handling" project. For now, this is enough for porting the Promise/Future libraries.
If you want to see what these look like in the Mongo codebase, they're in https://github.com/mongodb/mongo/blob/master/src/mongo/base/status.h and https://github.com/mongodb/mongo/blob/master/src/mongo/base/status_with.h.
> Add Status/StatusWith/ExceptionForStatus types to represent errors and exceptions for Promise/Future callbacks/results

- CHANGELOG.md
- src/realm/sync/apply_to_state_command.cpp
This fixes an internal command-line tool that applies wire protocol messages to a local realm so that it fails with a bad exit code if download message integration fails
> RCORE-807 ApplyToState tool should fail if download integration fails

- src/realm/group.cpp
- src/realm/group.hpp
- test/test_transactions.cpp
Fixes #4798.
A constant was already used. There is one place where the constant is not used and this is because we want increase the probability that the upgrade logic is updated appropriately to be able to upgrade to the new version. Unit tests will ensure that this is done. The assertion that was able to slip untouched through unit test is removed as it is not that relevant any longer because of the new backup logic.
> Reduce number of places to update file format version

- Jenkinsfile
[rlmNode](https://github.com/realm/ci/blob/master/vars/rlmNode.groovy) ([docs](https://github.com/realm/ci/blob/master/vars/rlmNode.txt)) will use a temp directory and clean up after itself in a finally block.
This is motivated by our windows hosts running out of disk space too often and should hopefully require less manual intervention going forward.
> use rlmNode to clean up local files

- CHANGELOG.md
- src/realm/object-store/thread_safe_reference.cpp
- src/realm/object-store/thread_safe_reference.hpp
- src/realm/query.hpp
- test/object-store/thread_safe_reference.cpp
Before core 6 ThreadSafeReference had to pin the source transaction version because we needed the transaction logs to update that TSR to a later version. Now that we have stable IDs we no longer need the origin version to continue to exist. The one exception to this is when the TSR is holding a Query: we don't actually _need_ to pin a version there, but Query currently needs a Transaction to exist, and while a Query not attached to a Transaction is conceptually possible we haven't implemented it.
A second unrelated change is that inside a write transaction we forbid creating a TSR to a Results which wraps a Query which depends on a Collection. This is because if the Collection was created inside that write transaction, the TSR would appear to be valid but would always give empty results …
> Avoid pinning versions in ThreadSafeReference except when needed

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/app.cpp
When receiving a 401/403 response on token refresh, we would create a fake `SyncError` with protocol error: `permission_denied`. This was incorrect as the SDKs would then expect the `user_info` dictionary to contain the path to the original file - see: https://github.com/realm/realm-core/blob/62527a1296a283f2b5ca6c7fde3454297acbedd6/src/realm/object-store/sync/sync_session.cpp#L446-L451
There would also be an expectation that a file where permissions have been denied would be deleted, which is neither the case, nor the intention of our code handling the 401 response. I've replaced the protocol error with `bad_authentication` because it better reflects reality and there's no special handling for this particular error code by SDKs.
@ironage I have updated the only test I could find that was …
> Use correct protocol error code for 401/403 on token refresh

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- test/object-store/sync/user.cpp
> RCORE-821 Update user metadata atomically

- CHANGELOG.md
- src/realm/obj.hpp
- test/test_array_mixed.cpp
It can be a bit cumbersome to use `get_any(ColKey)` when you only have the name of the property/column.
> Add Obj::get_any(StringData) for convenience

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
In realm-js, we were witnessing a large delay when the process was killed.
It seems this was due to the cleanup being left to the garbage collector,
which would take anywhere between 5 to 10 seconds to release everything.
This change will release the resources immediately on realm closure and
fixes the issue we were having.
This fixes the following issues: 
https://github.com/realm/realm-js/issues/3620
https://github.com/realm/realm-js/issues/2993
> Release Scheduler on Realm Closure

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- test/test_table.cpp
I ran into this while writing benchmarks for something unrelated. This affects `Table::create(... FieldValues)` when one of the values is a Mixed link. SDKs may be unaffected if they are not using this way of creating objects.
> fix inserting a mixed link

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/generic_network_transport.hpp
- test/object-store/realm.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/sync_manager.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
Now we just have `App::Config::transport` which is a
`shared_ptr<GenericNetworkTransport>`.
> de-factory GenericNetworkTransport::NetworkFactory

- src/realm/sync/noinst/client_impl_base.cpp
This should be identical to the original version, just easier to read.
> Use early return to clean up ClientImplBase::Session::send_message()

- CHANGELOG.md
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/session/progress_notifications.cpp
The names of these types were inconsistent and that bothered me when wrapping them in the C API. I think arranging them like this makes more sense from the API perspective.
> Consolidate type names in SyncSession

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
Add a convenient way to get the sync session for a particular realm instance so that the SDKs don't need to jump through hoops like this: https://github.com/realm/realm-dotnet/blob/db4522869d63f112ee37ae2db5db5755d0438c95/wrappers/src/app_cs.cpp#L277-L282
> Add Realm::sync_session() accessor

- CHANGELOG.md
- src/realm/util/file.cpp
- test/object-store/migrations.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
On Mac this changes the directory that test files are written from "/var/tmp/" to "/var/folders/1y/_7..." which allows the OS to clean them up on a reboot.
Additionally, `TestFile` will clean up the temp directory it creates when finished, if not instructed to persist it.
This should mitigate part of https://jira.mongodb.org/browse/BUILD-13876 going forward.
My dev machine had 2 million mostly empty directories in `/var/tmp/realm_*` totalling 12 GB. Every run of the object-store tests created around 4000 directories there. Since at this scale, most attempts to do anything at that path from the terminal didn't work I had to use a script to clean it out: 
```
util::DirScanner dir("/var/tmp/");
size_t count = 0;
size_t did_delete = 0;
std::string name;
while (dir.next(name)) {
if …
```
> Use the env TEMPDIR if available instead of P_tmpdir.

- CHANGELOG.md
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
The abstract factory class only ever had one method so a `std::function` is a better fit. Making it a `std::function` and not a raw pointer also makes life easier for some SDKs.
> Replace the SyncLoggerFactory class with a closure

- CHANGELOG.md
- src/realm/object-store/sync/sync_manager.cpp
I was running into a deadlock about 1 in 1000 runs in debug builds, in the tests that I added in the client reset branch. It could maybe explain why CI sometimes hangs on the object-store tests, but is unlikely that users would hit this in production.
I'm extracting the fix from the client reset work because it is a change not specifically related to client reset and deserves to get independent reviews.
> Fix a race to deadlock when unregistering a sync session

- CHANGELOG.md
- Jenkinsfile
- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/sync/changeset_encoder.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/server/server_history.cpp
- src/realm/sync/transform.cpp
- src/realm/sync/transform.hpp
- src/realm/util/buffer.hpp
- test/object-store/sync/metadata.cpp
- test/peer.hpp
- test/test_changeset_encoding.cpp
- test/test_sync.cpp
I hit a deadlock due to a lock-order inversion on m_user_mutex and m_filesystem_mutex, found it difficult to determine what the locking should be, and then adding thread-safety annotations revealed a bunch of problems.
While trying to figure out what lock client_uuid should be guarded by I discovered that it's no longer used for anything, as it was a partial sync thing.
> Fix some problems in sync manager locking

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- test/object-store/sync/session/progress_notifications.cpp
- test/test_sync.cpp
#4989 shifted where `downloaded_bytes + downloadable_bytes` was done, which resulted in streaming download notifiers reporting incorrect values. This moves it back and adds a different fix for what appears to be the bug it was trying to fix.
> Fix streaming download notifiers

- CHANGELOG.md
- src/realm/object-store/object_accessor.hpp
- test/object-store/object.cpp
Realm JavaScript is performing the same lookup, so the proposed method will make it possible to avoid the additional lookup.
Related to https://github.com/realm/realm-js/pull/4058
> Add Object::set_property_value(ContextType&, const Property&, ValueType, CreatePolicy)

- test/test_parser.cpp
Yet another attempt at fixing a sporadically failing test, as seen in https://github.com/realm/realm-core/pull/4993
```
/mnt/jenkins/workspace/realm_realm-core_PR-5006@3/test/test_parser.cpp:4037: ERROR in Parser_ObjectId: CHECK(generated_pk.get_timestamp().get_seconds() - ts_now.get_seconds() >= 1) failed
```
I think the reason this is still failing is because the two consecutive calls to get the current time are not guaranteed to be monotonically increasing due to using the system clock. Maybe at the time of failure, the system clock has been pushed back a bit to keep it's clock in line with the network time. I don't know for sure, but I rewrote the test to not rely on two consecutive calls to get the system time. 🤞
> really fix a sporadically failing test

- evergreen/install_baas.sh
This updates the URL where we download the stitch support libraries when starting baas in evergreen tests.
> Fix ubuntu2004 stitch support libs in baas install script

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
This adds the ability to request notifications (in the form of a Future resolving) for changes to the state of FLX sync subscription sets.
> Add state-change notifications for FLX subscription sets

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- test/object-store/sync/app.cpp
Fixes https://github.com/realm/realm-js/issues/3882 and https://github.com/realm/realm-core/issues/4195
Instead of adding a delay at the sync session level, hook into the sync client's existing retry logic which has built in backoff.
> Use existing sync client backoff on auth errors

- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/async_open_task.hpp
- src/realm/object-store/util/checked_mutex.hpp
I was curious if this'd have caught the bug fixed by #4956. It didn't, but seems good to have anyway. The unguarded use of `m_coordinator` in the completion callback currently happened to always be safe, but moving the access into the critical section is also just a good idea.
> Add clang TSE annotations to AsyncOpenTask

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
- test/object-store/benchmarks/client_reset.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
Several updates based on feedback from SDK integration.
- the notify callbacks now pass a SharedRealm object instead of a TransactionRef
- rename "seamless loss" to "discard local"
- don't download the fresh Realm copy with the local schema because it might be wrong
> Client reset updates

- src/realm/sync/subscriptions.cpp
This came up while writing .NET tests - the subscription got inserted in the penultimate position, which made the returned iterator incorrect.
> Insert FLX subscription at the correct index

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/sync_test_utils.cpp
Several sporadic failures were actually pointing to a real problem which was an oversight that copying a config object would not copy the sync config. This meant that a subsequent client reset would use manual mode. (ex [report](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-5009/15/pipeline/)) 
Increasing the wait time for baas to pull changes into the backing db from 3 to 5 minutes because sometimes this is timing out on CI (ex [report](https://spruce.mongodb.com/task/realm_core_stable_macos_1015_release_object_store_tests_patch_9878e696b6df99c65d99eaa31cae08908fbad5df_6193fcec3e8e8628da63a80b_21_11_16_18_48_13/logs?execution=0&sortBy=STATUS&sortDir=ASC))
The backoff times are relaxed a bit because there was a [failure …
> Fix some sporadically failing tests

- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
I was implementing the C API for .NET and noticed we're missing a get_at_index for the subscription set. This is needed to support C# enumerators (equivalent to C++ iterators) without building a lot of complex machinery around the already exposed subscription set iterator. Feel free to also discard this PR if there's a better way to go about it.
> Expose SubscriptionSet::at

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- test/test_sync_subscriptions.cpp
Fixes the erase() method if SubscriptionSet so that it returns the correct iterator. Also adds a test case for the iterator returned by the insert method.
Fixes https://github.com/realm/realm-core/issues/5052
> Fix iterator handling in SubscriptionSet erase

- CHANGELOG.md
- src/realm/query.cpp
- src/realm/query_expression.hpp
- src/realm/util/serializer.cpp
- test/test_parser.cpp
The impetus for all this is that queries of the sort `realm.objects(DictionaryContainingObject.self).filter("dictionary.@avg = %@", dictionary.average())` would sometimes fail to match the object containing that dictionary. There turned out to be a few problems.
1. Aggregate operations on Dictionaries always did the aggregate using Decimal128 temporaries, which produces incorrect rounding; summing a sequence of Decimal128s and then converting to float isn't identical to summing a sequences of floats. Fortunately the relevant code already supports aggregating the specific types and just had to be passed the data type. I don't know if the specific change here is ideal. I know we're trying to move away from converting ColumnTypes to DataTypes, but I don't see a good way to get the DataType. …
> Use the correct data type for aggregate queries on Dictionaries

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
Fixes https://github.com/realm/realm-core/issues/5061
It may be debatable if calling refresh on an immutable Realm should throw or silently do nothing. We could easily make it a no-op, but it seems that the historical behaviour has been to throw an exception so I'll bring that back to not break other SDKs who may be relying on this.
Tracking down the history led to https://github.com/realm/realm-core/pull/4688 being where the first refresh was allowed and did nothing. This was because the first refresh of an immutable Realm had no associated transaction and so populated one there. The second call to refresh, now having a transaction actually tried to advance the version and the DB object throws because it has been configured without history.
> Fix the exception message for refreshing an immutable Realm

- CHANGELOG.md
- src/realm/impl/simulated_failure.cpp
`SimulatedFailure` has support for intercepting calls to `mmap()` by installing a function pointer in a global variable. However, when running unit tests with `UNITTEST_THREADS=30`, the simulated failure would impact other threads.
This changes the mmap interception mechanism to be thread-local.
> Make SimulatedFailure mmap() handling thread-safe

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
- src/realm/version_id.hpp
- test/object-store/sync/client_reset.cpp
Requested via SDK feedback while integrating. (https://github.com/realm/realm-java/pull/7585#discussion_r755034989)
There is not much you could do with the after state in the _before_ callback so it makes more sense to move it to the _after_ callback so that if developers want to do some kind of manual diff themselves they have the opportunity to do it.
> swap the client reset callback signatures

- CHANGELOG.md
- src/realm/util/websocket.cpp
- test/object-store/sync/app.cpp
I think what's going on with this test being flakey is a subtle bug in our websocket implementation.
When the test is failing, this is the order of operations:
At T0, the client sends a message to the server that is too large for the server to receive.
At T1, the server sends a websocket close message with an error message
At T2, the client begins to send another message and the server closes the TCP underlying TCP socket.
At T3, the client's call to `send` fails with `ECONNRESET` and the client begins its reconnect loop. Go back to T0.
When the test is succeeding, this is the order of operations:
At T0, the client sends a message to the server that is too large for the server to receive.
At T1, the server sends a websocket close message with an error message
At T2, the client receives …
> Make sure sync client receives error message when TCP socket is closed

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
Reported by @clementetb  during SDK integration tests.
> Fix an assertion if the server adds an embedded table during client reset

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/conversion.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/migrations.cpp
- test/object-store/realm.cpp
This completes the renaming that should have happened shortly after https://github.com/realm/realm-object-store/pull/511
I also unsuccessfully attempted to reproduce https://github.com/realm/realm-core/issues/4599 and have added a passing test for it. I think the issue lies in the cocoa SDK.
> Rename SchemaMode::ReadOnlyAlternative to ReadOnly

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
Adds a unique ObjectId to Subscriptions so that you can uniquely identify them without comparing the query or name fields.
> Add unique id to Subscriptions

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- test/test_sync_subscriptions.cpp
This does what it says on the tin.
@nirinchev, is this the behavior you expected?
> Anonymous subscription assignment shouldnt replace named subscriptions

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_parser.cpp
Queries of the form "link.collection.@sum = 0" match when link is null and collection is a List or Set, but didn't when collection was a Dictionary.
> Align the result of @sum over a null link to a dictionary with the other collections

- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/config.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/protocol.cpp
- src/realm/sync/protocol.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
- test/test_sync_subscriptions.cpp
This is the MVP of flexible sync. This does a bunch of things, it:
- Adds some basic serialization of `SubscriptionSet`'s to json so they can be sent to the server 
- Connects the `SubscriptionStore` and the `SubscriptionSet` lifecycle up to the sync client, so that new subscription sets get sent to the server as QUERY messages and QUERY_ERROR messages get propogated to `SubscriptionSet`'s as errors.
- Adds an option for constructing the `SyncConfig` struct specifically for FLX sync, and uses that to decide whether to open an FLX sync connection/sync session or not.
- Implements retries on session-level ERROR messages where try_again is true. This lets the server send back a session level error message that causes just that session to unbind and attempt to re-bind after a delay with some …
> Hook up FLX subscriptions to wire protocol state machine

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
As part of commit_transaction, a callback on an a binding context can happen. During this callback, it should be possible to make new transactions or possibly close the Realm.
> Allow commit_transaction to be called recurcively

- Jenkinsfile
- test/object-store/sync/sync_test_utils.cpp
This should hopefully fix the failures we have occasionally been seeing. 
The issue is that the test harness creates several commits on the remote Realm and if the timing is just right, `wait_for_download` will only pick up the first one. Instead, `wait_for_upload` should block until the local changes are acknowledged by the server which causes the reset to take place.
This is only affecting the tests which are configured to run against the local sync test server, but I haven't seen any failures on the tests running against baas recently.
Recent reported failures that this may fix:
https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-5000/18/pipeline/
https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-5076/2/pipeline/ …
> Fix a race in the client reset tests

- CHANGELOG.md
- src/realm/util/websocket.cpp
- test/object-store/sync/app.cpp
I think what's going on with this test being flakey is a subtle bug in our websocket implementation.
When the test is failing, this is the order of operations:
At T0, the client sends a message to the server that is too large for the server to receive.
At T1, the server sends a websocket close message with an error message
At T2, the client begins to send another message and the server closes the TCP underlying TCP socket.
At T3, the client's call to send fails with ECONNRESET and the client begins its reconnect loop. Go back to T0.
When the test is succeeding, this is the order of operations:
At T0, the client sends a message to the server that is too large for the server to receive.
At T1, the server sends a websocket close message with an error message
At T2, the client receives the …
> Ensure receive queue is drained after socket error

- CMakeLists.txt
- src/realm/CMakeLists.txt
- src/realm/object-store/CMakeLists.txt
- test/CMakeLists.txt
`query_state.hpp` simply appears to be missing, and the copying of certs would fail for external projects considering where the cmake source directory would be pointing.
> Fix CMake files for external consumption

- CHANGELOG.md
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/obj_list.hpp
- src/realm/object-store/results.cpp
- src/realm/sync/subscriptions.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_cluster_tree.hpp
- src/realm/table_view.hpp
- test/test_array_mixed.cpp
- test/test_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_link_query_view.cpp
- test/test_object_id.cpp
- test/test_parser.cpp
- test/test_query.cpp
- test/test_query2.cpp
- test/test_table.cpp
- test/test_table_view.cpp
- test/test_uuid.cpp
The original implementation in ObjList uses two virtual methods to first find out if the key was valid and  - if it was - subsequently
find the object using that key. For tables, this can be done more efficiently by just trying to look up the object.
At the same time TableView::get() is removed. It is silly to have two names for the same function.
> Add 'try_get_object' function to TableView

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
The admin API for baas has [changed the format for queryable fields when creating an FLX sync app](https://jira.mongodb.org/browse/REALMC-10837) and this updates the sync client's testing framework to use the new format.
> Use new format for queryable fields in FLX sync app config

- evergreen/config_overrides.json
- evergreen/install_baas.sh
This should hopefully speed up the client reset integration tests which we have seen can take more than 3 minutes to propagate changes from the translator into the backing db.
If this works, I'll update our Docker file to do the same on Jenkins and local development.
> Add some baas config overrides to make integration tests faster

- .gitignore
- src/realm/group.cpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_shared.cpp
- tools/coverage.sh
We can now compare collections and embedded objects.
We can compare Groups that are not in the same realm.
No entry in CHANGELOG.md as this is not supposed to be used externally.
> Make comparing Groups more comprehensive

- src/realm/query.cpp
- test/test_query2.cpp
Respecting a limit on find_all would fail in a query with more than one Equal condition and when there was a search index on one of the properties involved in the query
> Fix error introduced in a5d82daaf2db0

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/error.cpp
- src/realm/object-store/c_api/error.hpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/c_api/util.hpp
- test/object-store/c_api/c_api.cpp
This changes the C api so that it doesn't use std::exception_ptr to store error information internally and just allocates a string to store the result of `what()` instead. It also changes the async_error type to capture the new `ErrorStorage` type. I've removed some helper functions that let you treat the C api realm error types a C++ exceptions since the philosophical change in this PR is that the error types we expose from the C API are not C++ exceptions, they're realm errors.
> Do not use std::exception_ptr for C error API

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_manager.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/sync_manager.cpp
This just makes sure that if FLX sync is enabled, then we can generate a sane default realm file name in the sync manager.
> Ensure path_for_realm works for FLX sync

- evergreen/config.yml
- evergreen/hang_analyzer/__main__.py
- evergreen/hang_analyzer/requirements.txt
- evergreen/hang_analyzer/src/dumper.py
- evergreen/hang_analyzer/src/hang_analyzer.py
- evergreen/hang_analyzer/src/pipe.py
- evergreen/hang_analyzer/src/process.py
- evergreen/hang_analyzer/src/process_list.py
This ports over the hang analyzer from the mongodb server's codebase and evergreen config. If a test times out in evergreen, the hang analyzer will attach to it via the local debugger (gdb, lldb, or windbg) and print a stacktrace for all the threads as well as other helpful info like what shared libraries were loaded and what critical sections were locked.
Most of this change is porting over the python code from https://github.com/mongodb/mongo/tree/master/buildscripts/resmokelib/hang_analyzer so that it works without all the resmoke infrastructure used in the server.
This is not an urgent PR, but I think it would be a nice quality of life improvement for timed out tests.
For an example of the output, can you check out this evergreen patch that forces the core tests to time out after only …
> Add hang analyzer

- CHANGELOG.md
- src/realm/util/future.hpp
This relaxes the requirement that callbacks to Future::get_async must be marked as noexcept. They will always be called from a noexcept context so if the callback does throw it will get noexcept behavior immediately from its caller. This also means you can pass in `UniqueFunction`'s without having to mark them noexcept in the function signature (something that is not currently supported).
> Relax noexcept requirement in util::Future::get_async

- CHANGELOG.md
- src/realm/object-store/object_store.cpp
- src/realm/object-store/object_store.hpp
- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
- test/object-store/schema.cpp
In AdditiveDiscovered mode we don't create tables for embedded object types which are never actually used. However, because of where we did this logic we would think that we had schema changes to apply every time we opened a Realm and so would commit an empty write transaction. https://github.com/realm/realm-core/pull/4965 changed this from a silent performance problem to a crash because starting the pointless write transaction would fail.
To fix this, filter out table additions for orphaned types in compare() rather than when applying the result of compare().
> Filter out embedded orphan types earlier in the schema update process

- evergreen/install_baas.sh
- test/object-store/util/baas_admin_api.cpp
This changes the baas admin api in our tests to use the new naming in REALMC-11259.
There's also a drive-by fix to the `install_baas.sh` script so it safely shuts down the baas server.
> Change baas admin API in tests to use new names

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/sync/client.cpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
- test/test_sync_subscriptions.cpp
This splits `SubscriptionSet` into `MutableSubscriptionSet` and `SubscriptionSet` to add some more type safety around what you can do with what gets returned from `SubscriptionStore::get_latest()`.
This also adds a method to the `SubscriptionSet` that lets you reload any state changes from disk and makes it clearer that `MutableSubscriptionSet`s should only exist until you commit them (i.e. `commit()` now returns a regular `SubscriptionSet` that reflects the set after it was committed.
> Split SubscriptionSet into MutableSubscriptionSet and SubscriptionSet for type safety

- test/CMakeLists.txt
> Workaround Windows command line size limit

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
- test/sync_fixtures.hpp
- test/test_sync.cpp
This change does a lot of things but shouldn't have any user-visible effects besides FLX sync actually working.
The first big change is that the ownership of the subscription store is moved out from the sync client internals and into the object-store SyncSession type. This was to make sure it's available when the sync session is inactive. But it's mostly just code motion.
The second big change - which is also the title of the PR - is that uploads and query change messages should now be totally ordered with respect to where the transaction that created the query change happened in local history.
Finally there are some new tests to make sure that development mode works and that you can create new subscriptions and mutate data in an FLX sync realm when offline.
> QUERY messages should be totally ordered with UPLOAD messages

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
If there have been writes to the database since SubscriptionSet was
created we need to refresh our state before maybe returning a ready
future. We also need to block process_notifications while determining
whether to return a ready future because otherwise the state may change
between deciding not to add a ready future and acquiring the lock to add
the pending future.
> Fix race in SubscriptionSet::get_state_change_nofication()
