realm/realm-core

- CHANGELOG.md
> Use template!

- src/realm/group.hpp
- src/realm/impl/continuous_transactions_history.hpp
- src/realm/impl/transact_log.hpp
- src/realm/util/interprocess_mutex.hpp
- test/test_query.cpp
- test/util/benchmark_results.cpp
- test/util/random.cpp
A few more instances.
@ironage please "review" 😉
> Use nullptr instead of 0.

- packaging/ubuntu-1604/build-image/Dockerfile
- packaging/ubuntu-1604/test-image/inside/test
@alebsack I moved your fix here. It seems to affect all PRs atm.
( cc: @ironage @teotwaki @radu-tutueanu )
> Update apt cache before attempting installs

- CHANGELOG.md
- build.sh
We need to align with Realm Mobile Platform so we don't ship two different versions of OpenSSL.
@beeender @cmelchior @radu-tutueanu @kspangsege @danielpovlsen
> Kneth/android/opgrade to openssl 1.0.2j

- Jenkinsfile
- dependencies.list
- packaging/centos-6/build-image/Dockerfile
- packaging/centos-6/test-image/Dockerfile
- packaging/centos-7/build-image/Dockerfile
- packaging/centos-7/test-image/Dockerfile
- packaging/docker_build.sh
- packaging/functions.sh
- packaging/generic/build-image/Dockerfile
- packaging/generic/test-image/Dockerfile
- packaging/package.sh
- packaging/ubuntu-1604/build-image/Dockerfile
- packaging/ubuntu-1604/test-image/Dockerfile
@emanuelez @radu-tutueanu @sorenvind This is based on the same work done elsewhere, but extended to be able to build cached images from the Jenkinsfile.
> Support for caching docker images

- CHANGELOG.md
- realm.xcodeproj/project.pbxproj
- src/realm/null.hpp
- src/realm/table.cpp
- test/test_all.cpp
- test/test_column_float.cpp
- test/test_index_string.cpp
Reverts realm/realm-core#2223
This was my _"In Progress"_ PR. Not sure why it was merged.
> Revert "Fix broken iOS unit tests"

- src/realm/array.cpp
- src/realm/array.hpp
> Optimize Array::adjust

- Jenkinsfile
> Formalise the logic on whether to publish and stash artifacts

- Jenkinsfile
> Fix a rogue s3cmd

- src/realm/table_accessors.hpp
> Fix unit test release build compilation issue

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
@radu-tutueanu @danielpovlsen please double check the version number and the release notes.
> Bump version to 2.1.2.

- Jenkinsfile
- packaging/functions.sh
> Limit docker image push to master

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
Please verify the version number and the release notes. @radu-tutueanu @finnschiermer
> Bump version to 2.1.3

- packaging/package.sh
> Pass the git tag into the docker build

- Jenkinsfile
@alebsack @emanuelez 
There were some differences between what the Jenkinsfile is doing and the core pipeline. This should even things out.
cc @ironage
> Fix core release

- CHANGELOG.md
- dependencies.list
- src/realm/alloc_slab.cpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- src/realm/util/thread.hpp
- src/realm/version.hpp
Preparing for release of 2.1.4
> Fsa/prepare 2.1.4

- src/realm/util/interprocess_mutex.hpp
Due to fast type syndrome.
@danielpovlsen @bdash
> Fixed spelling mistakes

- Jenkinsfile
@danielpovlsen @emanuelez @alebsack 
This should go in both develop and master
> Only publish on tag

- CHANGELOG.md
- src/realm/string_data.hpp
- src/realm/unicode.cpp
Fixes for https://github.com/realm/realm-core/pull/2265
* Added changelog entry
* Commented variables
* Moved actions to individual lines
@bmunkholm
> Minor fixes for review comments in Like queries

- src/realm/alloc.cpp
- src/realm/alloc.hpp
- src/realm/group_shared.cpp
- src/realm/unicode.cpp
- src/realm/util/file.cpp
- src/realm/utilities.cpp
- test/test_destroy_guard.cpp
- test/test_lang_bind_helper.cpp
- test/test_shared.cpp
- test/test_transactions_lasse.cpp
- test/util/timer.cpp
> Fix warnings (as reported by Visual Studio)

- src/realm/alloc_slab.cpp
- src/realm/group_writer.cpp
These checks are now present also in release builds
@rrrlasse
> Add more checks for memory corruption

- CHANGELOG.md
- Jenkinsfile
- dependencies.list
- packaging/functions.sh
- src/realm/Makefile
- src/realm/array.hpp
- src/realm/table.cpp
- src/realm/version.hpp
- test/test_replication.cpp
Keeping the develop branch up to date.
@radu-tutueanu @rrrlasse
> Update develop branch to latest master

- test/test_lang_bind_helper.cpp
This will also change the testcase for #2321 to work with any bp tree node size.
> Add testcase for bug 2321

- Jenkinsfile
Right now both develop and master publish *latest* artifacts on s3.
@emanuelez @danielpovlsen
> Only publish *latest artifacts from master

- CHANGELOG.md
- Jenkinsfile
- test/test_all.cpp
- test/util/unit_test.cpp
- test/util/unit_test.hpp
Fixes #1368.
I'm hoping @emanuelez can help guide this into production without too much workflow disruption.
> JUnit test format

- CHANGELOG.md
- src/realm/util/logger.hpp
- test/util/unit_test.hpp
@finnschiermer 
These changes are not a blocker!
I cherry picked them from the `devel` branch, because I heard that it might be a rather long time before the `devel` branch is merged to master, and that might negatively impact new code on the sync side (by the lack of the API improvements of this PR).
> Cherry picked commits from PR #2271 in devel branch

- Jenkinsfile
Fixes #2306
@emanuelez @alebsack
> Remove build for dotnet

- Jenkinsfile
Missing headers and debug symbols
> Add more files to the windows package

- src/realm/alloc.hpp
- src/realm/group_shared.cpp
- src/realm/impl/sequential_getter.hpp
- test/test_file_locks.cpp
- test/test_group.cpp
- test/util/benchmark_results.cpp
@ironage @finnschiermer please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/realm/realm-core/2397)
> Fixing arbitrary Coverity issues

- CHANGELOG.md
- build.sh
> Updating OpenSSL to 1.0.2k

- CHANGELOG.md
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
- test/test_query.cpp
Fixes #2408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/realm/realm-core/2415)
> Throw if column has been removed

- build.sh
This will prevent unnecessary rebuilds
> Do not update config.mk if no changes

- Jenkinsfile
This PR is cherry-picking caa6ccad845394 from develop to get the fix into master.
> Fix Jenkinsfile to get it to build cocoa

- test/test_link_query_view.cpp
- test/test_query.cpp
- test/test_table.cpp
- test/test_table_view.cpp
Extracted from another branch to keep PRs clean.
Should only pertain test code and should be trivial to review.
> Minor float fixes

- test/fuzz_group.cpp
- test/fuzzy/start_parallel_fuzzer.sh
Helpful?
@danielpovlsen @jedelbo
> Fuzz test with weighted random MAX_BPNODE_SIZE

- test/test_lang_bind_helper.cpp
…ded encryption to LangBindHelper_InRealmHistory_Downgrade
> Fixed encryption unit tests

- CHANGELOG.md
- Visual Studio/Realm.vcxproj
- Visual Studio/Realm.vcxproj.filters
- realm.xcodeproj/project.pbxproj
- src/realm/Makefile
- src/realm/group_writer.cpp
- src/realm/string_data.cpp
- src/realm/string_data.hpp
- src/realm/unicode.cpp
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
- test/test_string_data.cpp
Everything auto-merged except for CHANGELOG.md where I manually added both sides.
> Update develop to latest master

- CHANGELOG.md
In preparation for the release later today.
> Add missing links for two entries in the CHANGELOG

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
Resolved simple conflicts in CHANGELOG.md.
> Update develop branch to master v2.3.3

- src/realm/alloc.hpp
> Change a couple of stray non-ASCII characters to the ASCII equivalent.

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
> version bump

- CHANGELOG.md
Done quickly in the bus, so please check for errors. 😄
> Add PR links to CHANGELOG

- Jenkinsfile
> Revert back to using android-hub for testing core on an Android device

- CHANGELOG.md
- src/realm/column_string.cpp
- src/realm/column_string.hpp
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/utilities.hpp
- test/test_index_string.cpp
"Middle drop" of adding string index supported case insensitive string queries. Prerequisites already merged.
> Add Support for Case Insensitive Find All to the String Index

- src/realm/group_shared.cpp
For reference, see https://github.com/realm/realm-core/pull/2481#pullrequestreview-27320394.
@danielpovlsen
> Fix int cast warning introduced in #2481

- src/realm/group.cpp
- src/realm/group.hpp
Fixes problem introduced in commit 12f00d08c
> Allow realm files version 6 to be opened

- CHANGELOG.md
This is to help readers to easily get some more detailed information on changes they would care about.
> Changelog links

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
Bump version from 2.4.0 to 2.5.0.
> Prepare for release

- Jenkinsfile
Use double quotes to interpolate string
> Fix stashing of Windows build artifacts

- test/fuzz_group.cpp
Fix dangling pointer to buffer inside destructed `std::string` in `construct_mixed` used by `Shared_StaticFuzzTestRunSanityCheck` and AFL.
> Fix dangling pointer

- CHANGELOG.md
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- test/test_query.cpp
Queries like `begins_with`, `ends_with` ... is now supported on list of strings.
> Add support for string comparison on subtable columns

- CHANGELOG.md
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- test/test_util_file.cpp
- `util::remove_dir_recursive()`
- `util::File::for_each()`
@ironage @morten-krogh
> New file system utility functions

- CHANGELOG.md
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/test_query.cpp
This integrates index based case insensitive search into the query system.
We'll likely need to generalize the way integration is done going forward, as more flexibility is needed and this approach has some code duplication. For now this is left as a later refactoring.
> Integrate Index Based Case Insensitive Search into Query System

- CHANGELOG.md
- src/realm/column_table.cpp
- src/realm/column_table.hpp
- src/realm/table.cpp
- test/test_query.cpp
- test/test_table.cpp
You can say that a subtable column is inherently nullable so this is just about adding some interface to monitor and manipulate the state.
> Allow subtable columns to be nullable

- src/realm/util/string_buffer.hpp
I needed a move constructor for `StringBuffer` :-)
> StringBuffer::StringBuffer(StringBuffer&&)

- src/realm.hpp
- src/realm/alloc.hpp
> Include query_expression.hpp in realm.hpp

- test/bench/report_generator.py
This is an attempt to address the comment that the performance graphs seem "like they'd be more useful if 'max' wasn't part of the graph, since it often is so much higher that it hides changes to the other elements in the graph."
These changes make the graphs only scale to the other lines which gives much better resolution to the minimum, median, and average lines. The cost is that the max line sometimes jumps in and out from the top of the graph.
@finnschiermer @danielpovlsen take a look at the performance report on this PR, do you think this view is more informative than before?
> Do not scale performance graphs to the max metric

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
In preparation for patch release...
> bump version to 2.6.1

- CHANGELOG.md
> Add PR links to changelog items and rearrange slightly

- src/realm/table_view.cpp
'size' shadows a member of 'this'
> Fix compiler warning

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
Note that this PR adds a missing changelog under enhancements for PR #2558, please check that what I've written there is sufficient.
Since there are enhancements I've bumped the minor version.
> Release 2.8.0

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
- test/test_version.cpp
> Release 3.0.0-rc1

- src/realm/group_shared.cpp
Suppresses `[performance] group_shared.cpp:591:28: warning: offsetof within non-standard-layout type 'realm::SharedGroup::SharedInfo' is undefined [-Winvalid-offsetof]`
> Jenkins warning

- CHANGELOG.md
Fix release notes for #2655.
This never gets old 👴...
> Fix release notes for 2655

- src/realm/group_shared.hpp
- test/test_shared.cpp
- test/test_transactions_lasse.cpp
Maybe this can be retargeted to `master`...
> Change platform sleep calls to realm::millisleep

- CHANGELOG.md
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/encrypted_file_mapping.hpp
> Fix encryption bug (deadlocks/hangs)

- CHANGELOG.md
- dependencies.list
- src/realm/version.hpp
> Version bump to 2.8.4

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/impl/transact_log.hpp
- src/realm/replication.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/fuzz_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_replication.cpp
- test/test_table.cpp
- test/test_transactions.cpp
> Support adding new row and setting key value in one operation

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- test/test_index_string.cpp
- test/test_query.cpp
Core reproduction of https://github.com/realm/realm-java/issues/4788.
> Bug with Case-insensitive Query

- CHANGELOG.md
- Visual Studio/Realm.vcxproj
- Visual Studio/Realm.vcxproj.filters
- src/realm/util/aes_cryptor.hpp
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- src/realm/utilities.hpp
- src/win32/kalven-sha2/CMakeLists.txt
- src/win32/kalven-sha2/README.md
- src/win32/kalven-sha2/sha224.hpp
- src/win32/kalven-sha2/sha224k.cpp
- src/win32/kalven-sha2/sha256.hpp
- src/win32/kalven-sha2/sha256k.cpp
- src/win32/kalven-sha2/sha384.cpp
- src/win32/kalven-sha2/sha384.hpp
- src/win32/kalven-sha2/sha512.cpp
- src/win32/kalven-sha2/sha512.hpp
- src/win32/kalven-sha2/sum.cpp
- test/test_file.cpp
- test/test_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_shared.cpp
> Alternative Windows encryption PR

- .cproject
- .project
- CMakeLists.txt
Without this fix, the macro __cplusplus will have a wrong value. Has the effect that the index is not built correctly.
> Add support for Eclipse

- CHANGELOG.md
- src/realm/row.hpp
- src/realm/spec.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_table.cpp
The purpose of this PR is to release this enhancement in a patch release from master rather than waiting for develop to be merged into master.
The original PR of this feature is #2672.
> Cherry pick backlink count from develop to master

- src/realm/table.hpp
- test/test_table.cpp
> Document the behaviour of Table::get() on null cells

- CMakeLists.txt
This should help people when encountering this build error.
- it now gives the full path to the problematic file
- it now provides two possible solutions
> More descriptive build error

- src/realm/util/encrypted_file_mapping.cpp
PR #2713 added strict warnings in master. The changes were automatically pulled to develop without being built but the differences in master vs develop actually has some more warnings when compiled with clang for WatchOS.
The warnings are all about type conversions that can be ignored, they are fixed here by static cast.
This is currently causing any other PR based after #2713 to fail on develop.
> Fix watch os warnings

- src/realm/utilities.hpp
> Add guard around definition of ssize_t

- CMakeLists.txt
- how-to-build.md
> Update how-to-build.md with instructions on installing cmake

- .cproject
- .gitignore
- tools/release-init.sh
- tools/release-tag.sh
Update to some project files and a few new scripts
> Admin updates

- CHANGELOG.md
- src/realm/table_view.cpp
- test/test_table_view.cpp
It was passing the wrong index to `m_table->get()` and it turned out to be nearly untested.
> Fix incorrect results from TableView::find_first()

- packaging/centos-6/build-image/Dockerfile
- packaging/centos-6/build-image/inside/build-package
The installation of CMake 3 seems to be currently broken so it's going to be installed manually
> Fix the Centos6 builds

- src/realm/CMakeLists.txt
- src/win32/CMakeLists.txt
- src/win32/kalven-sha2/CMakeLists.txt
this makes it easier for bindings to consume them
> Embed sha and getopt libraries on windows

- CHANGELOG.md
- src/realm/column_link.cpp
- src/realm/column_link_base.cpp
- src/realm/column_linklist.cpp
- src/realm/group.hpp
- src/realm/link_view.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/fuzz_group.cpp
- test/test_group.cpp
If deleting an object removes the last link to another object, that object will be deleted too.
Fixes #2718
> Add table::remove_recursive function

- src/realm/util/thread.hpp
Replace `std::mutex` with [`CRITICAL_SECTION`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682530(v=vs.85).aspx) and `std::condition_variable` with [`CONDITION_VARIABLE`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682052(=vs.85).aspx).
This shaves off several minutes from running the core unit tests (in Debug, of course).
On my machine this goes from
```
Top 5 time usage:
---------------------------------------------------------------------------
ThreadSafety_RowDestruction                                           3m44s
ThreadSafety_LinkViewDestruction                                      1m50s
Shared_StaticFuzzTestRunSanityCheck                                   1m14s
StringIndex_Insensitive_Fuzz<struct+std::integral_constant<bool,1>>  41.78s …
```
> Reimplement Mutex and Condvar on Windows

- test/bench/revs_to_benchmark.txt
This affects the automated performance reports.
> Update benchmark versions with recent releases

- Jenkinsfile
This is a copy of https://github.com/realm/realm-core-private/pull/27. We want to apply the change here as we don't want the master branches to differ.
> Fix CI notifications to Slack

- test/test_destructor_thread_safety.cpp
The test case shows the crash when destruct subtable on a bg thread, and close the group on fg thread. As the agreement before, this scenario should work if there are proper locks to ensure group and accessors are not freed at the same time.
With a quick look, it feels the problem is with `SubtableColumnBase::m_subtable_map`.
> Subtable's destructor is not thread safe

- CHANGELOG.md
> added missing changelog entry

- CMakeLists.txt
> fvisibility=hidden is missing

- packaging/generic/build-image/inside/build-package
Moves the libraries from lib64 to lib
> Fix the generic package

- src/realm/util/terminate.cpp
__android_log_print is a variadic function.
> Fix compile warning for android

- CMakeLists.txt
- src/realm/CMakeLists.txt
See https://github.com/realm/openssl-android/pull/2
To fix sync ssl issue.
> Bump android openssl to 1.0.2k-1

- CHANGELOG.md
- dependencies.list
> Prepare release 4.0.3

- CHANGELOG.md
> Retry 4.0.3 release with publishing fixes

- packaging/centos-6/base-image/Dockerfile
This should fix https://github.com/realm/ci/issues/235
Related is https://github.com/realm/realm-sync/pull/1852
> Fix CI centos6 package failures

- src/realm/group_shared.cpp
I don't know the imact because we have moved the log inside the .realm file. If anybody knows, please describe it
@realm/core
> Fixed threading problem in .lock file

- src/realm/util/terminate.cpp
> Make ASSERT actually print its debug information in DEBUG mode

- CHANGELOG.md
- dependencies.list
Updated CHANGELOG.md with some missing notes.
> Prepare for 5.4.0

- CHANGELOG.md
- src/realm/alloc.cpp
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group.cpp
- test/test_destroy_guard.cpp
New slab allocator with O(log N) cost of allocations, where N is the number of different free block sizes.
> Improved scalability of slab allocator

- CHANGELOG.md
- dependencies.list
- src/realm/group.cpp
> Prepare 5.7.1

- src/realm/util/file.cpp
I want a bit more information from the assert here.
> improved assert for File::unlock()

- CHANGELOG.md
- doc/CHANGELOG_template.md
Related discussion https://github.com/realm/realm-core/pull/3117
> Remove the change log compatibility section

- src/realm/alloc_slab.hpp
- src/realm/group.cpp
- src/realm/group_writer.cpp
- src/realm/utilities.cpp
- test/test_query.cpp
- test/test_shared.cpp
- test/test_table_view.cpp
- test/test_transactions.cpp
- test/test_util_file.cpp
- test/util/jsmn.hpp
Change-Id: I7c97c673ab6240f4475b13cb1b36b2fbf8b02aa7
> Remove TAB characters from code

- src/realm/realm_trawler.cpp
Change-Id: Ied563b5892b6796e95d5c969c86184b81853713f
> Fix calculation of size in realm-trawler

- Jenkinsfile
We should only run publishing step when building a release branch.
Basic checking should be performed on all branches at all times.
> Fix build logic in Jenkinsfile

- CHANGELOG.md
- src/realm/group.cpp
> Get_used_space fix

- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
Reported by the thread sanitizer on my machine, but apparently not by CI so far.
> fix a race during initialization

- src/realm/alloc_slab.cpp
- src/realm/util/file_mapper.hpp
Change-Id: I2fa8a1393f457e8d5178e40bc593ec8f5dbaa251
> Fix compilation without encryption

- Jenkinsfile
Change-Id: If06f1aac232b2b75f0e2c79300145ac4be2f7ad8
> Test without encryption in CI

- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/exec/realm_trawler.cpp
Add ability to use the alternative top ref.
Make it possible to walk a realm with invalid top ref.
> Improve realm-trawler

- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/exec/realm_trawler.cpp
Change-Id: Id0491443b3cf5f5b721c0cfb7d0ea2cf98738171
> Updates to realm-trawler

- CHANGELOG.md
- src/realm/array.cpp
- test/test_array.cpp
Fixes https://github.com/realm/realm-sync/issues/2724
> Allow calculation of sum of an empty array

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group_shared.cpp
- src/realm/group_shared_options.hpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
Add the option to selectively disable sync to disk.
> added Durability::Unsafe

- CHANGELOG.md
- dependencies.list
Change-Id: I29e50301e69c34399016960c81a38fcf86d61da5
> Prepare release 5.14.0-ndk18.1

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/util/file.hpp
- test/test_shared.cpp
Fixes https://github.com/realm/realm-sync/issues/2754
> Improve performance of compact into encrypted realm

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/group.cpp
- src/realm/group_shared.cpp
- src/realm/group_shared.hpp
- test/test_shared.cpp
Change allocation logic in SlabAlloc
Ability to get commit size and allocated size
Refactor Slab class
Remove code behind REALM_SLAB_ALLOC_TUNE flag
> SlabAlloc updates

- CHANGELOG.md
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.hpp
- test/test_link_query_view.cpp
This can be utilized in permissions check in sync.
> Enhace LinksToNode so that it can check links to multiple targets

- src/realm/group_writer.cpp
- test/test_lang_bind_helper.cpp
> Prevent small realms from growing unreasonably

- src/realm/util/file.cpp
- test/test_util_file.cpp
- test/util/test_path.hpp
* util: Add Unicode path support for try_make_dir and try_remove_dir
> Add Unicode path support for Windows (#3293)

- .cproject
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/table.cpp
- src/realm/table.hpp
Few changes needed in order to make it useful from OS.
Add validation functions on Group and Table. Make sure
that cached primary key column key is up to date.
> Improve pk handling

- test/test_parser.cpp
Adding another test which I wrote to confirm behaviour. Might as well add it in.
> Extra include descriptor testing

- src/realm/list.cpp
- src/realm/table_view.cpp
> Make compile with GCC 8

- src/realm/column_type_traits.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- test/test_table.cpp
Makes some coding simpler in realm-object-store
> Add min, max,... as virtual members of ConstLstBase

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/exec/realm_trawler.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/fuzz_group.cpp
- test/test_shared.cpp
Fixes https://github.com/realm/realm-core-private/issues/324
> Fix link to self

- CHANGELOG.md
- src/realm/util/file_mapper.cpp
> fix for #3352

- src/realm/column_type_traits.hpp
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- test/test_metrics.cpp
- test/test_table.cpp
Fixes issue https://github.com/realm/realm-core-private/issues/327: Core6: nullability checks for list of primitives
> Add check for setting null values in non-nullable lists

- CHANGELOG.md
- src/realm/impl/transact_log.hpp
- src/realm/obj.hpp
- test/test_query.cpp
Fixes realm/realm-core-private#333
> Fix query over LinkView involving string index

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: Ide8f89ad2cf5333522503420d8a567d56c468581
> Prepare release 6.0.0-alpha.21

- src/realm/db.cpp
- src/realm/replication.hpp
Change-Id: Ifd0dfc6c39edbcd3d0299da43210e54880d5da44
> Fix issue with DB outliving Replication object

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: Ia2ea737d6c818281e73ff0051b38bb7dc1a2de6d
> Prepare release v6.0.0-alpha.22

- test/test_group.cpp
Change-Id: I519a7c8cebe577eb1a94839d4e24592670b1e400
> Fix Group_ToJSON

- src/realm/bplustree.cpp
- test/test_bplus_tree.cpp
> Fix problem with leaf cache in BPlusTree

- src/realm/timestamp.hpp
Change-Id: Idb65fa2e963a329e382518660e5ccbce3061fc8b
> Make timestamp output function reentrant

- CHANGELOG.md
- Package.swift
- dependencies.list
- test/test_links.cpp
Change-Id: I4d931868bc682c3b632ce9f19f455ea2b0e0a970
> Prepare release 6.0.0-alpha.24

- src/realm/db.cpp
- src/realm/list.cpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/test_lang_bind_helper.cpp
- test/test_query_big.cpp
Change-Id: I0af4c102b21addf19cd565ff98c6c07c1a4abca6
> Harden Obj by checking aliveness before handing out TableRef

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: I5d5720ca56b9ea0da43eeefe32cad19a8d18d918
> Prepare release 6.0.0-alpha.25

- CHANGELOG.md
- src/realm/group.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_group.cpp
Small updates to make it possible to change primary key column.
> Fix Table::validate_primary_column_uniqueness

- src/realm/array_backlink.cpp
- src/realm/exceptions.cpp
- src/realm/table.cpp
Change-Id: I781d23988c0cede127934261009db9f66a6df0be
> Fix shadow warnings

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/cluster_tree.hpp
- test/test_table.cpp
> Fix Table iterator

- CHANGELOG.md
- Package.swift
- dependencies.list
- src/realm/cluster_tree.hpp
Change-Id: I4f7f073810c42821c545e4ca3ae2200fd9f141b8
> Prepare release 6.0.0-alpha.26

- src/realm/util/file.cpp
Fixes https://jira.mongodb.org/browse/RCORE-215
> Fix potential error in File::get_file_pos

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- test/test_alloc.cpp
Change-Id: Ibce1bd3c976324f12e95226101741a6cbf97ab7d
> Fix assertion in SlabAlloc::allocate_block

- src/realm/group.cpp
- test/fuzz_group.cpp
Motivated by https://jira.mongodb.org/browse/RCORE-51
> Use only one DB object in fuzz test

- CHANGELOG.md
- src/realm/object_id.cpp
- src/realm/object_id.hpp
- test/test_object_id.cpp
Change-Id: I54181fd3f3dabe6210e41b185cad7d3abab5c56f
> Add ability to stream into an ObjectID

- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/util/thread.hpp
Optimizations of special value to the JS binding.
Change-Id: I8034891a350d12171d8e4ede87b1302f4a5c02e9
> optimize Group::key2ndx_checked and get_table

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: I3d5624e9ae5a95f19d2d3ca0faaf81dda1eed50c
> Prepare version 6.0.0-beta.0

- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/test_lang_bind_helper.cpp
- test/test_query.cpp
Change-Id: I2c748b49e23fff6a9cc086bd7a431c0d68a2bd55
> Make TableView::get_parent() return a TableRef

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/exceptions.hpp
- src/realm/exec/realm2json.cpp
- src/realm/group.cpp
Change-Id: I551fd8a4f51b792bf552a426d8dcc85904ff09a6
> Better exception when upgrade needed in RO mode

- src/realm/group.cpp
- test/test_lang_bind_helper.cpp
Add unittests exercising concurrent use of Group::get_table() on the same frozen transaction.
Also fix memory ordering on accesses to Group::m_table_accessors. (needs acquire/release)
> stress testing concurrent use of Group::get_table()

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: I47f53d5a452e38b6dd908b759e718310582c34ce
> Prepare release 6.0.0-beta.1

- CHANGELOG.md
- src/realm/db.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- test/benchmark-crud/main.cpp
- test/test_group.cpp
Change-Id: I0897b3c2ea6da4bd64c8b6b59634ea9ac15d5da3
> Require table name uniqueness

- CHANGELOG.md
- src/realm/table.cpp
- src/realm/table.hpp
This functionality would be useful in realm-java
> Add Table::contains_unique_values

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: I6821a1e8258b8e5952df02e4cb6209e5aa705de3
> Prepare release 6.0.0-beta.3

- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/query_expression.cpp
- src/realm/table_view.cpp
- test/test_group.cpp
Fixes https://jira.mongodb.org/browse/RCORE-229
> Update incoming links when table is rebuilt

- CMakeLists.txt
- src/realm/index_string.hpp
- test/test_table.cpp
There will be more, but I thought I'd put up a small initial set to iron out the PR process.
> Initial build enhancements

- CMakeLists.txt
Change-Id: If5fb7b841b1533b63b1a10cc4938a38ddaa706eb
> Require CMake version 3.15 (3.12 on Windows)

- Dockerfile
- src/realm/array_decimal128.hpp
- src/realm/data_type.hpp
- src/realm/decimal128.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.hpp
- test/test_decimal128.cpp
Change-Id: I73c456318c6f69f37205d6db666597c002722e60
> Simple query support for Decimal128

- src/realm/array_mixed.cpp
- src/realm/decimal128.hpp
- test/test_array_mixed.cpp
Change-Id: I1e865826834f7b8e42887ed99d291ddd040a8728
> Store Decimal128 and ObjectId in ArrayMixed

- Dockerfile
- src/realm/obj.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.hpp
Change-Id: Ibf0099d499b59f3fdf41f09e34f47370c6a7ab88
> Don't initialize query in Query::eval_object

- src/realm/mixed.hpp
- test/test_lang_bind_helper.cpp
Change-Id: I6e121e1bf4bd43b0ebb17da07f5669d7b0a61017
> Make Mixed able to store a full Decimal128

- Dockerfile
- src/realm/table.cpp
- test/expected_json_link_cycles2.json
- test/expected_json_link_cycles4.json
- test/expected_json_link_cycles5.json
Fixes https://github.com/realm/realm-core/issues/3548
> Fix json output of single link

- CHANGELOG.md
- clang.Dockerfile
- src/realm/bplustree.hpp
- src/realm/query_expression.hpp
- src/realm/timestamp.hpp
- test/test_parser.cpp
This reverts commit ab5d1493a8ff2866bedcad4ee9acd0eb99395951.
> Revert "Fix double & float max agg with all negative values"

- CHANGELOG.md
- src/realm/query_engine.hpp
- test/test_query2.cpp
Fixes https://github.com/realm/realm-core/issues/3564
> Fix case insensitive search on string primary key column

- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/table.cpp
- src/realm/table.hpp
Change-Id: Iacf5e9162a11ff0213c9af7ea53bf380aeb7f519
> Bump file format version to 11

- CMakeLists.txt
- Jenkinsfile
- src/realm/util/file.hpp
- test/CMakeLists.txt
- test/Package.appxmanifest
- test/main.cpp
- test/test_all.cpp
- test/test_shared.cpp
- test/util/benchmark_results.cpp
- test/util/mem.cpp
- test/util/timer.cpp
Also fixes the Bid library not building on Windows ARM.
I still have to figure out how to run tests on UWP for any project, unfortunately, but at least we test compilation and linkage.
> Build tests for UWP

- CHANGELOG.md
- src/realm/array_decimal128.cpp
- src/realm/bplustree.hpp
- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
- src/realm/mixed.hpp
- src/realm/table.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/test_table.cpp
Various changes that will be needed to build the object store on the core-6.1 branch. WIP.
> Decimal128 patches for object store

- Jenkinsfile
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- test/test_unresolved_links.cpp
Change-Id: Ic7f897c9a7dd53d42433b29990bb15d717feeea7
> Filter unresolved entries in LnkLst

- src/realm/cluster.cpp
- src/realm/cluster_tree.hpp
- src/realm/obj.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_unresolved_links.cpp
Dedicated cluster tree for dangling links
> Use dedicated cluster tree for dangling links

- src/realm/cluster.cpp
- src/realm/cluster.hpp
- test/test_group.cpp
- test/test_table.cpp
> Fix cluster bug

- CHANGELOG.md
- Package.swift
- dependencies.list
Change-Id: I24264ff7e16253aa26511dfb3a0c31a7fe4224e7
> Prepare release 6.1.0-alpha.5

- test/test_metrics.cpp
> Don't use NoPageReclaimGovernor after destruction in unit tests

- src/realm/util/hex_dump.hpp
- test/test_util_logger.cpp
> Fix util::hex_dump

- test/test_lang_bind_helper.cpp
This, however, cannot be merged until the hanging problem has been eliminated.
@finnschiermer @emanuelez
> Reenable LangBindHelper_ImplicitTransactions_InterProcess

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
This time with a workaround for the UWP linker issue.
> std::filesystem on Windows, take 2

- src/realm/array_mixed.cpp
- src/realm/array_mixed.hpp
- src/realm/cluster.cpp
- src/realm/column_type_traits.hpp
- src/realm/index_string.hpp
- src/realm/mixed.hpp
- src/realm/obj.cpp
- src/realm/replication.cpp
- test/fuzz_group.cpp
- test/test_array_mixed.cpp
Change-Id: I64f1e12e6708328267106dc09e56952b4611014f
> Add Table support for Mixed type

- src/realm/array_mixed.cpp
- src/realm/array_string.cpp
- test/test_array_mixed.cpp
It did not leave the object in a clean state.
> Fix ArrayMixed::clear()

- src/realm/array.hpp
- src/realm/array_backlink.cpp
- src/realm/array_blobs_small.cpp
- src/realm/array_blobs_small.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer.hpp
- src/realm/array_mixed.hpp
- src/realm/array_ref.hpp
- src/realm/array_string.cpp
- src/realm/array_string.hpp
- src/realm/cluster.cpp
- src/realm/group.cpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
- src/realm/list.hpp
- src/realm/query_engine.hpp
- src/realm/spec.cpp
- src/realm/spec.hpp
- src/realm/table.hpp
- src/realm/table_view.hpp
- test/large_tests/test_column_large.cpp
- test/test_array.cpp
- test/test_array_integer.cpp
- test/test_column_float.cpp
Lot of unused core removed. Use Array instead of ArrayInteger in most places.
> Cleanup - primarily ArrayInteger

- src/realm/alloc_slab.cpp
@finnschiermer What do you think of this?
> Problem in SlabAlloc::update_reader_view

- src/realm/table.cpp
- src/realm/table.hpp
- test/test_table.cpp
The cached value was not updated in Table::init
> Fix handling of Table::has_any_embedded_objects

- Jenkinsfile
fix failing windows build, based on https://github.com/realm/realm-core/pull/3723 from v10
> ignore warnings in windows build

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/exceptions.hpp
- src/realm/util/file.hpp
- src/realm/util/to_string.hpp
> Improve error messages when failing to open a DB

- src/realm/sync/CMakeLists.txt
- src/realm/sync/print_changeset_command.cpp
Forward-port from `realm-sync`.
> Fix command-line tool targets and add realm-print-changeset

- CHANGELOG.md
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_group.cpp
- test/test_upgrade_database.cpp
> Check for orphans in Table::set_embedded

- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/index_string.cpp
- src/realm/obj.hpp
- src/realm/table.hpp
- src/realm/table_cluster_tree.cpp
- src/realm/table_cluster_tree.hpp
This is the basis for creating a Dictionary based on a ClusterTree. The abstractions introduced here are perhaps not ideal, but it will allow us to move forward. We can polish it later without breaking any  file formats.
> Make ClusterTree more general

- CHANGELOG.md
- Jenkinsfile
> use vs2017 for v6

- CHANGELOG.md
- src/realm/parser/query_builder.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/table_view.cpp
- test/test_query.cpp
- test/test_table_view.cpp
Fixes https://github.com/realm/realm-core/issues/3869
> Allow appending or prepending sort descriptors

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/node.hpp
- test/test_shared.cpp
Fixes https://github.com/realm/realm-js/issues/3194
> Fix issue when adding a lot of data

- src/realm/keys.hpp
Should not change anything. But makes an assertion about the value.
> Implement ColKey::nullvalue like done for TableKey

- CHANGELOG.md
- src/realm/array_object_id.cpp
- src/realm/index_string.cpp
- src/realm/table.cpp
- test/test_object_id.cpp
- test/test_table.cpp
Fixed some missing edge cases around null ObjectIds.
Fixes https://github.com/realm/realm-core/issues/3919
> ObjectId null updates

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/node.hpp
- test/test_shared.cpp
Fixes problem described here: https://github.com/realm/realm-core/pull/3938#issuecomment-698635761
> Reset missing_parent_update when creating cluster array

- src/realm/collection.hpp
- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/parser/collection_operator_expression.hpp
- src/realm/parser/primitive_list_expression.cpp
- src/realm/query_conditions.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- test/test_array_mixed.cpp
- test/test_query.cpp
Will presumably reduce the code size with around 70k.
Implementation is simpler.
Performance is about the same.
> Make Compare template independent of type

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/query_expression.hpp
- test/test_table.cpp
> merge master into v10

- src/realm/group_writer.cpp
- src/realm/util/features.h
Fixes https://github.com/realm/realm-cocoa/issues/6790.
> Check correct flags to ensure whether or not we are on iOS on an iPhone

- Package.swift
Also cuts the build time with Xcode 12 from 15 seconds to 2.
> Fix Package.swift compilation with Xcode 11

- test/object-store/primitive_list.cpp
Restore lost changes to tests/primitive_list.cpp from commit 8910e94e50
> Restore test for notifications on sorted primitive lists

- test/test_parser.cpp
This will help us track down sporadic query failures on CI such as https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-3977/7/pipeline
> more descriptive query parser test failures

- CHANGELOG.md
- src/realm/obj.hpp
- test/test_links.cpp
Fixes https://github.com/realm/realm-core/issues/4028
> Fix Obj::set_list_values for linklists

- src/realm/array_mixed.cpp
- src/realm/dictionary.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_dictionary.cpp
You can now create a dictionary column where the values are links to a specific table.
> Support dictionaries of a specific link type

- src/realm/object-store/dictionary.hpp
- src/realm/object-store/impl/object_accessor_impl.hpp
- src/realm/object-store/object_accessor.hpp
- test/object-store/dictionary.cpp
- test/object-store/object.cpp
Made as PR on top of https://github.com/realm/realm-core/pull/4055 to show only the difference included in one commit
> Support creating objects with Dictionary property

- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/object-store/sync/impl/sync_file.cpp
cherry pick from OS master of
https://github.com/realm/realm-object-store/pull/1136
https://github.com/realm/realm-object-store/pull/1134
https://github.com/realm/realm-object-store/pull/1131
> fix win paths, multiprocess sync

- test/test_transactions.cpp
> Bump the file format in Transaction_LargeUpgrade

- .cproject.sample
- .gitignore
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- src/realm/query_expression.hpp
- src/realm/table.hpp
The idea is to have some type independent base types, you can cast to.
> Refactor some query classes to support new parser

- src/realm/set.hpp
- test/test_set.cpp
Implemented in terms of standard algorithms.
> Set: Union, Intersection, Difference, Symmetric Difference

- src/realm/object-store/CMakeLists.txt
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/subscribable.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- test/object-store/sync/app.cpp
Moving this PR over to monorepo.
> Make App and SyncUser subscribable

- src/realm/parser/CMakeLists.txt
- src/realm/parser/Makefile
- src/realm/parser/driver.cpp
- src/realm/parser/query_bison.cpp
- src/realm/parser/query_bison.hpp
- test/test_parser.cpp
A couple of initial enhancements, as well as seeing what regenerating the source files changes. (I have bison 3.7.4 via mac's brew)
@jedelbo what do you think about excluding the generated sources from clang-format?
> more string operations and better Xcode support

- src/realm/set.hpp
- test/bench-sync/bench_transform.cpp
Minor changes to fix building with Visual Studio.
> Fix Windows build

- src/realm/set.hpp
- test/bench-sync/bench_transform.cpp
> Fix Windows build (master)

- src/realm/parser/CMakeLists.txt
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- src/realm/table.hpp
- test/test_parser.cpp
Implemented enough to get `Parser_Backlinks` unit test to pass.
> Bison parser: Mappings

- src/realm/object-store/object_schema.cpp
> Add to schema validation that Mixed property must be nullable

- src/realm/collection.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.hpp
- src/realm/object-store/list.cpp
- src/realm/object-store/list.hpp
- src/realm/object-store/object.cpp
- src/realm/object-store/object.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/set.hpp
- test/object-store/frozen_objects.cpp
- test/object-store/primitive_list.cpp
> Add functions that work with Mixed on List and Results

- src/realm/column_type_traits.hpp
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/obj.hpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/object-store/set.cpp
- src/realm/object-store/set.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/object-store/results.cpp
- test/test_query.cpp
- test/test_query2.cpp
These are the last missing bits to reach full feature parity with lists.
> Set: Query support, Results object support, Handover

- src/realm/mixed.cpp
- src/realm/parser/driver.cpp
- test/test_parser.cpp
- test/test_query.cpp
Replacing https://github.com/realm/realm-core/pull/4054
It mostly just worked already.
> bison test mixed queries

- .gitmodules
- CMakeLists.txt
- Package.swift
- THIRD-PARTY-NOTICES
- test/benchmark-common-tasks/collect_stats.py
Removing the submodule and references that turned up in a simple search.
> remove PEGTL

- CHANGELOG.md
- src/realm/object-store/CMakeLists.txt
- src/realm/object-store/sync/app_credentials.cpp
- src/realm/object-store/sync/app_credentials.hpp
- src/realm/object-store/util/tagged_string.hpp
- test/object-store/sync/app.cpp
https://jira.mongodb.org/browse/RCORE-380
cc @mburdette
> Add Google credential for openId

- src/realm/sync/noinst/client_impl_base.cpp
Since Realm synchronization protocol version 2, the server (Stitch) is checking the WebSocket subprotocol specified by the client.
However, the server does not accept protocol version ranges as part of the syntax.
Side note: Because the range syntax is nonstandard, I decided that it would be better to remove the range feature from the client than to add it to the server.
Currently, this change has no material effect for the client, because it only supports one protocol version, namely 2.
It will become important in the future, though, so this PR makes the necessary adjustments.
cc @simonask @mpobrien
> Stop using protocol version ranges in WebSocket subprotocol header

- test/object-store/transaction_log_parsing.cpp
This adds a test case which triggers a crash from core versions v10.1.3 to v6.1.0-alpha.5 (the introduction of invalidated links). It was reported by a user [here](https://jira.mongodb.org/browse/HELP-19915).
The conditions to trigger this error are that a notification checker is added to a results that has a list of objects of which one has been invalidated. Object invalidation can only happen if the object is deleted by a different connected sync client.
The issue is that the DeepChangeChecker is using the [iterator interface](https://github.com/realm/realm-core/blob/develop/src/realm/object-store/impl/collection_notifier.cpp#L154) (LnkLst::begin() and LnkLst::end()) to check all linked objects. But these methods have not been overridden at that level so while LnkLst::size() returns the …
> Test change checking over invalidated links

- src/realm/object-store/set.cpp
- src/realm/object-store/set.hpp
- test/object-store/set.cpp
> Add functions that work with Mixed on Sets

- src/realm/cluster_tree.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/object-store/collection.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/list.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/object-store/set.hpp
- test/object-store/dictionary.cpp
- test/test_dictionary.cpp
> Enhance object_store::Dictionary interface

- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
Supporting sets for the query parser.
> bison query set

- CHANGELOG.md
- src/realm/table.cpp
- test/test_embedded_objects.cpp
Fixes https://jira.mongodb.org/browse/RCORE-486
> Fix invalidation of objects with embedded objects

- CHANGELOG.md
- CMakeLists.txt
> Fix REALM_INCLUDE_CERTS build-time option

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
- test/test_thread.cpp
> Reimplement Windows version of InterprocessCondVar

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/util/interprocess_condvar.cpp
- src/realm/util/interprocess_condvar.hpp
- test/test_thread.cpp
Mostly needed to pick up the condvar fix.
> Merge master into develop (2021-01-08)

- CHANGELOG.md
- src/realm/query_engine.hpp
- test/test_query.cpp
Fixes https://github.com/realm/realm-core/issues/4251
> fix links_to queries on sets of objects

- src/realm/parser/driver.cpp
- src/realm/table.hpp
Requested for the .Net team by @nirinchev
> add a mapping option to mixed string query parsing

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/crash.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
- src/realm/util/terminate.cpp
Add issue templates.
Change the reporting of crashes to ask for a github issue instead of email.
> Issue reporting

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/object-store/object_store.cpp
- src/realm/sync/changeset.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/schema.cpp
- test/test_dictionary.cpp
- test/test_sync.cpp
> Allow Dictionaries to be nullable

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/list.hpp
- src/realm/set.hpp
- test/object-store/set.cpp
- test/test_dictionary.cpp
Be sure to call update_if_needed before calculating values.
Fixes #4252
> Fix aggregate functions on Set and List

- src/realm/query_value.cpp
This fixes an issue on windows where the order of std::unordered_map is different than our POSIX platforms, so tests that assume the `@type` queries will return a specific typename do not return that type name.
> Do not assume std::unordered_map has a stable iterator order

- src/realm/query_expression.hpp
only_numeric() and friends existed to work around not having if constexpr pre-c++17, so we can now ditch them and simplify the code a bit.
> Use if constexpr to eliminate some template hacks

- test/test_parser.cpp
This functionality was supported but not tested anywhere. Requested in https://github.com/realm/realm-core/issues/4319
> Test '@type' queries on dictionaries

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/group.cpp
- src/realm/impl/transact_log.cpp
- src/realm/impl/transact_log.hpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/object-store/dictionary.cpp
- test/test_lang_bind_helper.cpp
- test/test_sync.cpp
> Distinguish between Dictionary insert and set in transaction log

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app_utils.cpp
- src/realm/object-store/sync/generic_network_transport.hpp
- test/object-store/sync/app.cpp
Reverts realm/realm-core#4263
The fix will be made on realm-cocoa side
> Revert "Refactor Response model to provide a separate error field"

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/thread_safe_reference.cpp
- test/object-store/dictionary.cpp
> Add ThreadSafeReference for Dictionary

- CHANGELOG.md
- src/realm/object-store/property.hpp
- test/object-store/object.cpp
> Allow Mixed property to be indexed

- src/realm/object-store/object_schema.cpp
- src/realm/object-store/property.hpp
- src/realm/table.cpp
- test/object-store/schema.cpp
> Require Dictionary of Object to be nullable

- CHANGELOG.md
- src/realm/object-store/impl/list_notifier.cpp
- test/object-store/dictionary.cpp
Problem was that we staticly casted the collaction pointer to LnkLst which caused problems when it in fact was a Dictionary.
Fixes #4346
> Fix error in ListNotifier

- CHANGELOG.md
- src/realm/object-store/keypath_helpers.hpp
- src/realm/object-store/object_schema.cpp
- src/realm/object-store/object_schema.hpp
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- test/object-store/realm.cpp
- test/test_parser.cpp
Requested by and fixes https://github.com/realm/realm-core/issues/4326
> Add class name support to KeyPathMapping

- CHANGELOG.md
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- test/object-store/dictionary.cpp
> Expose Dictionary.keys() collection

- CHANGELOG.md
- CMakeLists.txt
- Jenkinsfile
In order for Android build with link-time optimization to work we need to not hardcode the optimization level.
> Ensure Android LTO builds are viable

- src/realm/array_integer.hpp
- test/test_query.cpp
Preparation for #4378 and just general cleanup.
> Prepare int query refactor

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
> Query Parser: Fix argument substitution for LinkLists

- CHANGELOG.md
- src/realm/object-store/object_schema.cpp
- src/realm/object-store/object_schema.hpp
- src/realm/object-store/results.cpp
- test/object-store/dictionary.cpp
> Make Results based on dictionary keys return correct value in get_type()

- CHANGELOG.md
- src/realm/bplustree.cpp
- test/test_unresolved_links.cpp
> Fix double deallocation when clearing big linklist during sync

- CHANGELOG.md
- src/realm/object-store/results.cpp
- src/realm/table.cpp
- test/object-store/dictionary.cpp
> Make Results::get<Obj> work for collections

- src/realm/object-store/c_api/query.cpp
- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- test/test_parser.cpp
Requested by https://github.com/realm/realm-core/issues/4385
> Better exception messages for unhandled args

- CHANGELOG.md
- src/realm/sync/protocol.hpp
Match the protocol version on the server.
> Bump the sync protocol version to 3

- src/realm/parser/query_parser.hpp
Fixes compilation for .NET. No idea why this wasn't caught by Core's CI.
> Include mixed.hpp in query_parser.hpp

- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- test/object-store/schema.cpp
Added method to retrieve `ObjectSchema` from `Schema` given a `TabkeKey`.
> Added method to get object schema by table key

- CHANGELOG.md
- src/realm/array_backlink.cpp
- src/realm/cluster.cpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/list.cpp
- src/realm/object-store/list.hpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/dictionary.cpp
- test/test_embedded_objects.cpp
- test/test_table.cpp
Headline tells it all.
Fixes #4418
> Support embedded objects in Dictionary

- CMakeLists.txt
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_integer.hpp
- src/realm/bplustree.hpp
- src/realm/collection.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/sync/instructions.hpp
- src/realm/sync/transform.cpp
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
- src/realm/utilities.cpp
- src/realm/utilities.hpp
~~Note: This PR should be split into separate PRs and merge/reviewed individually. This branch is just to track improvements incrementally.~~
What we're measuring:
An LTO build of `librealm-ffi.so`, which contains everything (Core, Query Parser, Sync, Object Store, C API).
Effects:
- Reduce binary size by ~2 MB.
- Impacts performance by ???.
> Reduce code size

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- test/test_table.cpp
This would somewhat remedy https://github.com/realm/realm-cocoa/issues/7092
The test case added has a performance increase of 138%.
(Run time decreases from 71 to 30 ms)
> Adding extra caching to sort algorithm

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/test_dictionary.cpp
> Fix crash in Dictionary::find_any

- CHANGELOG.md
- src/realm/table.cpp
Fixes https://github.com/realm/realm-cocoa/issues/7111
> Add workaround for upgrade with illegal string

- CHANGELOG.md
- src/realm/parser/CMakeLists.txt
> Add missing query parser headers to release packages

- CHANGELOG.md
- src/realm/cluster_tree.cpp
- test/test_table.cpp
Fixes https://github.com/realm/realm-java/issues/7314
> Fix problem on 32bit devices when upgrading

- src/realm/keys.hpp
- src/realm/sort_descriptor.cpp
- test/test_link_query_view.cpp
- test/test_query.cpp
> Sort and Distinct on collection property is illegal

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- test/object-store/c_api/c_api.cpp
- test/test_parser.cpp
Fixes https://github.com/realm/realm-core/issues/4469
In general provides better checking on a bunch of exceptions by checking both the exception type and the message.
> more strict exception checking on parsed queries

- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/spec.hpp
Make sure we can store more bits in column attrs
> Minor changes

- CHANGELOG.md
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/object-store/c_api/c_api.cpp
- test/test_sync.cpp
> Fix missing parent update

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- src/realm/util/serializer.cpp
- src/realm/util/serializer.hpp
- test/object-store/realm.cpp
- test/test_parser.cpp
> Reproduce mapping error

- CHANGELOG.md
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/noinst/integer_codec.hpp
- test/test_instruction_replication.cpp
> Fix replication of large decimals

- src/realm/cluster.cpp
> Make 'dump_objects' work for dictionaries

- CHANGELOG.md
- src/realm/set.hpp
- test/object-store/set.cpp
- test/test_set.cpp
> Don't allow nulls in a Set that is not nullable

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/sync/instruction_applier.cpp
- test/test_instruction_replication.cpp
- test/test_table.cpp
> Support add_int on a mixed column

- CHANGELOG.md
- src/realm/obj.hpp
- src/realm/set.hpp
- src/realm/sync/instruction_applier.cpp
- test/test_instruction_replication.cpp
- test/util/compare_groups.cpp
> Make sync work for sets of objects

- CHANGELOG.md
- src/realm/object-store/collection.hpp
- src/realm/object-store/set.cpp
- src/realm/object-store/set.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- test/object-store/set.cpp
- test/test_set.cpp
- test/test_types_helper.hpp
> Adding overloads of the set methods that operate on collections

- src/realm/query.cpp
- test/test_query2.cpp
> Support 'links_to' query on a Mixed property

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/test_dictionary.cpp
> Allow unresolved links to be inserted in Dictionary

- CHANGELOG.md
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- test/test_set.cpp
> Remove backlinks when clearing set of links

- CHANGELOG.md
- Package.swift
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
- test/test_decimal128.cpp
> Make conversion of Decimal128 to/from string work for whole range

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.hpp
- test/test_query2.cpp
> Fix overload of Query::links_to() for Mixed columns

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/test_dictionary.cpp
> Make Dictionary key validation work on strings without nul termination

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/crash.md
- .github/ISSUE_TEMPLATE/feature-request.md
- CHANGELOG.md
- src/realm/object-store/impl/results_notifier.cpp
- test/CMakeLists.txt
- test/benchmark-larger/CMakeLists.txt
- test/benchmark-larger/main.cpp
- test/object-store/primitive_list.cpp
> Merge master into v11

- CHANGELOG.md
- src/realm/collection.hpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- test/object-store/dictionary.cpp
> Include table in comparison of Dictionaries

- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/group.hpp
Add a file format check when opening immutable realm files.
> add file format check when opening immutable files

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/object-store/dictionary.cpp
> Fix missing parent update in Dictionary::nullify

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.cpp
- test/test_parser.cpp
And also fixing a bug in LinkMap::map_links regarding Set.
Fixes #4633
> Fix handling of Set of links in the query parser

- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/query_expression.cpp
> Refactor handling of collections in LinkMap

- src/realm/query_expression.cpp
- test/test_link_query_view.cpp
- test/test_parser.cpp
> Fix query on baclinks with indexed property

- src/realm/object-store/util/scheduler.cpp
> REALM_PLATFORM_ANDROID -> REALM_ANDROID

- src/realm/object-store/dictionary.hpp
- src/realm/object-store/object_accessor.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- test/object-store/dictionary.cpp
Adding additional tests for object store's Dictionary and Results based on this.
https://github.com/realm/realm-core/issues/4470
> increase test coverage of dictionary

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/impl/cont_transact_hist.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- test/object-store/realm.cpp
- test/test_sync.cpp
> Support creating a realm file with initial app data

- CHANGELOG.md
I forgot to update the changelog in #4712, this just adds a changelog entry for that PR.
> RCORE-724 Update changelog

- src/realm/dictionary.cpp
- src/realm/object-store/results.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_dictionary.cpp
> Fix incorrect cast and problematic assignment

- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/deep_change_checker.cpp
- src/realm/object-store/impl/deep_change_checker.hpp
- test/object-store/object.cpp
- test/object-store/results.cpp
- test/object-store/transaction_log_parsing.cpp
I've added the new parts as a new branch and PR against the main branch so that the changes can be seen easier since the main branch is already accepted.
I hope it's easier that way to eventually merge everything into master since the changes have been rather big.
> Adding backlinks to an observed object property or collection.

- CHANGELOG.md
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- test/object-store/dictionary.cpp
> Store string values in DictionaryChangeSet

- CHANGELOG.md
- src/realm/table.cpp
- test/test_table.cpp
> Fix Table::set_nullability

- src/realm/dictionary.cpp
- test/test_dictionary.cpp
> Add test and fix

- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/dictionary_cluster_tree.hpp
- src/realm/table.hpp
Increase use of noexcept and reduce dependency on try/catch.
> Remove some dependency on exception handling

- evergreen/config.yml
- test/object-store/sync/app.cpp
> Fix ARM64 object-store timeouts

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/generated/query_bison.cpp
- src/realm/parser/generated/query_bison.hpp
- src/realm/parser/query_bison.yy
- test/test_parser.cpp
> Support BETWEEN operator in query parser

- .gitmodules
- CHANGELOG.md
> Update Catch2 URL

- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/dictionary_cluster_tree.hpp
- src/realm/table.cpp
- src/realm/table_cluster_tree.hpp
- test/test_group.cpp
- test/test_table.cpp
> Make some error messages include more information

- src/realm/decimal128.hpp
- src/realm/mixed.cpp
> Remove hashing of Decimal128

- CHANGELOG.md
- src/realm/query.cpp
- test/test_query.cpp
> Fix crash when querying with not on empty group

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
- test/test_db.cpp
These are no longer used and possibly never have been.
> Remove LogA and LogB

- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
Fixes https://jira.mongodb.org/browse/RCORE-803
> Support canceling async transaction

- CMakeLists.txt
- src/realm/parser/generated/query_bison.cpp
- src/realm/parser/generated/query_bison.hpp
Update to version that seems to be the default when installing on a Mac using 'brew`.
> Update to Bison v3.8.2

- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/table.cpp
- test/object-store/realm.cpp
Addresses question raised by @ironage
> An error handler for async transactions can be installed in Realm

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_query.cpp
- test/test_query2.cpp
> Remove the 'power' unary operator

- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
> Use util::UniqueFunction in async commit related functions

- .gitignore
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/generated/query_bison.cpp
- src/realm/parser/generated/query_bison.hpp
- src/realm/parser/query_bison.yy
- src/realm/timestamp.hpp
- test/test_parser.cpp
The syntax definition is easier to read. The canonicalize function opens up for optimizations done in the syntax tree.
> Streamline query language definition

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.hpp
> Even more use of util::UniqueFunction

- CHANGELOG.md
- src/realm/util/websocket.cpp
- test/object-store/sync/app.cpp
Reverts realm/realm-core#5047
@ironage this should not have been merged.
> Revert "Make sure sync client receives error message when TCP socket is closed"

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes https://github.com/realm/realm-core/issues/5067
> C-API append query

- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes https://github.com/realm/realm-core/issues/5082
No changelog entry because the bug had not been released.
> Fix c-api append query

- src/realm/db.cpp
- src/realm/db.hpp
Hopefully this can catch potential errors earlier
> Add sanity check on ReadLockInfo

- test/test_sync_subscriptions.cpp
This fixes a merge issue from merging #5075.
> Fix merge issue

- CHANGELOG.md
- src/realm/impl/simulated_failure.cpp
Compiling in debug mode for iOS architecture failed.  This PR addresses said issue.
> Fix issue compiling in debug mode for iOS.

- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/util/ez_websocket.cpp
- src/realm/util/ez_websocket.hpp
Putting up completed work prior to going on vacation. Each commit is topical and has a meaningful commit message, so I plan to rebase rather than squash.
> More sync client cleanup

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/impl/copy_replication.cpp
- src/realm/impl/copy_replication.hpp
- src/realm/obj.cpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/replication.hpp
- test/object-store/sync/app.cpp
- test/test_shared.cpp
> Support copying state from one realm to another

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
> Add testing for change of query for FLX sync

- src/realm/list.cpp
- src/realm/obj.cpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/query.cpp
- src/realm/table_view.hpp
> Small cleanup

- src/realm/table_view.cpp
- src/realm/table_view.hpp
Replace m_linked_obj_key and m_linked_table with accessor to the linked object itself.
> TableView simplification

- src/realm/cluster.cpp
- src/realm/exceptions.hpp
- src/realm/obj.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/query.cpp
- src/realm/sort_descriptor.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_query2.cpp
The two functions did the same
> Replace Table::report_invalid_key with Table::check_column

- test/test_lang_bind_helper.cpp
Adds a retry to waitpid in case of interruption by a signal. We have seen this happen occasionally on other system calls. If this is the fix, there is no way I can prove it but it also shouldn't hurt.
Also adds some assertions to validate that we are not hitting the system limits (unlikely).
If this works, then it replaces https://github.com/realm/realm-core/pull/5096.
> Maybe fix a test hang

- Jenkinsfile
- test/test_all.cpp
It has long been a wish to force the use of encryption in more test cases.
Fixes #1488
> Force encryption in a test run

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/set.hpp
- test/object-store/c_api/c_api.cpp
> Add missing filter and ordering functions for realm_results_t

- CHANGELOG.md
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
> Implement realm_results_snapshot in C API

- CHANGELOG.md
- src/realm.h
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/object-store/c_api/CMakeLists.txt
- src/realm/object-store/c_api/notifications.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/set.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/c_api/util.hpp
- src/realm/object-store/set.cpp
- src/realm/set.hpp
- test/object-store/c_api/c_api.cpp
> Add support for Set in C-API

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
This PR contains a subset of the commits originally contained in #5183. Created in order to break down the review work.
> Fix some async-write problems - part 1

- CHANGELOG.md
- src/realm.h
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/impl/copy_replication.cpp
- src/realm/object-store/c_api/CMakeLists.txt
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/c_api/notifications.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/thread_safe_reference.hpp
- test/object-store/c_api/c_api.cpp
- test/test_dictionary.cpp
> Add Dictionary support to C-API

- CHANGELOG.md
- src/realm/sync/tools/apply_to_state_command.cpp
Update apply_to_state_command tool to support QBS download messages.
> Support QBS download messages

- Dockerfile
- Jenkinsfile
- clang.Dockerfile
- generic.Dockerfile
Bump everything to GCC 11 and Clang 12
> Update Dockerfiles for latest compilers

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/util/bind_ptr.hpp
- test/object-store/c_api/c_api.cpp
> Add realm_query_get_description to C-API

- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/c_api/config.cpp
- test/object-store/c_api/c_api.cpp
Add support in c_api interface for setting: 
1. in memory realm 
2. fifo path
#5250 #5249
> export new settings in c_api interface

- src/realm/column_type.hpp
- src/realm/exec/CMakeLists.txt
- src/realm/exec/realm_decrypt.cpp
- src/realm/exec/realm_trawler.cpp
- src/realm/util/aes_cryptor.hpp
- src/realm/util/encrypted_file_mapping.cpp
Can be useful, when analyzing an encrypted file.
> Add realm-decrypt tool

- test/test_lang_bind_helper.cpp
More diagnostic info related to https://github.com/realm/realm-core/pull/5096
This is in light of more observed hangs of this test, and at least one [observed failure](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-5296/2/pipeline) indicating non normal exit `REALM_ASSERT(WIFEXITED(*status));`
```
1: /mnt/jenkins/workspace/realm_realm-core_PR-5296@3/test/test_lang_bind_helper.cpp:3101: [realm-core-11.10.0] Assertion failed: (((*status) & 0x7f) == 0)
```
> More debug info on test failure

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/notifications.cpp
- test/object-store/c_api/c_api.cpp
> C-API: Add support for keypaths in change notifications

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/c_api/types.hpp
- test/object-store/c_api/c_api.cpp
> Align notification/callback registration mechanism in the C-API

- evergreen/config.yml
- test/object-store/sync/flx_sync.cpp
TBH, I'm not sure what happened with these tests. I suspect they've always been inherently racy because they were testing the wrong thing? I've updated them and tried to comment exactly what outcome each part of the test is expecting so they're clearer. They also, more importantly pass multiple rounds of evg patch builds.
> Fix FLX tests for offline and unsynchronized writes

- CHANGELOG.md
- src/realm/util/file.cpp
- src/realm/util/file_mapper.hpp
> fix for various encryption bugs

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/object.cpp
Putting this up as it's fairly trivial, though I'd appreciate if someone takes over and adds tests for it.
Fixes #5414.
> Expose object.to_string via the C API

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/config.cpp
- src/realm/object-store/c_api/types.hpp
- test/object-store/c_api/c_api.cpp
Modified functions:
- realm_config_set_migration_function
- realm_config_set_data_initialization_function
- realm_config_set_should_compact_on_launch_function
Fixes #5222
> [C API] Add option to supply free function for some user data

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
Expose client reset functionalities for C API
Fixes:  https://github.com/realm/realm-core/issues/5425
> Expose client reset for C API

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- test/object-store/c_api/c_api.cpp
> Include category name in string version of std::error_code

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
Incorporate in the C API the possibility to retrieve the App given the User.
Fixes: https://github.com/realm/realm-core/issues/5478
> Expose API to get App for user in the C API

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
Expose delete user for C API
Fixes: https://github.com/realm/realm-core/issues/5490
> Expose delete user C API

- src/realm.h
- src/realm/alloc_slab.cpp
- src/realm/object-store/c_api/error.cpp
- src/realm/object-store/c_api/error.hpp
- test/object-store/c_api/c_api.cpp
Just a small improvement that may come in handy.
> C API: Make path available through realm_error_t

- src/realm/object-store/c_api/sync.cpp
Hot fix for restoring flx sync tests for C API
> fix flx sync tests

- src/realm/object-store/c_api/http.cpp
- src/realm/object-store/c_api/sync.cpp
> use reserve

- CHANGELOG.md
- src/realm/table_tpl.hpp
- test/object-store/results.cpp
Fixes #5137 by throwing an exception
* [-] C-API, if public C++ API changed.
> Throw an exception when trying to aggregate on a collection property

- CHANGELOG.md
- src/realm/impl/transact_log.hpp
> Fix exception with ArrayMove instruction on list of links with dangling links

- CHANGELOG.md
- test/object-store/sync/flx_sync.cpp
> Merged to the wrong version

- src/realm/alloc_slab.cpp
Small step towards being able to reduce file size.
> Shrink file if logical size is less than file size

- Jenkinsfile
Fix typo for nightly builds section in the Jenkins file.
> fix typo Jenkins file for nightly builds

- test/object-store/dictionary.cpp
- test/object-store/realm.cpp
Enable some remaining object store tests on Windows.
Partially 
Fixes: https://github.com/realm/realm-core/issues/5318.
> Object store tests windows

- test/object-store/sectioned_results.cpp
Point fix for android Armeabi builds.
> Fix warning android builds

- nightly.Jenkinsfile
- src/realm/object-store/object.cpp
Add notification system for realm core nightly builds.
> Notification mechanism for realm-core nightly builds

- Jenkinsfile
It seems to me that the loop as it was structured was an infinite loop.
> avoid to constantly upload files on s3

- CHANGELOG.md
- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
- test/test_decimal128.cpp
Fixes https://jira.mongodb.org/browse/RCOCOA-1751
> Fix syncing of Decimal128 values

- Jenkinsfile
Fix incorrect use of variable in 'Publish to S3' release stage
> Fixed incorrect use of variable in Jenkinsfile

- Jenkinsfile
Resource files should be copied correctly
> Fix buildAndroidTestsArmeabi again

- CHANGELOG.md
- src/realm/object-store/object_schema.cpp
- test/object-store/schema.cpp
Update error message when validating outgoing links from asymmetric objects to non-embedded objects.
> Update schema validation error message for outgoing links

- evergreen/config_overrides.json
This is "Ready to merge" but wont do anything until my PR here is merged: https://github.com/10gen/baas/pull/7161
> BAAS-15187: Update the BAAS server overrides to bypass the broker cache

- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
Constant lists does not need to be evaluated over and over again.
No functional changes
> Optimize for constant lists in Query

- src/realm/alloc_slab.cpp
- src/realm/parser/CMakeLists.txt
This reverts commit d808d899f935db00de81a72c940a7b7c9baaef63.
Fixes #5631
> Revert Revert "Shrink file if logical size is less than file size"

- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/table_view.hpp
Just a simple fix to mark things that should be const const.
> const-correctness fixes for Query

- CHANGELOG.md
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/transaction.cpp
- test/test_set.cpp
> Set<Mixed> should not consider string and binary data equivilent

- test/object-store/sync/app.cpp
Fixes: https://github.com/realm/realm-core/issues/5727
> Restore  ```app destroyed during token refresh```

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/test_table.cpp
> Add Obj::get_parent_object()

- test/object-store/sync/flx_sync.cpp
Disable test while waiting on the correct behavior to be implemented on the server side.
> Disable "flx: asymmetric sync::replace object"

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
Fixes: https://github.com/realm/realm-core/issues/5836
> Convert Collections into Results

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/realm.cpp
Fixes:  https://github.com/realm/realm-core/issues/5765
> Disable auto refresh for old realm during migration

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/5766
> expose `Group::remove_table` in the C API

- src/realm/object-store/object_schema.hpp
- src/realm/object-store/schema.hpp
- src/realm/object-store/shared_realm.hpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/object-store/sync/sync_user.hpp
- src/realm/query_value.hpp
- src/realm/sync/config.hpp
This is a collection of small improvements previously discussed on slack. I'm grouping them into a single PR to reduce overhead.
* Stop forcing enums to be 64 bits unnecessarily
* clean up documentation of internal fields in config structs
* SyncConfig should be default constructible
> Minor improvements

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/5858
> native types for `realm_results_get` and adding `realm_results_find`

- Package.swift
- src/realm/CMakeLists.txt
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/tokenizer.cpp
- src/realm/tokenizer.hpp
- test/test_query2.cpp
> Moving Tokenizer to separate file

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/5895
> add support for directly fetching backlinks in the c api

- CHANGELOG.md
- src/realm/tokenizer.cpp
- src/realm/tokenizer.hpp
- test/test_query2.cpp
> Remove diacritics from fulltext index

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
Adds a new kind of read-lock in preparation for work on multi-process encryption.
> Add a new type of readlock, called 'fully locking'

- CHANGELOG.md
Fix changelog adding PR info for breaking change.
> fix changelog entry

- src/realm/dictionary.cpp
- src/realm/object_converter.cpp
> Optimize Dictionary::sort_keys

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes:  https://github.com/realm/realm-core/issues/5928
> add support for `realm_query_parse_for_set` to the c api

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
> Fix IN query with TypedLink as left operator

- CHANGELOG.md
- src/realm/bplustree.cpp
Fix `BPlusTreeInner::verify()`
> Fix BPlusTreeInner::verify() 

- CHANGELOG.md
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.hpp
- test/test_query.cpp
> Revert removal of Query::validate

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/c_api/types.hpp
Fixes: https://github.com/realm/realm-core/issues/5966
> Add a way to register a thread observer listener in the C API

- test/object-store/benchmarks/client_reset.cpp
Fix common benchmark tests that was broken with logger changes
> Fix common benchmarks test

- CMakeLists.txt
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- src/realm/CMakeLists.txt
- src/realm/object-store/c_api/CMakeLists.txt
- src/realm/object-store/util/scheduler.cpp
- src/realm/util/basic_system_errors.cpp
- src/realm/util/thread.cpp
> basic changes for emscripten/wasm build

- CHANGELOG.md
- src/realm/object-store/c_api/realm.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/6075
> Return immediately if there is no transaction snapshot to advance to.

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_user.hpp
> SyncUsers should be compared by identity()

- how-to-build.md
After not being able to build it myself,  I thought having the documentation for it would probably be good.
> And guide to how to build RealmTrawler

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
Fixes:  https://github.com/realm/realm-core/issues/6134
> Fix: Core should not change schema property order when opening a transaction 

- src/realm/cluster.hpp
Improves use of FieldValues for fast creation of objects.
> Improve usability of FieldValues

- CHANGELOG.md
- src/realm/decimal128.cpp
- test/object-store/c_api/c_api.cpp
> Fix equality test on Decimal128 NaN values

- src/realm/exec/realm2json.cpp
- src/realm/object-store/c_api/socket_provider.cpp
Fix build errors in the web socket provider C API.
> Fix build errors in the C API

- CHANGELOG.md
- src/realm/list.hpp
- test/test_mixed_null_assertions.cpp
> Consider type explicitly when comparing elements in List<Mixed>

- CHANGELOG.md
- src/realm/object-store/c_api/config.cpp
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/c_api/list.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/scheduler.cpp
- src/realm/object-store/c_api/set.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/sectioned_results.cpp
- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- src/realm/query_engine.hpp
- test/object-store/audit.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/client_reset.cpp
> Convert some std exceptions to realm::Exception types

- CHANGELOG.md
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- test/test_util_file.cpp
Apparently this method is no longer used and was marked for deletion.
> Remove File::is_removed

- evergreen/config.yml
> fix distro size

- src/realm/CMakeLists.txt
- src/realm/data_type.hpp
- src/realm/geospatial.cpp
- src/realm/geospatial.hpp
- src/realm/obj.cpp
- src/realm/object-store/impl/object_accessor_impl.hpp
- src/realm/query_expression.hpp
- src/realm/util/serializer.cpp
- src/realm/util/serializer.hpp
- test/object-store/CMakeLists.txt
- test/object-store/geospatial.cpp
- test/test_query2.cpp
A basic object-store API and hooking up the core queries.
> Geospatial prototype

- CHANGELOG.md
- src/realm.h
- src/realm/dictionary.cpp
- src/realm/exec/realm_trawler.cpp
- src/realm/group.cpp
- src/realm/impl/transact_log.cpp
- src/realm/impl/transact_log.hpp
- src/realm/object-store/audit.mm
- src/realm/object-store/c_api/notifications.cpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/impl/collection_change_builder.cpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/replication.cpp
- src/realm/replication.hpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/collection_fixtures.hpp
- test/object-store/dictionary.cpp
- test/object-store/sync/app.cpp
- test/test_lang_bind_helper.cpp
Fixes: https://github.com/realm/realm-core/issues/6205
> Align dictionaries to Lists and Sets when they are cleared. 

- src/realm/array_decimal128.cpp
- test/object-store/c_api/c_api.cpp
> Fix storage of Decimal128 NaNs

- evergreen/config.yml
Bumping baas version to include fix for BAAS-19756
> Bump baas version in evergreen tests

- CHANGELOG.md
- src/realm/util/serializer.cpp
- test/test_query.cpp
> Fix query.get_description() to work with unicode symbols

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/config.cpp
- src/realm/object-store/c_api/conversion.hpp
- src/realm/object-store/schema.hpp
- test/object-store/c_api/c_api.cpp
Expose schema subset mode into the C-API
Fixes: https://github.com/realm/realm-core/issues/6370
> Expose subset schema mode in the c api

- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/protocol.cpp
- test/object-store/sync/flx_migration.cpp
Some additional change recommendations were suggested on #6355 after the changes had been merged. This PR addresses the recommendation to update a couple of strings from "flexible based sync" to "flexible sync".
> Flexible sync string updates

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/query.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/6402
> expose `Results::is_valid` in the C API

- src/realm/mixed.hpp
Just some convenience functions.
> Add Mixed::get_if<T>()

- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- test/test_list.cpp
> Implementation `CollectionList::remove()` (#6381)

- CHANGELOG.md
- src/realm/index_string.cpp
- test/test_query2.cpp
Fixes https://github.com/realm/realm-core/issues/6465
> fix fulltext results intersection

- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/set.cpp
- src/realm/spec.cpp
- src/realm/table.hpp
- test/test_dictionary.cpp
- test/test_list.cpp
> Handle links in nested collections

- src/realm/util/terminate.cpp
- Add missing new line separator for 'report' message on terminate
- Flush termination message at the end
- Refactor termination impl by code dedup
> Adjust termination message format and dump

- CHANGELOG.md
- test/util/spawned_process.cpp
Fixes: https://github.com/realm/realm-core/issues/6510
> Fix multiprocess encryption tests if run outside build folder

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_parser.cpp
Fixes https://github.com/realm/realm-kotlin/issues/1183
> Fix bug in 'list IN list' query

- .clang-format
- .gitignore
- Jenkinsfile
- bindgen/.prettierrc.yaml
- bindgen/CMakeLists.txt
- bindgen/src/bound-model.ts
- package.json
See the individual commits for a list of what has changed.
> Make bindgen in core work nicely outside of realm-js

- src/realm/index_string.cpp
- src/realm/tokenizer.cpp
- test/test_index_string.cpp
- test/test_query2.cpp
- Move tokenizer test to actual test suite
- Add checks for fulltext search results ids and simplify testing code. Add a few supposedly failing tests cases for corner cases.
> Improve testing of fts feature

- src/realm/array_mixed.cpp
- src/realm/array_mixed.hpp
- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/index_string.cpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/mixed.cpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/impl/list_notifier.hpp
- src/realm/set.hpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_applier.hpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/test_list.cpp
> Allow Lst<Mixed> to contain a collections

- test/test_array.cpp
- test/test_table.cpp
Fixes https://github.com/realm/realm-core/issues/6600
> mark some tests nonconcurrent to reduce memory pressure on CI

- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/mixed.cpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/thread_safe_reference.cpp
- src/realm/sync/instruction_replication.cpp
- test/object-store/nested_collections.cpp
- test/test_json.cpp
- test/test_list.cpp
- test/test_table.cpp
Main change is that insert... will not return the created collection. This has of course big influence on the test cases written for the old API.
> Streamlining interface

- bindgen/spec.yml
Added parameter to property for full-text search support
> Update spec.yml for full-text search

- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/test_list.cpp
- test/test_table.cpp
Preparation for replication of nested collections.
> Get path from collection objects

- .project
Indexer has a hard time dealing with Catch2
> Filter out external sources from Eclipse

- src/realm/collection_parent.cpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/transaction.cpp
- test/test_list.cpp
- test/test_shared.cpp
Supporting collections in mixed in the copy replication
> Copy replication nested collections

- bindgen/spec.yml
> [bindgen] Expose sync proxy configuration

- test/test_shared.cpp
Attempt to get more info on a difficult to reproduce test failure https://github.com/realm/realm-core/issues/6508
> print logs upon Many_ConcurrentReaders test failure

- src/realm/bplustree.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/set.hpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/6797
> Fix collection mismatch for `Set` in `Mixed`.

- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
- test/test_query2.cpp
> Allow TypedLinks to be part of path to property in queries

- src/realm/object-store/schema.cpp
Say we are checking for cycles starting from object A and traverse our way down through  A -> B -> C -> D -> E and A -> F -> C -> D -> E. Prior to this change, we'd traverse every single property, but if we've already checked C -> D -> E via object B, we can avoid checking it via object F. Cumulatively, this can save a bunch of redundant checks
We also stop keeping track of all the object types we've seen. This is because if there is a cycle A -> E -> B -> C -> D -> E, we can identify this when E is the object being considered as the start point (seeing as the caller goes through all embedded objects defined in the schema anyway).
If it is detected when A is the object being considered, we're not really adding any additional useful information. Instead, the do_check loop becomes much …
> Skip over objects already seen to speed up embedded object loop

- CHANGELOG.md
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/obj.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/util/serializer.cpp
- test/test_query.cpp
> Fix query involving size of collection of links over links

- src/realm/sync/changeset.cpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instructions.hpp
- src/realm/sync/transform.cpp
- test/test_sync.cpp
> Throw if syncing a collection nested in Mixed

- src/realm/obj.cpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/transact_log_handler.cpp
- test/object-store/list.cpp
> Add missing support for getting Sets

- src/realm.h
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/c_api/list.cpp
- test/object-store/c_api/c_api.cpp
Small refactory of the C-API for collections in mixed.
> new c api for collections in mixed

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/notifications.cpp
- test/object-store/c_api/c_api.cpp
> Make information on the deletion of a collection available in C API

- src/realm.h
- src/realm/object-store/c_api/list.cpp
- src/realm/object-store/c_api/object.cpp
- test/object-store/c_api/c_api.cpp
Explicit set_collection function for setting a collection inside a mixed in the C-API.
> Update `set_collection` for realm_list_t

- src/realm/collection_parent.cpp
- src/realm/transaction.cpp
- test/object-store/c_api/c_api.cpp
> Fix freezing a nested collection

- src/realm.h
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/results.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/dictionary.cpp
Expose collections in results of mixed in the C-API + plus minor fixes.
> Allow collections in mixed to be fetched from results

- src/realm/array.cpp
- src/realm/array.hpp
- test/test_array.cpp
Just remove some dead code. No changelog update for this.
> removed a few unused methods from Array

- bindgen/spec.yml
- bindgen/src/realm_helpers.h
> [bindgen] Merge v13.20.0

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
- src/realm/util/logger.hpp
> More detailed logging

- src/realm/object-store/c_api/error.cpp
- src/realm/object-store/c_api/types.hpp
nullify m_usercode_error on ErrorStorage creation
> fix ErrorStorage creation

- Android.bp
- src/external/json/LICENSE.MIT
- src/realm/sync/network/network_ssl.cpp
- tools/generate-version-numbers-for-soong.sh
This enables building as an Android Open Source Project (and derivates) component.
> Add Android.bp blueprints

- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/replication.cpp
- src/realm/util/logger.hpp
- test/test_table.cpp
> Limiting the output when logging large string and binary values

- bindgen/spec.yml
Needed by https://github.com/realm/realm-js/pull/6162
> Expose Table::get_primary_key_column

- Android.bp
- CHANGELOG.md
> Enable bundled OpenSSL certs for AOSP builds

- src/realm/object-store/sync/async_open_task.cpp
Fix comment to better reflect async open logic
> Fix comment to better reflect async open logic

- src/realm/query.cpp
- src/realm/sort_descriptor.cpp
- src/realm/table_view.cpp
- test/benchmark-common-tasks/main.cpp
- test/object-store/results.cpp
- test/test_table_view.cpp
Add test with initial query and query change
Check how this method compares with known query operations.
~* [ ] 📝 Changelog update~
~* [ ] C-API, if public C++ API changed.~
> Add more test for filtering TableView and Results by predicate, also add benchmark

- bindgen/spec.yml
- bindgen/src/realm_helpers.h
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/object.cpp
> Add Realm::is_empty

- CHANGELOG.md
- src/realm/array.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/query.cpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/benchmark-common-tasks/main.cpp
- test/object-store/results.cpp
- test/test_parser.cpp
- test/test_table_view.cpp
This is related to #6158 
The function TableView::get_num_results_excluded_by_limit() has been removed. It was supposedly only used in tests. The optimization that takes a following limit descriptor in account already when running the query makes it impossible to return that value.
> Filter TableView using custom function

- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- test/test_list.cpp
> Small fixes

- Package.swift
- tools/build-cocoa.sh
Enable `REALM_ENABLE_GEOSPATIAL`, geoWithin on points for SPM Installation
> Enable `REALM_ENABLE_GEOSPATIAL`, geoWithin on points for SPM Installation

- src/realm/obj.cpp
> Fix issue using REALM_ENABLE_MEMDEBUG=On

- CHANGELOG.md
- src/realm/sync/network/network_ssl.cpp
Implement BIO_CTRL_GET_KTLS_SEND and BIO_CTRL_GET_KTLS_RECV as OpenSSL versions < 3.0.4 depend on it.
> Implement BIO_CTRL_GET_KTLS_SEND and BIO_CTRL_GET_KTLS_RECV

- test/object-store/c_api/c_api.cpp
> Refactor the C API tests

- src/realm/collection.hpp
- src/realm/collection_parent.cpp
- src/realm/set.cpp
- src/realm/set.hpp
The is to prepare for merge with master. It is more or less a cherry-pick of commit bf5ffd3b0e74.
> Rearrange some code in Set<T>

- src/realm.h
- src/realm/collection.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/c_api/list.cpp
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/object_converter.cpp
- src/realm/set.hpp
- src/realm/to_json.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/dictionary.cpp
- test/object-store/nested_collections.cpp
- test/object-store/sync/client_reset.cpp
- test/test_list.cpp
- test/test_shared.cpp
- test/test_table.cpp
> Remove support for nested sets

- CHANGELOG.md
- bindgen/spec.yml
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/keys.hpp
- src/realm/object-store/c_api/notifications.cpp
- src/realm/object-store/impl/deep_change_checker.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/object.cpp
> Support wildcard notation for key path arrays

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/object-store/property.hpp
- src/realm/query_expression.hpp
- src/realm/search_index.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/primitive_list.cpp
- test/test_index_string.cpp
- test/test_parser.cpp
> Index on list of strings

- test/test_sync.cpp
Add missing commit call for the test, which may have blocked commits from sync thread
> Fix occasional sync tests hang

- CHANGELOG.md
- evergreen/config.yml
- evergreen/install_baas.sh
- evergreen/setup_baas_host_local.sh
- evergreen/wait_for_remote_baas.sh
Upgrade the mongod used in evergreen tests to 7.0.3. We've been seeing some flaky tests in the core testing environment that don't appear to happen in the baas testing environment and we narrowed it down to a problem aborting a transaction. This upgrades the mongod we use to rule out any bug fixes in mongod as a possible cause.
> Update mongod used by baas in testing to 7.0.3

- .github/workflows/bindgen-unit-tests.yml
- bindgen/.mocharc.json
- bindgen/src/bound-model.ts
- package-lock.json
- package.json
This creates a GitHub Actions workflow to run the `bindgen` unit tests on changes to the package.
> Create GHA workflow to run unit tests

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/test_links.cpp
- test/test_unresolved_links.cpp
> Unresolved links in Mixed should appear as nulls

- CHANGELOG.md
- src/realm/sync/network/http.cpp
- src/realm/sync/network/http.hpp
- test/test_util_http.cpp
Add chunked transfer encoding as per HTTP1.1 spec.
> Add support for chunked transfer encoding.

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/mixed.cpp
- src/realm/obj.cpp
- test/test_index_string.cpp
> Add support for collections in indexed mixed fields

- CHANGELOG.md
Improve changelog entry for bug fix.
> Improve changelog entry

- test/object-store/sync/flx_migration.cpp
This fixes a race in `"An interrupted migration or rollback can recover on the next session"`. Right now we wait for the "fresh" realm used in the migration client reset to appear and then pause/resume the session, but we don't prevent the client reset from finishing while we pause/resume the session so it's possible that the client reset will complete before we can pause/resume and we won't actually interrupt the migration. This PR fixes that.
> Fix race in migration test

- CHANGELOG.md
- Package.swift
- dependencies.list
> core v13.26.0

- CHANGELOG.md
Restore changelog next release section.
> restore changelog new section

- CHANGELOG.md
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/object-store/collection_notifications.hpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/path.hpp
- test/object-store/dictionary.cpp
- test/object-store/list.cpp
> Send notifitations about mutations on nested collections

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- src/realm/query_value.cpp
- src/realm/query_value.hpp
- test/test_parser.cpp
This will make sense both for strings, binaries and nested collections.
Fixes #7280
> Support querying for @size on Mixed

- bindgen/spec.yml
- bindgen/src/bound-model.ts
- bindgen/src/cpp.ts
- bindgen/src/realm_helpers.h
- package-lock.json
- package.json
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- src/realm/parser/driver.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/flx_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/test_query.cpp
- test/util/unit_test.hpp
- tools/build-apple-device.sh
Update next-major to latest core master
> Update next major

- dependencies.list
Fix merge error in `dependencies.list`.
> Fix merge error in dependency list

- CHANGELOG.md
- src/realm/index_string.cpp
- test/test_query2.cpp
> Fix crash in fulltext index

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/table.hpp
- test/test_parser.cpp
> Fix using ANY, NONE, ALL in query on Mixed property

- bindgen/spec.yml
> Remove LinkList

- CHANGELOG.md
- src/realm/object-store/impl/results_notifier.cpp
- test/object-store/list.cpp
> Fix Results nofitifation for changes to nested collections

- src/realm/collection.hpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- test/test_list.cpp
- test/test_sync.cpp
> Fix sync replication

- CHANGELOG.md
- Package.swift
- dependencies.list
> Prepare release

- CHANGELOG.md
- Package.swift
- dependencies.list
> Merge Release/14.0.0

- CHANGELOG.md
- Package.swift
- dependencies.list
> Prepeare release

- CHANGELOG.md
- Package.swift
- dependencies.list
> Merge Release/14.0.1

- CHANGELOG.md
- src/realm/group.cpp
> Prevent opening files with file format 23 in read-only mode

- CHANGELOG.md
- Package.swift
- dependencies.list
- tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
> Release 14.1.0

- test/benchmark-common-tasks/main.cpp
Add some new benchmarks, related to https://github.com/realm/realm-core/pull/7016.
Getting these in early serves to break out some of the code changes for reviewers. It also means that we will start collecting a baseline for performance on mainline commits now so that we can verify the performance impact of the later changes.
> RCORE-1784 Add new index related benchmarks

- src/realm/array_encode.cpp
- src/realm/group_writer.cpp
Test if CI is OK with this minimal change (OK locally for All Arrays encoded)
> Minimal changes to make CI pass if compression is always enabled. (Windows builds are failing because PR is missing master commits)

- test/benchmark-common-tasks/main.cpp
> Support regex for benchmarks selection

- test/benchmark-common-tasks/main.cpp
> Add * wildcard matching for benchmark filters and fix a crash

- test/test_list.cpp
> Remove flacky test

- src/realm/array_encode.cpp
- test/test_array_integer.cpp
> enable dynamic choice of compression method

- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
> moved typed_write/typed_print for bptree into class

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Release core v14.2.0

- src/realm/array_direct.hpp
Fix getter for lower and upper bound when bit widths are normal (....8,16,32,64)
> Fix getter lower upper bound

- CHANGELOG.md
- Package.swift
- dependencies.yml
> core v14.3.0

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Release core v14.3.0

- CHANGELOG.md
- Package.swift
- dependencies.yml
> prepare v14.4.0

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- test/object-store/c_api/c_api.cpp
Fixes (https://github.com/realm/realm-core/issues/7497)
> RCORE-2035 threadsafe realm for init subscription callback

- CHANGELOG.md
> Revert back catch2 submodule and up to latest

- CHANGELOG.md
- Package.swift
- dependencies.yml
> prepare v14.4.1

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Merge Release/14.4.1

- CHANGELOG.md
- src/realm/exec/realm2json.cpp
> Handle exceptions correctly in Realm2JSON tool

- CHANGELOG.md
- src/realm/object-store/index_set.hpp
> Work around MSVC arm64 issue

- src/realm/to_json.cpp
- test/expected_xjson_plus_link.json
- test/expected_xjson_plus_linkdict1.json
- test/expected_xjson_plus_linklist1.json
- test/expected_xjson_plus_linkset1.json
> Reintroduce table name for links in xjson_plus format

- CHANGELOG.md
- Package.swift
- dependencies.yml
> prepare v14.5.0

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Release v14.5.0

- src/external/hnswlib/hnswlib.h
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/object-store/results.cpp
- test/test_table_view.cpp
> Vector Search Improvements

- CHANGELOG.md
Manual step until something like https://github.com/realm/realm-core/pull/7566 is available.
> update changelog after v14.5.0 release

- CHANGELOG.md
- src/realm/array_mixed.cpp
- test/object-store/c_api/c_api.cpp
> Destroy keys array when clearing a Lst<Mixed>

- CHANGELOG.md
- Package.swift
- dependencies.yml
- src/realm/PrivacyInfo.xcprivacy
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- test/test_sync.cpp
> Prepare 14.5.1

- test/object-store/sync/flx_sync.cpp
- test/object-store/util/sync/baas_admin_api.cpp
Add tests for collections and nested collections in Mixed properties.
> RCORE-1493 Test roundtrip of collections in Mixed

- CHANGELOG.md
- src/realm/impl/copy_replication.cpp
- src/realm/obj.cpp
- src/realm/transaction.cpp
- test/test_shared.cpp
> RCORE-2091 Fix Transaction::copy_to() for nested collection

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- test/test_sync.cpp
> Do not require group in ClientHistory::update_from_ref_and_version

- CHANGELOG.md
- Package.swift
- bindgen/spec.yml
- bindgen/src/realm_helpers.h
- dependencies.yml
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/realm.cpp
- test/object-store/util/sync/baas_admin_api.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
Prepare release 14.6.0 (second attempt to fix up the commit revisions for the mainline branch).
> Prepare release 14.6.0

- CHANGELOG.md
- Package.swift
- bindgen/spec.yml
- bindgen/src/realm_helpers.h
- dependencies.yml
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/realm.cpp
- test/object-store/util/sync/baas_admin_api.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
Needed to recreate the 14.6.0 release to fix up the commits.
Merge the 14.6.0 release back into master
> merge release 14.6.0

- CHANGELOG.md
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/test_parser.cpp
- test/test_query2.cpp
> RCORE-2098: Fix issue with OR of two IN queries

- CHANGELOG.md
- Package.swift
- dependencies.yml
> core v14.6.1

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Core v14.6.1 

- CHANGELOG.md
Ops I forgot the next release note section.
> Forgot to add a commit with the release note.

- CHANGELOG.md
- Package.swift
- dependencies.yml
Merge Release v14.6.2 into master
> Merge release v14.6.2

- src/realm/object_converter.cpp
- src/realm/object_converter.hpp
- test/object-store/sync/client_reset.cpp
Mainly fixes these 2 cases:
1. We were not fully supporting links for collections in mixed
2. the prefix and suffix matching algorithms had some bugs in it
Requires a changelog entry once review is completed.
> Fix handling of collection in mixed. Adding support for Links + fix to prefix/suffix algo

- test/object-store/sync/client_reset.cpp
Fix test failure introduced in #7653.
> Fix test failure

- src/realm/array.hpp
- src/realm/bplustree.cpp
> Preserve context flag when comitting BPlusTree

- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
> RCORE-2119 Bump sync protocol version for collections in Mixed

- tools/release-init.sh
A few updates for https://github.com/realm/realm-core/pull/7566 based on the errors of the initial [run](https://github.com/realm/realm-core/actions/runs/9212445645/job/25344070472).
> RCORE-2134 update scripts for CI

- Android.bp
- CHANGELOG.md
Add a missing file from the bid library to the android blueprint.
> Add missing file to Android Blueprint

- src/realm/array.hpp
- src/realm/integer_compressor.cpp
- src/realm/integer_compressor.hpp
- src/realm/integer_flex_compressor.cpp
- src/realm/integer_flex_compressor.hpp
> Small optimizations

- test/realm-fuzzer/fuzz_engine.cpp
Better handling exception while creating fuzzer configuration
> handling exception better while creating fuzzer configuration

- CHANGELOG.md
> generate next changelog section

- src/realm/integer_flex_compressor.cpp
- src/realm/integer_flex_compressor.hpp
- src/realm/query_conditions.hpp
Use individual strategy when searching values and indexes. Early out on trivial conditions.
> Improve FlexCompressor::find_all

- test/test_sync.cpp
This refactors a refactor of this test to what it was doing before #7124.
> RCORE-2149 Restore behavior of Sync_UploadDownloadProgress_1 test

- bindgen/spec.yml
Adding `flexible_schema` to the `spec.yml`
> [bindgen] Add  to configuration

- test/object-store/sync/flx_schema_migration.cpp
> RCORE-2202 Fix asan failure in schema migration tests

- src/realm/exec/realm_trawler.cpp
> Fix compile error
