realm/realm-core

- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/sync/config.cpp
- src/realm/sync/protocol.cpp
- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
This adds the error code the server will send back if the client upload something that is "out-of-view" to the server as described in REALMC-11271. I'm not tackling supporting the DiscardLocal client resync mode here since I think that will be kinda involved, for now I think we should just make sure the error codes get exposed correctly.
> Handle out-of-view client resets in FLX sync

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
This reworks the implementation of `SubscriptionSet`/`MutableSubscriptionSet` so that `SubscriptionSet` does not actually hold on to any database resources and we can avoid pinning old versions of the database if a user holds on to a `SubscriptionSet` for a long time.
This simplified a bunch of things - like we don't need to maintain our own iterator implementation anymore, we can just re-use `std::vector`'s iterators. But it also made the commit method do actual serialization work in addition to just committing.
This also lets us handle the `Superceded` state a little more gracefully. Before, if you called `refresh()` on a `Superceded` `SubscriptonSet` it would throw a `KeyNotFound` error, and now it will properly update the state info.
> SubscriptionSet should not hold any database resources

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/tools/apply_to_state_command.cpp
This reworks integrating downloaded changesets so that errors are handled by throwing an exception rather than setting a mutable reference parameter to an error code an returning false.
It also adds some validation to the code that updates sync progress information so that it throws an error rather than aborting the process in debug builds.
* ~[ ] 🚦 Tests (or not relevant)~ there should be no user-facing changes from this.
> Rework integration error handling with exceptions

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
```
// FIXME: Replace this with a proper specific exception type once Core adds support for it.
```
The "IncompatibleHistories" error type has been released and can be used to satisfy this fixme.
This PR allows SDKs to more precisely catch incompatible history type errors.
> Translate IncompatibleHistories

- src/realm/dictionary.cpp
- src/realm/group.cpp
- src/realm/list.cpp
- src/realm/object-store/impl/collection_change_builder.cpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/instructions.cpp
- src/realm/sync/noinst/changeset_index.cpp
- src/realm/sync/noinst/changeset_index.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/sync/noinst/server/server_history.hpp
- src/realm/sync/object_id.hpp
- test/benchmark-common-tasks/main.cpp
- test/client/auth.hpp
Each instantiation of std::sort() is about 3 KB, which isn't a ton, but Lst was instantiating around 50 of them. We can reduce this to one at the cost of introducing a single virtual call per comparison. Based on the single benchmark of this, hoisting the load of `m_tree` out of the loop entirely cancels out the perf hit from this.
There were also a handful of other places where we were pointlessly instantiating std::sort() with different lambdas. ICF would make this not a problem, but ld64 doesn't support ICF.
File | Before | After | Change
----|-------|------|--
Stripped Realm.framework (SPM macOS) | 7,234,848 | 7,067,760 | 167,088
Stripped Realm.framework (Other iOS) | 7,152,304 | 6,971,216 | 181,088
Unstripped Realm.framework (SPM macOS) | 12,812,139 | 12,562,779 | 249,360
Unstripped …
> Reduce instantiations of std::sort and std::set

- CHANGELOG.md
- src/realm/sync/client.cpp
This fixes a pretty narrow race that happens if the callback to send a new QUERY message gets ordered on the sync thread's run loop after the session is torn down, so I haven't try to reproduce it in a test, but it's happened more than once for @tomduncalf. So I think we should get this change in that at least brings the behavior of checking whether its safe to send messages in line with how the rest of the sync client checks for that condition.
> Use correct tests when determining whether to send a QUERY message

- CHANGELOG.md
- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/list.hpp
- src/realm/replication.hpp
- src/realm/sync/instruction_replication.cpp
- test/object-store/list.cpp
- test/test_instruction_replication.cpp
The notification system in ObjectStore should work reflect the changes as seen by the user, so we need to adjust the indices according to the presence of unresolved links in the list.
Fixes #5164
> Filter out unresolved links in replication of list changes

- CHANGELOG.md
- doc/protocol/protocol_1.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/server/server.cpp
- test/test_sync.cpp
Token is ignored on the server so we send an empty one. Related to #4047.
> Discard token from bind and refresh messages

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/subscriptions.cpp
- test/object-store/sync/flx_sync.cpp
- test/test_sync_subscriptions.cpp
This changes the SubscriptionStore so it's initialized with a an empty "version zero" SubscriptionSet so that users can call `get_state_change_notification()` on the result of `get_latest()` before actually creating any subscriptions.
> SubscriptionStores should contain an implicit SubscriptionSet with version zero

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
Since changing SubscriptionSet's to not hold any database resources, the Subscription object's name hasn't been able to distinguish between a name that's an empty string and an anonymous subscription. This is definitely a very weird and small corner case, but I've fixed it here nonetheless for completeness's sake.
> Subscription names should be a default-constructed string_view if empty

- CHANGELOG.md
- src/realm/util/future.hpp
- test/test_util_future.cpp
I noticed while working on something that Future::on_completion() was not working. I don't know how I missed this when I was doing this work earlier in the year, but it looks like I missed some test coverage here. I've fixed on_completion and added a bunch of tests for it.
There were also two other minor bugs in the future header that get fixed as well.
> Fix Future::on_completion

- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/sync/protocol.cpp
- src/realm/sync/protocol.hpp
After the removal of the REFRESH message from sync protocol there were still some references to it and some unused test code. This pull request addresses that.
> Clean-up after removal of refresh message from sync protocol

- src/realm/sync/client.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/util/ez_websocket.cpp
- src/realm/util/ez_websocket.hpp
- src/realm/util/http.cpp
- src/realm/util/http.hpp
- test/sync_fixtures.hpp
- test/test_sync.cpp
This stack of 3 commits are all about making the sync client business logic not need to set low-level options (such as HTTP headers) when making websocket requests.
> Make sync client more compatible with simple websocket libs

- CHANGELOG.md
- evergreen/install_baas.sh
- src/realm/sync/noinst/server/crypto_server_apple.mm
- src/realm/sync/transform.cpp
- src/realm/util/allocator.hpp
- test/test_util_network_ssl.cpp
macOS 12 requires us to set DYLD_LIBRARY_PATH rather than LD_LIBRARY_PATH.
There's also just a pile of warnings when targeting macOS 12 that I fixed.
> Fix running the baas tests on macOS 12

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
Renaming to avoid SDKs propagating this typo to end-users.
> Rename "Superceded" to "Superseded"

- CHANGELOG.md
- src/realm/string_data.hpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_encoder.hpp
- src/realm/sync/changeset_parser.cpp
- test/test_changeset_encoding.cpp
- test/test_sync.cpp
Internal strings were stored as **std::string** and looked-up as **StringData**.  As it seems, the **less than** operator of realm::StringData behaves differently than the one of std::string (especially when it comes to UTF-8 strings). Storing the internal strings in a sorted collection led to wrongfully not finding existing intern strings.
This change makes sure we use std::string's to both look-up and insert intern strings.
> Trying to intern a string multiple times may lead to duplicates

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/client_reset.cpp
Fixes https://github.com/realm/realm-core/issues/5223
I forgot to check a function before calling it. I think SDKs other than cocoa have these always set because they wrap them up in a SDK layer callback so are likely not affected.
> Fix DiscardLocal client reset failure with unset callbacks

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- test/object-store/realm.cpp
Adds some checking when opening a realm to make sure you can't open an in-memory realm that's encrypted, which is not something we support.
> Disallow opening a realm as in-memory and encrypted

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/shared_realm.hpp
We need the ability to retrieve schema version of a realm as part of the Kotlin migration API. Just doing the obvious implementation to unblock. 
Closes #5236
> Add support for retrieving schema version through the C-API

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
This changes the behaviour of what `between` means in parsed queries. There might be some concern that this is a breaking change, but given that we have documented it otherwise I think it we can call it a fix.
The [docs](https://docs.mongodb.com/realm/reference/realm-query-language/#expressions) specify that `BETWEEN` "Evaluates to true if the left-hand numerical or date expression is between or equal to the right-hand range"
This is also the definition according to [NSPredicate](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-CJBDBHCB). Which means that this removes a discrepancy between parsed query syntax and cocoa's query syntax.
> Query parser's BETWEEN is a closed interval

- src/realm/exec/CMakeLists.txt
- src/realm/exec/realm2json.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
Allow for more fine grained inspection of objects when dealing with large Realms by printing only objects which match a query.
> Realm2Json can query for objects

- src/realm/object-store/impl/realm_coordinator.cpp
Putting quotes around File and Directory in this error just makes it awkward.
> Remove extraneous quotes from an error message

- CHANGELOG.md
- CMakeLists.txt
- src/realm/sync/CMakeLists.txt
Long ago, in https://github.com/realm/realm-sync/pull/2506, I had made the mistake of linking against the wrong Windows library to pull in a simple function to get the operating system version.
Instead of linking against `Version.lib` as I should have, instead I linked against the `MinCore` [umbrella library](https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-umbrella-libraries), which actually describes a [Windows API set](https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-apisets). API sets are useful, because they allow a binary to target different Windows platforms (PCs, tablets, HoloLens, etc.), but at the cost of additional runtime stub libraries the application needs to distribute which facilitate backwards compatibility on older versions of Windows.
Realm …
> Fix Windows 8.1 targeting when building with the Windows 10 SDK

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
Core may crash If a SubscriptionSet is used after the SubscriptionStore referenced by it is deallocated.
If an SDK user closes the realm but still operates on a SubscriptionSet, a use-after-free violation may occur. This only happens if QBS is used.
This pull request identifies when the SubscriptionStore is not available anymore and throws an exception if a SubscriptionSet is used.
Fixes #5208.
> Throw exception when operating on a SubscriptionSet after the SubscriptionStore is deallocated

- evergreen/config.yml
- test/object-store/sync/flx_sync.cpp
Because of RCORE-911 we cannot currently create new app configs in our object-store test harnesses. That's why our object-store tests are hanging/timing out. This temporarily pins the version of baas we use so that our tests should pass again.
> Pin BAAS version in evergreen config for now

- CHANGELOG.md
- src/realm/mixed.cpp
- test/test_array_mixed.cpp
Mixed::compare() promoted floats to double before converting to Decimal128, which as of #5191 results in different rounding than converting a float to Decimal128 directly. The comparison was also invalid before #5191, but in the opposite direction (comparing double to Decimal128 used too little precision), and fixing that revealed this.
This is sort of a file-format break as it changes the result of Mixed::compare(), which matters for Set<Mixed>. However, it's just partially walking back #5191's change to comparison, so if this is actually a problem then we're in trouble regardless.
The other changes to mixed.cpp are just making the helper functions not be exported as they don't need to be.
> Fix inconsistent float/decimal128 comparisons in Mixed

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
Starting an async write transaction from within a write transaction while the async state was idle would result in the background thread waiting on the write lock while the Transaction already held it on the current thread. This isn't an
inherently invalid thing to do, but it's something that can't happen in any other way and had a pile of race conditions. Rather than try to get this to work correctly, it's easier to just schedule the async write to be kicked off when the synchronous write is committed, which makes this scenario work much more like other scenarios.
> Fix an assertion failure when starting an async transaction from within a synchronous transaction

- Jenkinsfile
#5247 added Windows ARM64 release packages but didn't actually update the Windows SDK version to one that can build ARM64 for regular Windows. This fixes the SDK mistake, and adds an Windows ARM64 parallel branch to make sure we exercise it during the checking stage.
> Add a Windows ARM64 checking build

- evergreen/config.yml
#5271 broke running benchmarks on macOS on Evergreen because it started using Xcode as a generator instead of the default Unix Makefiles. This is a problem because Xcode and other config-aware generators place products in a configuration-specific folder in the build tree (e.g. `${CMAKE_BINARY_DIR}/$<CONFIG>/$<TARGET_OUTPUT_NAME>`), and our benchmark tasks hardcode the paths to the benchmark executables.
The fix this PR proposes is to bite the bullet and always use configuration-aware generators (Xcode and Visual Studio already are, Ninja Multi-Config becomes the default everywhere else). This allows us to always assume build product paths contain the configuration everywhere, not just on some generators, and makes fixing the actual benchmark task simpler.
> Build with config-aware CMake generators on evergreen

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/sync_manager.cpp
- test/object-store/sync/app.cpp
Refreshing the user profile after the app has been destroyed leads to assertion failure and use-after-free violation. 
This is fixed by making it impossible that callbacks are executed after the app is deallocated. All user callbacks hold a reference to the app until they are executed. Fixes #5238, [#2800](https://github.com/realm/realm-dotnet/issues/2800)
> App cannot be deallocated while api calls are in progress

- CHANGELOG.md
- src/realm/obj.cpp
Fixes #5283
Also potentially fixes other corruption bugs.
> Fix possibly missing parent update when setting null values

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
This restores the previous behavior where calling any of the mutation functions on a MutableSubscriptionSet after its been committed should throw.
> Throw if you mutate a committed MutableSubscriptionSet

- test/test_lang_bind_helper.cpp
Due to the [extra assertions ](https://github.com/realm/realm-core/pull/5297) added to this test, I found a [failure in CI](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/PR-5325/2/pipeline/) with the "populate" child giving an assertion failure on exit `1: /mnt/jenkins/workspace/realm_realm-core_PR-5325@2/src/realm/util/thread.cpp:186: [realm-core-11.11.0] Destruction of mutex in use`
There are three static Mutexes in use in the tests: in utilities.cpp, test_util_type_list.cpp, and random.hpp. Notably, GlobalRandom makes use of a mutex when sourcing randoms. Given this, I think the source of the hangs is that if the call to `fork()` happens while some concurrent test has the GlobalRandom mutex locked, then that state is copied over to the child process and the …
> fix hangs in LangBindHelper_ImplicitTransactions_InterProcess

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/impl/apple/keychain_helper.cpp
- src/realm/object-store/impl/apple/keychain_helper.hpp
- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- test/object-store/sync/metadata.cpp
- test/object-store/sync/sync_manager.cpp
While on iOS the keychain basically just always works, on macOS the keychain is a user-managed thing with permissions and accessing it can either fail or pop up a prompt for the user to approve or reject it, and we need to not just crash when that happens.
If we can't access the keychain, this makes it so that we simply store the metadata realm unencrypted. This isn't a great solution: ideally we'd expose some customization hooks in the SDK to let the app configure the authentication dialog, gracefully recover from keychain access being rejected, and decide whether to disable encryption. That would be a much larger project, though.
Most of this error handling can't be automatically tested. macOS 12 deprecated a lot of the advanced keychain management functionality, so we can no longer …
> Improve handling of keychain errors on macOS

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/flx_sync.cpp
While refreshing the access token, there is no session. If at the same time a subscription set is updated, the session is accessed resulting in a crash.
We have now guarded access to the session for this specific case. Fixes #5343.
> Updating subscription while refreshing the access token would crash

- CHANGELOG.md
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/config.hpp
- src/realm/util/checked_mutex.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_sync.cpp
And fix a few problems exposed by them, mostly related to that `m_config` was used unguarded despite being mutable. This adds a new mutex to guard `m_config` because reusing the state mutex for that made some code I wanted to write on the audit branch deadlock.
> Add thread-safety annotations to SyncSession

- CHANGELOG.md
- src/realm/object-store/collection_notifications.hpp
- src/realm/object-store/impl/collection_change_builder.cpp
- src/realm/object-store/impl/collection_change_builder.hpp
- test/object-store/collection_change_indices.cpp
- test/object-store/list.cpp
- test/object-store/set.cpp
Added a new flag to `CollectionChangeSet` to indicate when `remove_all` is called on collections.
> Added flag to CollectionChangeSet to indicate cleared collection

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- test/object-store/sync/app.cpp
The accumulated size was always zero, resulting in it always uploading all pending changesets in a single UPLOAD message.
Fixes https://jira.mongodb.org/browse/HELP-32882.
> Fix changeset batch size calculation

- evergreen/config.yml
As part of trying to find encryption corruption bugs we found that we don't run our core tests in EVG with encryption enabled, and we don't run our core tests with encryption enabled AND the sanitizers enabled anywhere. This adds a few more builders to change that.
The TSAN encryption builder is currently red because it actually found a bug.
> Run encryption tests in evergreen

- evergreen/config.yml
We've been having issues with some of the hosts in the macos 10.15 pool on evergreen. Instead of mucking around older macos hosts, I figured we can just upgrade to macos 11 which has newer and more builders available.
> upgrade macos builders to macos 11.0

- src/realm/table.cpp
- src/realm/table.hpp
- test/test_unresolved_links.cpp
Collision in the generated unresolved key would not be detected.
> Fix potential issue in creating tombstones for invalidated objects

- CHANGELOG.md
- tools/cmake/xcode.toolchain.cmake
Turns out they weren't actually needed after all.
> Remove CMAKE_OSX_ARCHITECTURES from the Xcode toolchain

- CHANGELOG.md
- src/realm/cluster.cpp
- test/test_set.cpp
> Remove backlinks when deleting an objects containing a LnkSet

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
We have an issue with the JS SDK where "hot reloading" (which reloads the JS part of the application on a new JS thread, but keeps the native part running) a React Native app which is using Realm sync can result in a `Multiple sync agents attempted to join the same session` exception (https://github.com/realm/realm-js/issues/4506).
The underlying cause of this is a race condition between the sync client for the "old" JS application being destroyed (which happens [after upload completion](https://github.com/realm/realm-core/blob/master/src/realm/object-store/sync/sync_session.cpp#L115) by default), and the "new" (reloaded) JS application opening its Realm and therefore creating a new sync client.
The React Native [invalidate](https://github.com/realm/realm-js/blob/master/react-native/ios/Re …
> Add RealmCoordinator::log_out_all_sync_sessions method

- how-to-build.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
- test/util/compare_groups.cpp
Fixes https://github.com/realm/realm-core/issues/5289
Introduces a third mode `RecoverOrDiscard` which gives better control of the automatic reset behaviour. This is to allow clients to opt in to Recovery mode _only_ without attempting to discard data if it comes to that. It is expected that `RecoverOrDiscard` will be the default in the future. This also introduces a boolean to the notify_after callback so that users can know which type of automatic reset actually happened.
The cycle detection operates by writing to an internal non-sync'd table which is created as needed. An entry is created there  when starting a reset, and it is erased on the next successful sync upload to the server. If a reset is started while a previous reset has been detected either an error is generated or a …
> Detect and prevent client reset cycles

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- test/object-store/c_api/c_api.cpp
Use `realm_results_t` rather than explicit `realm_query_t` to better adhere to sdk usage of queries. 
Fixes https://github.com/realm/realm-core/issues/5431
> pass down a result object instead of an explicit query

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
Expose `SyncUser::access_token()` and `SyncUser::refresh_token()` in the C API
Fixes: https://github.com/realm/realm-core/issues/5419
> Expose `SyncUser::access_token()` and `SyncUser::refresh_token()` C API

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/realm.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/metadata.cpp
- test/test_shared.cpp
- test/test_sync.cpp
#5432 made it so that sync -> sync convert() synthesizes new sync history, which makes the end result not work as a bundled Realm. The tests did not catch this because none of the tests actually verified that sync worked with the end result (opening the Realm worked, but it'd just result in bad changeset errors from the server).
The path version of `write_copy()` was just a compatibility wrapper to avoid forcing SDKs to update their code, but that's pointless when the function is renamed anyway.
No changelog message since we didn't actually ship it.
> Fix created bundled sync Realms

- test/object-store/sync/flx_sync.cpp
Fix a test failure in "flx: query on non-queryable field results in query error message"
The server error messaged recently changed and so the evergreen tests which pull in the latest version started failing this check. The Jenkins tests pin a specific baas version so they were ok. But this leaves us in a state where we can't check for a specific message. The change here extracts out the beginning and end of the message which are the same for both versions.
old message: `"Client provided query with bad syntax: invalid match expression for table "TopLevel": key "non_queryable_field" is not a queryable field"'`
new message: `'"Client provided query with bad syntax: unsupported query for table "TopLevel": key "non_queryable_field" is not a queryable field"`
> baas has different error messages for different versions

- evergreen/config.yml
- test/object-store/main.cpp
While debugging a hang that I could only trigger on evergreen, I found that the hang analyzer stack traces were not enough to figure out which test sections were problematic. 
These changes will help debug hangs in evergreen by printing out the successful test sections as they complete.
> Turn on durations for object-store tests in evergreen

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
This variable was added in #5373 and if you call find_sync_history_entry() such that end_version - begin_version is zero, it will never get initialized and we'll set our upload cursor to an uninitialized value.
> Fix uninitialized variable

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- test/object-store/c_api/c_api.cpp
The callback function called during realm_async_open_task_start must
receive a pointer to a thread-safe-ref that can be transferred to another thread.
For that to be possible the object must be allocated on the heap so that the
callee owns the object. Previously the pointer was pointing to a stack based
local variable.
> Make thread-safe-ref transferable

- src/realm/object-store/sync/sync_session.hpp
Looks like a warning snuck into master due to a non-trivial merge.
`sync_session.cpp:303 | -Wthread-safety-analysis: calling function 'handle_fresh_realm_downloaded' requires holding '!m_connection_state_mutex'`
> Fix a thread safety analysis warning

- src/realm/sync/client_base.hpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_reset.hpp
- test/object-store/sync/client_reset.cpp
e92de0471 broke using the release packages. Installed headers can't import noinst headers because those are not included in the installed package.
> Fix invalid header dependencies

- src/realm.h
Similar to https://github.com/realm/realm-core/pull/5492
Kotlin uses pattern matching in our code generation layer, and this was messing some things up. This just align the `erased` parameter, so it uses the same name as the similar methods around it.
> Align C-API parameter naming

- .github/pull_request_template.md
Add mention of C-API to PR template since we need to keep public C++ API and C-API in Sync.
> Mention C-API in PR template

- CHANGELOG.md
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
Quick fix in order to avoid ordering for queries passed to sync subscriptions. 
Fixes: https://github.com/realm/realm-core/issues/5504
> Fix ignoring ordering for queries passed into sync subscription in the C API

- CHANGELOG.md
- src/realm/sync/changeset.hpp
- src/realm/sync/noinst/changeset_index.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- test/test_sync.cpp
This came out of troubleshooting some test failures @ironage had passed to me. The bug here is that the client's ChangesetIndex stores Changesets in a Map sorted by version but has a bunch of checks to make sure that they are transformed in the order they are received. Since bootstraps can contain the same version number over and over again and the sort in the map is not stable, that means we can sometimes hit REALM_ASSERT's when Changesets get "out-of-order" with respect to where they appeared in the incoming message.
I think this is super blocking for World, so I threw together this quick fix that adds a new parameter to the sort in the ChangesetIndex to represent the position of the Changeset within the download message. I think we should absolutely rip out this quick fix with a better …
> Ensure ChangesetIndex ranges are sorted by version and order within download message

- evergreen/install_baas.sh
This does what it says on the tin. If you aren't on one of the platforms we build in evergreen, install_baas.sh now lets you specify local paths to the various binary dependencies for baas so you can do local testing on exotic linux distros.
> Fix install_baas.sh script on exotic linuxes

- CHANGELOG.md
- evergreen/config.yml
This just bumps the version of Xcode we build with on MacOS builders in evergreen from 12.4 to 13.1.
> Bump Xcode version in evergreen to 13.1

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/notifications.cpp
- test/object-store/c_api/c_api.cpp
Remove the scheduler argument to the C API `realm_*_add_notification_callback` functions, because it wasn't actually used.
> [C API] remove unused argument

- CHANGELOG.md
- evergreen/config.yml
- src/realm/mixed.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/changeset_parser.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/protocol.cpp
- src/realm/sync/protocol.hpp
- test/object-store/CMakeLists.txt
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
This adds support to the sync client and object store for handling compensating write errors from the server. There are some new fields in the SyncError class that represent which objects caused the compensating writes and why. The changeset parser has been refactored a bit to support parsing some of the values encoded in compensating write errors. The test that previously checked that uploading an object out-of-view results in a client reset now checks that a compensating write error is received. The test for compensating writes is only enabled on a special build variant that runs against the master branch of baas - this will be undone when baas releases next week.
> Handle compensating writes

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
Merged the `realm_sync_upload_completion_func_t` and the `realm_sync_download_completion_func_t` typedefs in the C API because they were identical.
> [C API] Merge identical typedefs

- test/object-store/CMakeLists.txt
- test/object-store/backup.cpp
- test/object-store/main.cpp
- test/object-store/realm.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/util/test_file.cpp
Set environment variable UNITTEST_ENCRYPT_ALL in order to use encryption
as default.
Fixes #5567
> Enable the use of encryption in OS tests

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_session.cpp
PendingBootstrapStore is created early in session initialization, which performs a write and thus reads the write validator. This can race with setting the write validator on the thread which created the sync session, and tsan complains about it.
Moving the initialization to SyncSession's constructor ensures that it's set before we create the `sync::Session`.
> Fix a data race on write_validator_factory

- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
There may be some unintended cross test state in the client reset tests because we used the same partition and _id values across the suite. Generating a random partition and using ObjectId values should ensure that there are no unintended state changes from the translator.
> Use random partitions and object _ids across tests

- Package.swift
This appears to have been broken since https://github.com/realm/realm-core/pull/5568
The error was:
```
Undefined symbols for architecture x86_64:
"__ZN5realm9test_util21enable_always_encryptEv", referenced from:
_main in main.cpp.o
"__ZN5realm9test_util9crypt_keyEb", referenced from:
__ZN8TestFileC2Ev in test_file.cpp.o
ld: symbol(s) not found for architecture x86_64
[124/140] Compiling Capi schema.cpp
```
This is because the object-store tests now require building with "../util/crypt_key.cpp" which is part of the core test utils. The solution here is to add the core test utils as a dependency of the object store tests. A better long term solution might be to combine our test suites.
> fix undefined symbol crypt_key in swift builds

- CHANGELOG.md
- src/realm/obj.cpp
- src/realm/object-store/object_schema.cpp
- src/realm/table.cpp
- test/object-store/schema.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
Embedded objects were wrongly not allowed in asymmetric sync. This PR addresses that.
Fixes #5565.
> Allow embedded objects with asymmetric sync

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
`realm_sync_before_client_reset_func_t` and `realm_sync_after_client_reset_func_t` in the C API now return a boolean value to indicate whether the callback succeeded or not, which signals to the sync client that a fatal error occurred.
> [C API] client reset callbacks can indicate error

- CMakeLists.txt
- Jenkinsfile
Catch2 uses [sigaltstack](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sigaltstack.2.html), which is unavailable on tvOS and watchOS.
This PR adds a PR build check for tvOS, making sure the code compiles for tvOS on every PR. It also moves the Catch2 include in `CMakeLists.txt` below the `REALM_CORE_SUBMODULE_BUILD` check so it's not picked up by downstream projects including realm-core, removes it from the default build unless explicitly required by another target, and sets `CATCH_CONFIG_NO_POSIX_SIGNALS` to disable the particular functionality requiring `sigaltstack`.
> Fix building Catch2 for tvOS and watchOS

- CHANGELOG.md
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/object-store/sync/client_reset.cpp
Specifically: erasing or moving a list item to trigger verbatim copying of the list, but also erasing the base object locally later on in the recovery. The way exceptions are handled during recovery is to fallback to a manual client reset (or discard local if in recoverOrDiscard mode) so the impact of this is expected to be minimal, especially because SDKs have not released recovery yet.
I found this issue when writing benchmarks.
> Fix an exception during recovery of lists

- test/object-store/sync/flx_sync.cpp
- test/object-store/util/baas_admin_api.cpp
Reusing a single app for all of the asymmetric sync tests makes them run in 20 seconds instead of 3 minutes on my machine. This doesn't really solve the broader problem of the baas-enabled tests taking way too long to run (it's still 25 minutes for me) but it's a step in the right direction at least.
> Speed up the asymmetric sync tests

- external/generated/empty.cpp
This fixes Xcode builds that are using Package.swift directly.
I don't know if there is a better way to set up the swift build dependency, but this seems to do the trick for me.
> Add a dummy file to trick the swift build into working

- CHANGELOG.md
- src/realm/sync/changeset.hpp
A customer (HELP-34650) reported slow downloads on iOS 14 and android. Profiling sync on an iOS 14 device revealed tons of time being spent requesting memory. I tried to reproduce this on mac, and ubuntu but could not. @ericjordanmossman profiled an actual iOS 14 device, and we found a bottleneck in `InstructionBuilder::add_string_range`:
I noticed that changesets were mostly adding small strings (~10-50 bytes) such that `m_string_buffer` has to constantly request more memory, but only by a little bit each time once it outgrows the initial 1024 reserved capacity. The fix is to keep reserving 1k buffer space in chunks rather than increasing a little bit each time. I think this is not a problem on machines with more memory, because if the initial allocation uses memory that has additional …
> optimize memory allocation of changesets with many small strings

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- src/realm/sync/noinst/client_reset_recovery.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
- test/object-store/sync/sync_test_utils.cpp
Enable client reset with recovery in flexible sync mode.
In this mode, changeset recoveries are grouped together in a commit up until the next pending FLX sync subscription, where at that point the corresponding subscription is committed separately as well. This cycle repeats until no local changes remain. In this way, we handle offline writes that only match a temporary subscription.
Built on top of https://github.com/realm/realm-core/pull/5404
> FLX client reset with recovery

- test/CMakeLists.txt
- test/object-store/benchmarks/CMakeLists.txt
- test/object-store/benchmarks/client_reset.cpp
- test/object-store/benchmarks/main.cpp
- test/object-store/benchmarks/object.cpp
Update the object store benchmarks to fix build errors and add some basic recovery benchmarks.
Fixes https://github.com/realm/realm-core/issues/5291
Baseline results from my local machine:
```
Filters: client reset
Randomness seeded to: 330187956
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
object-store-benchmarks is a Catch2 v3.0.1 host application.
Run with -? for options
-------------------------------------------------------------------------------
client reset
DiscardLocal: from empty initial state
-------------------------------------------------------------------------------
/Users/js/Documents/code/realm-core2/test/object-store/benchmarks/client_reset.cpp:279
............................................................................... …
```
> Recovery benchmarks

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/config.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/client_reset.cpp
When a client reset callback is dispatch to a event loop on another thread, it is not possible to access the Realm. 
Related to https://github.com/realm/realm-js/issues/4410
> Thread independent client reset

- test/object-store/c_api/c_api.cpp
I got a sporadic failure in CI while working on something unrelated. This is an attempt to fix it.
```
[2022/06/17 18:18:01.156] 3: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022/06/17 18:18:01.156] 3: realm-object-store-tests is a Catch2 v3.0.1 host application.
[2022/06/17 18:18:01.156] 3: Run with -? for options
[2022/06/17 18:18:01.156] 3:
[2022/06/17 18:18:01.156] 3: -------------------------------------------------------------------------------
[2022/06/17 18:18:01.156] 3: app: flx-sync basic tests
[2022/06/17 18:18:01.156] 3: -------------------------------------------------------------------------------
[2022/06/17 18:18:01.156] 3: /System/Volumes/Data/data/mci/caa9b8efc23df0ce69bdd3301a401077/realm-core/test/object-store/c_api/c_api.cpp:4401 …
```
> extend wait times in a c_api test

- CHANGELOG.md
- evergreen/config.yml
- src/realm.h
- src/realm/exec/realm_trawler.cpp
- src/realm/object-store/c_api/conversion.hpp
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/object_accessor.hpp
- src/realm/object-store/object_schema.cpp
- src/realm/object-store/object_schema.hpp
- src/realm/object-store/object_store.cpp
- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/audit.cpp
- test/object-store/dictionary.cpp
- test/object-store/list.cpp
- test/object-store/migrations.cpp
- test/object-store/object.cpp
- test/object-store/realm.cpp
- test/object-store/schema.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
- test/object-store/util/baas_admin_api.cpp
- test/test_embedded_objects.cpp
- test/test_json.cpp
This PR fixes and improves several things around asymmetric sync.
- The bug in RCORE-1120 resulted as an implementation oversight due to using boolean values for asymmetric and embedded properties in ObjectSchema. This is now replaced by an Enum value.
- Migration tests were added to make sure it is not allowed to migrate to or from an asymmetric table.
- Asymmetric objects can now contain lists and dictionaries of embedded objects.
- Integration test was added to validate an asymmetric table can be added in development mode.
Fixes RCORE-1120.
(Commits are logically separated to make review easier)
> Do not allow migrations with asymmetric tables

- src/realm/alloc_slab.cpp
Reverts realm/realm-core#5601.
There are failing windows tests that should be addressed before merging:
```
[2022/06/17 10:11:02.654] 1: FAILURE: 2 out of 1532 tests failed (0 out of 48718136 checks failed).
[2022/06/17 10:11:02.656] 1: C:\data\mci\48c73cd92a871c1c1c07c742e13323b2\realm-core\test\test_shared.cpp:418: ERROR in Shared_CompactingOnTheFly: Unhandled exception struct realm::InvalidDatabase: Realm file initial open failed: SetEndOfFile() failed: The requested operation cannot be performed on a file with a user-mapped section open. Path: Shared_CompactingOnTheFly.1.path.realm
[2022/06/17 10:11:02.656] 1: Exception backtrace:
[2022/06/17 10:11:02.656] 1: <backtrace not supported on this platform>
[2022/06/17 10:11:02.656] 1: …
```
> Revert "Shrink file if logical size is less than file size"

- CHANGELOG.md
- src/realm/sync/tools/apply_to_state_command.cpp
The problem is related to the `decompress()` operation in `DownloadMessage::parse()` and `UploadMessage::parse()`. The buffer was being decompressed to a local smart pointer that was going out of scope at the end of the method. These functions were updated to save the decompressed body buffer data into the `uncompressed_body_buffer` property in the `UploadMessage`/`DownloadMessage` object returned by the function.
Re-ran the test after the fix and exception was no longer seen.
> Exception when decoding interned string in realm-apply-to-state tool

- CHANGELOG.md
- src/realm/transaction.cpp
This will ensure the the stage is correct even if subsequent
procedure calls will trigger an exception.
> Update transaction stage earlier in commit_and_continue_as_read

- test/object-store/sync/flx_sync.cpp
This test has been failing pretty consistently in CI so I'm going to disable it while we figure out the root cause and fix it.
Also disabling "flx: bootstrap batching prevents orphan documents" since it's been particularly flakey lately.
> Disable flakey "flx: asymmetric sync - dev mode" test for now

- Jenkinsfile
- tools/build-apple-device.sh
This ensures that the CPack tarballs have the correct version in their filename in nightly builds.
> Pass the nightly version string to the Xcode build script

- CHANGELOG.md
- src/realm/impl/simulated_failure.cpp
- src/realm/util/features.h
Fix an error when compiling a watchOS Simulator target on an M1 is not supporting Thread-local storage https://github.com/realm/realm-swift/issues/7694
https://github.com/realm/realm-swift/issues/7695
> Fix WatchOS simulator not supporting thread_local

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/benchmark-common-tasks/main.cpp
- test/object-store/audit.cpp
- test/object-store/dictionary.cpp
- test/object-store/frozen_objects.cpp
- test/object-store/primitive_list.cpp
- test/object-store/realm.cpp
- test/object-store/set.cpp
- test/object-store/transaction_log_parsing.cpp
- test/test_decimal128.cpp
- test/test_embedded_objects.cpp
- test/test_index_string.cpp
- test/test_json.cpp
- test/test_lang_bind_helper.cpp
- test/test_link_query_view.cpp
- test/test_object_id.cpp
- test/test_parser.cpp
- test/test_query.cpp
- test/test_query2.cpp
- test/test_set.cpp
- test/test_sync.cpp
- test/test_table.cpp
- test/test_transform.cpp
- test/test_typed_links.cpp
- test/test_uuid.cpp
- test/util/compare_groups.cpp
This makes it so that it is passed in registers rather than on the stack (on Itanium ABI platforms), which gives a small but measurable performance improvement to basically everything.
A side effect of this is that Obj becomes trivially destructible as well, which results in clang now warning about unused Obj variables.
> Make MemRef trivially destructible

- CHANGELOG.md
- evergreen/config.yml
* The bloaty test is failing after the compile step due to the compile output file 'librealm-ffi.so' not being found when the bloaty analysis is run.
* The path to the file did not include the target directory (e.g. `RelWithDebInfo`). The list of files passed to the bloaty tool was updated with the cmake build type variable to point to the correct directory.
> Fix bloaty CI test that is currently failing on master

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/audit.mm
- src/realm/table.hpp
The emulated implementation of InterprocessCondVar requires that the associated mutex be held when `notify_all()` is called because it performs non-atomic reads and writes on the shared part, which would be a data race if done without a mutex covering the access. This is already noted as a precondition of the function, which DB::do_end_write() violated.
Calling `DB::set_replication()` inside a write transaction is _almost_ safe to do, but it turns out that there's a few scenarios where the sync client will call `DB::get_replication()` outside of a write. Scoping the replication setting to just the specific Table fixes this (as live Table accessors actually are thread-confined) and also simplifies the logic a bit.
> Fix a few thread sanitizer failures

- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/encrypted_file_mapping.hpp
This PR adds a method to the encryption layer through which we can communicate changes on disk of the underlying file (presumably made by another process).
This is an internal interface decoupling future work on block management and multiprocess encryption.
> preliminary API extension in support of multiprocess encryption

- CHANGELOG.md
- src/realm/object-store/audit.hpp
- src/realm/object-store/audit.mm
- src/realm/object-store/shared_realm.cpp
Recording audit write events requires having access to the old and new versions of the objects so that we can report the old value of properties in the events. This was done by beginning a read Transaction at the old version after committing the write transaction, but this is too late; if another write transaction happens on a different thread (say, by the sync client) in between the commit and the call to `record_write()` the old version may be cleaned up already.
No new test since this requires a very tight timing window, and if it wasn't for that one of the Swift tests coincidentally hits this ~5% of the time I would have thought it couldn't actually happen in practice.
> Fix a race condition when recording audit write events

- test/benchmark-larger/main.cpp
- test/object-store/benchmarks/results.cpp
- test/object-store/sectioned_results.cpp
Fix warnings for benchmark build. Compiler warnings are treated as errors in evergreen.
> Fix benchmark results warnings

- CHANGELOG.md
- src/realm/object-store/audit.mm
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
As reported by @LaPeste, the client reset callbacks would be called with null Realm instances if the call to `RealmCoordinator ::get_existing_coordinator()` returned a nullptr. This can happen if the sync session is running a client reset operation while all references to the Realm have been released. To fix this, we need to get or create a coordinator and the way to do that is to pass in the `RealmConfig`. This is not something that the sync session had, so I added it in place of the SyncConfig that was already there. It is a bit of a heavy handed solution, but a better way wasn't obvious to me.
> Fix client reset callbacks not populating Realm instances sometimes

- src/realm/array_basic.hpp
Point fix windows warning narrow conversion between float and double
> fix warning on windows

- Jenkinsfile
- src/realm/array_basic.hpp
- test/test_util_future.cpp
There is another warning in https://github.com/realm/realm-core/pull/5681 reported for windows-Win32-Release-uwp builders.
```
query_flex.ll:2182 | C4018 | Normal | 1
-- | -- | -- | --
'>': signed/unsigned mismatch (compiling source file C:\jenkins\workspace\realm_realm-core_PR-5681\src\realm\parser\generated\query_flex.cpp)
query_flex.ll:2182	[C4018](https://ci.realm.io/job/realm/job/realm-core/job/PR-5681/1/windows-Win32-Release-uwp-16f2e064-1cec-4e52-a7e9-51ee7d30d30b/category.63472742/)	[Normal](https://ci.realm.io/job/realm/job/realm-core/job/PR-5681/1/windows-Win32-Release-uwp-16f2e064-1cec-4e52-a7e9-51ee7d30d30b/NORMAL)	1
'>': signed/unsigned mismatch (compiling source file C:\jenkins\workspace\realm_realm-core_PR-5681\src\realm\parser\generated\query_flex.cpp)
```
This change …
> Ignore warnings in generated code

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
Some future expressions does not allow you to just swap left and right, so in order to be able to handle those, we must stop swapping.
> Don't swap left and right in Query Parser

- evergreen/install_baas.sh
- src/realm/array_basic.hpp
- src/realm/util/websocket.cpp
- test/object-store/main.cpp
This gives less of a speedup than I was hoping, but it does cut 2 minutes off the test suite runtime (~10%). The `GOMAXPROCS` has no meaningful effect over the course of the entire test suite, but it makes it so that running a single test takes twice as long as usual less often.
> Use arm64-native BaaS on m1

- CHANGELOG.md
- src/realm/object-store/audit.mm
It requires very specific timing, but it's possible for an AuditRealmPool to outlive the parent AuditContext, and trying to use the logger when that happens was a use-after-free.
I tried to find a way to write a test for this, but it doesn't seem to be possible. The specific sequence of events it needs are:
1. Upload completes while the AuditContext is still alive.
2. `auto self = weak_self.lock()` succeeds as the AuditContext is still holding a strong reference
3. AuditContext is destroyed on a different thread. The AuditRealmPool remains alive as it's currently holding a strong reference to itself, but the logger is destroyed.
4. We try to log something and use the destroyed logger.
If the AuditContext is destroyed _before_ the completion callback is invoked `weak_self.lock()` returns …
> Hold a strong reference to the logger in AuditRealmPool

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
This is pretty minor but there's some scenarios where we end up calling `refresh()` on a SubscriptionSet that definitely hasn't changed a bunch of times and it does a nontrivial amount of work even if there's no newer transaction versions.
https://github.com/realm/realm-core/pull/5150 added a second call to `get_by_version(version())` and I don't see how the first call could possibly have any effect, so I removed it.
> Check if there are any new versions before refreshing in SubscriptionSet

- src/realm/status_with.hpp
- src/realm/sync/client.cpp
Remove some warnings in release builds
> Suppress -Wmaybe-uninitialized warnings in selected places

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/util/bind_ptr.hpp
- test/object-store/realm.cpp
The schema version of a synchronized Realm is a local concept, so it doesn't get set by the sync client when downloading. We don't bother performing a write if the schema version is the only thing that's changed, but we do need to set the schema version if it's NotVersioned.
> Set the schema version when doing an async open in read-only mode

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- test/object-store/c_api/c_api.cpp
Fixes https://github.com/realm/realm-core/issues/5713.
The C-API wrapper was missing the parameter which gives control over what to do with an existing destination file.
> Expose  in C-API realm_convert_with*

- src/realm.h
- src/realm/object-store/c_api/sync.cpp
Added missing `ProtocolError::compensating_write` to the C-API.
> [C-API] - Added missing `ProtocolError::compensating_write`

- CHANGELOG.md
- src/realm/util/terminate.cpp
We often get stack traces from assertion failures reported from iOS users that do not have stderr output attached. Then the first thing we have to do is ask which version was used. This embeds the core version number into the stack trace so we can see it without asking. Example:
> The top of an assertion failed stack trace now includes the core version

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/query_parser.hpp
- src/realm/query_expression.hpp
Storing the string in the argument buffer space is not sufficient as the query
may live longer than the arguments object.
Fixes #5735
> QueryParser: Make handling of list of strings more robust

- CHANGELOG.md
- src/realm/object-store/object_store.cpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
#5696 accidentally made it so that we apply more changes than intended. `create_initial_tables()` will remove columns from the tables which aren't in the schema, which we don't want to do. I ported over all of the remaining relevant tests from Cocoa, so hopefully this is now correct.
> Don't apply schema changes other than setting the schema version in read-only mode

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
This PR changes where/how we handle errors while processing/applying bootstrap changesets in FLX sync mode. The old way relied on calling `on_integration_error()` and doing the normal download processing error handling. Apparently that didn't work because all that error handling assumed you were actually connected to the server and had a bunch of invariants that would fail. This changes things around a bit to handle the special case of a bootstrap error happening before we've connected/sent the BIND/IDENT messages.
> Properly handle exceptions thrown during bootstrap application before bind/ident

- src/realm/object-store/shared_realm.hpp
The function was deleted in https://github.com/realm/realm-core/commit/a1812736201fb19ba681011366d0fb7a53603217, but the declaration was orphaned in the header.
> Remove Realm::file_format_upgraded_from_version() from header

- .gitignore
- CHANGELOG.md
- tools/build-apple-device.sh
Jenkins iOS builds were failing because the SDKROOT variable was already set to a MacOS SDK.
When running tools/build-apple-device.sh, the script will now unset the SDKROOT env variable and validate that the DEVELOPER_DIR env variable is set to a valid directory.
> Fix Jenkins iOS builds

- CHANGELOG.md
- src/realm/query_expression.hpp
This was a bug Introduced in https://github.com/realm/realm-core/pull/5663.
Dereferencing an empty optional is undefined behaviour. It didn't seem to manifest except in our Windows x64 Debug builds.
> Fix undefined behaviour dereferencing an empty optional

- evergreen/config.yml
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- test/object-store/CMakeLists.txt
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
This makes it so evergreen object-store tasks run with debug-level logging turned on so that we can see exactly what was happening when a test failure occurs. I've made some adjustments to exactly what gets logged at trace vs debug to get the most info possible here, but it looks like at debug we don't add significant enough overhead to cause tests to fail/time out just because of logging.
> Run object-store tests with debug logging by default

- src/realm/string_data.hpp
This made `object_store::Dictionary::get_any(size_t)` ambiguous with the `StringData` overload.
* ~[ ] 📝 Changelog update~
* ~[ ] C-API, if public C++ API changed.~
> Delete deleted implicit conversion from int to StringData

- CHANGELOG.md
- src/realm/object-store/collection_notifications.cpp
- src/realm/object-store/collection_notifications.hpp
- test/object-store/object.cpp
* ~~[ ] C-API, if public C++ API changed.~~ C-API already has `realm_free` as an explicit deleter call. This change is more necessary when directly binding GC language objects to the C++ API. That said, a C-API version can easily be added if it would be helpful.
> Add NotificationToken::unregister()

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/object.cpp
- test/object-store/c_api/c_api.cpp
Expose `Obj::add_int()` in the CAPI.
FIxes: https://github.com/realm/realm-core/issues/5763
> expose Obj::add_int in the CAPI

- test/object-store/benchmarks/object.cpp
- test/object-store/benchmarks/results.cpp
Object store benchmarks are failing compiling on evergreen, as result stable builds are failing.
> Fix compilation problems with object-store-benchmarks

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/types.hpp
- test/object-store/c_api/c_api.cpp
Expose realm support for async transactions in the C API.
Fixes: https://github.com/realm/realm-core/issues/5771
> Expose async transaction support in the C API

- CHANGELOG.md
- src/realm/sync/changeset.cpp
- src/realm/sync/changeset.hpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_encoder.hpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/noinst/server/server_history.cpp
- src/realm/sync/tools/apply_to_state_command.cpp
- src/realm/sync/transform.cpp
- src/realm/sync/transform.hpp
- test/peer.hpp
- test/sync_fixtures.hpp
- test/test_changeset_encoding.cpp
- test/test_sync.cpp
- test/util/unit_test.cpp
- test/util/unit_test.hpp
While looking into how to resolve the QoS inversions caused by the sync client, I refreshed my memory on what exactly the sync client even needs to be writing and noticed a few easy spots to make it better behaved.
The sync protocol supports tables without primary keys by effectively synthesizing primary keys using the combination of the local key and the client file ident. We don't know what the client file ident is until we connect to the server for the first time, so this requires rewriting the stored transaction logs to add the client ident. BaaS doesn't support this at all, so we want to skip the rewriting in normal usage and only enable it for compatibility with all of the existing sync tests. Long-term we should probably migrate the sync tests to using primary keys and drop this …
> Reduce the amount of work the sync client does while holding the write lock

- src/realm/table.cpp
- src/realm/table.hpp
This will prevent re-compilation of all test files when updating the interface to index, which should be internal only. It has the consequence that we have to remove inlining of Table constructors, but that is probably not a bad thing either. The header file was included when we introduced smart pointers to hold the indexes.
> Remove inclusion of index_string.hpp from table.hpp

- CMakeLists.txt
- test/object-store/sync/app.cpp
We hit 1661896476 a few hours ago so now the test creating a JWT token with that as an expiration date is failing. I bumped it to be valid for another 10 years. I also enabled the relevant catch2 option to have the failing test print:
```
test/object-store/sync/app.cpp:76: FAILED:
REQUIRE_FALSE( error )
with expansion:
!AuthError: invalid custom auth token: token is expired
```
instead of 
```
../test/object-store/sync/app.cpp:76: FAILED:
REQUIRE_FALSE( error )
with expansion:
!{?}
```
> Bump the expiration date on a jwt token used in a test

- CHANGELOG.md
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
When terminating sync as part of our client reset tests, we need to wait for sync to actually terminate before we can re-enable it. This change adds a new API for querying whether sync is terminated and makes the client reset test harnesses wait for it to report sync being fully terminated.
~* [ ] 🚦 Tests (or not relevant)~ The test here is whether all our failing tests pass again.
> Detect sync termination with new endpoints

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
This is a stop-gap fix for #5705 that makes it so that downloading a fresh realm waits for download completion when handling a client reset with FLX sync. @ironage  is there anywhere else that we'd need to add a wait_for_download_completion?
~* [ ] 🚦 Tests (or not relevant)~
~* [ ] C-API, if public C++ API changed.~
> Wait for download completion when downloading fresh FLX realm in client reset

- test/object-store/sync/sync_test_utils.cpp
The client reset test harness relies on finding a recently added object in the backend before continuing. For the test "a Realm can be reset twice" this object already exists from the first reset, so we also need to wait for an expected field value to persist before continuing.
This should fix the following test failure:
```
[2022/09/02 20:09:12.901] 7.759 s: sync: client reset
[2022/09/02 20:09:12.901] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022/09/02 20:09:12.901] realm-object-store-tests is a Catch2 v3.0.1 host application.
[2022/09/02 20:09:12.901] Run with -? for options
[2022/09/02 20:09:12.901] -------------------------------------------------------------------------------
[2022/09/02 20:09:12.901] sync: client reset
[2022/09/02 …
```
> fix a race in the test 'a Realm can be reset twice'

- CHANGELOG.md
- doc/protocol.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
- test/test_sync.cpp
The sync protocol is updated such that JSON_ERROR messages can be sent from client to server too. The sync client sends error messages when remote changesets cannot be integrated.
This is part 2 of error handling v2.
> Send client integration errors to the server

- tools/run-tests-on-exfat.sh
I noticed that sometimes the new exFAT tests [recently added](https://github.com/realm/realm-core/pull/5806) to CI are failing ([example](https://evergreen.mongodb.com/task/realm_core_stable_macos_release_test_on_exfat_c3b8e14a5f6b0d8dc7f655a8ac5ca040dc35beda_22_09_06_16_07_15)) with out of disk space errors such as:
`[2022/09/06 18:45:09.158] Thread[05]: /System/Volumes/Data/data/mci/3bb701c34a8c7885799a55fd63607d5f/realm-core/test/test_sync.cpp:4845: ERROR in Sync_VerifyServerHistoryAfterLargeUpload: Unhandled exception realm::OutOfDiskSpace: write() failed: No space left on device`
I think happens because we are running several tests that use a lot of disk space together in parallel. The fix is to use one test thread.
> Fix sometimes running out of disk space when running exFAT tests on CI

- evergreen/config.yml
I've noticed that the evergreen ASAN builds do not have symbolized stacktraces - which is deeply unhelpful for using them to actually diagnose what went wrong. This just passes the correct path to the llvm-symbolizer to ASAN on ubuntu so that we get nice stacktraces. It also makes it so that if you run just the object-store tests in an evergreen patch build, only the object store tests will be compiled.
~* [ ] 🚦 Tests (or not relevant)~
~* [ ] C-API, if public C++ API changed.~
> Supply symbolizer for ASAN builds on Ubuntu

- CHANGELOG.md
- src/realm/object-store/impl/apple/external_commit_helper.cpp
- src/realm/object-store/impl/apple/external_commit_helper.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/epoll/external_commit_helper.cpp
- src/realm/object-store/impl/epoll/external_commit_helper.hpp
- src/realm/object-store/impl/generic/external_commit_helper.cpp
- src/realm/object-store/impl/generic/external_commit_helper.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/object-store/impl/transact_log_handler.hpp
- src/realm/object-store/impl/windows/external_commit_helper.cpp
- src/realm/object-store/impl/windows/external_commit_helper.hpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/results.cpp
- test/object-store/sync/flx_sync.cpp
On Apple platforms, waiting on a condition variable does not support donating the waiting thread's priority to the thread doing the work, as the OS doesn't know what thread will notify the CV. This can result in stalls from QoS inversions where a high priority thread is waiting on a low priority thread to complete work, but the low priority thread doesn't get scheduled.
Instead of using a condition variable, we now guard `run_async_notifiers()` with a mutex. If notifiers aren't ready, we try to acquire the mutex on the advancing thread. If the background thread is actively running the notifiers, this'll block and donate the advancing thread's priority and time slice to the background thread. If it's not, then we just call `run_async_notifiers()` on the current thread.
Updating the tests …
> Handle collection notifiers not being ready in a QoS-friendly way 

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/object.cpp
- src/realm/object-store/c_api/query.cpp
Fixes: https://github.com/realm/realm-core/issues/5837
> Expose `Obj::get_parent_object` in the C API

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/object_schema.cpp
- src/realm/object-store/object_schema.hpp
- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/schema.cpp
- test/object-store/sync/flx_sync.cpp
Do not allow asymmetric tables in schemas when using partition based sync.
Fixes #5691.
> Do not allow asymmetric tables in pbs

- CHANGELOG.md
- src/realm.h
- src/realm/list.hpp
- src/realm/object-store/c_api/list.cpp
- src/realm/set.hpp
- test/object-store/c_api/c_api.cpp
- test/test_set.cpp
Fixes:  https://github.com/realm/realm-core/issues/5842
> Expose `list_find` in the c api

- CHANGELOG.md
- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/collection.cpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/obj.cpp
- src/realm/obj_list.hpp
- src/realm/object-store/impl/deep_change_checker.cpp
- src/realm/query.cpp
- src/realm/query_expression.cpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/table_cluster_tree.cpp
- src/realm/table_tpl.hpp
- src/realm/table_view.cpp
- src/realm/utilities.hpp
- test/test_table.cpp
This change is for readability. Whenever I come across this pattern in the code I have to look up what true and false means contextually. Having a verbose type makes it easier to see what is going on without this mental indirection.
> Traversal functions use IteratorControl values rather than true/false

- CHANGELOG.md
- evergreen/install_baas.sh
With baas being updated to use go 1.18.6, the install_baas.sh script has been updated to download and use go 1.18.6.
Fix for https://github.com/realm/realm-core/issues/5862
> Update install-baas to use go 1.18.6

- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/c_api/util.cpp
The former check did not work.
dynamic_cast<> to `WrapC` on a pointer that is already a `WrapC` is a null operation.
> Improve type check when casting to WrapC

- CMakeLists.txt
- src/realm/obj.hpp
- src/realm/table_view.cpp
- test/object-store/benchmarks/results.cpp
On non-Apple arm64 `int64_t` is `long`, so `set_all(1LL)` is invalid as it calls the nonexistent `Obj::set<long long>()`.
This also fixes some arm64+gcc specific warnings which I noticed while tracking this down.
> Fix linker errors when building OS benchmarks on non-Apple arm64 

- CHANGELOG.md
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/c_api/schema.cpp
- src/realm/query_conditions_tpl.hpp
- src/realm/table_view.cpp
- test/object-store/results.cpp
Results accidentally allowed aggregating a collection of collection properties as long as those collections stored aggregateable types, with nonsensical results as it aggregated the refs.
> Add some missing validation for aggregation on collection properties

- CHANGELOG.md
- src/realm/global_key.hpp
- src/realm/object-store/sync/mongo_collection.cpp
- src/realm/object-store/sync/mongo_collection.hpp
- test/object-store/sync/app.cpp
- test/object-store/util/baas_admin_api.cpp
When upserting into a mongo collection, the code expected that the type of the `upsertedId` was always `ObjectId` when in fact it should be the same as the primary key (i.e, `_id`). This PR addresses that.
Fixes #5345.
> Fix crash when upserting into mongo collection

- CHANGELOG.md
- evergreen/config.yml
CI test runs were intermittently failing during the `compile` stage on the `windows-x64-vs2019` variants due to incompatible git and Cygwin versions. These variants are running Windows Server 2016, which has been EOL'ed.
Updated evergreen config to use the `windows-vsCurrent` variants, which are running Windows Server 2019. The version of Visual Studio remained at VS 2019.
Also added `exec_timeout_secs` parameters to tasks where they were missing, since the legacy evergreen UI showed a warning that this parameter was missing and the 6hr default is being used.
> Update Windows distros to vsCurrent to resolve error due to cygwin.dll incompatibility

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- test/benchmark-common-tasks/main.cpp
I noticed in #5163 that dictionary sorting is rather slow and took a stab at improving it.
Dictionary lookup by index is slow, so read all of the keys/values from the dictionary into a vector and sort that instead. Using a dictionary iterator to read the values replaces O(N log N) ClusterTree lookups with O(log N), so this is asymptotically faster. The benchmark is sped up from 3.77 seconds to 21.62 milliseconds, but more reasonably sized Dictionaries will see proportionally smaller benefits.
The downside of this is that the array of Mixed requires 24 bytes of scratch space per element in the dictionary. We already require 8 bytes per element to store the results, so this is just a constant factor increase rather than an asymptotic change in memory use and it's probably not a problem.
> Greatly improve performance of sorting dictionaries

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/util/http.hpp
#5743 added an inclusion of this file to a public header so it needs to be included in the release package.
> Install util/http.hpp

- CHANGELOG.md
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
CollectionNotifier::version() requires holding RealmCoordinator::m_notifier_mutex, which was being violated in a few places.
> Fix a data race in notifier packaging

- test/object-store/sync/flx_sync.cpp
Disable client reset tests while we investigate the websocket disconnect issues.
> Disable FLX client reset tests until websocket issues are resolved

- CHANGELOG.md
- src/realm/object-store/object_schema.cpp
- test/object-store/realm.cpp
- test/object-store/schema.cpp
Fixes https://github.com/realm/realm-core/issues/5894
Mixed in an inherently nullable type. Somehow we allowed collections of nullable Mixed types passed schema validation. If this had happened in a Debug build for Dictionaries users would have seen an obscure debug assertion, and if this had happened in Release mode where the assertion was disabled, the dictionary would be created as nullable anyhow.
> Improve error handling on collections of non-nullable Mixed

- test/object-store/sync/flx_sync.cpp
Point fix. In order to avoid getting warning during CI builds.
> fix warning after client reset test got disabled

- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_lang_bind_helper.cpp
Fixes https://github.com/realm/realm-core/issues/5908
To guarantee that the global `mapping_mutex` is not locked during `fork()` the page reclaimer thread is turned off for this test. It will be turned back on automatically by other tests using encryption because of the idempotent nature of `ensure_reclaimer_thread_runs()` which will be triggered during attempts to access encrypted data.
I ran into a related problem with the page reclaimer not working well across `fork()` in https://github.com/realm/realm-core/pull/5786 so I've extracted the solution I wrote from there.
> Reset page reclaimer on a test using `fork()`

- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_session.cpp
Taking a strong reference to the sync manager in `SyncSession::become_inactive()` can result in the sync manager being destroyed from inside the sync client run loop, which doesn't work. Joining the sync worker thread while on the thread throws `std::resource_deadlock_would_occur`, and detaching instead would just result in use-after-frees as we unwind the stack through a bunch of sync client call frames.
Fortunately `SyncManager::unregister_session()` can be called while holding a lock, so we can just unregister the session before dropping the state lock instead.
This fixes the crash seen in https://spruce.mongodb.com/task/realm_core_stable_ubuntu2004_tsan_object_store_tests_patch_7b087008a19773f1bb92324d410f9e70db17fca9_633765800ae60657c336d99b_22_09_30_21_54_08/logs, which manifested …
> Fix another race when tearing down the sync manager

- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/benchmark-sync/bench_transform.cpp
- test/object-store/sync/flx_sync.cpp
I've been writing tests that need to add more and more hooks into the sync client to be able to deterministically check our state/inject faults, so I decided to unify them into a single hook that takes a struct and an event and returns an action, rather than adding more and more discrete hooks.
> Unify sync client testing hooks

- CHANGELOG.md
- src/realm/object-store/keypath_helpers.hpp
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/keypath_mapping.cpp
- src/realm/parser/keypath_mapping.hpp
- src/realm/parser/query_parser.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/util/serializer.cpp
- src/realm/util/serializer.hpp
- test/test_parser.cpp
Way back in 2014 we had the idea that the new object database SDKs might be used alongside the older language bindings which exposed core's table-based API. The `class_` prefix was something done by the object database SDKs to mark tables which they were using. The query parser was originally written to work in this world, and so supports both object database class names, core table names, and whatever other namespaces we might come up with (we never did).
That's now all just historical cruft and the query parsing and serialization can just always assume that the `class_` prefix is being used. In practice the only call to `set_backlink_class_prefix()` outside of core's tests was in `populate_keypath_mapping()`, which sets it to a hardcoded `class_`.
The modified or deleted tests here are …
> Delete set_backlink_class_prefix() and the serializer options to set the prefix

- CHANGELOG.md
- src/realm/mixed.hpp
- src/realm/sync/changeset_parser.hpp
- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
- test/object-store/util/test_file.cpp
OwnedMixed didn't work (it set the Mixed to the incorrect type and didn't handle copying or moving), and also wasn't actually used in CompensatingWriteErrorInfo. The net result was that every string PK was instead reported as a bool, typically false.
> Fix reporting string primary keys in CompensatingWriteErrorInfo

- test/object-store/util/test_file.cpp
Changes in #5897 made it so we throw an exception and continue running tests after a call to wait_for_session times out instead of immediately calling std::abort. However, when the sync session becomes inactive and all registered notification callbacks get called with an operation_aborted error code, the callback in wait_for_session attempts to acquire a lock on a mutex that was destroyed when wait_for_session threw and the test suite fails with an uncaught std::system_error.
This change makes it so that the callback is operating on state in a weak_ptr so that if the call to wait_for_session times out and we don't care about getting the callback result anymore, we can just ignore it.
> Do not lock destroyed mutex after wait_for_upload timeout

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/sync/sync_session.cpp
`DB::get_encryption_key()` returns a pointer to a buffer owned by the thing which created the DB, which may no longer be valid when we're downloading the new Realm for client reset.
This was hit by the "callbacks are seeded with Realm instances even if the coordinator dies" client reset test when running with encrypt all enabled.
> Fix a use-after-free in client reset when the original RealmCoordinator is gone

- CHANGELOG.md
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/object-store/sync/client_reset.cpp
The path iteration code was missing handling of single link columns.
This could result in an assertion failure during recovery as reported by [internal link](https://jira.mongodb.org/browse/HELP-38625).
```
/Users/realm/workspace/realm_realm-core_release_12.9.0/src/realm/sync/noinst/client_reset_recovery.cpp:525: [realm-core-12.9.0] Assertion failed: col.is_dictionary()
0   Realm                               0x0000000114867c8c _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   Realm                               0x0000000114867b91 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 385
2   Realm                               0x00000001148f07a2 …
```
> Bugfix for client reset with recovery

- src/realm.h
- src/realm/object-store/c_api/object.cpp
The previous implementation was taking a pointer to an object, but we needed a pointer to a pointer instead as we need to store a pointer to the object, not the value itself. Additionally, I've added an extra argument to return the class key of the object as without it, there's no way to meaningfully use the `realm_object` value (the SDK would not know what class materialize it into).
> Fix C-API for realm_object_get_parent

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/util/future.hpp
- test/object-store/sync/app.cpp
- test/object-store/sync/sync_test_utils.hpp
The server sends code 1009 when it receive a message larger than it can process. This is done inside the websocket library so it is impractical for it to send a true "in-band" error message which is how we normally signal client reset cases. Given that an oversized message (typically a giant single transaction) is a "sticky" condition that will keep happening whenever we reconnect, we should treat it as a client reset condition.
> The client sending too much data is now reported as a ProtocolError::limits_exceeded

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- test/object-store/sync/app.cpp
The realm core version is already included in the user agent string when a client opens a websocket with the server, but the server is going to be collecting metrics based on the information sent in the body of the app login request.  Currently, this includes the platform and sdk version information. Add the core version so the server doesn't need to maintain a list of sdk version/core version table to translate the sdk version to the core version. This will also help with reporting to the users whether or not all or what percentage of their clients have upgraded to the sdk version that supports PBS->QBS migrations.
Fixes #5959 
> Added realm core version to app login request

- CHANGELOG.md
- src/realm/object-store/sectioned_results.cpp
- src/realm/object-store/sectioned_results.hpp
- test/object-store/sectioned_results.cpp
If the SectionedResults had been previously evaluated, reset_section_callback() would leave it in an inconsistent state where m_has_performed_initial_evalutation was false but the previous run info was non-empty. #5926 introduced some assertions that now fail when this happens, but I suspect the actual behavior was also broken before that.
> Fix assertion failures after calling SectionedResults::reset_section_callback()

- evergreen/config.yml
Adds an evergreen builder for the core tests with encryption enabled on Windows.
> Run core tests with encryption enabled on windows

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/group_writer.cpp
- src/realm/util/aes_cryptor.hpp
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/encrypted_file_mapping.hpp
- src/realm/util/file.hpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_alloc.cpp
- test/test_group.cpp
- test/test_lang_bind_helper.cpp
- test/test_shared.cpp
- test/util/unit_test.cpp
- test/util/unit_test.hpp
If a read on an encrypted file failed for any reason other than the hmac check failing, we simply ignored the failure and skipped the read. This is required for when we're only reading a page so that we can subsequently write to it and is almost okay the rest of the time, but it resulted in misleading errors in some cases.
I thought this'd have more severe consequences in some scenario, but I was unable to find any. The incorrect error message is something that has tripped up users before (the most common being that a smallish unencrypted streaming-format file would report an incorrect mnemonic rather than a decryption failure)
> Add stricter checks for valid reads on encrypted files 

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
The scenario which deadlocked is the following:
Sync worker thread: Reporting a sync commit made to object store
1. SessionWrapper::report_sync_transact()
2. SyncSession::create_sync_session() wrapped_callback lambda
Holding strong reference to self and acquires SyncSession::m_state_mutex
Calls m_sync_transact_callback while holding the mutex
4. RealmCoordinator::init_external_helpers() sync callback lambda
Acquires strong reference to self, does some work, then releases it, triggering destructor
6. ~RealmCoordinator()
7. ~ExternalCommitHelper()
8. ExternalCommitHelper::m_thread::join()
Waiting for the ECH thread to complete, while holding SyncSession::m_state_mutex
Notifier thread: Trying to report a non-sync commit to sync
1. ExternalCommitHelper::listen()
2. void …
> Fix a deadlock with simultaneous sync and nonsync commit notifications while tearing down RealmCoordinator

- CHANGELOG.md
- src/realm/object-store/audit.mm
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- test/object-store/realm.cpp
- test/object-store/sync/session/session.cpp
- test/object-store/sync/session/session_util.hpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
The intended behavior with async open is that sync errors related to the async open are delivered to the completion callback. This didn't work reliably even in the simplest scenario because we activated the sync session before attaching the download completion handler, so a sufficiently fast error could be received too early. This resulted in the async open completion callback getting called with a generic "operation cancelled" error rather than the correct one.
To fix this, defer calling `revive_if_needed()` until after we've had the chance to call `wait_for_download_completion()` This requires significantly changing where this call happens.
Scenarios where the Realm is being opened on multiple threads at once still aren't guaranteed to report errors correctly. I think that would require …
> Fix a race condition in error reporting for async open

- evergreen/config.yml
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
- test/object-store/util/baas_admin_api.cpp
- test/object-store/util/baas_admin_api.hpp
Talking with @kmorkos, it seems there's always been a narrow race in our PBS tests that some recent changes in the server has exacerbated. We start each client reset test by creating a realm and creating an object in it and then uploading/downloading it, disconnecting, and mutating it while disconnected to create a diverging history with the server. It turns out the translator can pick up our object and then initial sync it back into server history - which in turn deletes/re-creates the object on the client before we can disconnect. This means that when we try to mutate the object to create a diverging local write, we're writing to an object that's been deleted.
The fix is to just wait for initial sync to be fully complete doing any of our local writes.
This can't happen in FLX sync …
> Fix race with translator in PBS client reset tests

- CHANGELOG.md
- evergreen/install_baas.sh
Update `install_baas.sh` to use stitch-support library version 4.4.17 for macos and rhel7
(ubuntu was already at 4.4.17 and macos arm64 is supported by a different version)
Fixes #5989 
> Update install_baas stitch library to 4.4.17

- CHANGELOG.md
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/app_service_client.hpp
Closes #4182
* New function used as implementation for old overloads, so existing coverage should be sufficient
* C-API was already string based. Now it avoids extra parsing and serialization overhead.
> Add App::call_function overload working with raw ejson strings

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
- src/realm/util/checked_mutex.hpp
Change from using a std::recursive_mutex to a CheckedMutex. This helps prevent introducing unintentional deadlocks and brings clarity to the code. There are several [reasons](http://www.zaval.org/resources/library/butenhof1.html) why using a recursive mutex is not a great idea. For this case, the only real need for it was in `DB::compact()` which required reordering a couple things and making a "pre-locked" version of a method.
This was part of https://github.com/realm/realm-core/pull/5786 but I am extracting it here because I think it is worth a PR by itself.
> DB uses a CheckedMutex instead of a std::recursive_mutex

- CHANGELOG.md
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- test/object-store/results.cpp
Fix `Results.distinct(keypaths)` and `Results.sort(keypaths)` not correctly handling keypaths names for properties that have a public/private(column) property name.
This is a fix to enable custom column names in the Realm Swift SDK.
> Fix `Results.distinct(keypaths)` and `Results.sort(keypaths)` not correctly handling keypaths names.

- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/flx_sync_harness.hpp
This is some low hanging fruit from the compensating writes project. We had an error on the server during our initial implementation where the EraseObject instructions sent as part of a bootstrap to make bootstraps idempotent were not in the merge window for uploaded objects. So you could create some objects that conflict with an object on the server and you would end up getting those objects replaced locally, but other realms would get the objects you created - ending up with diverging histories.
This was fixed as part of the server-side compensating writes project and this change just adds an integration test to make sure it works and we catch any future breakage.
> Add test case for OT-ing across a bootstrap

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
Adds a typedef for `realm_app_call_function` callback function. This is required because `SWIG` in the Kotlin SDK cannot map it properly to a Java type.
> Add typedef for realm_app_call_function callbacks

- test/object-store/sync/app.cpp
This test has started failing. Likely due to server changes discussed in https://github.com/realm/realm-core/pull/5986.
The test was wrong to compare object keys (and table keys) across different Realms as those are internal values. The fix is to compare by linked table name and linked primary key instead.
Fixes this failure:
```
[2022/11/04 16:35:40.346] 3: -------------------------------------------------------------------------------
[2022/11/04 16:35:40.346] 3: app: mixed lists with object links
[2022/11/04 16:35:40.346] 3: -------------------------------------------------------------------------------
[2022/11/04 16:35:40.346] 3: /System/Volumes/Data/data/mci/7fe61e07991afa19bd95c327a80373bc/realm-core/test/object-store/sync/app.cpp:1572
[2022/11/04 16:35:40.346] 3: …
```
> Compare linked pk instead of object key in test

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- test/CMakeLists.txt
- test/object-store/sync/flx_sync.cpp
- test/test_sync_pending_bootstraps.cpp
This fixes an issue where bootstraps are not properly broken up into batches - so if you get a really big set of data in a bootstrap, it can end up being applied all in one transaction. This also adds a unit test for this to make sure we don't regress.
This adds some statistics to the pending bootstrap store and more logging to help with debugging problems with large bootstraps.
Finally, the size of a bootstrap batch is configurable in the SyncConfig, but still defaults to 1MB of changeset data per batch.
> Fix bootstrap changeset batching

- evergreen/install_baas.sh
Baas has upgraded to go 1.19 and the object-store tests are failing because we cannot start the baas server with go 1.18.6 anymore.
> Upgrade golang used by baas to 1.19.1

- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/app_service_client.hpp
This makes it easier to bind to since you can use normal nullable pointer logic, rather than needing a special case for empty string.
Follow-up to #5984.
* ~~[ ] 📝 Changelog update~~ Modification of something not yet released, or consumed by any SDK
> use a null pointer rather than empty string for error case in App::call_function callback

- evergreen/config.yml
- src/realm/util/file.cpp
Avoid to call explicit full sync barrier if F_BARRIERSYNC is not available (exFat filesystems). Since `msync` should be already enough. 
On exFAT, a full barrier is actually introducing a deadlock and stalling the sync threads, while one thread is writing and falling back to a full barrier the other is actually syncing dirty pages. 
I removed the barrier and ran the sync tests without it on exFAT, and all of them passed.
```
thread #3
[2022/11/10 10:48:51.778]     frame #0: 0x00007fff2047cc8e libsystem_kernel.dylib`__fcntl + 10
[2022/11/10 10:48:51.778]     frame #1: 0x00007fff2047cc47 libsystem_kernel.dylib`fcntl + 170
[2022/11/10 10:48:51.778]     frame #2: 0x000000010f49826f realm-sync-tests`realm::util::File::sync() + 31
[2022/11/10 10:48:51.778]     frame #3: 0x000000010f340071 …
```
> Do not revert to full sync barrier for exFat, in order to avoid deadlocks

- test/object-store/sync/app.cpp
Since an app is not being created on the server for the "app: app destroyed during token refresh" test, the websocket connection would occasionally receive a 404 response while attempting to connect, which causes the test to fail. The test quickly creates a session, requests token refresh and then closes the session, but sometimes, the websocket attempts to connect to a "fake app" on the server, which returns a 404 (not found) response back to the client.
This fix adds a custom error_handler to this test to ignore websocket errors while still printing and aborting the test when other errors are received.
Fixes #6013
> Fix failing "app destroyed during token refresh" test

- test/object-store/sync/flx_sync.cpp
The test has been removed because currently there is way to update/replace an asymmetric object (i.e, the server does not allow it treating it as a no-op).
> Remove test since replacing asymmetric objects is a no-op

- CHANGELOG.md
- src/realm/object-store/sync/sync_user.cpp
- test/object-store/sync/app.cpp
It was possible that while the profile of a user was fetched from the server, the user logged out causing an assertion crash.
This PR addressed that by making some methods a no-op if the user is not logged in anymore.
Fixes #5571.
> Turn methods into no-op if the user logged out

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/table.hpp
- test/test_parser.cpp
I verified that this works with realm-js on top of bindgen, which is using this API. Previously [this test](https://github.com/realm/realm-js/blob/c2fba8876c0b12025a531597eaa7f3d127632fc5/integration-tests/tests/src/tests/queries.ts#L122) was failing (note that JS uses varargs for query args, so mentally add an extra layer of vector wrapping).
> Use a variant for query args so we can distinguish scalars from single-element lists

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/list.cpp
- test/object-store/c_api/c_api.cpp
This expose `List::move` on the C-Api. Needed for https://github.com/realm/realm-dart/issues/794
> Add realm_list_move to c-api

- CHANGELOG.md
- evergreen/config.yml
- src/realm/util/file.cpp
> Restore barrier on exfat

- CHANGELOG.md
- src/realm/group_writer.cpp
- test/test_compaction.cpp
Wrong value for the size of the top array was used because values were added after the sizes were calculated. Now the decision to compact the realm is moved to a point before the sizes are calculated so that the correct top array size is used. The reason for moving the logic to the point after the calculation of the sizes was to use an updated values for the free space size - mostly in order to get a test passing, but that was obviously a wrong decision.
> Fix corruption of freelist during compaction

- src/realm/exec/CMakeLists.txt
- src/realm/exec/realm_enumerate.cpp
- src/realm/table.cpp
Introducing a utility to convert Realm files to use enumerated columns. This enables us to check the space savings of a Realm if it were to use the string enum type. It can also double as a compaction utility if the threshold parameter is set to 0 or less.
> RealmEnumerate tool

- CHANGELOG.md
- src/realm/object_id.cpp
- src/realm/object_id.hpp
- test/test_object_id.cpp
My main motivation for adding the `StringData` constructor was to match the APIs of `UUID` and `Decimal128`. This will let me remove the special case at https://github.com/realm/realm-js/blob/64dd59e6df591fa0e28bc80d3cc417a228f51da1/packages/bindgen/src/templates/node.ts#L315-L321
I made the constructors explicit both because it caused an ambiguity in `bson.h`, but also because it seems like the right thing to do. The implicit conversions don't seem like a good idea here, especially from arbitrary strings. If somebody _really_ wants the conversion from `std::array<uint8_t, 12>` to be implicit, I can bring that one back, but it doesn't seem useful to me.
> Make ObjectId ctor explict and take StringData rather than const char*

- src/realm/group_writer.cpp
- test/test_compaction.cpp
This will enable a test that was previously disabled.
The problem with the test was that the compacted realm was still bigger than expected. This was because the free space size used in the algorithm was way smaller than what was actually free, so the used space size was way bigger, which resulted in the evacuation point being too high.
> Trim algorithm for determining evacuation point

- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/realm.hpp
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/c_api/types.hpp
This actually implements a viable API for consuming object store thread events.
Actually
Fixes: https://github.com/realm/realm-core/issues/5966
> C API expose a suitable API for listening to thread observer events

- CHANGELOG.md
- src/realm/util/aes_cryptor.hpp
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/encrypted_file_mapping.hpp
- test/test_file.cpp
Failing to decrypt a block that has not been written to is not necessarily a problem if it is above the logical file size.
Fixes https://github.com/realm/realm-swift/issues/8030
> Loosen checks when reading an encrypted file

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/realm.cpp
- test/object-store/c_api/c_api.c
- test/object-store/c_api/c_api.cpp
This fixes `realm_refresh` so it properly returns the result of the operation and also properly returns error conditions
This also fixes `realm_compact` to actually do a compaction even if the caller does not care for the result by not providing a `did_compact` argument.
> [C-API] fix refresh and compact

- src/realm.h
In `realm_app_email_password_provider_client_call_reset_password_function`, not specifying the callback parameter name leads to SWIG not matching the text for wrapper generation for the Kotlin SDK. This PR simply adds the parameter name for the callback for `realm_app_email_password_provider_client_call_reset_password_function`.
Needed for https://github.com/realm/realm-kotlin/issues/744
> Add the callback parameter name to the reset function definition

- CHANGELOG.md
- src/realm/object-store/c_api/realm.cpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/6075
> Refresh callback not invoked if the realm is already at the latest version

- src/realm/util/basic_system_errors.cpp
- src/realm/util/http.cpp
The C++ SDK with reuse the networking stack that sync relies on when using Android. I found a few gotchas along the way:
- HTTP parser looks for "Content-Length" in a response, but the `realm.mongodb.com` endpoint returns this as all lower case so this needed to be handled.
- `basic_system_errors` required additional header guards to let `strerror_r ` use the correct branch.
> Add support for Android using C++SDK

- test/object-store/c_api/c_api.cpp
Fixes a flakey test introduced in https://github.com/realm/realm-core/pull/6103.
> Make sure compensating writes are in the right order in test

- CHANGELOG.md
- src/realm/status.hpp
- src/realm/sync/client.cpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/network/network.cpp
- src/realm/sync/network/network.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/sync/socket_provider.hpp
- src/realm/sync/trigger.hpp
- test/benchmark-util-network/main.cpp
- test/test_util_network.cpp
- test/test_util_network_ssl.cpp
First pass at new DefaultSocketProvider that owns the network::Service object. With these changes, the WebSocket and event loop updates can continue in parallel. The Timers have been updated to SyncTimer classes and the get_service().post() calls have been updated to pass the call to DefaultSocketProvider.
The event loop thread is still owned by the Sync Client and the old WebSocket connect path is still in place. These will be updated later. Triggers have not been touched since these will be updated in a different review.
Fixes #5450 #6124
> Create DefaultSocketProvider class

- CHANGELOG.md
- doc/CHANGELOG_template.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/app.cpp
- test/object-store/util/baas_admin_api.hpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
Add new sync connection parameters that allow the sdk to indicate additional metrics information regarding the device where realm is running.
SDK breaking changes:
* Device information in sync connection parameters was moved into a new `device` structure in App::Config
* `sdk` is now a required field in the `device` structure in App::Config
Fixes #6029
> Normalize sync connection parameters

- CHANGELOG.md
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/socket_provider.hpp
The app services request ID is super useful for correlating sync client problems with server logs, but we currently only log it in trace level output of all the HTTP headers we receive. This punches a hole in our websocket implementation to log the request id at the info level when the sync client connection gets connected.
In #6142 we'll move this information in-band so we don't need to access the HTTP headers to get this, since not all websocket implementations expose this info. However, for now, it's very helpful to debug customer issues so I think exposing this implementation detail is worth it.
> Log app services request ID at info level on connection

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/version_id.hpp
- test/benchmark-common-tasks/main.cpp
- test/object-store/benchmarks/object.cpp
Acquiring the file lock which guards the lock file is an expensive operation which dominates the runtime of creating a new Transaction. To avoid doing that when possible, this makes it so that we only update the lock file when transitioning between zero and one of each lock type, and all other refcounting is done purely in memory.
This replaces a file lock with a much cheaper local mutex whenever we already have a read lock of that type for the given version (or when releasing, if we still have a read lock of that type). This makes the temporary Transactions used for things like notifications much cheaper.
Benchmark results:
TransactionDuplicate (v13.1.2): 10.52ms
TransactionDuplicate (this): 1.80ms
OS notification delivery (tg/notifier-badversion): 800ms in do_refresh()
OS notification …
> Optimize acquiring and releasing read locks when one is already held

- tools/build-apple-device.sh
The latest Xcode version combos seem to be putting things in a different location in the build folder so I just had to update the paths in `combine_library`. I also removed the Bid special handling, since `librealm.a` merges its object files and `build-cocoa.sh` doesn't take `libBid.a` into account in any case.
Tested in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/release%2F13.2.0/10/pipeline. The original behavior can be seen in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/release%2F13.2.0/8/pipeline.
> Update watchOS paths in build-apple-device.sh

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/conversion.hpp
- src/realm/object-store/c_api/sync.cpp
- src/realm/sync/network/network.cpp
- src/realm/sync/network/network.hpp
- src/realm/sync/network/network_ssl.cpp
- src/realm/sync/network/network_ssl.hpp
- test/client/peer.cpp
- test/object-store/c_api/c_api.cpp
Added error category for resolve errors (e.g. when no connection or DNS server is unreachable) instead of returning unknown category.
Fixes #6015
> Added c_api error category for resolve errors instead of unknown category

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
This fixes a crash if client reset with recovery is used when flexible sync is enabled and there is only one subscription set defined. For a write-up of how the crash occurs, see [#6070](https://github.com/realm/realm-core/issues/6070#issuecomment-1362218681).
> Fix version corruption during client reset with recovery with a single FLX subscription

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/app.cpp
Update App to support both 301 and 308 redirect response from the server when the deployment model is changed. Also added support to `handle_refresh` to handle the "too many redirects" or redirect response. Updated the App redirect tests to use both 301 and 308 in the simulated http response.
Fixes #6162
> Update App to support 308 redirect response

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.hpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/socket_provider.hpp
Migrated ClientImpl to use a reference to a SyncSocketProvider (instead of DefaultSocketProvider) and integrated changes to match the base class interface. Some temporary additions were made to the base interface to support the DefaultSocketProvider until it is completely integrated with the new interface.
Marked items that will be removed as "deprecated" to start to get the word out that these items will be going away.
Fixes #6165 
> Integrate default socket provider as SyncSocketProvider in sync client

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/migrations.cpp
Point Fix for client reset crashed with `DiscardLocalChanges` set. 
Fixes: https://github.com/realm/realm-core/issues/6144
> Point fix for client reset DiscardLocalChanges crash

- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/array.hpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/history.cpp
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/file.cpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
I'm extracting several changes from the multiprocess encryption branch to declutter it a little bit.
This includes strengthening the debug assertions with more information, and a refactoring around memory mapping files.
No functional changes, so no changelog or tests.
> Refactoring around encryption

- src/realm/exec/CMakeLists.txt
- src/realm/exec/realm2json.cpp
- src/realm/exec/realm_trawler.cpp
- src/realm/sync/noinst/client_history_impl.hpp
Realm2JSON makes a better attempt on using the proper parameters (replication, read-only) to open a realm file.
RealmTrawler can detect enumerated string columns.
> Updates to Realm2JSON and RealmTrawler

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/CMakeLists.txt
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/schema.cpp
- src/realm/object-store/c_api/socket_provider.cpp
- src/realm/object-store/c_api/types.hpp
Extend the C API so SDK's can provider their own platform specific implementation of websockets and event loop.
Fixes #5917.
> C API for custom websocket

- CHANGELOG.md
- test/test_metrics.cpp
Update the `Metrics_TransactionTimings` so it doesn't check the fsync timing if sync to disk is disabled. The test is looking for an fsync time greater than 0 and this value will be 0 if sync to disk happens to be disabled (by another concurrent test) when this test runs. The `for()` loop in this test already checks to see if sync to disk is disabled before checking the fsync timing value, but the last fsync check was always checking the value.
Fixes #6164
> Fix failures in Metrics_TransactionTimings core test

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
When we start a client reset with recovery we insert an object into the realm to track whether we've already started a client reset with recovery so that if the client reset fails (say because we recover local changes that cannot be applied to the server) we don't end up in an endless loop. Previously we cleared this tracking tombstone when we received a download message that [advanced the upload progress](https://github.com/realm/realm-core/blob/42e3abcd4d9cf9aca8bf3b4a35924736ad1902b4/src/realm/sync/noinst/client_history_impl.cpp#L823) - the idea being that if the server acknowledged our client reset with a download ack then the recovered changes must have been valid.
It turns out that if client reset with recovery doesn't actually recover anything, then there's nothing for the server …
> Reset client reset cycle detection after upload/download complete

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/tools/apply_to_state_command.cpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
- test/object-store/sync/flx_sync.cpp
- test/test_sync.cpp
In flexible sync, history can diverge if writes occur during bootstraps. Only writes to objects that come into/go out of view are affected. This happens because each side (client & server) sees their write as the most recent one.
In this PR, bootstrap changesets are applied and committed continuously without releasing the write lock so the user cannot commit their changes until bootstrap is done.
Fixes [#5804](https://github.com/realm/realm-core/issues/5804).
> Continuously apply bootstrap changesets without releasing the write lock

- CHANGELOG.md
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/object_accessor.hpp
- src/realm/object-store/object_store.cpp
- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/migrations.cpp
- test/object-store/object.cpp
- test/object-store/realm.cpp
Rather than tying this to the Additive schema mode, make it an option which can be used with all applicable schema modes. It turns out that adding additional properties to the end of persisted_properties does cause problems, as it makes `Object::create()` expect values for those properties. However, we do (sometimes) want the additional tables to be added to the schema and not just in Additive mode, so that's a separate option.
This also fixes several bugs in the implementation which would result in it failing to actually have a complete view of the schema in some cases, and could result in frozen Realms having an incorrect schema.
This also incidentally improves the performance of freezing Realms as part of the fix for the schema management and fixes a few race conditions related to …
> Make getting a complete view of the schema optional

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/client_reset.cpp
This changes the `SyncSession::download_fresh_realm()` function to use the `SyncManager` to handle the lifetime of the sync session of the fresh realm. This should make it so that if we need to re-open the fresh realm after an aborted attempt, there should already be a `SyncSession` available to re-use (and we won't accidentally try to open a new sync session that will conflict with any existing ones).
> Client reset w/recovery can throw a MultipleSyncAgents if interrupted during the fresh realm download

- CHANGELOG.md
- src/realm/sync/client.cpp
- test/object-store/sync/flx_sync.cpp
This fixes the sync client so that if it receives a FLX bootstrap changeset larger than what can fit into a BinaryColumn, it treats that as a bad_changeset_size error and fails gracefully rather than crashing the process.
> Make sure very large changesets in bootstraps do not crash the sync client

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
This turned out to not be the source of the problem I was looking in to, but `get_realm(config, VersionID())` does strange and invalid things that appears to work in simple cases but can cause weird problems. VersionID() is turned into an actual version only when acquiring a read lock, and won't turn into the same version every time for a given frozen Realm.
> Fix an invalid use of frozen Realms in client reset

- CHANGELOG.md
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
- test/test_util_logger.cpp
- test/util/unit_test.cpp
When the log level threshold was updated to be atomic, the `IntraTestLogger` was updated to provide its own log level threshold, but this value was not being used properly by subsequent loggers that were linked to this object. An instance of the `IntraTestLogger` is used by each of the test threads in a unit test run to prevent changes in one thread from affecting the other threads, but they all print out using a single root logger (protected by a `ThreadSafeLogger`) that is created when the test is started.
Fix the level threshold in the `IntraTestLogger` so it has its own atomic log level threshold that is used by linked loggers.
Fixes #6233 
> Fix default enabled debug output during realm-sync-tests

- CHANGELOG.md
- Jenkinsfile
- Package.swift
- src/realm.h
- src/realm/error_codes.hpp
- src/realm/object-store/CMakeLists.txt
- src/realm/object-store/c_api/realm.cpp
- src/realm/object-store/c_api/realm.hpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/sync/CMakeLists.txt
- src/realm/sync/binding_callback_thread_observer.cpp
- src/realm/sync/binding_callback_thread_observer.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/socket_provider.hpp
- test/benchmark-sync/bench_transform.cpp
- test/sync_fixtures.hpp
- test/test_handshake.cpp
- test/test_sync.cpp
Migrate the `network::Service` object from `ClientImpl` to `DefaultSyncSocket` and update operation so the event loop thread is no longer owned by `SyncClient`. Update `realm-sync-tests` to work with the new scheme.
The `BindingCallbackThreadObserver` class and global variable was moved from _src/realm/object-store_ to _src/realm/sync_.
First set of updates for #5448
> Migrate service and event loop into DefaultSyncSocket

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/dictionary.hpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/6181
> Expose more dictionary APIs in the C API

- CHANGELOG.md
- src/realm/error_codes.cpp
- src/realm/error_codes.hpp
- src/realm/object-store/c_api/socket_provider.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/websocket.cpp
- src/realm/sync/network/websocket.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/socket_provider.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/util/test_file.hpp
- test/test_sync.cpp
Remove the deprecated callbacks in`WebSocketObserver` and update `ClientImpl::Connection` and `DefaultWebSocketImpl` to use the ones according to the websocket rfc.
Fixes #6094.
> Update Connection and DefaultWebSocketImpl to use the new WebSocketObserver callbacks

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
The work limit could wrap around resulting in an unlimited run, which could take a long time to finish.
> Fix handling of work limit in online compaction

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/notifications.cpp
- test/object-store/c_api/c_api.cpp
Dictionaries don't seem to be obeying to the same semantics we have for Lists and Sets (https://github.com/realm/realm-core/issues/6205). It does not seem to me, we have a sync protocol message for it. Probably a quick hack is to raise some sort of "dictionary cleared" event and set the flag accordingly. 
Fixes: https://github.com/realm/realm-core/issues/6200
> Expose collection cleared flag

- CHANGELOG.md
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- test/object-store/collection_fixtures.hpp
- test/object-store/primitive_list.cpp
- test/test_set.cpp
- test/util/unit_test.hpp
Now that Set<Mixed>'s on-disk storage order doesn't match our sort order, Set<Mixed>::sort() needs to actually sort the items rather than being a no-op. It remains a no-op for other types of set.
Adjusting the data used for tests to test this also revealed that Lst::distinct() picked an arbitrary value of the equal ones rather than the first. This isn't necessarily incorrect, but it makes testing distinct more complicated and can have surprising results when the collection isn't sorted. Making it always use the first is simple and doesn't add any overhead, so it now does that.
I took a stab at instead making it so that Mixed::compare() uses Set<Mixed>'s comparison rules, but it quickly became obvious why #5607 didn't do that as there's some pretty reasonable things that rely on the …
> Actually sort in Set<Mixed>::sort()

- CHANGELOG.md
- src/realm/util/features.h
Add macros to more easily distinguish ARM targets across targets.
> Add REALM_ARCHITECTURE macros for ARM architectures

- CHANGELOG.md
- Package.swift
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- src/realm/array_decimal128.cpp
- src/realm/array_decimal128.hpp
- src/realm/decimal128.cpp
- src/realm/decimal128.hpp
- test/test_decimal128.cpp
> Optimize size of ArrayDecimal128

- CHANGELOG.md
- src/realm/object-store/c_api/socket_provider.cpp
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/client_base.hpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/socket_provider.hpp
- src/realm/util/buffer_stream.hpp
- test/object-store/sync/app.cpp
- test/sync_fixtures.hpp
- test/test_sync.cpp
- test/test_sync_history_migration.cpp
This makes it so you can destroy a sync Client without having to destroy or even stop the run loop its using for network I/O, timers, and other asynchronous callbacks. The event loop the sync client is running on must be running in order to tear down the sync client successfully, but the sync client no longer needs to be able to control the event loop or wait for it to stop to safely stop itself.
I've also made a few other minor changes in support of the larger change:
- replace the use of `util::Mutex`/`util::CondVar` in the sync client with `std::mutex`/`std::condition_variable`.
- move the creation/lifetime of the `DefaultSocketProvider` out of the sync client itself and into the object store wrapper for the sync client
- the `SyncSocketProvider` `connect()` method now takes a …
> Separate lifecycle of sync Client from its websocket provider

- test/benchmark-sync/bench_transform.cpp
This updates our sync benchmarks to detach any sessions before explicitly stopping/draining their associated sync clients. I updated the evergreen build to build/run the benchmarks as part of the testing for this PR.
> Fix sync benchmarks

- src/realm/exec/realm_trawler.cpp
Add a new option "--hexkey \<the-very-long-key\>" to realm-trawler.
This option allows the trawler to get the key to an encrypted realm directly on the command line instead of via a binary file.
> Add handling of hex encoded key to realm-trawler

- CHANGELOG.md
- src/realm/sync/changeset.hpp
- src/realm/sync/transform.cpp
There are errors/exceptions which require help from support. Therefore, such error messages will mention `Please contact support`.
By default, all BadChangesetError's will contain the message above.
Additionally, TransformError's not related to schema will contain the message above.
> BadChangesetError and TransformError notify users to contact support

- CHANGELOG.md
- test/test_metrics.cpp
Revisit the `Metrics_TransactionTimings` test since failures were still being observed as a result of the test.
For now, just disable the failing line and investigate why the final `get_fsync_time_nanoseconds()` check in the test is sometimes returning `0`. Since this is a "non-concurrent" test, there shouldn't be any other tests that are running that could change the disable_sync_to_disk setting.
> Revisit metrics test - update metrics to store whether or not sync to disk was disabled

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- test/object-store/sync/app.cpp
If `metadata_mode` was set to `NoMetadata` the app was not updating the hostname and websocket sync route when the location was requested after a 301/308 redirection occurred. The hostname and websocket sync route is now being updated regardless as to whether or not any app metadata is being saved. It also sets a flag after a successful location request to prevent querying the location again on every request.
Added an object store test to verify the operation.
Fixes #6280
> App 301/308 redirection support doesn't use new location if metadata mode is set to 'NoMetadata'

- src/realm/sync/noinst/client_impl_base.cpp
WebSocket_Fatal_Error error code was never handled. Instead WebSocket_Retry_Error was handled twice.
> Fix wrong handling of WebSocket_Retry_Error

- CHANGELOG.md
- src/realm/db.hpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
Immutable Realms have a fake read lock to make them behave mostly like mutable Realms that happen to not change, but the version on that read lock was VersionID(), which is used as a sentinel value. Switch to using VersionID(1, 0) so that the version read from an immutable Realm appears to be a normal valid VersionID.
Fixes #6260.
> Use a real transaction version for immutable Realms

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
- test/test_client_reset.cpp
This fixes a crash in automatic client resets where there are dangling links in the destination realm (i.e. the realm being client reset). The `transfer_group()` function takes a fresh copy of a realm and transfers a source realm's contents to a target by comparing each property in each object in each table, and creating/setting properties as needed if they don't exist or do not match. If the target table has a list of links where some of them are dangling, and the dangling link targets exist in the source realm, it will create the target objects, thereby resurrecting the dangling link, and end up with duplicate entries in the list. This violates an invariant in the IntraRealmObjectConverter class.
> Re-create all objects before updating their properties during client_reset::transfer_group()

- src/realm/object-store/c_api/socket_provider.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/flx_sync_harness.hpp
E2E C API test using DefaultSocketProvider as custom websocket provider. This tests the existing C API and makes sure everything works as expected.
Fixes #6169.
> [C API] Integration test for websocket provider

- CHANGELOG.md
- evergreen/install_baas.sh
Yarn was failing to download from stitch-artifacts, since it had been moved to Glacier long term storage. Updated download path to use the official yarn download site: https://yarnpkg.com/latest.tar.gz
> Update yarn download path in install_baas.sh

- src/realm/object-store/c_api/app.cpp
Fixes the C-API functions like `realm_mongo_collection_find`, `realm_mongo_collection_find_one` and so on.
The callback can not be found if its pointer is passed by reference. 
It was not handled because the tests in `realm-core` don't call these methods with passing callbacks as arguments.
Related to the implementation in https://github.com/realm/realm-dart/pull/1162
> Pass callback and user data by value in realm_mongo_collection_<func>

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/sync_fixtures.hpp
- test/test_sync.cpp
There's a race when force closing a connection where sessions may still be getting finalized. This makes it so that if there are still any active sessions on a connection, force_close() makes it so that the connection will close as soon as the last session has ended and will skip all the linger period timing.
> Wait for sessions to drain during sync client shutdown

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/benchmark-common-tasks/main.cpp
> Initialize sub-query only once

- src/realm/sync/tools/apply_to_state_command.cpp
ApplyToStateCommand was broken for PBS due to wrong batch state in ClientHistory::integrate_server_changesets.
> Fix ApplyToStateCommand for PBS

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- test/benchmark-sync/bench_transform.cpp
- test/sync_fixtures.hpp
- test/test_client_reset.cpp
- test/test_sync.cpp
These overloads of `sync::Session::bind()` let you override the server info used to connect to sync and were only being used in tests. This PR removes them and adjusts the sync unit tests to match. As part of fixing session multiplexing, there are more factors to consider when choosing a connection than just the server address/port/envelope, and rather than adding the other factors to these functions, I'd rather just remove them and remove the extra mostly unused code.
> Remove non-void overloads of Session::bind()

- CHANGELOG.md
- src/realm/sync/changeset.hpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- test/test_sync.cpp
Once a reciprocal changeset has all its instructions discarded during OT, it is stored as a null changeset in the realm. This makes it hard to differentiate it from a non-existing reciprocal changeset and was causing histories to diverge among clients. A fix was put in place so that an empty reciprocal changeset is indeed saved as an empty changeset in the realm.
Fixes #6191.
> Distinguish between an empty and a null (not existing)  reciprocal changeset

- test/object-store/sync/flx_migration.cpp
Increase the allowed timeout for a FLX->PBS or PBS->FLX server migration to 5 minutes since it sometimes (but rarely) takes longer than the original 90 seconds. Eventually, these tests will most likely be moved to a separate test executable.
> Increase server FLX/PBS migration timeout

- test/test_array.cpp
The `Array_get_sum` core test was failing in the `checkWindows_x86_Release` run on Jenkins CI. Updated test to force x64 integer math.
> Updated Array_get_sum test to force 64bit integers in some instances

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
Setting different loggers on different SyncManagers is something we have exposed in our public API so we need to continue to support it. SyncManager will continue to fall back to `Logger::get_default_logger()` if no logger factory is set.
> Restore the ability to set loggers per-SyncManager

- CHANGELOG.md
- CMakeLists.txt
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
The conversion from SyncError to SessionErrorInfo in this function is incorrect (it drops most of the fields of the SyncError) and it isn't really worth fixing as updating the code using this test hook to just construct a SessionErrorInfo was trivial.
> Remove SyncSession::OnlyForTesting::handle_error(SyncError)

- test/object-store/util/baas_admin_api.cpp
I had a test [fail](https://spruce.mongodb.com/task/realm_core_stable_macos_release_object_store_tests_patch_7eac25f920a7d11255f8c416b1b43cfe1e8c9a06_641c918c61837da0da50f3a5_23_03_23_17_51_10/logs?execution=0&sortBy=STATUS&sortDir=ASC) on an unrelated change in one of these asserts.
There's not much more I can do without knowing the response code and body, so I'm adding this info here in case it happens again.
> verbose asserts in the Admin API

- CHANGELOG.md
- src/realm/parser/driver.hpp
- test/test_parser.cpp
Reported in https://github.com/realm/realm-core/pull/6428
This changes from a recursive call to using an iterative stack for LogicalNodes.
> remove some recursion when parsing chained OR/AND queries

- CHANGELOG.md
- src/realm/object-store/results.cpp
- test/object-store/c_api/c_api.cpp
Throw an exception instead of returning empty Results object
> Fix `Results::is_valid()` for invalid results bound to deleted collections + throw if results is constructed using a deleted object.

- CHANGELOG.md
- src/realm/db.cpp
Access to `m_info` was not guarded by a lock, so one thread could potentially remap it while another thread was reading from it. TSan sometimes catches this running the Swift tests.
> Fix data races in VersionManager

- Package.swift
- src/realm/CMakeLists.txt
- src/realm/collection.hpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/table.hpp
- test/test_links.cpp
- test/test_table.cpp
Fixes #6362 
No functional changes - just a refactoring.
A collection does not use the Obj interface to access its parent object, but rather an interface defined in CollectionParent, which Obj then inherits from. This enables that the parent can be other than Obj.
> Allow Collections to be owned by Collections

- CHANGELOG.md
- src/realm/query.cpp
> Don't crash in Query.count() when table is not defined

- CHANGELOG.md
- src/realm/CMakeLists.txt
- src/realm/sync/CMakeLists.txt
Build would not succeed when consuming core as an installed dependancy due to missing headers on install.
> Fix missing dependencies on install

- test/object-store/sync/app.cpp
We had a sporadic failure on CI with the [report](https://spruce.mongodb.com/task/realm_core_stable_macos_object_store_tests_a16fb7c2e99f3b9941a0155abf662b9489f4f7d9_23_04_06_15_02_19/tests?execution=0&sortBy=STATUS&sortDir=ASC):
```
Assertion failure: /System/Volumes/Data/data/mci/897e431e841ecd7e2626a0a59fc296f0/realm-core/test/object-store/sync/app.cpp:2768
from expresion: 'delay_times[i] > expected_min_delays[i]'
with expansion: '737 (0x2e1) > 740 (0x2e4)'
```
I am changing the test to simply check for increasing delay times instead of relying on internal implementation details of the backoff calculation.
> relax test timing checks

- src/realm/object-store/object_schema.cpp
- src/realm/object-store/object_schema.hpp
- src/realm/object-store/object_store.cpp
- src/realm/object-store/property.hpp
- src/realm/object-store/schema.cpp
- test/object-store/CMakeLists.txt
- test/object-store/migrations.cpp
- test/object-store/nested_collections.cpp
- test/test_list.cpp
Schema support for nesting collection
> Schema support for nesting collection

- src/realm/geospatial.hpp
Use simple placeholder value for center sphere radius instead of std::optional to reduce size of Geospatial type, since initialisation is controlled through constructors anyway.
> Use NaN for GeoPoint

- CHANGELOG.md
- src/realm/object-store/c_api/types.hpp
- src/realm/sync/client.hpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.hpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- src/realm/sync/noinst/client_reset_recovery.hpp
- src/realm/sync/tools/apply_to_state_command.cpp
- test/object-store/object.cpp
- test/object-store/realm.cpp
- test/object-store/sync/migration_store_test.cpp
- test/sync_fixtures.hpp
- test/test_sync_subscriptions.cpp
Installed headers cannot depend on noinst headers as they are not installed. Fortunately it did not actually need it.
> Fix an invalid header inclusion

- CMakeLists.txt
- Package.swift
- src/CMakeLists.txt
- src/realm/CMakeLists.txt
- src/realm/data_type.hpp
- src/realm/mixed.hpp
- src/realm/obj.cpp
- src/realm/object-store/c_api/query.cpp
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/query_parser.hpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- test/CMakeLists.txt
- test/object-store/CMakeLists.txt
- test/test_parser.cpp
Add opt-out REALM_ENABLE_GEOSPATIAL option for cmake to disable the feature code almost completely. Leave only relevant classes fro grammar to raise useful error for RQL with 'geowithin' operator
> Add REALM_ENABLE_GEOSPATIAL cmake option to disable feature

- src/realm/db.cpp
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
As part of adding support for the new logging framework, the SDKs have reviewed the current log output and have a few suggestions for modifications that we think provide a better compromise between verbosity and information needed when debugging at the default level.
Currently, the ide is that all SDKs will set INFO as the default level going forward.
> Adjust log levels to be more SDK friendly

- CHANGELOG.md
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/noinst/client_impl_base.cpp
This fixes the (non) fatal error that is causing an abort when the AuditRealmPool attempts to open a synced realm, but the connection does not complete successfully during the SSL handshake. Any errors that occur during the SSL Handshake are being reported as fatal handshake errors.
This fix brings back the original ssl handshake error handling from before the platform networking changes: https://github.com/realm/realm-core/blob/v13.2.0/src/realm/sync/noinst/client_impl_base.cpp#L1023-L1043
Fixes https://github.com/realm/realm-core/issues/6434
> Fix incorrect error types during SSL handshake

- src/realm/geospatial.cpp
- src/realm/geospatial.hpp
- src/realm/object-store/impl/object_accessor_impl.hpp
- src/realm/util/serializer.cpp
- test/object-store/geospatial.cpp
- test/test_parser.cpp
- test/test_query_geo.cpp
- Fix build without geospatial
-- Bring back compilation of geo queries test which was accidentaly hiden
- Don't force to copy primitives on get<>
- Allow less curly braces for GeoPolygon on init
> Fix test build for geo feature, optimize copying

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- src/realm/transaction.cpp
- test/object-store/results.cpp
This fixes one of the common problems resulting from https://github.com/realm/realm-swift/issues/4818, as it makes it so that adding new callbacks from within a notification callback will _usually_ work even if the notification was triggered by beginning a write transaction. It still will not work if a previously invoked callback made any changes (which would be a very strange thing to do, but possible).
> Allow registering notifiers in write transactions prior to the first change

- Jenkinsfile
We rely solely on the Evergreen lint check now which also runs clang-format.
The Evergreen lint check and the Jenkins format check are running slightly different versions of clang-format which means that it is impossible for some code changes to pass CI because each versions has a different interpretation of what is correctly formatted code. 
Since we intend to eventually move off of Jenkins, I will remove the format check there.
Related to https://github.com/realm/realm-core/pull/6563 where Evergreen's clang-format is updated.
> remove clang-format from Jenkins CI

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
The sync history can be short circuited because it will be discarded right after `transfer_group()`
I made a temporary client reset test that inserted a bunch of large strings on the server state so that transfer_group had to insert them and recorded the memory use before and after using `/usr/bin/time -l ./test/object-store/realm-object-store-tests.app/Contents/MacOS/realm-object-store-tests "sync: client reset" -c "recovery" -c "insert" -d yes`
The amount of memory difference will vary widely based on the actual data, but I take the following improvement from my synthetic test to be an indication of improvement:
Before: `17581760  peak memory footprint`
After:    `13338304  peak memory footprint`
> Reduce the memory footprint of an automatic reset

- CHANGELOG.md
- evergreen/config.yml
Add new tasks to build Realm Core on Ubuntu 22.04 using Clang 16 and run the core and sync tests. Updated the lint task to use this variant as well due to incompatibilities between evergreen and Jenkins lint tasks.
NOTE: I am not running the Object Store tests during this build, since we will likely need some additional helper libraries to run baas and there are no 5.0.3 mongodb variants that are building the stitch support library for Ubuntu 22.04.
> Added CI tests for Clang 16/Ubuntu 22.04

- src/realm/object-store/impl/deep_change_checker.hpp
- src/realm/object-store/shared_realm.cpp
Fix issues reported by UBSAN
* uninitialized variable:
core/src/realm/object-store/impl/collection_notifier.cpp:51:14: runtime error: load of value 152, which is not a valid value for type 'bool'
* nullptr access after invalidate:
core/src/realm/object-store/shared_realm.cpp:136:27: runtime error: member call on null pointer of type 'realm::_impl::RealmCoordinator'
> Fix undefined behaviour issues

- src/realm/collection_parent.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/test_table.cpp
> Refactoring get_path()

- src/realm/array_mixed.cpp
- src/realm/array_mixed.hpp
- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- src/realm/collection_parent.hpp
- src/realm/column_type.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/keys.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/mixed.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/dictionary.cpp
- src/realm/set.hpp
- test/test_list.cpp
Preparation for actually storing a collection in a Mixed property.
> Store ref in ArrayMixed

- Package.swift
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- src/external/s2/CMakeLists.txt
- src/realm/alloc.hpp
- src/realm/collection.hpp
- src/realm/dictionary.hpp
- src/realm/geospatial.cpp
- src/realm/geospatial.hpp
- src/realm/list.hpp
- src/realm/obj.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/set.hpp
- src/realm/util/functional.hpp
- src/realm/util/serializer.cpp
- src/realm/util/serializer.hpp
Some easy size improvements that jumped out at me when looking at the binary size change from adding geospatial in bloaty. Sizes below are the size of the dylib resulting from `./tools/build-cocoa.sh -bmx && lipo -thin arm64 core/librealm-monorepo-macosx.a -output out.a && clang++ -dynamiclib -Wl,-all_load out.a -lcompression -framework Security -lz -o out.dylib`.
The size for Realm.framework (macOS arm64 only) is 7525808 bytes with 13.10.1, and 7542208 bytes with these changes and geospatial queries enabled.
| Commit | Size | Change | Net Change |
| ------ | ---- | ------ | ---------- |
| Initial | 6955960 | 0 | 0 |
| Geospatial Enabled | 7262136 | 306176 | 306176 |
| value_separator | 7240472 | -21664 | 284512 |
| CollectionBaseImpl | 7147400 | -93072 | 191440 |
| Compare | 7122984 | …
> Assorted binary size improvements

- tools/pre-commit
Apply clang-format in pre-commit only for changes staged for commit ignoring changes not intended to be commited
> Apply clang-format only on staged changes

- bindgen/src/context.ts
- bindgen/src/formatter.ts
- bindgen/src/output-directory.ts
This change `file` to take a rest list of `formatter` functions instead of names of pre-registered callbacks.
> `bindgen`: Refactored formatter to take callbacks

- CHANGELOG.md
- src/realm/object-store/results.cpp
- test/object-store/c_api/c_api.cpp
- test/object-store/frozen_objects.cpp
> Fix crash on Results.freeze after owning collection removal

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/sync/flx_migration.cpp
There is a sequence of events where we tried to open a frozen Realm with new object types in the schema and this fails schema validation causing client reset to fail.
- Add a new class to the schema, but use async open to initiate sync without any schema.
- Have the server send a client reset.
- The client tries to populate the notify_before callback with a frozen Realm using the schema with the new class, but the class is not stored on disk yet. This hits the `update_schema()` check that makes sure that the frozen Realm's schema is a subset of the one found on disk. Since it is not, a schema exception is thrown which is eventually forwarded to the sync error handler and client reset fails.
This was discovered during PBS->FLX migration which uses client reset. In particular, when using …
> Fix an error in client reset notifiers when using async open

- CHANGELOG.md
- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
Bump the protocol version to 9 to indicate to the server that the client has the client reset fix when async opening a realm identified in #6601.
Fixes #6609
> Bump protocol to v9 to indicate client has fix for client reset error during async open

- CHANGELOG.md
- src/realm/error_codes.hpp
- src/realm/table_ref.hpp
- src/realm/util/to_string.hpp
We still have some build failures in catch (which hopefully will be fixed by https://github.com/realm/realm-core/pull/6605), but they don't interfere with building the realm lib
> fix missing includes of cstdint surfaced by gcc13

- CHANGELOG.md
- src/realm/sync/protocol.hpp
Update the changelog to include an Enhancement statement about PBS->FLX client migration being supported with this release, and the Realm Core 13.10.0 release is no longer supported.
> Update changelog with PBS->FLX migration support update

- src/external/s2/util/math/mathutil.h
A [recent](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-core/detail/master/2359/pipeline/974/) nightly build failed with this error for watchos simulator:
```
/Users/realm/workspace/realm_realm-core_master/src/external/s2/util/math/mathutil.h:386:13: error: GNU-style inline assembly is disabled
__asm__ __volatile__
^
/Users/realm/workspace/realm_realm-core_master/src/external/s2/util/math/mathutil.h:411:13: error: GNU-style inline assembly is disabled
__asm__ __volatile__
^
```
This change uses the unoptimized version of the code if we are on a watchos simulator.
> Assembly in S2 math is disabled on watchos simulator builds

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/tokenizer.cpp
- src/realm/tokenizer.hpp
- test/test_query2.cpp
> Fix some issues in FTS

- src/external/s2/util/math/mathutil.cc
- src/external/s2/util/math/mathutil.h
- test/CMakeLists.txt
- test/test_query_geo.cpp
This ports the upcoming changes from https://github.com/10gen/mongo/pull/11605
The underlying issue is that certain numbers are inconsistent in rounding up or down depending on the platform.
IMO we shouldn't wait for the server to merge their fix because it is a bug fix and the app lifecycle is not tied in any way to the server. We don't want to end up in a situation where the server has rolled out their fix, but client side apps are running an old version of geospatial without the fix.
> Use consistent int rounding in S2 math

- CHANGELOG.md
An simple mistake from a longstanding [PR](https://github.com/realm/realm-core/pull/6445) that merged to the wrong changelog version.
> fix entries that went to the wrong change version

- CHANGELOG.md
- src/realm/mixed.cpp
- src/realm/mixed.hpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- src/realm/object-store/sectioned_results.cpp
- src/realm/object-store/sectioned_results.hpp
- src/realm/object-store/util/apple/scheduler.hpp
- src/realm/object-store/util/scheduler.cpp
- src/realm/table_view.cpp
- src/realm/table_view.hpp
- test/object-store/benchmarks/results.cpp
- test/object-store/sectioned_results.cpp
- test/object-store/set.cpp
A first pass at addressing https://github.com/realm/realm-swift/issues/8087.
SectionedResults used a std::map in a few places where the keys are a dense range (i.e. always [0..map.size())) and so they can be std::vector instead. The maps keyed on Mixed are now std::unordered_map.
Change notifications now report changes as a `std::vector<IndexSet>` rather than `std::map<size_t, IndexSet>`. This is slower and uses more memory when the only sections that changed are near the end of a SectionedResults with a large number of sections, but is much faster if all sections changed or if the sections which changed are early in the SectionedResults. Change notifications now reuse buffers, which increases persistent memory usage slightly but significant reduces allocations.
Change notifications for a …
> Improve SectionedResults performance 

- src/external/IntelRDFPMathLib20U2/LIBRARY/src/bid128_string.c
- src/external/s2/base/casts.h
- src/external/s2/base/logging.h
- src/external/s2/base/macros.h
- test/test_query_geo.cpp
Some warnings snuck into our builds.
The S2 warnings came in through https://github.com/realm/realm-core/pull/6477 which included some new S2 headers in our tests.
I've seen the Decimal128 warnings for a while and have been ignoring them.
> Fix some warnings

- src/realm/object-store/results.cpp
- test/object-store/frozen_objects.cpp
The result should be an empty result, not the whole table.
> Fix importing Results with deleted collection

- CHANGELOG.md
- src/realm/bplustree.hpp
- src/realm/dictionary.cpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/sort_descriptor.cpp
- src/realm/sort_descriptor.hpp
- test/test_unresolved_links.cpp
While trying to understand some details of what the code dealing with unresolved links was doing I discovered that some of it was not covered by tests. Adding some more tests ended up exposing a bug: Dictionary::get_any() was missing the check for unresolved links that the other getters have. This is the getter used for queries on dictionaries, so it resulted in queries using tombstone objects.
> Filter out unresolved links in Dictionary::get_any()

- evergreen/config.yml
Updated _evergreen/config.yml_ to point to the baas version that incorporates [baas PR #9596](https://github.com/10gen/baas/pull/9596), which should address many of our recent CI failures, where the migration from PBS to FLX was timing out or the `wait_for_session()` was failing after rolling back to PBS.
> Updated baas server tag for CI

- src/realm.h
- src/realm/collection.hpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/exceptions.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/mixed.cpp
- src/realm/obj.cpp
- src/realm/object-store/c_api/dictionary.cpp
- src/realm/object-store/c_api/list.cpp
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
- src/realm/set.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/nested_collections.cpp
Sets can also be held inside a collection. The only caveat is that, `sets` can only be a "terminal" node (leaf), they cannot hold other collections. 
We lack support for adding and getting a `set` into a collection (list/dictionary). The trick is that, although you can fetch such a collection, trying to nest another collection into, will result in some exception to be thrown.
This is the invariant to ensure that if a `Mixed` contains a nested collection, doing something like this:
Set<Mixed> set;
set.insert_collection(); //fails
However, doing something like this is still doable (and probably harmless).
```
obj.set_collection(col, CollectionType::Set);
object_store::Set set{r, obj, col};
auto col2 = table->add_column(type_Mixed, "any_val2");
obj.set_collection(col2, CollectionType::Set); …
```
> Set interface nested collections

- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
We recently had a test [failure](https://spruce.mongodb.com/task/realm_core_stable_macos_release_object_store_tests_patch_2d8fb23633293d0e9bab2c904f5695b25546f9fb_6467e53c7742aea9a51e981c_23_05_19_21_08_12/tests?execution=0&sortBy=STATUS&sortDir=ASC):
```
[2023/05/19 21:49:25.696] 3: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023/05/19 21:49:25.696] 3: realm-object-store-tests is a Catch2 v3.3.2 host application.
[2023/05/19 21:49:25.696] 3: Run with -? for options
[2023/05/19 21:49:25.696] 3:
[2023/05/19 21:49:25.696] 3: -------------------------------------------------------------------------------
[2023/05/19 21:49:25.696] 3: flx: geospatial
[2023/05/19 21:49:25.696] 3:   non-geospatial FLX query syncs data which can be queried locally
[2023/05/19 …
```
> Maybe fix a race in a test

- CHANGELOG.md
- src/realm/metrics/query_info.cpp
- src/realm/metrics/query_info.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_expression.cpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- src/realm/utilities.hpp
- test/object-store/benchmarks/object.cpp
- test/object-store/benchmarks/results.cpp
- test/object-store/dictionary.cpp
- test/object-store/results.cpp
Our use of aligned_storage was basically a complicated manual version of this. I was hoping this'd have binary size benefits, but it ended up making the library 100 bytes larger instead. Nonetheless, it greatly simplifies things.
> Use std::optional to store cached leaves in query nodes

- src/realm/collection.hpp
- src/realm/collection_list.cpp
- src/realm/collection_list.hpp
- src/realm/collection_parent.cpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/history.cpp
- src/realm/impl/transact_log.cpp
- src/realm/impl/transact_log.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/audit.mm
- src/realm/object-store/dictionary.cpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/replication.cpp
- src/realm/replication.hpp
- src/realm/set.hpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- test/test_lang_bind_helper.cpp
- test/test_list.cpp
- test/test_table.cpp
Enables support for notifications on nested collections. There is a FIXME in `src/realm/object-store/impl/transact_log_handler.cpp` that indicates where this support should take off.
> Add nested collection path in transaction log

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/generated/query_bison.cpp
- src/realm/parser/generated/query_bison.hpp
- src/realm/parser/query_bison.yy
- test/test_parser.cpp
This gives more flexibility to users who have a known shape but dynamic coordinates. It also gives users more ways to use this feature immediately for SDKs which use the parser but haven't added a wrapper around the new geospatial types for the query arguments yet.
Fixes https://github.com/realm/realm-core/issues/6662
> Allow geo coordinate numeric argument substitutions

- CHANGELOG.md
- src/realm/sync/network/network.hpp
Remove the catch clause from `AsyncOper::do_recycle_and_execute()` to avoid truncating the stack trace when an exception occurs on the event loop. This has the side effect that `do_recycle()` may have not been called on the `AsyncOper` object, but these exceptions are fatal and it doesn't matter if the memory is deleted or reclaimed at this point.
#Fixes #6665
> Remove catch() clause to prevent truncating stack trace in AsyncOper::do_recycle_and_execute()

- src/realm/dictionary.cpp
- src/realm/impl/transact_log.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/sync/changeset.cpp
- src/realm/sync/changeset_encoder.cpp
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- src/realm/sync/instructions.hpp
- src/realm/sync/transform.cpp
- test/test_sync.cpp
Make sure nested collections can be replicated through our legacy test framework.
> Replication of operations on nested collections

- CHANGELOG.md
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
- test/object-store/util/event_loop.cpp
- test/object-store/util/event_loop.hpp
Between when the callback after acquiring the write lock is scheduled and when it's invoked a synchronous write transaction can be begun, and if it's not ended before the next time the scheduler gets to run, the scheduled callback will be invoked inside the write. When this happens we want to just do nothing. Ending the synchronous write transaction will take care of rescheduling the async write it preempted.
Fixes #6649.
> Fix an assertion failure if an async write callback ran during a write transaction

- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/migration_store.cpp
- src/realm/sync/noinst/migration_store.hpp
Small documentation and code fixes.
> Small documentation and code fixes

- test/object-store/util/test_utils.cpp
The "sync: non-synced metadata table doesn't result in non-additive schema change" has been failing occasionally, even though it doesn't perform anything really different than other tests. It turns out that the test was timing out due while trying to query the location info from `https://realm.mongodb.com/api/client/v2.0/app/app_id/location` (which doesn't exist) while trying to refresh the user access token when using the local SyncServer. For all the other tests that use the SyncServer, the access token is still valid and is not attempted to be refreshed.
The current timeout is 30 minutes, which is valid beginning from the time the test program starts. When the test was failing, more than 30 minutes had elapsed and the access token was no longer valid. The access token timeout was …
> Fix failing "sync: non-synced metadata table doesn't result in non-additive schema change" tests

- src/realm/object-store/sync/impl/emscripten/network_transport.cpp
Currently, Http errors report as 
```
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```
This fixes the network transport for Emscripten to report errors properly 
```
{"error":"password must be between 6 and 128 characters","error_code":"BadRequest","link":"https://realm.mongodb.com/groups/5d84ec2dcf09a2dcb343aa7a/apps/63d93da2dad7c0ff7cabdd5f/logs?co_id=6480656e2dac9d38f50821a5"}. Client Error: 400
```
> Reporting correct error message on HTTP errors for Emscripten target

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app_credentials.cpp
- src/realm/object-store/sync/app_credentials.hpp
- test/object-store/sync/app.cpp
Fixes https://github.com/realm/realm-core/issues/5914
As reported, both the user and server API key providers are actually the same on the server side called "api-key". This can lead to confusion and weird things like `enum_from_provider_type(provider_type_from_enum(AuthProvider::SERVER_API_KEY)) != AuthProvider::SERVER_API_KEY;`
This replaces both with a new provider called "API key". I'm not sure how SDKs downstream want to handle this change, but if they don't want to break any user code, it should be fine to wrap the old two to point to this new provider as it does the same thing as the old behaviour.
> User/Server API key provider becomes a single 'API key' provider

- CHANGELOG.md
- src/realm/object-store/schema.cpp
- src/realm/object-store/schema.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/sync/sync_session.cpp
- test/object-store/realm.cpp
- test/object-store/sync/flx_sync.cpp
We had a report that since https://github.com/realm/realm-core/pull/6602 there was an issue with the frozen Realm instance passed to the client reset notify callbacks not retaining the same schema property indexes as in the live version. This is because the change in 6602 had reset the schema which used whatever order there was on disk rather than the schema passed to the configuration.
This change undoes the previous fix to restore the property ordering. This brings up the original issue of how to pass schema validation in the case of an async open client reset where the frozen Realm has no schema set yet. I have chosen to address this by changing the schema validation on a frozen Realm to allow new classes. I reason that this should be fine, since we allow Results to be backed by …
> Allow frozen Realms to be opened with additive schema changes

- Package.swift
Reverted the Swift minimum version update to 5.6 from 5.5 in #6647, since the `swift-build-and-test` CI tests were failing during the build step on realm core master on Evergreen. The current Mac OS hosts in Evergreen only support OS version 11.x, which does not support Swift version 5.6. There are Mac OS 13.x hosts in process of being added soon and these changes can be reapplied at that point with updates to the evergreen config to use the new hosts.
Verified that the `swift-build-and-test` CI tests run with this fix on a separate patch:
https://spruce.mongodb.com/version/64825c9d9ccd4e91f1fda66a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Reverted minimum swift version to fix failing CI tests

- test/object-store/sync/app.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/file.cpp
- test/object-store/sync/flx_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/metadata.cpp
- test/object-store/sync/migration_store_test.cpp
- test/object-store/sync/sync_manager.cpp
- test/object-store/sync/user.cpp
Add tags to the sync test cases in the object store tests executable to separate out the tests that rely on BAAS vs those that can run locally either against the sync server or do not require a server at all. This will be used to split the test into two different executables, based on the tags assigned.
> Add [baas] and [local] tags to object store sync tests to identify the tests that rely on BAAS or not

- bindgen/CMakeLists.txt
- bindgen/src/bound-model.ts
- bindgen/src/context.ts
- bindgen/src/generator.ts
- bindgen/src/program.ts
- bindgen/src/spec.ts
- bindgen/src/spec/model.ts
Adds initial support for an opt-in list for the Bindgen spec. This allows SDKs to use only some of the classes and records/structs of the [general spec](https://github.com/realm/realm-core/blob/bindgen/bindgen/spec.yml) and generate bindings only for the items in the opt-in list.
* Command option
* The `realm-bindgen` command now accepts an optional `--opt-in` option specifying the path of the opt-in list.
* If omitted, none of the bound methods or fields will be marked as opted in to.
* Examples (showing only the opt-in option):
```sh
realm-bindgen --opt-in path/to/opt/in/spec.yml
```
```CMake
bindgen(OPTIN path/to/opt/in/spec.yml)
```
* Spec/yaml opt-in file
* The opt-in file should list:
* The `records` along with their `fields` (names).
* The `classes` along with their `methods` …
> Support Bindgen opt-in list

- CHANGELOG.md
- src/realm/geospatial.cpp
- test/object-store/sync/flx_sync.cpp
Reported by @papafe.
S2 may report matches on points that are invalid. It appears that MongoDB does not allow invalid points into its geo index and so would never return a match. The fix is an early out if the point is not valid.
> Fix queries sometimes matching on invalid geospatial points

- src/realm/array.cpp
- src/realm/array_unsigned.hpp
- src/realm/cluster.hpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_conditions_tpl.hpp
- src/realm/query_expression.hpp
- src/realm/query_state.hpp
- src/realm/table_view.cpp
- test/test_query.cpp
Replace TableView and limit with a single QueryStateBase object. This will in principle allow us to call do_find_all with an alternative QueryState object with some enhanced functionality.
This change triggered some other small refactorings.
More flexibility in the future
> Change interface to Query::do_find_all

- src/realm/link_translator.cpp
- src/realm/link_translator.hpp
- src/realm/obj.cpp
- src/realm/table.cpp
- test/object-store/sectioned_results.cpp
- test/test_dictionary.cpp
- test/test_set.cpp
- test/test_sync.cpp
- test/test_typed_links.cpp
Removes some complexity/code. Is easy to re-introduce. Can be safely removed if we disallow creating columns of this type. This can also safely be done, as this feature is not yet used.
> Remove support for TypedLinks in LinkTranslator

- CHANGELOG.md
- src/realm/impl/copy_replication.cpp
This error was introduced in 601805bd148aa8, where the destructor on Mixed was removed. It was not possible to actually prove that Valgrind was right in reporting a read from uninitialized memory, but changing the logic a bit could make the error go away. The new code is probably slightly slower, but it is not on the critical path.
Fixes #6643
> Silence a Valgrind error

- CHANGELOG.md
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- test/object-store/c_api/c_api.cpp
Make a single implementation that will work for all types. This is to ensure consistent behavior.
Fixes #6695
> Consolidate the implementation of Results::index_of

- CHANGELOG.md
- src/realm/exceptions.hpp
- test/object-store/sync/app.cpp
- test/test_util_file.cpp
Issues like https://github.com/realm/realm-core/issues/6739 would be much easier to diagnose if the reported exception message had the details about what the error code was. The std error code was already stored there, so this change just appends the details to the existing message.
> More detailed error message for SystemError exceptions

- src/realm/object-store/c_api/object.cpp
- test/object-store/c_api/c_api.cpp
I forgot to add a check in the C API for `SETs` that are held into a mixed.
> C-API checks for Set in Mixed.

- CHANGELOG.md
- src/realm/object-store/sync/async_open_task.cpp
- test/object-store/sync/flx_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/sync_test_utils.cpp
- test/object-store/sync/sync_test_utils.hpp
Although the recent merge of my [PR](https://github.com/realm/realm-core/pull/6723) was running green on CI, it has caused failures after being merged. 
I haven't been able to reproduce this locally on my mac, but the various failures on CI have given clues to the following hypothesis:
The async open task has a notifier registered on the session that gets invoked even after the `async_open_realm()` function has returned. The fix is to cancel the task which unregisters the notifier and shuts down the session.
The new tests triggered the unhappy path of async open which uncovered a recently added double call to std::move introduced in https://github.com/realm/realm-core/pull/6722
~~The exception pointer passed out of the newly added async open utility was causing a use-after-free when …
> Fix a use after free error in tests

- CHANGELOG.md
- src/realm/exceptions.cpp
- src/realm/exceptions.hpp
- test/object-store/sync/app.cpp
- test/test_util_file.cpp
- test/util/unit_test.cpp
SystemError is used in two places: as a base class for SyncError, and for filesystem errors. Filesystem errors don't include the actual error message and need it appended, but sync errors do and appending the message from the error code just results in it being duplicated.
> Don't duplicate error messages for SyncError

- bindgen/spec.yml
We need to expose `bundle_id` to complete the sync connection parameter project.
> [bindgen] Expose DeviceInfo::bundle_id

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- test/fuzz_tester.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_sync.cpp
- test/test_query2.cpp
For complicated performance reasons, Cocoa doesn't pass the schema in the RealmConfig and instead calls update_schema() later. This means that when a client reset happens during an async open, the object store code doesn't have access to the actual schema yet, and the write to update the schema needs to happen in the SDK code.
> Add an option to pass a live Realm to the before-reset callback

- test/test_shared.cpp
A purely internal longshot: we want to catch if we somehow end up opening an empty file in this test.
> A bit more testing in Many_ConcurrentReaders

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- test/test_sync.cpp
This changes the upload/download completion API on `sync::Session` to use Status instead of std::error_code. The SDK-facing API had already been ported to use Status so this change should only result in better error messages and no user-facing changes.
> Port upload/download completion API to Status

- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
The client metadata table hasn't been used since v10.
All the calls to `verify_thread()` were no-ops because we use a dummy scheduler that doesn't do any thread checking.
> Delete some unused old code in SyncMetadataManager

- test/object-store/sync/flx_sync.cpp
The test was already enabled and had been passing on evergreen for a while, so I removed the comment.
Fixes #5640.
> Remove comment since test is already enabled

- src/realm/object-store/object_store.cpp
- test/object-store/sync/flx_sync.cpp
> Update error message when breaking changes are detected

- CHANGELOG.md
- src/realm/object-store/object_store.cpp
- test/object-store/sync/app.cpp
This makes processing additive schema changes where one of the changes is adding a full-text search index actually add the full text search index. Without this change synchronized realms opened asynchronously could end up without any of their defined full text search indexes created and full text searches throwing an error with the message `Column has no fulltext index`.
> Actually add full text indexes when processing schema changes that require them

- CHANGELOG.md
- evergreen/config.yml
- test/object-store/sync/app.cpp
A new test that was added in PR #6823 was missing the `"[baas]"` tag and was not being run against the baas server during the Evergreen CI tests. (I didn't see that this test was added when merging and missed adding the tag.)
> Add missing [baas] tag that is causing failing tests

- evergreen/config.yml
This just updates the evergreen config so object store tests don't fail on branches besides master. If you aren't on the "main" branch of the evergreen project it doesn't fill in the `${project}` expansion which causes our s3 upload paths to be invalid. Since we now only have one evergreen project I think its safe to hardcode these paths and just rely on the `${branch}` expansion to differentiate between branches. For an example of how this could fail you can look at this [patch failure](https://spruce.mongodb.com/task/__feature_sync_error_unification_macos_1100_arm64_object_store_tests_patch_fdf34f4795d83fb79a6a9aac3b6ccdd852685129_64bfeaace3c331fa1e4a1ffd_23_07_25_15_30_54/logs?execution=1).
> Handle uploading logs in evg tasks on feature branches

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/test_sync.cpp
We report partial progress for download messages from state when the sync client decides to split such a message if it's too large. The partial progress is the download cursor of the last changeset in that chunk. This happens for all chunks. But the last chunk should report the download cursor of the message (not the last changeset). Sometimes the download cursor of last changeset is not the same as the download cursor of the message (i.e, server skips versions). This may result in an extra  round-trip to the server to receive and ack the skipped versions.
Fixes #6827.
> Sync progress for download messages from server state is updated wrongly

- CHANGELOG.md
- src/realm/object-store/audit.mm
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/client_base.hpp
- src/realm/sync/config.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/audit.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/session/session.cpp
- test/object-store/sync/session/wait_for_completion.cpp
- test/object-store/util/test_file.cpp
- test/sync_fixtures.hpp
- test/test_client_reset.cpp
- test/test_sync.cpp
This is a transitional PR to make SyncError and sync::SessionErrorInfo aware of Status and use it instead of std::error_code to capture error information. Just in this PR all the actual errors are still `std::error_code` via the SystemError type, but this change lets me start to transition our various error types without having to change all our tests/call sites at once.
> Make SyncError/SessionErrorInfo Status-aware

- CHANGELOG.md
- src/realm/alloc_slab.cpp
- src/realm/alloc_slab.hpp
- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/util/file_mapper.hpp
- test/test_alloc.cpp
We changed (in v12.12.0) how we attach files in order to give better errors. Unfortunately this can lead to scenarios in which a file on streaming format (as produced by compact on launch or copy to file) is truncated or expanded before conversion to normal (non-streaming) format. If the app is then terminated (for whatever reason) we can no longer find the file footer and do the conversion later. The end result is a corrupted file - either the footer is lost or it is no longer at the end of the file, as expected.
This PR retains the better error reporting, while only doing file size changing operations *after* the conversion to normal format. 
In response to: https://github.com/realm/realm-kotlin/issues/1440
> convert from streaming form *before* any changes to file size

- CHANGELOG.md
- src/realm/timestamp.hpp
- test/test_object_id.cpp
> Only allow system_clock timepoints when creating a Timestamp

- evergreen/config.yml
The filter I thought would work for removing the tasks for the nightly test run from the commit test runs (when a PR is merged to `master`) was not working as expected.
Updated the nightly test tasks to include the `patch_only: true` setting to remove them from the commit test runs 🤞.
The `"for_nightly_tests"` task tag was kept, so the set of tasks for commit test runs can be selected using the "commit_tests" alias.
> Updated nightly test tasks to be excluded from commit builds

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
For the Sync Schema Migration project the sync client sends the schema version the realm is opened with as part of the BIND messages. The schema version is added to the JSON data section of the FLX BIND message.
Fixes #6840.
> Add schema version to flexible sync client BIND message

- evergreen/config.yml
The last set of changes to add `patch_only: true` did not work as expected; they removed the tasks from both the commit and the nightly test runs.
After speaking with evergreen support, using the `activate: false` setting to the tasks defined for a build variant should remove the task from the set of tasks run for the commit test runs and allow it to be started "manually" for the nightly test runs.
> Updated evergreen definitions for nightly tests

- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/sync/session/session.cpp
The SyncSession has a `pause` API which shuts down the synchronization session (sync::Session), but there is no way to know when the Realm file is no longer open on behalf of it.
This PR adds a `pause_async` API (hidden from the public api currently) which returns a Future the users can use to get notified when the realm file is no longer open on behalf of the session.
Fixes #6841.
> Add pause_async to SyncSession

- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.hpp
- test/test_list.cpp
> Make exceptions thrown by nested collections more consistent

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/error.cpp
- test/object-store/c_api/c_api.cpp
When the `realm_get_async_error()` function was added it is ignoring the result of the `get_as_realm_error_t()` function that is called. Update `realm_get_async_error()` to return whether or not an error is present in the `async_err` parameter (the return value from `get_as_realm_error_t()`).
Fixes #6897
> C API: Return result of get_as_realm_error_t from realm_get_async_error

- CHANGELOG.md
- src/realm/query_expression.cpp
- test/test_query.cpp
> Fix query on size of a single link over links

- CHANGELOG.md
- evergreen/config.yml
- evergreen/setup_baas_host_local.sh
- src/realm/sync/changeset_parser.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- test/test_changeset_encoding.cpp
- test/test_sync.cpp
After the updates from the unify core error handling project, the realm-sync-tests were crashing due to an "unknown instruction type" if debug level trace or higher was enabled. This was due to an exception being thrown by `parse_changeset()` during the `Sync_BadChangeset` test, which intentionally creates a bad changeset.
Updated debug output handling to catch the `BadChangesetError` exception and print a message instead of passing this exception up.
Also, fixed the race condition in the `Sync_DetectSchemaMismatch_*` tests that was resulting in the `realm::TableNameInUse: The specified table name is already in use` error. This was due to the first session completing sync before the write transaction transaction on the second session was completed. Moved the call to …
> Handle badchangeset error when printing changeset contents in debug

- src/realm/CMakeLists.txt
- src/realm/collection.hpp
- src/realm/collection_parent.hpp
- src/realm/column_mixed.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/impl/transact_log.cpp
- src/realm/impl/transact_log.hpp
- src/realm/index_string.cpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/object-store/impl/transact_log_handler.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.hpp
- src/realm/table.hpp
- test/test_list.cpp
Change the index held by the collection object from std::string to a structure (KeyIndex) ) containing both the beginning of the dictionary key (mostly for debugging purposes) and an index key generated for that particular collection. The key value is stored alongside the ref and compared with the key value found in index when trying to obtain the ref for the collection.
This is equivalent to what was previously done for Obj.
At the same time StableIndex is made simpler in that it is no longer an mpark::variant, but just a more simple structure. Main reason that this is now possible is that we are dropping storing the Dictionary key in the index, but only the salt.
> Check for stale accessors to a collction embedded in a dictionary

- src/realm/timestamp.hpp
- src/realm/util/serializer.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/test_json.cpp
I haven't been able to get TSAN to report the errors locally so this is a best guess as to what the problem could be. I'll let CI verify.
I think the first problem was that the test `Json_Timestamp` was using an insufficient buffer size. I changed the size to be part of the type so that an incorrect size is a compiler error.
The thread issue about using Catch macros on a different thread I think I have solved by invoking the finish callback from our `async_open_realm` test utility on the calling thread.
> tsan fixes

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
The SDKs who use the CAPI do not have support for passing geospatial objects as arguments to the query parser. It is not trivial to enable that and so that work was postponed to geospatial phase 2 which has since been deprioritized. This PR enables this by allowing SDKs to pass the geo object as a serialized string instead which is then parsed by core and the geo object reconstructed. In an ideal world, this problem would be solved by the binding generator, but given our timelines this should work as a temporary solution.
Also see this [comment in the scope](https://docs.google.com/document/d/1Z7CK79CqebEtVllVHTNEq8neKhoMWeFCDjKBrn_pq1Y/edit?disco=AAAAwzW2Z5g) as to why a proper solution in the CAPI support was not implemented.
> allow RQL geo args to be strings

- src/realm/collection.hpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/keys.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/set.hpp
- test/test_list.cpp
This commit fixes the problem that trying to access position 0 in a newly created nested list would give an exception saying that the collection was gone instead of an out-of-bounds exception. This was because we had a test for attached before validating the index.
The solution selected is to remove "ensure_attached" and let the exceptions thrown in "get_collection_ref" flow all the way to the client. This is kind of fundamental change in that we must remove the noexcept specification from  "update_if_needed_with_status" and make the "init_from_parent" functions rethrow the exceptions caught. The noexcept functions calling "update_if_..." must add a try..catch block.
> More consistent exception handling for nested collections

- src/realm.h
- src/realm/collection.hpp
- src/realm/dictionary.hpp
- src/realm/object-store/c_api/query.cpp
- src/realm/object-store/results.cpp
- src/realm/object-store/results.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/dictionary.cpp
> Add ability to get collections from Results

- src/realm/query.cpp
- src/realm/sort_descriptor.cpp
- test/benchmark-common-tasks/main.cpp
- test/test_table_view.cpp
If the limit is much smaller than the total size of the TableView, then it is faster to make a sorted insert into a vector that is kept at the limit size.
> Optimize sort followed by limit

- CHANGELOG.md
- evergreen/config.yml
- src/realm/array_basic_tpl.hpp
- src/realm/array_bool.hpp
- src/realm/array_list.hpp
- src/realm/array_typed_link.hpp
- src/realm/object-store/util/copyable_atomic.hpp
- src/realm/sync/CMakeLists.txt
- src/realm/util/serializer.cpp
We've had a few issues with headers being added as dependencies of an installed header but not being installed, so add a CI job that validates that all installed headers can be compiled with only the other installed headers available. This also catches some incidental missing header inclusions where a header failes to include everything it depends on.
Only runs on macOS since Cocoa seems to be the only SDK which relies on this being valid.
> Add an evergreen job to validate that all installed headers build

- evergreen/config.yml
Now that evergreen has been updated to use the `allowed_requesters` task specification, update the nightly only tasks so they are no longer "allowed" to run as part of the evergreen runs that occur when a PR is merged to `master`. By specifying `"ad_hoc"` and `"patch"`, these tasks will be allowed to run for periodic test runs (ad_hoc) or manual patches (patch).
A weird looking failure was seen in CI where the `git clone` operation hung and was killed, leading to the hang analyzer task to run and attempt to build the hang analyzer executable, which failed since not all the files had been populated in the repo. Added a check at the beginning of the "build hang analyzer" function so it verifies the necessary components are present before attempting to build the executable.
~~* [ ] 📝 …
> Move nightly evergreen CI tasks out of commit to master builds

- src/realm/util/file.cpp
There is no clear suggestion that it was the case. Besides the original reports mentioned activating needed manifest for external storage access. What is supported on external storage from the realm side is not yet clear and need clarification.
> Remove confusing message for flock unlock failure on Android

- src/realm/error_codes.cpp
- src/realm/error_codes.h
- src/realm/error_codes.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/async_open_task.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/protocol.cpp
- src/realm/sync/protocol.hpp
This is the main body of work for sync schema migrations.
A schema migrations is performed whenever the client receives `schema_version_changed` error (236) from the server. In such cases, the synchronization session is left active so any unsynced changes are uploaded to the server before migrating the schema. The realm file is then deleted and reopened at the new schema version. Data is bootstrapped at the new schema version.
These are the steps the client and server take in case of a schema migration:
* Client BINDs with the new schema version
* Client IDENTs
* Server detects a difference in the previous file version and new version, sends an error schema version changed
* Client uploads its local data at the old schema version
* Client waits for acknowledgement of upload
* Client …
> Upload data and migrate schema

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- test/object-store/sync/flx_sync.cpp
When a change of query (COQ) needs to be sent to the server, the sync client first uploads the local changes up to the client version associated to the query. Sometimes, these upload messages are empty. If the the client disconnects and reconnects before the query was fully bootstrapped, the sync client re-sends the upload and COQ messages to the server. This is a problem especially if the upload message is empty. Due to history trimming, the sync client may not know anymore the last_integrated_server_version associated with the client version sent in the upload message. This results in the server issuing a `Bad server version` error (and a client reset) due to inconsistent sync progress (same client version is sent with two different server versions).
This PR fixes the issue by making …
> Resending pending subscriptions can result in inconsistent sync progress

- src/realm/alloc_slab.hpp
- src/realm/db.cpp
- src/realm/group.hpp
- src/realm/group_writer.cpp
- src/realm/group_writer.hpp
- src/realm/transaction.cpp
An attempt to simplify GroupWriter and GroupComiter as a follow up on the fix in https://github.com/realm/realm-core/pull/6962
WIP.
> reorg GroupWriter and GroupComitter so that each is their own

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/sync/async_open_task.cpp
- test/object-store/sync/flx_sync.cpp
1. Fix open async logic when rerun on open is set. 
2. Consolidate tests
3. Fix wrong use of `std::move `for `init_sb_callback`.
> Fix open async when rerun on open is set.

- src/realm/parser/driver.cpp
- src/realm/parser/driver.hpp
- src/realm/parser/generated/query_bison.cpp
- src/realm/parser/generated/query_bison.hpp
- src/realm/parser/query_bison.yy
TSAN reported a data [race](https://evergreen.mongodb.com/task_log_raw/realm_core_stable_ubuntu2004_tsan_core_tests_patch_a3717e492ec606e42995169cf706a82fc1cd0698_65000bc93e8e8688b5e7890c_23_09_12_06_57_15/0?type=T&text=true) between a couple unit tests. The cause was because we were using a static map to translate integer values into a human readable string for error messaging purposes. This was working fine for read only access, except that we had forgotten to handle a new comparison type for the TEXT operator, so accessing the map for that value added an empty entry from multiple tests that used full text search. To fix this and make it more future proof, I changed from using static constant ints, to using an enum class. This means that for values we add in the future, we will get a …
> Use an enum class instead of int constants

- CHANGELOG.md
- src/realm/object-store/object_schema.cpp
- src/realm/table.cpp
- test/object-store/schema.cpp
- test/test_table.cpp
* ~~C-API, if public C++ API changed.~~
Fixes: https://github.com/realm/realm-core/issues/6976
> Allow non-embedded links in asymmetric objects

- test/object-store/CMakeLists.txt
- test/object-store/benchmarks/CMakeLists.txt
The `benchmarck-common-tasks` test was failing to compile in the evergreen CI for the nightly and master commit test runs.
These changes address the compilation failures by importing the `TestUtil` library as a `target_link_library` when building the `realm-object-store-tests` and `realm-benchmark-common-tasks` executables instead of including individual files from the `test/util/` directory.
* ~~[] 📝 Changelog update~~
> Fix benchmark-common-tasks test failures

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/util/logger.hpp
- test/object-store/util/test_file.cpp
- test/util/compare_groups.cpp
Logger::m_base_logger_ptr seems not to be used in the class itself. The member is added to the sub-classes that need it.
get/set level_threshold need not be virtual is we remove support for NullLogger.
> Simplify Logger class a bit

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/protocol.hpp
- test/object-store/sync/flx_sync.cpp
In case of `write_not_allowed` errors, `compensatingWriteServerVersion` is optional. This was incorrectly handled by the sync client and hence it would lead to a crash.
Fixes #6978.
> Receiving write_not_allowed error crashes the app

- test/object-store/sync/flx_sync.cpp
I observed several test [failures](https://spruce.mongodb.com/task/realm_core_stable_macos_release_baas_integration_tests_patch_eb34d4cb210b5e5374717c512ea910e3cb7d0bba_650b46f7d6d80a0eb4bca004_23_09_20_19_24_41/tests?execution=0&sortBy=STATUS&sortDir=ASC) with the exception `message: wait_for_session() timed out`.
`wait_for_session()` is called from either `wait_for_upload()` or `wait_for_download()` and there were several unnecessary calls to these in the tests that were failing. They are not needed in the places where I removed them, because immediately afterwards, the test waits on an error future.
My guess as to why these calls were timing out is that by the time the test code gets to call `wait_for_upload()`, sync has already completed the upload on the background thread, so that …
> remove unnecessary upload/download waiters in tests

- src/realm/object-store/impl/results_notifier.cpp
> Remove redundant call to Query::find_all

- CHANGELOG.md
- src/realm/table.cpp
- test/object-store/audit.cpp
- test/object-store/realm.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/thread_safe_reference.cpp
- test/object-store/util/sync/flx_sync_harness.hpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/object-store/util/sync/sync_test_utils.hpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
The schema validation checks forbidding this were removed in https://github.com/realm/realm-core/pull/6981, but Table
also had its own validation. Most of the changes here are just making the asymmetric sync tests verify that the expected documents are actually created on the server.
> Allow collections of non-embedded objects in asymmetric objects

- src/realm.h
- src/realm/db.cpp
- src/realm/object-store/c_api/logging.cpp
- src/realm/query.cpp
- src/realm/replication.cpp
- src/realm/transaction.cpp
- src/realm/transaction.hpp
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
- src/realm/util/timestamp_logger.cpp
- src/realm/util/timestamp_logger.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
- test/test_util_logger.cpp
- test/util/compare_groups.cpp
> Introduce logging categories

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/realm.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/migration_store_test.cpp
- test/peer.hpp
- test/test_array_sync.cpp
- test/test_client_reset.cpp
- test/test_embedded_objects.cpp
- test/test_sync.cpp
- test/test_sync_history_migration.cpp
- test/test_sync_subscriptions.cpp
- test/test_transform.cpp
- test/test_util_http.cpp
The concrete bug which this fixes is that `await realm.subscriptions.update {}; await realm.refresh()` would hang forever. SubscriptionStore writes failed to notify RealmCoordinator of the write, so the async refresh would see that the Realm is not on the latest version, register a handler to be called when the autorefresh happened, and then nothing would ever schedule the autorefresh.
The sync client needs to be notified of non-sync writes and notify non-sync components when it performs writes. When it was first written, DB did not exist yet and so this was orchestrated via RealmCoordinator. However, that's a very awkward place to do it: not all writes go via RealmCoordinator, and the lifetime of sync sessions isn't actually tied to a coordinator. Nowadays we do have DB, and handling …
> Simplify internal commit notification

- test/object-store/sync/flx_migration.cpp
Device sync is enabling indexed queryable fields in PBS->QBS migrations which means that there are limitations on the types of queries that a QBS client is able to make after the migration ([See Here](https://www.mongodb.com/docs/atlas/app-services/sync/configure/sync-settings/#indexed-queryable-fields))
This change fixes some non compliant queries in migration tests
```
realm_id = partition1 OR realm_id = partition2 -> realm_id = partition2
truepredicate -> realm_id = partition2
```
> IQF compliant queries in migration tests

- CHANGELOG.md
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/db.cpp
- src/realm/group.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/object.cpp
- test/object-store/sync/flx_sync.cpp
Likely to fix https://github.com/realm/realm-kotlin/issues/1537
> Allow deletion of ephemeral objects before commit

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/list_notifier.cpp
- src/realm/object-store/impl/object_notifier.cpp
- src/realm/object-store/impl/results_notifier.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/transaction.hpp
- src/realm/util/scope_exit.hpp
- test/object-store/dictionary.cpp
- test/object-store/list.cpp
- test/object-store/realm.cpp
- test/test_parser.cpp
- test/test_table.cpp
> Logging notification activity

- bindgen/spec.yml
- bindgen/src/realm_helpers.h
- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/object-store/object_store.cpp
- src/realm/replication.cpp
- src/realm/transaction.cpp
- src/realm/util/logger.hpp
- test/object-store/c_api/c_api.cpp
- test/test_upgrade_database.cpp
> Logging of schema migrations

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/db.cpp
- src/realm/group.cpp
- src/realm/group.hpp
- test/object-store/c_api/c_api.cpp
> Log free space and history sizes when opening file

- CHANGELOG.md
- tools/build-apple-device.sh
- tools/cmake/xcode.toolchain.cmake
The visionOS SDK is currently only available in beta versions of Xcode, so we can't use a major version check to enable it. Instead we need to explicitly enable visionOS when building for it.
> Fix building with non-beta Xcode 15

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/test_sync_subscriptions.cpp
`SubscriptionStore::get_next_pending_version()` returns the next subscription that needs to be sent to the server with a snapshot version **past** the upload cursor. Empty uploads may be acknowledged during bootstraps and so that will advance the upload cursor past the snapshot version of the subscription. If the subscription bootstrap is interrupted, it is not picked up by the sync client the next time get_next_pending_version() is called (and as a side effect a notification on that subscription will no be fulfilled).
get_next_pending_version() does not need to take into account the upload cursor, so the fix is to remove querying on it.
Fixes #7077.
> Re-send subscription if bootstrap is interrupted and upload cursor is past the sub's snapshot version

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/session/wait_for_completion.cpp
Completion callbacks are canceled when a fatal error is received from the server or the sync session becomes inactive. The subscription notifications would not fulfill in such cases causing a hang for the users. This PR addresses that by canceling the subscription notifications in such cases.
Fixes #5315.
> Cancel subscription notifications

- CHANGELOG.md
- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer.hpp
- src/realm/array_integer_tpl.hpp
- src/realm/array_with_find.cpp
- src/realm/array_with_find.hpp
- src/realm/query_conditions_tpl.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- src/realm/query_state.hpp
- src/realm/table.cpp
- test/benchmark-common-tasks/main.cpp
- test/large_tests/test_column_large.cpp
The query system supported two ways of dealing with matches: using QueryStateBase::match() and using a custom callback.
The callback was only used in one place, and I replaced it by caching the results array leaf inside our existing QueryStateBase handler class.
There is no noticeable performance drop for the affected query case that was using the callback. Here's the newly added benchmark compared to master showing no significant change for this case:
```
Req runs:   14  QueryWithForeignAggAvg (MemOnly, EncryptionOff):        min  35.16ms (-2.43%)            max  35.80ms (-1.63%)            med  35.23ms (-2.32%)            avg  35.32ms (-2.19%)            stddev   210us (+99.14%)
```
The benefit of doing this is that we can delay fetching the values until the `match()` function which may …
> remove unnecessary callback use for ArrayWithFind::find_action()

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
A race in `send_upload_message()` causes subscriptions not being sent to the server (and as a side effect a notification on that subscription may never be fulfilled). This can happen when send_upload_message() is called as a result of a commit previous to the one for subscriptions. send_upload_message() then forwards the upload cursor past the version associated with the subscription and so the subscription is never uploaded to the server.
A second bug was uncovered while investigating this issue.
SessionWrapper reads the state of the SubscriptionStore when it is created, but this state can change after a client reset (when then state of existing subscription may change, in addition to new subscriptions being created and old subscriptions being removed). This can cause a crash with …
> Fix race in send_upload_message

- src/realm/query_state.hpp
The `validate-installed-headers` test was failing since the `query_state.hpp` file was using a class without including the file.
> Fix validate-installed-headers test

- CHANGELOG.md
- evergreen/config.yml
- src/realm/cluster.cpp
- src/realm/collection.hpp
- src/realm/list.hpp
- src/realm/object-store/set.cpp
- src/realm/set.cpp
- src/realm/set.hpp
- test/object-store/audit.cpp
- test/object-store/set.cpp
- test/test_set.cpp
It turned out that the set algebra functions on Set<T> were a full 5% of the compiled core library. Doing set algebra on Mixed instead will make them slightly slower, but they weren't particularly optimized to begin with. If it turns out that anyone cares about the performance of these, we could do something much faster for Set<Int>. This cuts ~700 kB off the obj-c dylib and is a net simplification of the code.
> Implement the set algebra functions on Mixed

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/scheduler.cpp
- test/object-store/c_api/c_api.cpp
> Change the C API around custom scheduler

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/noinst/server/server.cpp
- src/realm/sync/noinst/server/server_history.cpp
- src/realm/sync/noinst/server/server_history.hpp
- src/realm/sync/tools/apply_to_state_command.cpp
- src/realm/sync/transform.cpp
- src/realm/sync/transform.hpp
- test/peer.hpp
- test/test_sync.cpp
- test/test_sync_pending_bootstraps.cpp
https://github.com/realm/realm-sync/pull/3196 pulled TransformerImpl out of the anonymous namespace and made it extern. This innocent-looking change actually had a meaningful effect: a very, very large number of functions defined by composing templates were no longer inlined out of existence because static functions are inlined more aggressively than extern functions. Moving all of the helper functions back to the anonymous namespace results in transform.o halving in size due to better inlining.
While poking at this I noticed that Transformer's API didn't make any sense any more. It was designed to support Transformer objects holding state between transformations and to hide the implementation type entirely in the cpp file. Neither of these are done any more, so it was just very …
> Simplify sync::Transformer and eliminate the abstract interface

- test/test_file.cpp
Apparently uids on fat32/exfat are assigned not so deterministically on truncate, so try to make simplier checks.
Example failure where most likely uids either stay the same or get completely new values:
```
[2023/10/30 23:39:13.137] Thread[08]: /System/Volumes/Data/data/mci/6327106b375800ccccaed93352fa5563/realm-core/test/test_file.cpp:588: ERROR in File_GetUniqueID: CHECK(uid1_1 == file2_1.get_unique_id()) failed
[2023/10/30 23:39:13.137] Thread[08]: /System/Volumes/Data/data/mci/6327106b375800ccccaed93352fa5563/realm-core/test/test_file.cpp:589: ERROR in File_GetUniqueID: CHECK(uid2_1 == file1_1.get_unique_id()) failed
```
or just one failure where it is probably just completely new uid for second file:
```
[2023/10/29 23:38:40.219] Thread[11]: …
```
> Loosen checks for uids on exfat fs

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/util/sync/sync_test_utils.cpp
Updating the subscription store in a separate write transaction from the recovery means that we temporarily commit an invalid state. If the application crashes between committing the client reset diff and updating the subscription store, the next launch of the application would try to use the now-invalid pending subscriptions that should have been discarded.
This is the fairly uninteresting case; client reset with recovery can do much more invalid things than this if the process crashes. That'll be a significantly more involved thing to fix so I'm splitting it off to a subsequent PR.
> Use a single write transaction for DiscardLocal client resets on FLX realms

- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
- test/util/test_path.hpp
#7110 accidentally made it so that we no longer complete subscription state notifications in DiscardLocal client resets. I uncovered this while writing tests for a separate set of changes, so this includes some refactoring which those tests depend on.
No changelog entry since the bug hasn't been shipped.
> Deliver appropriate subscription state change notifications in DiscardLocal client resets

- bindgen/spec.yml
> [bindgen] Expose Obj::set_embedded()

- CHANGELOG.md
- src/realm/set.cpp
`Set<ObjKey>` is the single type not implicitly instantiated in `Obj::get_setbase_ptr()`, so it needs to be explicitly instantiated. Fixes the linker error seen in https://ci.realm.io/job/objc_pr/target=osx,xcode_version=14.3.1/10813/consoleFull. I have no idea why this works with LTO off but breaks with LTO on.
> Explicitly instantiate Set<ObjKey> in set.cpp

- evergreen/config.yml
Updated the `realm-core-stable` project aliases to exclude the tasks with the `disabled` tag and added the `disabled` tag to the `baas-network-tests` to prevent them from running.
Also, updated log level to `debug` for the network tests to reduce the log size.
> Disable the network tests

- CHANGELOG.md
- src/realm/collection.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/test_set.cpp
On platforms where `char` is signed, ordering StringData and Mixed containing the same strings gives different results, so we need to use the typed comparisons. This brings us up to 6 instantiations of each operation rather than 2, but it's still a lot less than the 38 we used to have.
While looking at the code I also noticed another problem: `assign_intersection()` cleared the set and then inserted the elements from the RHS set, which is a use-after-free if the RHS set is `this`.
Fixes #7135.
> Use typed comparisons for set algebra on strings and binary

- CHANGELOG.md
- src/realm/index_string.cpp
- src/realm/index_string.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/object-store/object_store.cpp
- src/realm/object-store/property.hpp
- src/realm/query_expression.hpp
- src/realm/table.cpp
- test/object-store/primitive_list.cpp
- test/test_index_string.cpp
- test/test_parser.cpp
I have chosen  to store the whole word in the index as I believe it would be too slow to try to find the value in the list based on the prefix.
Partial fix for #7132
> Index on list of strings

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
- test/object-store/sync/client_reset.cpp
- test/test_client_reset.cpp
Tracking that a client reset was in progress was done in the same write transaction as the recovery operation, so if recovery failed the tracking was rolled back too. This worked for FLX due to that codepath committing before beginning recovery.
The good news is that we don't have any reports of users running into this problem, which is a strong sign that client reset recovery failing isn't a common scenario in the first place.
> Fix client reset cycle detection for PBS recovery errors

- CHANGELOG.md
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- src/realm/sync/noinst/client_reset_recovery.hpp
- test/object-store/benchmarks/client_reset.cpp
- test/test_client_reset.cpp
After we copy a list in client reset recovery we need to not apply any changes to that list in subsequent transactions as we copy directly to the final state of the list and applying changes would just duplicate those changes.
This is only applicable to flexible sync when there's a subscription change in between the write with unrecoverable changes and the write with recoverable changes.
> Fix duplication of recoverable list changes after unrecoverable changes

- evergreen/config.yml
- src/realm/CMakeLists.txt
The validate-install-headers job on realm-core-stable has been [failing](https://parsley.mongodb.com/evergreen/realm_core_stable_macos_validate_installed_headers_750db452530f44213039e67527c74336ade087dd_23_11_23_17_57_22/0/task?bookmarks=0,2743) since https://github.com/realm/realm-core/pull/7157
No changelog, since this hasn't been released yet.
> Add missing install headers

- evergreen/config.yml
Change the default from 2 to 4 to help with 'failed to restore the stack' situation. Also, dump stacktrace for ubsan.
> Expand stacktrace buffer for tsan

- bindgen/spec.yml
As per https://github.com/realm/realm-core/blob/master/src/realm/object-store/dictionary.hpp#L122 the second argument is optional.
> Update spec.yml to expose `Dictionary::add_key_based_notification_callback` correctly

- evergreen/config.yml
- test/tsan.suppress
* Disable builders testing faulty network - it was not supposed to run since it's not yet ready, and 'disable' tag doesn't work as expected
* Also, don't run core/sync internal test on new macos arm64 with tsan since it's not stable with apple clang 13 #7185
* Introduce new builders for asan/tsan on ubuntu arm64
> Disable failing ci builders

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- test/object-store/sync/flx_sync.cpp
This makes sure we catch exceptions getting thrown during bootstrap application and surface them to the user via the sync error handler. It also fixes one place during session activation where we were not exception-safe which may have caused an uncaught exception to manifest as a `REALM_ASSERT(!m_sess)` failure rather than a regular uncaught exception.
> Gracefully handle all exceptions during bootstrap processing

- CHANGELOG.md
- src/realm/sync/config.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/test_utils.hpp
If you get multiple non-fatal errors in a row and explicitly resume the session without waiting for (or canceling) the try_again timer to fire, the sync client can hit an assertion on the second error when it tries to create a new try again timer without canceling the old one. This fixes that and a few bad assertions we were making about when you could request download notifications after a retryable error has been received.
> Allow calling handle_reconnect() multiple times after a non-fatal error

- src/realm/util/backtrace.cpp
When building Core inside of AOSP both `defined(__linux__)` and `defined(__GNUC__)` are true, this conflicts with the macro guard around `g_backtrace_depth` which states `!REALM_ANDROID`. This should use `REALM_HAVE_BACKTRACE` as the source of truth instead.
> Fix backtrace macro

- CHANGELOG.md
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/obj.hpp
- src/realm/sync/instruction_replication.cpp
- test/test_unresolved_links.cpp
The process of first removing the backlink from the tombstone and then creating it again in the live object took a long time. As the backlinks will end up being identical, we can just move the whole structure from the tombstone to the new object and then just replace the link in the linking object without worring about backlinks.
This change is only done for link and linklist properties.
Fixes #7217
> Improve performance when resurrecting an object with many backlinks

- evergreen/config.yml
The `content-type` for the uploaded text files was originally set to `text/text`, which is not a valid content type. Updated these uploads to use a content type of `text/plain` to enable the **Parsley** button on the **Files** tab in Evergreen.
* ~[ ] 📝 Changelog update~
* ~[ ] C-API, if public C++ API changed~
* ~[ ] `bindgen/spec.yml`, if public C++ API changed~
> Enable the Parsley button in evergreen for uploaded file artifacts.

- test/test_shared.cpp
- test/test_transform.cpp
Shared_ManyReaders and Transform_Randomized dominate whole test suite running time under simulator and on debug builds.
This often leads to CI failures on Jenkins on checkiOSSimulator_Debug and checkLinuxDebug_* builders manifested as: 
"... wrapper script does not seem to be touching the log file... if on an extremely laggy filesystem..."
Adjust constants so that the time taken for these tests in same range as with others slowests tests.
> Align run time for debug and simulator for slowests tests

- evergreen/config.yml
- test/test_lang_bind_helper.cpp
CI reports an [error](https://parsley.mongodb.com/evergreen/realm_core_stable_ubuntu_valgrind_valgrind_6595edf80ae606e16db012bb_24_01_03_23_30_00/0/task?bookmarks=0,886,5432):
```
[2024/01/03 15:45:24.366] ../test/test_lang_bind_helper.cpp:131: Begin Transactions_ConcurrentFrozenTableGetByName
[2024/01/03 15:47:04.549] Use --max-threads=INT to specify a larger number of threads
[2024/01/03 15:47:04.549] and rerun valgrind
[2024/01/03 15:47:04.549] valgrind: the 'impossible' happened:
[2024/01/03 15:47:04.549]    Max number of threads is too low
```
Valgrind's [default value](https://man7.org/linux/man-pages/man1/valgrind.1.html#:~:text=%2D%2Dmax%2Dthreads%3D%3Cnumber,%2D%2Dmax%2Dthreads%3D3000.) is 500 threads.
Since we have several of these tests that may run concurrently, we have …
> Bump valgrind max threads

- CHANGELOG.md
- bindgen/spec.yml
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/app.cpp
- test/object-store/util/test_file.cpp
This is a collection of changes that I am extracting from another PR in order to reduce the complexity there as these changes can stand on their own.
- `App::get_uncached_app(...)` and `App::get_shared_app(...)` have been replaced by `App::get_app(App::CacheMode, ...)`
- The App constructor is now enforced to be unusable by the public.
- Renamed some static variables to have the `s_` prefix.
- Use a checked mutex to help validate locking throughout the API.
> Consolidate app creation to a single method

- test/object-store/sync/app.cpp
- test/object-store/util/test_file.hpp
This appears to have been accidentally reverted to NoEncryption in a bad merge while merging object store into the monorepo (in c51c278c9dd5537992ccba8094d27414a0abedd4). NoEncryption roughly doubles the runtime of the non-baas object store test suite compared to NoMetadata.
Disabling metadata for the baas tests has a much smaller benefit (~10 seconds off the 15+ minute runtime).
> Switch back to disabling metadata storage for most object store tests

- src/realm/sync/network/http.hpp
This PR addresses the comments on https://github.com/realm/realm-core/pull/7222 which were added after the PR was merged.
> Address Chunked Encoding comments

- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/audit.mm
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/async_open_task.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- src/realm/sync/noinst/migration_store.cpp
- src/realm/sync/noinst/migration_store.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
This PR is replacing the inheritance pattern used to instantiate shared-only objects with private tags in the constructors of such classes.
> Use private tags in constructor of shared-only classes

- CHANGELOG.md
- src/realm/sync/client.cpp
- test/object-store/sync/flx_sync.cpp
Pausing and resuming the sync session at a very specific time may cause the next download message to be mistaken for a bootstrap message and crash the application.
Fixes #6611.
> Fix incorrect rebootstrap

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/object.cpp
- test/object-store/c_api/c_api.cpp
This aligns the return type with the `realm_collection_set/insert_collection` API and makes it easier to consume.
> [C-API] Fix the return type of realm_set_collection

- CHANGELOG.md
- src/realm/util/file.cpp
Fixes https://github.com/realm/realm-js/issues/6349 and https://github.com/realm/realm-dotnet/issues/3482.
I think this has emerged as an issue since the change in https://github.com/realm/realm-core/pull/7067 where the compile  time detection of POSIX_FALLOCATE changed.
According to the man pages, `posix_fallocate` can return not supported:
```
EOPNOTSUPP
The filesystem containing the file referred to by fd does
not support this operation.  This error code can be
returned by C libraries that don't perform the emulation
shown in NOTES, such as musl libc.
```
Fortunately for us, we do not rely on this and already have a fallback path so it is simply a matter of handling this error code in the same way. Testing this requires combination of a system that passes our compile time check but …
> Fallback to manually consume space if posix_fallocate isn't supported at runtime

- CHANGELOG.md
- src/realm/query_value.cpp
- src/realm/query_value.hpp
- test/test_parser.cpp
> Support querying with @type on nested collections

- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app_credentials.cpp
- src/realm/object-store/sync/app_credentials.hpp
- src/realm/object-store/sync/mongo_collection.cpp
- src/realm/object-store/sync/mongo_collection.hpp
- src/realm/object-store/sync/sync_user.cpp
- src/realm/object-store/sync/sync_user.hpp
- src/realm/util/bson/bson.cpp
- src/realm/util/bson/bson.hpp
- test/object-store/audit.cpp
- test/object-store/bson.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/test_file.cpp
This is done by defining the interface explicitly and in a way that makes it possible to easily change the underlying implementation. The longer goal is to change this implementation to be able to easily produce BSON according to https://bsonspec.org/spec.html. Doing that makes lookup of elements in a document a bit slower, but building the document from a string faster. So the net result in typical applications as found in App, will be a speedup of ~20% on average.
> Don't leak implementation of BsonDocument and BsonArray to the users.

- CHANGELOG.md
- package-lock.json
- package.json
This upgrades the dependency on `@commander-js/extra-typings` and adds a missing peer dependency on `commander`.
> [bindgen] `commander` dependency upgraded

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query.cpp
- src/realm/query.hpp
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/test_query.cpp
- test/util/unit_test.hpp
This feature was requested by https://github.com/realm/realm-swift/issues/8008.
I also added a small performance improvement for string queries; no need to always convert the constant `std::optional<std::string>` to a `StringData` in the hot query path, it can be done once in the constructor of the query node.
> Lexicographical comparison for string queries

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- test/object-store/sync/flx_sync.cpp
When performing recovery after a client reset, the server version of the recovered changesets is updated with the latest server version. The changesets recovered are *only* the changesets with actual changes, but empty changesets may have been created when a new subscriptions set is committed for example. The server version of such changesets was not updated, leading to `Bad server version` errors during uploads.
The server version is now updated on all entries in the sync history.
Fixes #7279.
> Update server version on all entries in the sync history during client reset with recovery

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/c_api/types.hpp
- test/object-store/c_api/c_api.cpp
Fixes: https://github.com/realm/realm-core/issues/7301
> expose sync user subscribe in the c-api

- CHANGELOG.md
- CMakeLists.txt
- evergreen/config.yml
Fixes https://github.com/realm/realm-core/issues/6537
CMake 3.15.0 was released on July 17, 2019.
CMake 3.22.1 was released on June 1, 2022.
The current latest version is 3.26.4 released in April 2023.
This change does not bump to the very latest because there is no pressing need for the latest features yet and some systems do not have it easily available in their package managers yet etc. Notably, Android Studio comes with CMake 3.22.1 and apparently it is a bit of a hassle to set up a custom cmake path although it can be done.
This change may require SDKs who rely on building core with CMake to also bump their minimum required version.
> The minimum CMake version is now 3.22.1

- CHANGELOG.md
- src/realm/object-store/audit.mm
- test/object-store/audit.cpp
Some tests triggered background work without waiting for it to complete, resulting in a race condition when tearing down.
The specific test where I hit this didn't even need to be opening the audit realm at all so I added a minor optimization to the implementation for that scenario. Setting `automatic_change_notifications` on the test configs is also just a minor optimization that makes the tests a little faster.
> Fix a race condition in audit tests 

- CHANGELOG.md
- bindgen/spec.yml
- bindgen/src/realm_helpers.h
- src/realm.h
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/c_api/config.cpp
- src/realm/object-store/shared_realm.cpp
- src/realm/object-store/shared_realm.hpp
- test/object-store/migrations.cpp
- test/test_upgrade_database.cpp
> Add RealmConfig::needs_file_format_upgrade

- CHANGELOG.md
- src/realm/query_expression.hpp
- test/test_parser.cpp
Fixes https://github.com/realm/realm-java/issues/7862
We had an optimization in Comparison nodes that would try to use an index if comparing a single value constant to an indexed property. This optimization should only apply if the constant's expression comparison type is ALL or ANY because NONE produces different results.
> fix == NONE {x} queries

- test/object-store/sync/app.cpp
This updates some of the app URI redirect tests so they can run with arbitrary baas base URIs rather than requiring `localhost:9090`. I also did some refactoring of some of the hooked transport types so we communicate what the test should do via return value rather than futzing with member variables.
> Fix app URI tests for baasaas

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.hpp
This fixes #7074 and #6844. The problem turned out to be a pretty basic race between the user thread calling `Session::bind()` which sets `m_initiated` to true and the event loop thread trying to activate the session which reads `m_initiated`. Usually there's some waiting for mutexes and some networking activity that has made this race unlikely, but I was able to verify the bug by adding a check for `m_initiated` just earlier in the session setup code.
The fix is to make sure what we update `m_initiated` while holding the sync client's mutex (which also protects the list of tasks to run on the event loop) - that way we know that `m_initiated` cannot be read by the event loop while it's being updated by the user's thread.
There was also a race between the event loop setting `m_finalized` …
> Mitigate races in accessing `m_initated` and `m_finalized` in various REALM_ASSERTs

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_file.cpp
- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- test/object-store/sync/metadata.cpp
- test/object-store/sync/sync_manager.cpp
Checking if the destination of a copy exists before trying to copy is a TOCTOU race because the state of the filesystem can change between when we check and when we perform the copy. We should instead just open the target file and not perform the copy if it already existed.
`clonefile()` is an APFS feature to perform copy-on-write clones of files. This is much faster, and makes it so that the copy and then delete original that we do doesn't consume extra disk space. It's not always supported, so we fall back to manual copying if it fails.
Two of the file action fields weren't actually used for anything.
> File a minor race condition in the backup realm file action

- test/object-store/sync/flx_schema_migration.cpp
- test/object-store/util/sync/baas_admin_api.cpp
- test/object-store/util/sync/baas_admin_api.hpp
In the new baasaas world we don't have access to the backing cluster and the schema migration tests fail. Fortunately there is an admin API endpoint that does exactly what we need. This just updates our tests to use the correct API.
> Schema migration tests to use admin API rather than querying backing cluster

- evergreen/config.yml
- test/object-store/c_api/c_api.cpp
- test/object-store/realm.cpp
Include paths for the tests are set up slightly different for the SPM build from the CMake build.
Enable testing spm on PR jobs as this was previously Jenkins-only.
> Fix SPM compilation errors

- CHANGELOG.md
Changelog downgrade information was not correct. If trying to downgrade an 
```
Provided schema version 6 is less than last set version 7
```
exception will be thrown.
See https://mongodb.slack.com/archives/C010R3CMP3N/p1705057505573319 for details.
> Update to CHANGELOG

- CMakeLists.txt
- bindgen/src/realm_helpers.h
https://github.com/realm/realm-core/pull/7334 incorrectly installed targets when Core is consumed as a submodule. While this is required for vcpkg support other SDK's relied on the original behaviour.
> Don't allow Core targets to be installed if submodule

- CHANGELOG.md
- src/realm/object-store/impl/transact_log_handler.cpp
- test/object-store/realm.cpp
Specific change indices are only applicable to NSArray and not the other collection types, and supplying them actively breaks things.
> Do not populate list KVO information for non-list collections

- CHANGELOG.md
- src/realm/obj.cpp
- test/test_mixed_null_assertions.cpp
Setting a Mixed field to ObjLink equal to the current value removed the existing backlink and then exited before adding the new one, leaving things in an invalid state.
> Don't update backlinks in Mixed self-assignment

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app_credentials.cpp
- src/realm/object-store/sync/mongo_collection.cpp
- src/realm/object-store/sync/mongo_collection.hpp
- src/realm/util/bson/bson.cpp
- src/realm/util/bson/bson.hpp
- src/realm/util/bson/indexed_map.hpp
- test/object-store/sync/app.cpp
- test/object-store/sync/flx_sync.cpp
Returning things by value performs a deep copy, which is very expensive when those things are also bson containers.
Re-align the naming with the conventional names for the functions rather than being unnecessarily different.
> Eliminate copies when accessing values from Bson types

- CHANGELOG.md
- src/realm/query_expression.cpp
- test/test_query.cpp
The base table's allocator was being used to read from the target table.
> Use the correct allocator for queries on dictionaries over links

- src/realm/util/bson/bson.cpp
- test/object-store/bson.cpp
If you construct a Bson object from a std::vector<char>, the  extjson streaming format should encode the binary data in base64.
> Bson object should hold binary data in decoded form

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
> RCORE-1994 Fix passing a double as argument to query on Decimal128

- CHANGELOG.md
- src/realm/collection.cpp
- test/test_parser.cpp
- test/test_query2.cpp
This behavior is indeed weird, but changing it results in a very large number of test failures and introduces a different set of weird behavior: `dict['key'] != $1` and `NOT(dict['key'] == $1)` give different results, with the first excluding objects which are missing the key and the second including them. This change introduced the ability for a keypath to neither equal nor not equal a value which seems at least as weird as the thing it was fixing, and so doesn't justify a breaking change.
An alternative might be to make `!=` behave like `NOT(==)` so that `dict['missing'] == null` doesn't match and `dict['missing'] != null` does, but I didn't see a straightforward way to implement that.
> Treat missing keys in dictionaries as null in queries

- CHANGELOG.md
- src/realm/parser/driver.cpp
- src/realm/query_expression.hpp
- test/test_parser.cpp
This is something which Cocoa and the query engine supports but the core query parser did not. This was broken by the addition of the evaluate(int) override in Columns<Mixed> as it shadows the evaluate(ObjKey) function in the base class, so we need to explicit unhide that function. While trying to add a core test for this I discovered that the core parser just didn't support it, so I added that support.
This is the final thing needed to get all of Cocoa's non-performance tests passing with core 14.
> Allow using aggregate operations on Mixed properties in queries

- CHANGELOG.md
- src/realm/replication.cpp
- src/realm/replication.hpp
Most of the replication log statements do some work including memory allocations which are then thrown away if the log level it too high, so always check the log level first. A few places don't actually benefit from this, but it's easier to consistently check the log level every time.
This makes the obj-c bulk insert benchmark slightly faster than v13.27.0 rather than ~10% slower.
> Avoid doing unneeded logger work in Replication

- CHANGELOG.md
- tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
Explicitly opt-in to the slower bfd linker over gold, because gold in GCC 11.2 doesn't play nice with R_ARM_REL32 relocations and OpenSSL 3.2 started to expose symbols like `OPENSSL_armcap_P` with this kind of relocation.
> Use the bfd linker in the armv7 toolchain

- evergreen/config.yml
This adds a builder to evergreen to compile/run the local tests on 32-bit windows.
> RCORE-1990 Add X86 Windows Release builder to evergreen

- evergreen/config.yml
Fixes linking against libcurl on windows builders in evergreen.
> Use updated curl on evergreen windows hosts

- CHANGELOG.md
- src/realm/bplustree.hpp
- src/realm/set.cpp
- src/realm/set.hpp
- test/util/compare_groups.cpp
Now that Mixed uses the same comparisons as Set we don't need all the support code for using a different order in Set.
> Delete leftover code for Set's order differing from Mixed

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/logging.cpp
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
- test/object-store/c_api/c_api.cpp
> Add ability to get logging level via C API

- test/test_transform_collections_mixed.cpp
@danieltabacaru, I did some futzing with the collections in mixed transform unit tests so there's less boilerplate in each test to have to read/review. If you think this is an improvement I'll keep reviewing collections in mixed after this is merged.
> Reduce boilerplate in collections in mixed unit test

- src/realm/sync/network/network.hpp
Since the DeadlineTimer is not thread safe, added comment that `async_wait()` or `cancel()` must be called from the event loop.
Fixes #7364
> RCORE-1987 network::Service does not start waiting on timers if no other events are currently active

- src/realm/array_direct.hpp
- src/realm/array_encode.hpp
- src/realm/array_flex.cpp
- src/realm/array_flex.hpp
- src/realm/array_packed.cpp
- src/realm/array_packed.hpp
- src/realm/node_header.hpp
> Fix for 32 bit archs for encoded Arrays

- CHANGELOG.md
- src/realm/group.hpp
- src/realm/object-store/impl/collection_notifier.cpp
- src/realm/object-store/impl/collection_notifier.hpp
- src/realm/object-store/impl/deep_change_checker.cpp
- test/object-store/benchmarks/object.cpp
With large notifier counts the lock contention on CollectionNotifier::m_realm becomes a very significant overhead, with unlock() taking upwards of 50% of the total runtime. This is only a problem when the notifiers run on the background thread and the target thread forces a refresh, as there's otherwise no contention. Using an atomic variable to avoid the mutex solves the problem entirely.
std::unordered_map is pretty slow and TableKeys are *almost* dense so we can use a vector instead. This speeds up almost-noop notifications where gathering the related table information is the bulk of the runtime in obj-c by~20%.
Together these speed up one of the obj-c benchmarks from 2.959 seconds to .765 seconds. The newly added object-store benchmark is less dramatic but still goes from 86ms to …
> Improve performance with very large numbers of notifiers

- CHANGELOG.md
- Package.swift
- dependencies.yml
> Release core v14.2.0

- src/realm/array.cpp
- src/realm/array_encode.hpp
- src/realm/node_header.hpp
Visual Studio keeps reporting some warnings on some implicit casting that are indeed safe, considering the layout of the encoded arrays.
> Fix some warnings that Visual Studio keeps reporting

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/obj.cpp
- src/realm/object-store/c_api/list.cpp
- src/realm/object_converter.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_replication.cpp
- src/realm/sync/instruction_replication.hpp
- src/realm/sync/instructions.hpp
- src/realm/sync/transform.cpp
- test/CMakeLists.txt
- test/object-store/sync/client_reset.cpp
- test/test_all.cpp
- test/test_sync.cpp
- test/test_transform.cpp
- test/test_transform_collections_mixed.cpp
Add support to sync collections of Mixed (i.e, List\<Dictionary\>).
This PR contains:
1. Updates to OT rules to account for collections of mixed
2. Set of tests to exercise the OT changes and the InstructionApplier
3. Bug fix (resulting in a crash) of AddInteger (with a higher timestamp) vs Update(other_type) OT rule for Mixed fields
Note: it's easier to review each commit individually.
<details>
<summary>Test Plan:</summary>
Same level of nesting (both on Mixed properties and nested collections):
* CreateArray vs AddInteger (only on Mixed properties)
* CreateDictionary vs AddInteger (only on Mixed properties)
* CreateArray vs UpdateInt
* CreateDictionary vs UpdateInt
* ArrayInsert vs ArrayInsert
* DictionaryInsert vs DictionaryInsert
* CreateArray vs CreateDictionary
* ClearArray vs …
> RCORE-1490 Sync collections in Mixed and nested collections

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/scheduler.cpp
- src/realm/object-store/util/scheduler.cpp
- src/realm/object-store/util/scheduler.hpp
- test/object-store/benchmarks/main.cpp
- test/object-store/test_runner.cpp
This makes it trivially destructible and so eliminates a spurious crash related to reading the variable on one thread while it's being destroyed on another (due to the application exiting). This breaks the C API for registering a custom default scheduler, but that turns out to be unused and so it can be deleted. All users of the C++ scheduler API work with just a function pointer.
Fixes #7420 assuming that issue actually is just a spurious crash and not some other bug. An alternative solution here would be to heap allocate the UniqueFunction as we do for many globals, but cutting down on our global constructors/destructors is a good thing and we currently don't have anything which needs it to be a UniqueFunction.
> RCORE-2001 Make Scheduler's factory function a function pointer rather than a UniqueFunction

- CHANGELOG.md
- src/realm/collection.hpp
- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/object-store/results.cpp
- src/realm/table.cpp
- src/realm/table.hpp
This fixes the one remaining v14 perf regression reported by the object store benchmarks. It ended up being a sort of fake optimization - it makes sum() on empty dictionaries more than twice as fast, but once there's a single object it's only 10% faster and is meaningless for any larger - but IMO it's a net improvement to the code.
> Improve performance of aggregate operations on empty dictionaries

- CHANGELOG.md
- bindgen/spec.yml
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/protocol.hpp
- test/object-store/c_api/c_api.cpp
Added values to the `SyncClientTimeouts` for configuring the SyncSession resumption delay. This work was pulled from the recommendations posted for PR #7365 and separated out into its own pull request since that design is being reworked.
> RCORE-2007 Added Resumption delay configuration to SyncClientTimeouts

- src/realm/array_encode.cpp
- test/test_array_integer.cpp
Changes heuristics governing integer leaf compression.
1. Require compression to packed format to gain at least 12.5% or don't use it.
2. Require compression to flex format to gain at least 25% or don't use it.
This reflects that since the compressed leafs are somewhat slower we want to have a clear gain before compressing.
Changed unittest accordingly.
> changed heuristics governing integer leaf compression

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_direct.hpp
- src/realm/array_encode.cpp
- src/realm/array_encode.hpp
- src/realm/array_flex.cpp
- src/realm/array_flex.hpp
- src/realm/array_integer.cpp
- src/realm/array_integer_tpl.hpp
- src/realm/array_packed.cpp
- src/realm/array_packed.hpp
- src/realm/array_unsigned.cpp
- src/realm/parser/generated/query_flex.cpp
- src/realm/parser/generated/query_flex.hpp
- test/test_array_integer.cpp
Avoid to compute the same mask over and over again inside parallel subscan.
The PR has become a little bit bigger and overlaps with  https://github.com/realm/realm-core/pull/7447 .
I think we should first merge 7447 and the go ahead with this. 
This commit: 1b1532e8c2d9b85fe77607b76e6db1ba86087c3e has introduced the same concept we have for Array, essentially a vtable used for fetching the right implementation based on the type of encoding we are in. 
The vtable is set during the init phase, which happens when the array is converted into a compressed format (during a commit).
Perf wise, timestamps are as fast as integers or even faster than current master implementation.
> Improve queries for encoded arrays.

- CHANGELOG.md
- src/realm/collection.hpp
- src/realm/collection_parent.hpp
- src/realm/dictionary.hpp
- src/realm/list.hpp
- src/realm/obj.hpp
- test/test_list.cpp
The parent of a nested collection will always be up to date after making a modification to the collection as we update it prior to performing the modification and the modification cannot make the parent stale. Failing to update the parent's content version meant that the parent was always considered stale after an update to a child collection, resulting in the child getting updated between each modification even when the modifications were all done via a single accessor.
> Update the parent's content version when bumping it in a nested collection

- CHANGELOG.md
- src/realm/group.cpp
For encrypted files we always write data in page sized increments, so using a buffer smaller than the page size results in writing the same page multiple times. On arm64 Apple platforms, this was a problem for files between 16 KB and 4 MB.
> Set the minimum buffer size in Group::write() to be equal to the page size

- CHANGELOG.md
- src/realm/collection_parent.hpp
Fix depth for nested collections in debug mode in order to avoid to break tests in debug mode for SDKs.
Fixes (https://github.com/realm/realm-core/issues/7484)
> RCORE-2028 fix depth for nested collections set to 4 in debug mode

- CHANGELOG.md
- src/realm/collection.cpp
- src/realm/collection.hpp
- test/test_list.cpp
> RCORE-2005: Include nested path in 'OutOfBounds' error message

- evergreen/install_baas.sh
Makes install_baas.sh work on linuxmint.
> Derive correct ubuntu version on linuxmint

- src/realm/cluster.cpp
Disable timestamps for compressed arrays.
> Disable timestamps for compressed arrays.

- dependencies.yml
Bumping baas version to get the fix for "Test client migration and rollback with recovery" flakeyness.
> RCORE-2008 Bump baas version

- src/realm/array_direct.hpp
- src/realm/array_encode.cpp
- src/realm/array_flex.cpp
- src/realm/array_flex.hpp
- src/realm/array_packed.cpp
- src/realm/array_packed.hpp
- src/realm/cluster.cpp
Heuristics for parallel subscan in flex format in order to limit subscan only to large range queries. 
~6x better on range queries.
> Heuristics parallel subscan flex

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/app.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/sync/baas_admin_api.hpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/object-store/util/sync/sync_test_utils.hpp
- test/object-store/util/test_file.cpp
- test/object-store/util/test_file.hpp
- test/object-store/util/test_utils.hpp
- test/object-store/util/unit_test_transport.hpp
Updated the sync_route provided to then `SyncManager` so it receives a generated initial value that should be correct most of the time. If the websocket fails to connect using this value, the Session will force a location update attempt (via updating the access token) to request the proper websocket address using the current base URL. If that fails, the Session will use the current connection reconnect timer to try again after the usual holdoff.
A "verified" flag was added to determine if the websocket address was either provided via a location request or has been successfully connected to prevent excessively querying the location endpoint.
In addition, when the sync route is updated via a call to `SyncManager::set_sync_route()`, this function will also restart the existing sessions to …
> RCORE-1982 Opening realm with cached user while offline results in fatal error and session does not retry connection

- CHANGELOG.md
- src/realm/array_mixed.cpp
Working on compressing collections in mixed, I noticed that we allow col type Set to be stored inside a Mixed. 
There should be no way to get into Array Mixed via the API, but better to be safe IMO.
> Disallow Set inside ArrayMixed

- bindgen/spec.yml
* Add std::chrono::milliseconds as primitive type. 
* Update return value of SyncSession::full_realm_url.
Closes #7506
> RCORE-2037: [bindgen] smaller fixes after 14.4.0

- src/realm/array_encode.cpp
- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- test/test_list.cpp
Enable support for compressing Mixed and Collection in Mixed.
> Compression for leaf Mixed arrays of integers and collection in mixed. 

- src/realm/array.cpp
- src/realm/array_encode.cpp
- src/realm/bplustree.cpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- test/test_list.cpp
We have added a bunch of assertions in some critical path of the code that are slowing down a bit the commit machinery, and also while reading the file. 
Demoting them to debug, since they are not needed in release mode. 
It depends on https://github.com/realm/realm-core/pull/7501 to be merged.
> Demote some assertions inside commit hot path to trigger only in debug mode

- CHANGELOG.md
- test/object-store/CMakeLists.txt
Updates the libuv we use in the object store tests so we get the fixes from https://github.com/libuv/libuv/issues/3683 in our tsan runs.
> RCORE-1984 Upgrade libuv to v1.48.0 for object-store tests

- CHANGELOG.md
- bindgen/spec.yml
Made `set_default_logger` nullable in `spec.yml` to allow the SDK to remove the default logger entirely.
> Made `set_default_logger` nullable in `spec.yml`

- tools/release-init.sh
The git submodules had not been updated prior to running the `tools/release-init.sh` script, which lead to a stale version of `external/catch` to be committed to the release.
This update ensures the submodules are initialized and up to date prior to starting the release process. It also adds help text to help with running this script.
> Update 'release-init.sh' script to update git submodules prior to starting the release process

- CHANGELOG.md
- src/realm/util/interprocess_mutex.cpp
- src/realm/util/interprocess_mutex.hpp
[This was added to reduce the number of file descriptors used](https://github.com/realm/realm-core/pull/1986/commits/dca07db60e6ee1691ec79c80ccc9f415d8e17b82) back when we opened a separate SharedGroup on each thread. We now normally only ever open one DB per file per process at a time, so sharing files between them is no longer useful and it's been the source of a few bugs.
Fixes https://github.com/realm/realm-swift/issues/8507 by just removing the code containing the assertion entirely.
> RCOCOA-2301 Remove the emulated InterprocessMutex File cache

- src/realm/collection_parent.cpp
- src/realm/dictionary.cpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- test/object-store/object.cpp
- test/test_list.cpp
Eg. List::clear should replicate even though the list is already empty. Obj::set should replicate even though old and new values are equal.
This has influence on OT. If you want to assign new values to an empty list and does not replicate the clear instruction you could end up having your values added to some content added by another client.
> Make sure we replicate instructions unconditionally

- CHANGELOG.md
- bindgen/spec.yml
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/app.cpp
Updated default base url to `https://services.cloud.mongodb.com`.
The default base url string value can be retrieved using `App::default_base_url()` static accessor or the `realm_app_get_default_base_url()` C_API function.
Fixes #7449
> RCORE-2010 Update default base URL to new domain

- CHANGELOG.md
- src/realm/list.hpp
- test/object-store/object.cpp
- test/test_transform.cpp
We have a replication bug when setting default null values (embedded objects included). This used to generate two sync instructions, and the first one did **not** take is_default into account. If it is then merged with an instruction with is_default = true, it wins the conflict resolution (default values lose to non-default values) when maybe it shouldn't have (when both are default values, the timestamp is used as a tiebreak).
The bug was fixed in #7523 (among other things), and this PR adds a unit test for it an updates the changelog.
This PR also **reverts** replicating the clear instruction on empty lists (introduced in #7523). There is no need for a changelog entry since it was not released.
* ~~[ ] `bindgen/spec.yml`, if public C++ API …
> RCORE-1980 Add unit test and changelog entry for replication bug

- src/realm/alloc_slab.cpp
- src/realm/array.cpp
- src/realm/array_direct.hpp
- src/realm/array_encode.cpp
- src/realm/array_encode.hpp
- src/realm/array_flex.cpp
- src/realm/array_flex.hpp
- src/realm/array_packed.cpp
- src/realm/array_packed.hpp
- src/realm/utilities.hpp
- test/test_array.cpp
1. Mainly Inlining array packed and array flex getters and other function table APIs for compressed arrays, marginally better nothing big. 
2. Deleting most of the code related to find_all, adding a single templated function.
3. Adjusted heuristic for flex arrays (width of indices is not really important, it is max 8)
4. Construct the iterators for accessing the data only once (since they will be valid as long as the array is in compressed format)
> Inlining main getters for ArrayEncode 

- src/realm/object-store/sync/app.cpp
As was pointed out by customer help ticket [HELP-57538](https://jira.mongodb.org/browse/HELP-57538), the current app "`do_authenticated_request()`" debug is confusing when the server URL location info needs to be updated. When the app is started, the debug output for first app request will potentially show as being sent to the original base URL value instead of the actual server URL.
Updated the App debug output so the request URL is displayed in the `do_request()` function or before sending the request after the location has been updated.
Original debug example:
```
Debug: App: do_authenticated_request: POST https://realm.mongodb.com/api/client/v2.0/app/securehealth-gtcux/functions/call
Debug: App: request location: https://realm.mongodb.com/api/client/v2.0/app/securehealth-gtcux/location …
```
> RCORE-2062 Update App debug statements to show final request URL before sending

- CHANGELOG.md
- bindgen/src/formatter.ts
- package.json
The `clang-format` package is unmaintained https://github.com/angular/clang-format/issues/82#issuecomment-1748482685 and it doesn't publish arm64 based binaries. I suggest we remove the dependency and rely on the binary provided by the system instead.
> Use the "clang-format" provided by the system

- CHANGELOG.md
- src/realm/collection_parent.cpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/realm.cpp
Fixes #7434 
I was not able to reproduce the problem, so mayby we are not getting the full picture. But this change will at lease prevent a nullpointer exception if the transaction is terminated.
> RCORE-2004 Make Realm::call_completion_callbacks() resilient to trasaction being deleted

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
Trying to build Core for an iphone simulator by invoking:
```
./tools/build-apple-device.sh -p iphonesimulator -c Debug -v 14.4.1 -f -DREALM_BUILD_LIB_ONLY=1
```
yields the following error to me:
```
realm-core/src/realm/sync/noinst/client_impl_base.cpp:2368:60: error: 
'value' is unavailable: introduced in iOS 12.0
int64_t query_version = is_flx ? message.query_version.value() : 0;
```
> Follow-up to make #7124 target iPhone 11

- CHANGELOG.md
- bindgen/spec.yml
- src/realm.h
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/impl/apple/keychain_helper.cpp
- src/realm/object-store/impl/apple/keychain_helper.hpp
- src/realm/object-store/sync/impl/sync_metadata.cpp
- src/realm/object-store/sync/impl/sync_metadata.hpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- src/realm/sync/network/network_ssl.cpp
- src/realm/util/cf_str.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/sync/metadata.cpp
- test/object-store/sync/sync_manager.cpp
- test/object-store/sync/user.cpp
Access groups are shared storage for one or more apps on iOS (and other Apple platforms). Sharing a metadata Realm between apps requires placing the file in the access group storage and storing the encryption key in the access group's keychain.
Including the bundle ID in the service name breaks sharing the key between apps, as different apps will have different bundle IDs. For everything but un-sandboxed macOS there wasn't actually any reason to include the bundle ID in the first place, as each app has its own keychain anyway. As such, this switches back to not including it. On macOS this continues to include the bundle ID when not using an access group, as otherwise different applications could conflict with each other. This means that sharing users between macOS applications will …
> RCORE-2070 Allow setting a security access group for the metadata realm keychain

- CHANGELOG.md
- Package.swift
- src/realm/PrivacyInfo.xcprivacy
Fixes https://github.com/realm/realm-swift/issues/8535.
It appears that the core xcframework doesn't need a privacy manifest (since it doesn't end up in the final app binary), but the Swift package does as the SPM build does properly track the provenance of each component. The manifest is a direct copy of the one from the obj-c framework.
> RCOCOA-2328 Add a privacy manifest to the Swift package

- src/realm/object-store/impl/apple/keychain_helper.cpp
- src/realm/sync/network/network_ssl.cpp
This requires iOS 11.3 and we currently target iOS 11. No changelog entry since this didn't make it into a release.
> Add missing availability checks for SecCopyErrorMessageString

- src/realm/object-store/impl/apple/keychain_helper.cpp
Current master does not compile for iOS.
Fixed by changing a target conditional in `keychain_helper.cpp`. TARGET_OS_OSX means only mac, where as TARGET_OS_MAC includes iPhone, tvOS, etc. (see `TargetConditionals.h`). Apple works in mysterious ways.
Fixes: #7580 
~~📝 Changelog update~~
~~🚦 Tests (or not relevant)~~
~~C-API, if public C++ API changed~~
~~`bindgen/spec.yml`, if public C++ API changed~~
> RCORE-2080: Use the correct target conditional

- src/realm/dictionary.cpp
- src/realm/dictionary.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- test/test_sync.cpp
It is only safe to use get_dictionary/get_list on a collection that is either at level 1 or if referenced by a shared pointer. The collection created in instruction_applier is always stack allocated and can be at any level.
Fixes #7573
> Use proper constructor when clearing links is nested collections

- src/realm/sync/network/network_ssl.cpp
The object store test "sync: error handling" started failing for me locally after pulling in the latest changes. Looks like the buffer was accidentally scoped too narrowly when we added the availability checks.
This seems to be passing on CI, but on my machine I saw the following:
```
-------------------------------------------------------------------------------
sync: error handling
reports TLS error as handshake failed
-------------------------------------------------------------------------------
/Users/james.stone/Documents/code/realm-core3/test/object-store/sync/session/session.cpp:390
...............................................................................
/Users/james.stone/Documents/code/realm-core3/test/object-store/sync/session/session.cpp:404: FAILED:
CHECK( …
```
> fix accidental use after free

- src/realm/node_header.hpp
> Fix encoding enum numbers

- CHANGELOG.md
- src/realm/alloc.hpp
- src/realm/alloc_slab.cpp
- src/realm/util/encrypted_file_mapping.cpp
- src/realm/util/encrypted_file_mapping.hpp
- src/realm/util/file.cpp
- src/realm/util/file.hpp
- src/realm/util/file_mapper.cpp
- src/realm/util/file_mapper.hpp
- test/test_alloc.cpp
- test/test_encrypted_file_mapping.cpp
- test/test_shared.cpp
Fixes https://github.com/realm/realm-core/issues/7322
This is also suspected to fix:  https://github.com/realm/realm-core/issues/7252, https://github.com/realm/realm-core/issues/7319, https://github.com/realm/realm-core/issues/6752
There was a regression due to the changes in https://github.com/realm/realm-core/pull/6807. Those changes moved the file expansion out of `SlabAlloc::attach_file` but this had the side effect that the actual file size is used when updating the reader view rather than using a multiple of the page_size(). 
Users reported this regression since swift [v10.42.0](https://github.com/realm/realm-swift/blob/master/CHANGELOG.md#10420-release-notes-2023-07-30) which matches the release of the change in core version v13.17.1.
I had originally thought that we did not …
> RCORE-1969 Fix bundled encrypted Realm regression

- CHANGELOG.md
- src/realm/util/future.hpp
- test/test_util_future.cpp
Promise needs to update `m_shared_state` before fulfilling the promise, as `Future::get()` on another thread could return before the write occurs. If the Promise is destroyed immediately after `get()` returns, the destructor could then read the non-null value of `m_shared_state` before the write happens and attempt to report a broken promise error, which hits an assertion.
This was introduced in the port from the mongo version of this code and this change realigns it with what that code does. A repro test which more closely matches the actual scenario that was breaking is the following, which *eventually* hits the assertion failure:
```c++
while (true) {
auto pf = util::make_promise_future<void>();
std::thread([&] {
pf.promise.emplace_value();
}).detach();
pf.future.get();
}
```
We don't …
> Fix a race condition in Promise

- src/realm/sync/changeset_parser.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/transform.cpp
- test/test_transform_collections_mixed.cpp
Given the Clear instruction now has the collection type information, some adjustments have been made to the OT rules:
1. Clear vs Update (same type) => no conflict
2. Clear vs Update (different types) => the tiebreaker is used
3. Clear vs AddInteger => Clear wins
> RCORE-2015 Merge rules for Clear instruction

- src/realm/group.cpp
- src/realm/group.hpp
- src/realm/sync/noinst/sync_schema_migration.cpp
- src/realm/table.cpp
- src/realm/table.hpp
- test/object-store/sync/flx_schema_migration.cpp
During a schema migration all tables are deleted from the realm. Deleting a column linking to a table already deleted leads to a crash. This PR fixes it by firstly removing all columns and only after that the tables. There is no need for a changelog entry because the feature is not released yet.
> Schema migrations: Remove columns before removing the tables

- test/util/unit_test.cpp
We observed a strange [test run](https://spruce.mongodb.com/task/realm_core_stable_macos_14_arm64_test_on_exfat_patch_bfcc09f8681ed259f43ad946aa44a3f57d37e833_66292e0874d607000726b9fc_24_04_24_16_06_34/logs?execution=0) that logs a test failure, but still marks the suite as successful. 
I think this could be due to a release mode code optimization that runs the check on `errors_seen` before it was changed. Regardless, it should be guarded by the mutex.
```
[2024/04/24 09:12:39.996] Platform: macOS Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103 arm64
[2024/04/24 09:12:39.996] Encryption: Enabled at compile-time (always encrypt = no)
[2024/04/24 09:12:39.996] REALM_MAX_BPNODE_SIZE = 1000
[2024/04/24 09:12:39.996] …
```
> modify errors_seen under lock to avoid race

- bindgen/spec.yml
#7300 comes with a number of breaking changes and new APIs. This PR follows up on #7300 to work around some limitations in the Binding Generator. Moreover, the PR fixes a couple of typos.
* ~[ ] 📝 Changelog update~
* ~[ ] C-API, if public C++ API changed~
* ~[ ] `bindgen/spec.yml`, if public C++ API changed~
> [bindgen] follow up to #7300

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
This is a follow-up on https://github.com/realm/realm-core/pull/7300, where we restore the ability for SDKs to construct a fake user for testing when actual sync session is not necessary. This is only intended to be used for tests and should never be exposed to users.
Fixes https://github.com/realm/realm-core/issues/7633.
> RCORE-2100: Restore ability to create test users

- evergreen/config.yml
- src/realm/CMakeLists.txt
- src/realm/util/encrypted_file_mapping.cpp
- test/object-store/sync/metadata.cpp
- test/test_sync_history_migration.cpp
- test/test_sync_subscriptions.cpp
This adds two builders we ran in Jenkins to evergreen. The small BPNode builder runs the core/sync/local obj store tests with small BPNodes to force core to aggressively split BPNodes. The no encryption disables encryption support entirely at compile time rather than just not running tests with encryption enabled.
~* [ ] 📝 Changelog update~
~* [ ] C-API, if public C++ API changed~
~* [ ] `bindgen/spec.yml`, if public C++ API changed~
> RCORE-1991 Add small BPNode/no encryption builders

- CHANGELOG.md
- CMakeLists.txt
12d53fc139cbc48350e5805d2ee58e733f2d95e8 made it so that REALM_BUILD_LIB_ONLY did not disable building the tests, which broke building for platforms where the tests aren't supported.
> Fix building for Apple devices

- evergreen/config.yml
Moving the exfat testing back to x86_64/macos 11 builders while we troubleshoot the macos 14 timeouts
> Temporarily revert exfat changes

- CHANGELOG.md
- evergreen/config.yml
- src/external/IntelRDFPMathLib20U2/CMakeLists.txt
- src/external/bson/CMakeLists.txt
- src/external/bson/bson-macros.h
- src/external/bson/bson-types.h
- src/realm/object-store/object_store.cpp
- src/realm/object-store/sync/impl/app_metadata.cpp
- src/realm/object-store/sync/sync_manager.cpp
- src/realm/object-store/sync/sync_manager.hpp
- test/object-store/CMakeLists.txt
- test/object-store/benchmarks/main.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/util/test_file.cpp
- test/test_encrypted_file_mapping.cpp
We used to have the Jenkins error parser that made the job fail if there were any warnings, but now we have nothing and warnings can slip through. This is a little worse as it makes the build fail immediately rather than letting it run the tests, but it's better than nothing.
> Build with -Werror on CI

- CHANGELOG.md
- src/realm/query_engine.cpp
- src/realm/query_engine.hpp
- test/test_parser.cpp
- test/test_query2.cpp
I think this should fix https://github.com/realm/realm-core/issues/7642
There were two issues I discovered:
- Indexes were still being used when conditions had been combined
- It has been tradition that integer queries accept double values as input because JS passes all numbers as doubles.
> RCORE-2102 Query in fixes

- CHANGELOG.md
- Package.swift
- dependencies.yml
Prepare release 14.6.2
This release is needed since the changes for PR #7650 did not make it into the 14.6.1 release when it was tagged.
> Prepare release v14.6.2

- bindgen/spec.yml
In [this commit](https://github.com/realm/realm-core/commit/978ae24bd68f337efb118fb747d4aaca5f7642e9#diff-6423f65e7503b75f69dfdb175adc29ad7ee3ca341f3301466ef202e56ccfa93d) the signature of `update_base_url` was changed, but `spec.xml` wasn't updated to match it.
> [bindgen] fix signature of update_base_url

- CHANGELOG.md
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/app.hpp
- test/object-store/sync/app.cpp
App::switch_user() emitted changes without first releasing the lock on m_user_mutex, leading to a deadlock if anyone inside the listener tried to acquire the mutex. The rest of the places where we emitted changes were correct.
The newly added wrapper catches this error when building with clang.
Fixes #7670.
> RCORE-2112 Fix a deadlock when accessing current user from inside an App listener

- CHANGELOG.md
- src/realm/dictionary.cpp
- test/test_dictionary.cpp
Fixes https://github.com/realm/realm-core/issues/7676
This regression was caused by https://github.com/realm/realm-core/pull/7523
I couldn't cause any hard crashes or exceptions so it is hard to say that this has been observed outside of niche query cases.
This is because we have previously chosen to ignore nullifying backlinks that point to an object that no longer exists, since https://github.com/realm/realm-core/pull/6638
> RCORE-2115 Fix multiple backlinks created by dictionary

- CHANGELOG.md
- src/realm/array_backlink.cpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/replication.cpp
- src/realm/replication.hpp
- src/realm/table.cpp
- test/test_list.cpp
> RCORE-2108: Clear backlinks when object containing nested collections is deleted

- CHANGELOG.md
- dependencies.yml
- src/realm/object_converter.cpp
- src/realm/object_converter.hpp
- src/realm/sync/changeset.cpp
- src/realm/sync/instruction_applier.cpp
- src/realm/sync/instruction_applier.hpp
- src/realm/sync/noinst/client_reset_recovery.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_sync.cpp
The recovery of local instructions operating on nested collections follows closely the recovery of operations on embedded objects (you can think of a nested dictionary or list as an embedded object). 
Notably:
- list operations (including accessing an element in an intermediate list) are only applied if they involve elements inserted during the recovery, otherwise the entire list is copied verbatim
- clearing a collection sets the collection type too (even if it was changed remotely), essentially allowing to recover subsequent operations on that collection
Additionally, I fixed a crash when recovering AddInteger instructions on a non-integer value (changed remotely).
Fixes #7490.
> RCORE-2030 Add full support for automatic client reset for collections in mixed

- .clang-format
- src/realm/object-store/audit.mm
- test/object-store/audit.cpp
Set the correct schema version in audit test using flx realm.
Fixes #7688.
> RCORE-2121 Fix audit test

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- test/object-store/sync/session/progress_notifications.cpp
- test/test_sync.cpp
This is split up into a few commits.
1) Contains the functional changes - basically reverts the object-store behavior of progress notifications back to [before the latest changes](https://github.com/realm/realm-core/commit/255cb33d838122e23fae4685dc253d708aac435e) and reverts the tests back to before the latest changes. Not sure the best way to review this in github, but the tests should look like they did in https://github.com/realm/realm-core/commit/255cb33d838122e23fae4685dc253d708aac435e, only with the query_version threaded through for FLX and checks progress estimates for PBS are what we expect them to be based on the old behavior.
2) Adds a bunch of unit-tests for FLX sync where we test the new progress estimates for FLX sync under various circumstances.
3) Adds some integration …
> RCORE-2099 Restore progress notifier behavior when sync session is already caught up

- src/realm/exec/CMakeLists.txt
Updated target link libraries list for the `realm2json` executable to remove the "duplicate libraries" warning:
```
[552/847] Linking CXX executable src/realm/exec/realm2json-dbg
ld: warning: ignoring duplicate libraries: 'src/realm/librealm-dbg.a'
```
The link libraries for `realm2json` were updated to match that of the `SyncServer` in _src/realm/sync/noinst/server/CMakeLists.txt_, which imports the same libraries.
> Removed duplicate library warning when building realm2json

- evergreen/config.yml
Upload also the realm file if the fuzzer fails, in order to reply the fuzzer locally using the input crash file and apply it to the same input file.
> Upload also the realm file when the fuzzer fails

- Android.bp
- CHANGELOG.md
- src/realm/object-store/util/scheduler.cpp
- tools/generate-version-numbers-for-soong.sh
This adds vendor support for Android Blueprints and is a prerequisite for RCPP-47
> Add vendor support to Android blueprints

- CHANGELOG.md
- src/realm/util/thread.cpp
- src/realm/util/thread.hpp
- src/realm/util/thread_exec_guard.hpp
- test/test_lang_bind_helper.cpp
- test/test_shared.cpp
- test/test_thread.cpp
- test/util/thread_wrapper.hpp
- test/util/unit_test.cpp
This was a backport of std::thread to C++03 and we haven't needed it for a long time. std::thread doesn't expose set_name(), so that remains.
The other things in thread.hpp are still relevant for robust and process shared mutexes.
> Delete the old pre-c++11 Thread implementation

- evergreen/config.yml
This adds a package task to the ubuntu 20.04 builder to build artifacts for the baas server team. It also runs the OT unit tests in the mode where they dump all the generated changesets for the baas server team to use in testing.
> RCORE-1997 RCORE-2113 Add baas artifact generation to evergreen

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
The parser will throw later anyway if the comparison cannot be done.
Fixes #7714
> RCORE-2131: Don't throw immediately when convertion of string to number fails

- test/realm-fuzzer/fuzz_configurator.cpp
Fixes: https://github.com/realm/realm-core/issues/7716
> RCORE-2132 fix fuzzer bootstrap when encryption key is not provided

- .github/workflows/make-release.yml
- .github/workflows/prepare-release.yml
- tools/release-init.sh
Related to https://github.com/realm/realm-core/pull/7566 and https://github.com/realm/realm-core/pull/7726.
Fixes based on the error reported in this [run](https://github.com/realm/realm-core/actions/runs/9214708552/job/25351498106).
The error is
```
Rebasing commits made to branch 'master' on to base branch 'refs/heads/master'
fatal: refusing to fetch into branch 'refs/heads/master' checked out at '/home/runner/work/realm-core/realm-core'
```
This is because I had set the `base` parameter unnecessarily, and the action wasn't smart enough to know that it should be a no-op. According to the [docs](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#providing-a-consistent-base):
> There may be use cases where it makes sense to execute the workflow on a …
> RCORE-2134 GHA release script fixes

- CHANGELOG.md
- Package.swift
- dependencies.yml
Commits since the last release:
4cfdcd65b GHA release script fixes (#7727)
e3d053b2d update scripts for CI (#7726)
94c8f6772 RCORE-2134 automate the release process (#7566)
5d1d15067 fix fuzzer bootstrap when encryption key is not provided (#7722)
3648014ff RCORE-2131: Don't throw immediately when convertion of string to number fails (#7715)
de18fc379 RCORE-1997 RCORE-2113 Add baas artifact generation to evergreen (#7692)
37be84048 Delete the old pre-c++11 Thread implementation (#7696)
93d5fffbd Add vendor support to Android blueprints (#7614)
4b38b44a5 Upload also the realm file when the fuzzer fails (#7700)
0c72dc336 Fix error message
c6cb1ef17 Removed duplicate library warning when building realm2json (#7710)
c280bdb17 RCORE-2099 Restore progress notifier behavior when sync session is …
> Prepare for 14.8.0

- src/realm/object-store/util/scheduler.cpp
> Fix compilation of scheduler on Android

- src/realm/list.cpp
- src/realm/set.cpp
- test/expected_xjson_linkset1.json
- test/expected_xjson_plus_linkset1.json
> Include '$set' in set of links

- CHANGELOG.md
- src/realm/sync/changeset.cpp
- src/realm/util/overload.hpp
util::overload hits https://developercommunity.visualstudio.com/t/runtime-stack-corruption-using-stdvisit/346200, which has been fixed in the latest version of Visual Studio but not the version we have installed on evergreen (including on the vsCurrent builders). We switched away from using it in one place in https://github.com/realm/realm-core/pull/4825 due to this bug, but the core tests also hit this when run with debug runtime checks enabled. This change works around the bug so that util::overload works.
> RCORE-2140 Work around a VC++ bug in util::overload

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/object-store/c_api/types.hpp
- src/realm/object-store/sync/impl/sync_client.hpp
- src/realm/object-store/sync/sync_session.cpp
- src/realm/sync/binding_callback_thread_observer.hpp
- src/realm/sync/client.cpp
- src/realm/sync/client.hpp
- src/realm/sync/network/default_socket.cpp
- src/realm/sync/network/default_socket.hpp
- src/realm/sync/network/network.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/util/future.hpp
- src/realm/util/scope_exit.hpp
- test/benchmark-sync/bench_transform.cpp
- test/sync_fixtures.hpp
- test/test_client_reset.cpp
- test/test_sync.cpp
- test/test_util_scope_exit.cpp
Some preparatory refactoring before adding a bunch of complexity around handling not being able to acquire the sync agent.
Initializing a sync::Session was a multi-step process of creating the Session with a config, configuring some additional things via mutation functions, and then calling bind(). Over time we've gradually reduced how many things were set via mutation functions or parameters to bind(), and now there was only two left. Both of them can easily be pushed to the Config struct, so the explicit bind() step is no longer needed and SessionWrapper can initialize immediately, eliminating one of the states that it can be in and letting us make more of the members const.
> RCORE-2092 Simplify the SessionWrapper lifecycle a bit

- src/realm/array_direct.hpp
- src/realm/integer_compressor.hpp
- src/realm/integer_flex_compressor.hpp
- src/realm/integer_packed_compressor.hpp
- src/realm/query_conditions.hpp
- src/realm/query_state.hpp
- test/test_array.cpp
> Getting rid of some glue code

- evergreen/config.yml
- evergreen/hang_analyzer/requirements.txt
The hang analyzer became disconnected due to a variable working dir, incorrect precondition checks on the requirements.txt file, and the python venv being updated to 3.12.
* Update paths to use `realm-core` as the working directory.
* Change `-d` check to `-f` check for `requirements.txt` precondition.
* Add `setuptools` to `requirements.txt` because [`distutils` is no longer included with python3.12](https://docs.python.org/3/whatsnew/3.12.html).
> RCORE-2148 Reconnect Hang Analyzer to evergreen

- Android.bp
- CHANGELOG.md
- src/realm/mixed.cpp
Adds missing `REALM_APP_SERVICES` flag to blueprint and addresses warning in `mixed` due to lack of break or fall through.
> Add missing flag to Android blueprint

- CHANGELOG.md
- src/realm/group.cpp
- test/test_shared.cpp
This will ensure that the current history version is written, so that an upgrade will not be required when opening the file.
Fixes #7747
> RCORE-2145: Output InRealmHistory when compacting

- .github/workflows/make-release.yml
- .github/workflows/prepare-release.yml
- doc/development/how-to-release.md
- tools/release-init.sh
Related to https://github.com/realm/realm-core/pull/7566 https://github.com/realm/realm-core/pull/7726 and https://github.com/realm/realm-core/pull/7727
The make-release action failed near the [end](https://github.com/realm/realm-core/actions/runs/9216410854/job/25356630029):
```
Run juliangruber/merge-pull-request-action@9234b8714dda9a08f3d1df5b2a6a3abd7b695353
with:
github-token: ***
number: 77[2](https://github.com/realm/realm-core/actions/runs/9216410854/job/25356630029#step:8:2)9
method: squash
env:
PULL_REQUEST_NUMBER: 7729
Error: At least 1 approving review is required by reviewers with write access. - https://docs.github.com/articles/about-protected-branches
```
realm-core doesn't allow merging without reviewers which is a protection we have in place for a reason. 
Until we can …
> RCORE-2134 touch up the GHA release process based on the first full run

- .github/workflows/make-release.yml
- .github/workflows/prepare-release.yml
https://github.com/realm/realm-core/pull/7730 added a summary, but the syntax didn't work: https://github.com/realm/realm-core/actions/runs/9323985651/workflow
> RCORE-2134 fix output syntax

- test/object-store/sync/flx_schema_migration.cpp
Some of the schema migration tests test the recovery of subscriptions and objects after a schema migration. This requires that the subscriptions and objects are committed when the synchronization session is paused so nothing is uploaded. `SyncSession::pause()` is used for this, but pause is an async operation so there is a race between pausing the session and uploading the data and subscriptions. `SyncSession::shutdown_and_wait()` is used instead.
Fixes #7767.
> RCORE-2151 Fix race in schema migration tests

- Package.swift
A bunch of old obsolete test files were removed as part of PR #7695, but an exclude entry for one of the items removed was still in the `Package.swift` xcode project file, which led to a warning when that file was opened in XCode. This PR removes that line that is no longer used to remove the warning.
> Fix XCode warning after 'notifications-fuzzer' directory was removed

- src/realm/sync/noinst/pending_bootstrap_store.cpp
This reverts commit afe0e0f3b57d57d93215f1c9ec9d5a2b1beafbb7.
DisableReplication actually disables replication on the DB, not the Transaction, so it's extremely unsafe to use. This was a very minor optimization so it's not worth doing if there's anything complicated about it.
> Revert "Disable replication when writing to the pending bootstrap store"

- .github/workflows/prepare-release.yml
- .gitignore
- tools/release-init.sh
As discussed in the round table today, we'd like the automated process to check that the base branch is in a releasable state. This gives us confidence in the release, and allows us to skip evergreen checks on "changelog/version" only changes in the release process.
These script changes use the Github API to check the status of the commit being released. It writes the status in the "prepare" PR description along with a link to the build page. This is a non-blocking way of quickly seeing the state of the build without requiring that it pass to release. This allows us to manually inspect the build and make a release even if there are failing checks that have been deemed "sporadic failures" by the releaser.
> Add a check to verify the base commit build status in the release process

- .github/workflows/make-release.yml
> Use environment in make-release.yml

- src/realm/array.hpp
- src/realm/array_integer_tpl.hpp
- src/realm/query_engine.hpp
- test/test_query.cpp
- test/util/test_path.cpp
If you are just testing one element, use simple compare instead of leaf->find_first. This will speed up queries where secondary nodes are IntegerNodes.
> Optimize IntegerNode::find_first_local

- .github/workflows/prepare-release.yml
Starting a release [failed](https://github.com/realm/realm-core/actions/runs/9421105486/job/25954419353) due to not finding the github token in the environment. Related to the changes in https://github.com/realm/realm-core/pull/7775. This was [documented](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) as a requirement, but somehow I missed this and it wasn't required when I tested the script locally because I was signed in to my account. This should fix it.
> The GHA release script requires a token in the environment

- CHANGELOG.md
- src/realm/object-store/impl/realm_coordinator.cpp
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/async_open_task.hpp
- test/object-store/sync/flx_sync.cpp
Opening an FLX realm asynchronously may not wait to download all data. We changed it so the asynchronous task now waits until all subscriptions finish bootstrapping.
Fixes #7720.
> RCORE-2135 Make AsyncOpenTask wait until all pending subscriptions finish bootstrapping

- src/realm/array.cpp
- src/realm/array.hpp
- src/realm/array_string.cpp
- src/realm/node.hpp
- src/realm/string_compressor.cpp
- src/realm/string_compressor.hpp
- src/realm/string_interner.cpp
- src/realm/string_interner.hpp
- src/realm/table.cpp
- test/object-store/sync/client_reset.cpp
1. Removes all the `unique_ptrs` from `string interner` and `string compressor`. 
2. Limits numbers of interners created per column key (only mixed and strings now, https://github.com/realm/realm-core/pull/7804 enables collections)
> No Unique PTRs for `string interner` and `string compressor`

- doc/development/how-to-release.md
A few updates to the docs after running through the process today.
> update release process documentation

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/list.cpp
- src/realm/list.hpp
- test/object-store/object.cpp
- test/test_sync.cpp
> RCORE-2168: Replicate clear instruction unconditionally

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/history.hpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- src/realm/sync/noinst/protocol_codec.hpp
- src/realm/sync/noinst/server/server_history.hpp
- src/realm/sync/protocol.hpp
- src/realm/sync/tools/apply_to_state_command.cpp
- src/realm/sync/transform.cpp
- test/object-store/benchmarks/client_reset.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
- test/test_sync.cpp
Multiprocess sync needs this information to be available to non-sync-agent processes, which means storing it in the Realm file like the other progress information. For FLX we previously were always writing 0 to the downloadable_progress field in the history compartment, so we can reuse that field and don't have to make any schema changes. It's an integer field, so the double is stored as a fixed-point value with five digits of precision.
Pending bootstrap bytes similarly need to be read from the Realm file rather than passed directly to SessionWrapper, but that was already being persisted.
The separate notify_upload_progress() and notify_download_progress() functions and `only_if_new_uploadable_data ` flag don't work in a multiprocess context. We need to determine what notifications …
> RCORE-2155 Store FLX download progress in the Realm file

- src/realm/array_backlink.cpp
- src/realm/array_mixed.cpp
- src/realm/array_mixed.hpp
- src/realm/array_string.cpp
- src/realm/array_string.hpp
- src/realm/bplustree.hpp
- src/realm/cluster.cpp
- src/realm/cluster_tree.cpp
- src/realm/collection.cpp
- src/realm/collection.hpp
- src/realm/dictionary.cpp
- src/realm/impl/array_writer.hpp
- src/realm/list.cpp
- src/realm/list.hpp
- src/realm/obj.cpp
- src/realm/query_expression.hpp
- src/realm/set.hpp
- src/realm/table.cpp
- src/realm/table.hpp
- src/realm/to_json.cpp
- test/object-store/sync/client_reset.cpp
- test/test_lang_bind_helper.cpp
- test/test_list.cpp
- test/test_query.cpp
> RCORE-2162: Add compression of strings in Mixed, Lst<String> and Dictionary

- src/realm/integer_compressor.cpp
- src/realm/integer_compressor.hpp
- src/realm/integer_flex_compressor.hpp
- src/realm/integer_packed_compressor.hpp
We can never call `set_direct` or in general set a value in a compressed array, because every change to any array is done after `copy_on_write()` (which decompresses the array)
> No need to have`IntegerCompressor::set_direct`

- test/object-store/sync/session/connection_change_notifications.cpp
Updated the "unregister connection change listener" so it registers a callback when the session is first created and unregisters the callback when it is called the first time. There is a call count variable that is updated every time this callback is called and verified that it is only called one time during the test.
Fixes #7823 
> RCORE-2172 Fix race condition in "unregister connection change listener" test while listener is being unregistered

- CHANGELOG.md
- src/realm/util/flat_map.hpp
- test/test_util_flat_map.cpp
This does what it says on the tin. I ran across this while changing HTTPHeaders to be a flat map and discovered util::FlatMap doesn't actually implement the semantics of std::map.
I also added some additional constructors so you can construct a FlatMap from an initializer_list or pair of iterators the way you can construct a std::map or std::vector.
> RCORE-2184 Fix util::FlatMap to use Compare to check equality as well as ordering

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/sync/noinst/server/server.hpp
- test/sync_fixtures.hpp
- test/test_shared.cpp
- test/test_sync.cpp
- test/util/crypt_key.cpp
- test/util/crypt_key.hpp
`compact()` stored the existing encryption key in a `std::string`, which expects a nul-terminated string, not a fixed-size buffer. If the key contained any nul bytes then the key would be truncated and garbage data would be used as the encryption key instead, and if it didn't then arbitrarily large additional amounts of memory would also be copied into the buffer. The tests happened to always use a nul-terminated string as the key and so worked by coincidence.
Fixes #7842.
> RCORE-2183 Fix compacting a Realm file using the existing encryption key

- src/realm/sync/noinst/client_reset_recovery.cpp
Part of https://github.com/realm/realm-core/pull/7845 which caused this warning on [CI](https://evergreen.mongodb.com/version/realm_core_stable_98fe08e8bce3927f857270a0a3ee76a117baac5c?redirect_spruce_users=true):
```
[2024/06/27 10:26:05.490] FAILED: src/realm/sync/CMakeFiles/Sync.dir/RelWithDebInfo/noinst/client_reset_recovery.cpp.o
[2024/06/27 10:26:05.490] /usr/bin/c++ -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D_POSIX_C_SOURCE=200112L -DCMAKE_INTDIR=\"RelWithDebInfo\" -I/data/mci/6bf986cc686e1d44d0a88c98eaefe20e/realm-core/src -I/data/mci/6bf986cc686e1d44d0a88c98eaefe20e/realm-core/build/src -O2 -g -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -Wall -Wextra -Wempty-body -Wparentheses -Wunknown-pragmas -Wunreachable-code -Wunused-parameter …
```
> RCORE-2184 remove unused method now that FlatMap uses the < comparator

- CHANGELOG.md
- src/realm/dictionary.cpp
- src/realm/list.cpp
- test/test_sync.cpp
Fixes #7809
This change makes sure that a collection nested in a Mixed type always will contain the values that has been assigned to it by some client. Before this change you could end up having a combination of values assigned by different clients.
> RCORE-2168: Replicate clear instruction unconditionally for nested collections

- src/realm/array_mixed.cpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/query_engine.cpp
- src/realm/query_expression.hpp
This will prevent us from accidently creating an ObjKey from something that cannot identify an Obj.
> Replace ObjKey with RowKey in selected places

- CHANGELOG.md
- src/realm/array_mixed.cpp
- src/realm/cluster.cpp
- src/realm/cluster.hpp
- src/realm/cluster_tree.cpp
- src/realm/cluster_tree.hpp
- src/realm/list.cpp
- src/realm/obj.cpp
- src/realm/query_engine.cpp
- src/realm/query_expression.hpp
- test/test_mixed_null_assertions.cpp
I discovered these when inspecting the code while investigating https://github.com/realm/realm-core/issues/7594
The first issue appears to have been a mistake, and was introduced by https://github.com/realm/realm-core/pull/6766
I don't know of any reports of the wrong objects being deleted so hopefully this is niche enough that nobody has been affected, but on the other hand maybe it is related to some of the `Key 'Number' not found in '<Class Name>'` exceptions we have seen because unexpected objects are being deleted.
The second issue is more benign, as fewer objects than expected may be deleted. The main thing there is that the state shouldn't have been ignored, and we already had a method for handling this.
The third issue was found due to CI running the new tests in the BPNODE=4 …
> RCORE-2175 RCORE-2176 RCORE-2182 RCORE-2083 Fix several problems with object removal and links

- evergreen/config.yml
- src/external/s2/s2polygonbuilder.cc
- src/realm/sync/noinst/client_reset_recovery.cpp
- src/realm/util/cli_args.cpp
Mainline commits are hitting another warning after https://github.com/realm/realm-core/pull/7851 was merged, due to more unused methods. We didn't catch these warnings on patch builds because the runner that is failing is a ubuntu variant that only runs on mainline commits (benchmarks). This adds a patch build runner that will help us discover these types of warnings on PRs.
The warning causing the failure was:
```
[2024/06/28 11:01:27.139] FAILED: src/realm/sync/CMakeFiles/Sync.dir/RelWithDebInfo/noinst/client_reset_recovery.cpp.o
[2024/06/28 11:01:27.140] /usr/bin/c++ -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D_POSIX_C_SOURCE=200112L -DCMAKE_INTDIR=\"RelWithDebInfo\" -I/data/mci/767ecea29c5786b2cf212408cae2c839/realm-core/src …
```
> RCORE-2188 fix gcc warnings and add a ubuntu 2404 GCC runner

- CHANGELOG.md
- src/realm/chunked_binary.cpp
- src/realm/chunked_binary.hpp
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
Rather than tracking a bunch of derived state in-memory, check for upload completion by checking if there are any unuploaded changesets. This is both multiprocess-compatible and is more precise than the old checks, which had some false-negatives and minor inconsistencies. Previously creating local commits which produced empty changesets and then calling wait_for_upload_completion() would complete immediately, but pausing and then resuming the session would make it wait until the new session performed the upload scan, which didn't happen until after download completion.
The synchronous completion waits (which are hopefully only used in tests) are now just thin wrappers around the async waits. This exposed a small inconsistency around when completion happened when the sync client is …
> RCORE-2160 Make upload completion reporting multiprocess-compatible

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/sync/flx_role_change.cpp
It was discovered during testing of role changes while the realm is currently downloading a bootstrap, that the pending bootstrap store is not being reset when the session reconnects after the 200 error is received from the server due to the role change.
This issue is likely related to #7707 where the bootstrap is not being applied if it has been completely downloaded when the connection (and possibly session) are restarted.
Fixes #7827 
> RCORE-2174 Bootstrap store is not being reset if initial subscription bootstrap is interrupted by role change

- CHANGELOG.md
- src/realm/db.cpp
- src/realm/db.hpp
- src/realm/object-store/impl/realm_coordinator.hpp
- src/realm/object-store/sync/app.cpp
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/impl/app_metadata.cpp
- src/realm/object-store/sync/impl/app_metadata.hpp
- test/object-store/c_api/c_api.cpp
- test/object-store/realm.cpp
- test/object-store/results.cpp
- test/object-store/sync/client_reset.cpp
- test/object-store/sync/flx_schema_migration.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/metadata.cpp
- test/object-store/test_runner.cpp
- test/object-store/thread_safe_reference.cpp
- test/test_sync.cpp
File actions are performed on "next launch" since that's a time where we know it's safe to delete or move Realm files which may have been in use. This previously meant when the metadata store was next constructed, which was incorrect when multiple processes are sharing a metadata file. Instead, it tries to claim the sync agent flag on the metadata Realm file, and only performs the launch actions if it's able to.
There is still a race condition here: process 1 could initialize the metadata realm, claim the flag, then get suspended. Process 2 initializes, opens a Realm, and then removes the user. Process 1 then unsuspends and proceeds to run file actions, deleting the Realm process 2 has open. This is probably not actually a problem but I'll continue to try to find a fix.
Keeping the …
> RCORE-1900 Make "next launch" metadata actions multiprocess-safe

- CHANGELOG.md
- CMakeLists.txt
- evergreen/config.yml
- src/external/bson/bson-decimal128.c
- src/external/bson/bson-iter.c
- src/realm/util/file.cpp
- test/benchmark-common-tasks/main.cpp
- test/util/test_path.cpp
This PR tries to address the following:
* Recently Core has been change to leave the [decision about the C++ standard to the SDKs](https://github.com/realm/realm-core/pull/7802)
* Bindgen generates code with [`requires`](https://en.cppreference.com/w/cpp/keyword/requires) which is new keyword in C++20: [node template](https://github.com/realm/realm-js/blob/main/packages/realm/bindgen/src/templates/node.ts#L354) and [jsi template](https://github.com/realm/realm-js/blob/main/packages/realm/bindgen/src/templates/jsi.ts#L427)
* Core's file operations are using [`u8string()`](https://github.com/realm/realm-core/blob/master/src/realm/util/file.cpp#L343) on Windows, and signature has changed between [C++17 and C++20](https://en.cppreference.com/w/cpp/filesystem/path/string) with the implication …
> Building for Windows using C++20

- src/realm.h
- src/realm/object-store/c_api/config.cpp
Expose new configuration option to C-API
```
RLM_API void realm_config_set_flexible_schema(realm_config_t* realm_config,
bool flexible_schema) noexcept
{
realm_config->flexible_schema = flexible_schema;
}
```
> [C-API] Add relaxed schema configuration option

- CHANGELOG.md
- test/object-store/sync/session/connection_change_notifications.cpp
This produced a tsan error for me when running locally. The assignment to token1 on the main thread and the read of it on the sync worker thread didn't have any intervening synchronization and in theory the callback could read it before it's actually written. Fixing this requires adding some locking.
Conversely, listener2 doesn't actually need to be atomic since the second callback should only ever be invokved synchronously inside log_out(), and if it's called on some other thread that's a bug.
It doesn't matter here, but `listener1_call_cnt = listener1_call_cnt + 1` is a nonatomic increment that will drop updates if it happens on multiple threads at once, while `++` will not.
> Fix data races in the connection state changes tests

- CHANGELOG.md
- src/realm/object-store/results.cpp
- test/object-store/results.cpp
From the RJS ticket:
> When mapTo is used to have an alias for a property name, Realm.Results.sorted() doesn't recognize the alias leading to errors like Cannot sort on key path 'NAME': property 'PersonObject.NAME' does not exist.
This closes https://github.com/realm/realm-js/issues/6779
* ~[ ] C-API, if public C++ API changed~
* ~[ ] `bindgen/spec.yml`, if public C++ API changed~
> RJS-2858: Allow both internal and public name in realm::Results::{sort, distinct}

- CHANGELOG.md
- src/realm/object-store/c_api/logging.cpp
- src/realm/util/logger.cpp
- src/realm/util/logger.hpp
Updates the return type of `LogCategory::get_category_names()` from `std::vector<const char*>` to `std::vector<std::string_view>` in order to alleviate marshaling of strings in DotNet.
This also aligns better with `LogCategory::get_category(std::string_view name)` (already taking a `std::string_view`).
We don't believe this will be a breaking change.
**SDK reviewers, please confirm if this is non-breaking/breaking for you.**
* Remains unchanged. 
* This API was never exposed.
> Update return type of `LogCategory::get_category_names()` from `std::vector<const char*>` to `std::vector<std::string_view>`

- CHANGELOG.md
- src/realm/sync/CMakeLists.txt
- src/realm/sync/network/network_ssl.cpp
- src/realm/sync/network/network_ssl.hpp
- test/test_util_network_ssl.cpp
If an app runs in an enterprise environment where the machine is configured with a traffic-intercepting firewall any custom SSL certificates issued by the firewall need a new trusted root certificate to be installed on the machine. The interface we currently expose puts the onus on the app developer to provide us with a certificate we can add to the OpenSSL certificate store, but in such an environment the app developer is not able to do so.
What we can do to better conform is to automatically look up certificates in the machine's Trusted Root Certification Authorities store on OpenSSL's behalf and use them for the SSL handshake.
> RCORE-2196 Use the Windows trusted root certificates for TLS

- CHANGELOG.md
- src/realm/object-store/sync/async_open_task.cpp
- src/realm/object-store/sync/async_open_task.hpp
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- test/object-store/sync/app.cpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/sync/session/progress_notifications.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/object-store/util/sync/sync_test_utils.hpp
- test/test_sync_pending_bootstraps.cpp
We need to store the download progress for each batch of a bootstrap and not just at the end for it to be useful in any way. Whoops.
The server will sometimes send us DOWNLOAD messages with a non-one estimate followed by a one estimate where the byte-level information is the same (as the final message is empty). When this happens we need to report the download completion to the user, so add the estimate to the fields checked for changes.
A subscription change which doesn't actually change what set of objects is in view can result in an empty DOWNLOAD message with no changes other than the query version, and we should report that too.
Fixes #7869. Fixes #7867.
> RCORE-2192 RCORE-2193 Fix FLX download progress reporting

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/schema.cpp
- test/object-store/c_api/c_api.cpp
Kotlin uses some heuristic for which is required to know the local schema version, before opening a synchronized realm via `open_async`.  
There is no clear API for reading the local schema version without opening the realm, and most importantly, avoiding opening a synchronized realm (in order to guarantee that no sync code is run). 
Opening realm in immutable mode seems a viable and simple approach for achieving that, although it will result in a double opening, if a migration is needed (since it requires opening a synchronized realm in async mode). 
Another possible approach is to add a new cnf param that the SDK needs to specify and throw an exception inside `RealmCoordinator::do_get_realm` if the new param is set.
> Add get local schema version to the C-API

- CHANGELOG.md
- src/realm.h
- src/realm/object-store/c_api/app.cpp
- src/realm/object-store/c_api/socket_provider.cpp
- src/realm/object-store/c_api/sync.cpp
- src/realm/object-store/c_api/types.hpp
- test/object-store/c_api/c_api.cpp
As part of the changes to separate the App from the Sync Client, a `realm_app_config_get_sync_client_config()` function was added to the C_API to retrieve a pointer to the sync client config stored in the AppConfig. Unfortunately, this function was never implemented and was only a function declaration.
There are two implementations for getting a `realm_sync_client_config_t`, depending on the value of the `REALM_APP_SERVICES` build flag:
* If it is set, `realm_app_config_get_sync_client_config()` is available to get a pointer to the `sync_client_config` member property of the `realm_app_config_t` structure. The value returned by this function is a reference and should not be freed using `realm_release()`.
* If it is not set, `realm_sync_client_config_new()` is available to create a new …
> RCORE-2201 Add an implementation for the realm_app_config_get_sync_client_config() function in the Core CAPI

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.cpp
- test/object-store/sync/flx_sync.cpp
We were sending unnecessary uploads to the server when there was no data to synchronize and no downloads to acknowledge.
Fixes #7711.
> RCORE-2129 Do not send empty upload messages if there are no downloads to ack

- CHANGELOG.md
Fix bad merge in changelog after https://github.com/realm/realm-core/pull/7859.
> Fix bad merge

- test/object-store/sync/flx_role_change.cpp
- test/object-store/util/sync/baas_admin_api.cpp
- test/object-store/util/sync/baas_admin_api.hpp
- test/object-store/util/sync/sync_test_utils.cpp
The initial sync progress endpoint has an additional key, `accepting_clients`, which in FLX is only set to true after the first initial sync completes. This is a more reliable way to check for initial sync completion than relying on individual namespaces. This PR updates the test helper to check that value instead for FLX apps.
Additionally fixing a bug in the role change tests' API calls that is manifesting in the latest baas, but not the pinned baasaas version for some reason.
> RCORE-2204: Use accepting_clients key to check for initial sync completion in flx tests

- CHANGELOG.md
- src/realm/sync/noinst/client_impl_base.hpp
- test/object-store/sync/flx_sync.cpp
We don't clear out the list of pending compensating write errors when we get disconnected - so if you get disconnected between receiving the error message containing the compensating write error messages and receiving the download message containing the actual compensating writes, we may report a duplicate message since the server will send us both again when we reconnect.
Fixes #7708.
> RCORE-2127 Do not report compensating write errors multiple times

- CHANGELOG.md
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/noinst/client_history_impl.hpp
- src/realm/sync/noinst/client_impl_base.cpp
- src/realm/sync/noinst/client_impl_base.hpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset.hpp
- src/realm/sync/noinst/client_reset_operation.cpp
- src/realm/sync/noinst/client_reset_operation.hpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.hpp
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
- test/object-store/sync/flx_sync.cpp
- test/object-store/util/sync/sync_test_utils.cpp
- test/test_client_reset.cpp
- test/test_sync_pending_bootstraps.cpp
- test/test_sync_subscriptions.cpp
- test/util/unit_test.hpp
As with the other multi-process notifications, the core idea here is to eliminate the in-memory state and produce notifications based entirely on the current state of the Realm file.
SubscriptionStore::update_state() has been replaced with separate functions for the specific legal state transitions, which also take a write transaction as a parameter. These functions are called by PendingBootstrapStore inside the same write transaction as the bootstrap updates which changed the subscription state. This is both a minor performance optimization (due to fewer writes) and eliminates a brief window between the two writes where the Realm file was in an inconsistent state.
There's a minor functional change here: previously old subscription sets were superseded when the new one reached the …
> RCORE-2191 Add support for multi-process subscription state change notifications

- evergreen/config.yml
In Jenkins we actually had two UWP builders:
- Windows 64-bit UWP debug app build with Sync and encryption enabled
- Windows 32-bit UWP release app build with Sync and encryption enabled
This makes the evergreen config match that.
> RCORE-1990 Get exact parity with Jenkins for UWP builders in evg

- test/object-store/sync/app.cpp
This test was relying on the default log level being high enough that the expected messages would actually be logged.
> RCORE-2187 Fix a test failure when the default log level is too low

- CHANGELOG.md
- src/realm/sync/CMakeLists.txt
- src/realm/sync/client.cpp
- src/realm/sync/noinst/client_reset.cpp
- src/realm/sync/noinst/client_reset.hpp
- src/realm/sync/noinst/migration_store.cpp
- src/realm/sync/noinst/pending_bootstrap_store.cpp
- src/realm/sync/noinst/pending_reset_store.cpp
- src/realm/sync/noinst/pending_reset_store.hpp
- src/realm/sync/noinst/sync_metadata_schema.cpp
- src/realm/sync/noinst/sync_metadata_schema.hpp
- src/realm/sync/subscriptions.cpp
- test/object-store/sync/client_reset.cpp
- test/test_client_reset.cpp
- test/test_sync_subscriptions.cpp
If the previous attempt at performing a client reset was done with a different core version than the current one, then attempting the client reset again is not yet a cycle as something significant has changed between the two attempts. This means that we don't actually need the ability to read old client reset tracker schemas; if the schema isn't an exact match we can just discard the existing data.
Running with the idea that retrying the client reset if the core version has changed is not only acceptable but desirable, I also made it store the exact core version which wrote the tracker entry and discard it if the version has changed even if the schema hasn't.
Since I was touching the schema for this anyway, I removed the unused primary key and made the error fields required - we never …
> Only track pending client resets done by the same core version

- CHANGELOG.md
- src/realm/replication.cpp
- src/realm/replication.hpp
- test/test_replication.cpp
This uses the idea in https://github.com/realm/realm-core/pull/7734 and takes it a bit further. Although mutations on embedded objects are now ignored, the selections on their tables still made it into the history. In the test download this leads to a history like this:
```
Select table: class_top
Create object: ObjKey(1)
Select table: class_top__meta
Select table: class_top
Select table: class_top__meta
Select table: class_top
Select table: class_top_embedded1
Select table: class_top
Select table: class_top_embedded1_embedded2
Select table: class_top_embedded1
Select table: class_top_embedded1_embedded2
Select table: class_top_embedded1_embedded2_embedded5
Select table: class_top_embedded1_embedded2
Select table: class_top_embedded1_embedded2_embedded5
Select table: …
```
> RCORE-2223 reduce unnecessary table selections in replication

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- test/test_sync_subscriptions.cpp
I found this unnecessary version pin when inspecting the version locks while downloading a large bootstrap. Releasing it should improve resource utilization, especially for large sync'd Realms. I'm not sure how long SDKs hold onto the subscriptions for so this change may or may not help in practice.
Fixes https://github.com/realm/realm-core/issues/7946
> RCORE-2224 clean up an unused read lock on subscription sets

- bindgen/spec.yml
- src/realm/obj.cpp
- src/realm/obj.hpp
* Add `Obj::has_schema_property()`
* Expose `Obj::has_schema_property()`, `TableRef::get_column_key()`, and `Obj::set_any_by_name()` in bindgen
> Add `Obj::has_schema_property`

- bindgen/spec.yml
- src/realm/object-store/collection.cpp
- src/realm/object-store/collection.hpp
> More flexible schema work for RJS

- CHANGELOG.md
- evergreen/config.yml
- src/realm/sync/noinst/protocol_codec.cpp
- src/realm/util/serializer.cpp
- test/test_alloc.cpp
This adds a builder that runs as part of the nightly build that runs our test suites with logging set to `all`. Because the log output can be 100s of MB per run, we only capture the logs if the tests fail, and we upload them directly to s3 rather than capturing them inline in the evergreen logs.
This also fixes some UBSAN failures and one bug that only manifested when trace level logging was enabled.
> RCORE-2213 Add CI builder that runs tests with log level set to all

- src/realm/query_conditions.hpp
> Remove HackClass

- CHANGELOG.md
- src/realm/parser/driver.cpp
- test/test_parser.cpp
Introduced in https://github.com/realm/realm-core/pull/7785. The between node only handles a single column, not a link chain, so we should check this before using the optimized query node.
Replaces https://github.com/realm/realm-core/pull/7940
Fixes https://github.com/realm/realm-core/issues/7935
> RCORE-2221 fix RQL BETWEEN regression for properties over links

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- src/realm/sync/transform.cpp
- test/test_sync.cpp
This PR fixes two bugs related to storing and retrieving reciprocal changesets:
1. Storing empty reciprocal changesets (after non-empty reciprocal changesets) in the realm file lead to BadChangeset exceptions or data divergence and consistency errors (RCORE-1977)
2. Empty reciprocal changesets retrieved from internal cache lead to the same issues
Fixes #7893.
> RCORE-1977 Empty reciprocal changesets lead to crashes or data divergence

- CHANGELOG.md
- dependencies.yml
- tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
> Upgrade to OpenSSL 3.3.1

- src/realm/string_interner.cpp
- src/realm/string_interner.hpp
Reduce locking in the string interner:
* when using it for comparing strings or for mapping strings to StringIDs.
* when mapping StringIDs to strings.
Also entirely remove locking from methods where it isn't needed (less important since they are much less frequently used than the methods mentioned above).
> RCORE-2233 Reduce locking for StringInterner lookup and compare methods

- CHANGELOG.md
- src/realm/sync/noinst/client_history_impl.cpp
- test/object-store/realm.cpp
We can have local changesets stored which have already been uploaded and acknowledged by the server, so checking all of the changesets is incorrect. We need to instead only check changesets for versions after the current position of the upload cursor.
I wrote a basic test since we didn't have any tests at all which hit the case where we threw this exception, but I couldn't figure out how to write a standalone test for this scenario (one of the tests I wrote for #7921 hit it very indirectly). For things to break we need to have the server send us a DOWNLOAD with upload_client_version > download_client_version (i.e. it's acknowledged the upload of some version, but needs us to store some older version still for merging purposes) and then try to write a copy before we receive a DOWNLOAD …
> RCORE-2232 Actually check for unuploaded changes in no_pending_local_changes()

- src/realm/exec/realm2json.cpp
Handling link depth and `--link-depth` was removed in v14.0.0 or specifically 9169fa1c9ae32b8317a7239ffd436d8287759947.
From changes in test_json.cpp it looks like it now defaults to 0, is it worth explaining the change in the tool?
> Remove mention of --link-depth in realm2json.cpp

- src/realm/exec/realm2json.cpp
> RCORE-2178: Fix Realm2JSON help

- CHANGELOG.md
- src/realm/object-store/c_api/notifications.cpp
- test/object-store/c_api/c_api.cpp
> RCORE-2167: C API: Fix empty keypath issue

- CHANGELOG.md
- src/realm/object-store/impl/deep_change_checker.cpp
- src/realm/object-store/shared_realm.cpp
- test/object-store/object.cpp
Fixes #7530 
We should also check that right column key is changed when checking a backlink column
> RCORE-2061: Fix handling backlink column as last element in KeyPath

- src/realm/exec/realm_trawler.cpp
We should be able to handle files that uses type_LinkList
> Small fix for realm-trawler

- src/realm/sync/tools/hist_command.cpp
Update history command tool to support realm files with file format v24.
> Fix history command tool

- bindgen/spec.yml
- bindgen/src/bound-model.ts
- bindgen/src/realm_helpers.h
Related to https://github.com/realm/realm-core/pull/7991#issuecomment-2306349074
> Updated bindgen spec and helpers

- CHANGELOG.md
- src/realm/object-store/sync/impl/sync_file.hpp
- src/realm/util/file.cpp
- test/object-store/sync/file.cpp
- test/object-store/util/test_utils.cpp
- test/object-store/util/test_utils.hpp
> RCORE-2242: Include pathname in exception thrown in File::rw_lock

- CHANGELOG.md
- Package.swift
- src/realm/CMakeLists.txt
- src/realm/exceptions.cpp
- src/realm/exceptions.mm
- test/CMakeLists.txt
- test/test_nsexception.mm
When the Swift API is misused from within a callback from core a NSException may escape, which we want to propagate. Since this is always a fatal error that cannot be programmatically handled by the user, we can always translate this to UnknownError rather than trying to preserve the original error code.
Fixes #7836.
> RCORE-2180 Add basic translation of NSExceptions to Status

- test/object-store/object.cpp
> Add failing test

- evergreen/wait_for_baas.sh
Fixes the install_baas.sh script used for local development.
> Restore wait_for_baas.sh script

- CHANGELOG.md
- src/realm/query_engine.hpp
The function should ensure strict weak ordering. According to the current one
{1, 0} == {0, 1} and {0, 1} == {2, 1}
but
{1, 0} < {2, 1}
It is not possible to construct a failing test as the outcome very much depends on how the runtime types are laid out.
Fixes #8028
> RCORE:2259: Fix comparison function for ConditionType

- CHANGELOG.md
- src/realm/backup_restore.cpp
- src/realm/backup_restore.hpp
- src/realm/object-store/audit.mm
- test/object-store/audit.cpp
Backup realms from file format upgrades are placed next to the original file, so the audit realm pool will find the backup and attempt to upload it, triggering another upgrade and backup until the filename becomes too long and it crashes instead. It needs to instead skip the backup files and delete any lingering backups of Realms which have already been uploaded.
Fixes #8040
> RCORE-2264: Skip backup files when scanning for audit Realms to upload

- CHANGELOG.md
- src/realm/object-store/object_store.cpp
- test/object-store/migrations.cpp
This is fixing a regression introduced by f7c8e97. The change done in this commit is reverted. Instead the primary key column is set in the post migration changes.
Fixes #8056
> Do not set primary key column before migration function is called

- CHANGELOG.md
- src/realm/object-store/sync/sync_session.cpp
- src/realm/object-store/sync/sync_session.hpp
- test/object-store/sync/app.cpp
This fixes an issue discovered in a HELP ticket. If you open a synchronized realm and it needs to refresh its access token, and that refresh operation doesn't complete before the realm is closed, the lifetime of the sync session will be extended until the refresh is complete. If you open the realm again before that refresh is complete, then you'll have two sync sessions both try to start synchronizing the realm when the refreshes do complete, and that will crash the process with a MultipleSyncAgents exception.
> Sync access token refreshes shouldn't extend SyncSession lifetime

- CHANGELOG.md
- src/realm/sync/subscriptions.cpp
- src/realm/sync/subscriptions.hpp
Instead of throwing the read transaction away after committing subscription changes and then opening a new frozen transaction at the committed transaction's version - we should just re-use the read transaction.
> Reuse transaction when refreshing subscriptions after commit

- CHANGELOG.md
- src/realm/object-store/audit.mm
- test/object-store/audit.cpp
Audit Realms typically don't get client resets due to being very short lived, but restarting sync while one is partially uploaded can result in a bad client file ident error which also blocks uploading any other unuploaded files.
Standard automatic recovery is very inefficient here - it redownloads the already uploaded data for the partition, bypasses the optimization to not actually apply the transaction logs locally, and then rewrites the transaction logs - but doing the optimal thing turned out to actually be pretty complicated and I couldn't get it fully working after spending more time on it than is justified.
> Enable automatic client reset handling for audit Realms
